;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2015 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-3677-7074-51			    |
; |		Michalis Polychronakis,	Stony Brook University		    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	3610E3635F55B3CEFF739A8718CBDD68
; Input	CRC32 :	C74BCB69

; File Name   :	C:\compspace\Diff\openssl\obj\p_dec.obj
; Format      :	COFF (X386MAGIC)
; includelib "MSVCRT"
; includelib "OLDNAMES"

		.686p
		.mmx
		.model flat

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_text$mn	segment	para public 'CODE' use32
		assume cs:_text$mn
; COMDAT (pick no duplicate)
		assume es:nothing, ss:nothing, ds:_rdata, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================


		public _EVP_PKEY_decrypt_old
_EVP_PKEY_decrypt_old proc near

arg_0		= dword	ptr  4
arg_4		= dword	ptr  8
arg_8		= dword	ptr  0Ch
arg_C		= dword	ptr  10h

		mov	ecx, [esp+arg_C]
		cmp	dword ptr [ecx], 6
		jz	short loc_25
		push	4Dh ; 'M'
		push	offset ??_C@_0BF@MNAMDHDJ@?4?2crypto?2evp?2p_dec?4c?$AA@ ; ".\\crypto\\evp\\p_dec.c"
		push	6Ah
		push	97h
		push	6
		call	_ERR_put_error
		add	esp, 14h
		or	eax, 0FFFFFFFFh
		retn
; ---------------------------------------------------------------------------

loc_25:					; CODE XREF: _EVP_PKEY_decrypt_old+7j
		push	1
		push	dword ptr [ecx+14h]
		push	[esp+8+arg_0]
		push	[esp+0Ch+arg_4]
		push	[esp+10h+arg_8]
		call	_RSA_private_decrypt
		add	esp, 14h

$err$5:
		retn
_EVP_PKEY_decrypt_old endp

; ---------------------------------------------------------------------------
		align 10h
_text$mn	ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 40h
; COMDAT (pick any)
		public ??_C@_0BF@MNAMDHDJ@?4?2crypto?2evp?2p_dec?4c?$AA@
; `string'
??_C@_0BF@MNAMDHDJ@?4?2crypto?2evp?2p_dec?4c?$AA@ db '.\crypto\evp\p_dec.c',0
					; DATA XREF: _EVP_PKEY_decrypt_old+Bo
_rdata		ends

; ===========================================================================

; Segment type:	Externs
; UNDEF
		extrn _ERR_put_error:near ; CODE XREF: _EVP_PKEY_decrypt_old+19p
		extrn _RSA_private_decrypt:near	; CODE XREF: _EVP_PKEY_decrypt_old+36p


		end
