;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2015 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-3677-7074-51			    |
; |		Michalis Polychronakis,	Stony Brook University		    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	AAD67A4F87186AF771E2BBEDC0905E2F
; Input	CRC32 :	ACDF66EB

; File Name   :	C:\compspace\Diff\openssl\obj\t_req.obj
; Format      :	COFF (X386MAGIC)
; includelib "MSVCRT"
; includelib "OLDNAMES"

		.686p
		.mmx
		.model flat

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_text$mn	segment	para public 'CODE' use32
		assume cs:_text$mn
; COMDAT (pick no duplicate)
		assume es:nothing, ss:nothing, ds:_rdata, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================


		public _X509_REQ_print
_X509_REQ_print	proc near

arg_0		= dword	ptr  4
arg_4		= dword	ptr  8

		push	0
		push	0
		push	[esp+8+arg_4]
		push	[esp+0Ch+arg_0]
		call	_X509_REQ_print_ex
		add	esp, 10h
		retn
_X509_REQ_print	endp

; ---------------------------------------------------------------------------
		align 4
_text$mn	ends

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_text$mn	segment	para public 'CODE' use32
		assume cs:_text$mn
		;org 18h
; COMDAT (pick no duplicate)
		assume es:nothing, ss:nothing, ds:_rdata, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================


		public _X509_REQ_print_ex
_X509_REQ_print_ex proc	near		; CODE XREF: _X509_REQ_print+Cp
					; _X509_REQ_print_fp+46p

var_11		= byte ptr -11h
var_10		= dword	ptr -10h
var_C		= dword	ptr -0Ch
var_8		= dword	ptr -8
var_4		= dword	ptr -4
arg_0		= dword	ptr  4
arg_4		= dword	ptr  8
arg_8		= dword	ptr  0Ch
arg_C		= dword	ptr  10h

		mov	eax, 14h
		call	__chkstk
		push	ebx
		mov	ebx, [esp+18h+arg_8]
		mov	eax, ebx
		push	ebp
		push	esi
		and	eax, 0F0000h
		mov	[esp+20h+var_11], 20h ;	' '
		xor	esi, esi
		push	edi
		cmp	eax, 40000h
		jnz	short loc_49
		mov	[esp+24h+var_11], 0Ah
		mov	esi, 0Ch

loc_49:					; CODE XREF: _X509_REQ_print_ex+25j
		mov	edi, [esp+24h+arg_0]
		test	ebx, ebx
		mov	eax, 10h
		cmovz	esi, eax
		mov	eax, [esp+24h+arg_4]
		mov	ebp, [eax]
		mov	eax, [esp+24h+arg_C]
		mov	[esp+24h+var_8], ebp
		test	al, 1
		jnz	short loc_9D
		push	15h
		push	offset ??_C@_0BG@FLGIJJOD@Certificate?5Request?3?6?$AA@	; "Certificate Request:\n"
		push	edi
		call	_BIO_write
		add	esp, 0Ch
		test	eax, eax
		jle	$err$89
		push	0Ah
		push	offset ??_C@_0L@JAJPBNB@?5?5?5?5Data?3?6?$AA@ ;	"    Data:\n"
		push	edi
		call	_BIO_write
		add	esp, 0Ch
		test	eax, eax
		jle	$err$89
		mov	eax, [esp+24h+arg_C]

loc_9D:					; CODE XREF: _X509_REQ_print_ex+4Fj
		mov	edx, offset ??_C@_00CNPNBAHC@?$AA@ ; `string'
		test	al, 2
		jnz	short loc_106
		mov	eax, [ebp+0Ch]
		mov	ecx, offset ??_C@_01JOAMLHOP@?9?$AA@ ; `string'
		cmp	dword ptr [eax+4], 102h
		mov	ebp, [eax]
		cmovnz	ecx, edx
		xor	edx, edx
		mov	[esp+24h+var_4], ecx
		xor	ecx, ecx
		test	ebp, ebp
		jle	short loc_DB
		mov	ebx, [eax+8]

loc_C9:					; CODE XREF: _X509_REQ_print_ex+BDj
		movzx	eax, byte ptr [ebx+edx]
		inc	edx
		shl	ecx, 8
		add	ecx, eax
		cmp	edx, ebp
		jl	short loc_C9
		mov	ebx, [esp+24h+arg_8]

loc_DB:					; CODE XREF: _X509_REQ_print_ex+ACj
		mov	eax, [esp+24h+var_4]
		push	ecx
		push	eax
		push	ecx
		push	eax
		push	offset ??_C@_00CNPNBAHC@?$AA@ ;	`string'
		push	offset ??_C@_0BN@MPJOBKLA@?$CF8sVersion?3?5?$CFs?$CFlu?5?$CI?$CFs0x?$CFlx?$CJ?6?$AA@ ; "%8sVersion: %s%lu (%s0x%lx)\n"
		push	edi
		call	_BIO_printf
		add	esp, 1Ch
		test	eax, eax
		jle	$err$89
		mov	ebp, [esp+24h+var_8]
		mov	eax, [esp+24h+arg_C]

loc_106:				; CODE XREF: _X509_REQ_print_ex+8Cj
		test	al, 40h
		jnz	short loc_154
		movsx	eax, [esp+24h+var_11]
		push	eax
		push	offset ??_C@_0BD@PPLJHLMD@?5?5?5?5?5?5?5?5Subject?3?$CFc?$AA@ ;	"	 Subject:%c"
		push	edi
		call	_BIO_printf
		add	esp, 0Ch
		test	eax, eax
		jle	$err$89
		push	ebx
		push	esi
		push	dword ptr [ebp+10h]
		push	edi
		call	_X509_NAME_print_ex
		add	esp, 10h
		test	eax, eax
		js	$err$89
		push	1
		push	offset ??_C@_01EEMJAFIK@?6?$AA@	; `string'
		push	edi
		call	_BIO_write
		add	esp, 0Ch
		test	eax, eax
		jle	$err$89

loc_154:				; CODE XREF: _X509_REQ_print_ex+F0j
		mov	ebx, [esp+24h+arg_C]
		test	bl, bl
		js	loc_205
		push	21h ; '!'
		push	offset ??_C@_0CC@MHFIINFH@?5?5?5?5?5?5?5?5Subject?5Public?5Key?5Info?3@	; "	   Subject Public Key Info:\n"
		push	edi
		call	_BIO_write
		add	esp, 0Ch
		test	eax, eax
		jle	$err$89
		push	offset ??_C@_00CNPNBAHC@?$AA@ ;	`string'
		push	offset ??_C@_0BL@FFNOEEIC@?$CF12sPublic?5Key?5Algorithm?3?5?$AA@ ; "%12sPublic Key Algorithm: "
		push	edi
		call	_BIO_printf
		add	esp, 0Ch
		test	eax, eax
		jle	$err$89
		mov	eax, [ebp+14h]
		mov	eax, [eax]
		push	dword ptr [eax]
		push	edi
		call	_i2a_ASN1_OBJECT
		add	esp, 8
		test	eax, eax
		jle	$err$89
		push	offset ??_C@_01EEMJAFIK@?6?$AA@	; `string'
		push	edi
		call	_BIO_puts
		add	esp, 8
		test	eax, eax
		jle	$err$89
		mov	ebp, [esp+24h+arg_4]
		push	ebp
		call	_X509_REQ_get_pubkey
		mov	esi, eax
		add	esp, 4
		test	esi, esi
		jnz	short loc_1EF
		push	offset ??_C@_00CNPNBAHC@?$AA@ ;	`string'
		push	offset ??_C@_0BP@GNNOMHLK@?$CF12sUnable?5to?5load?5Public?5Key?6?$AA@ ;	"%12sUnable to load Public Key\n"
		push	edi
		call	_BIO_printf
		push	edi
		call	_ERR_print_errors
		add	esp, 10h
		jmp	short loc_209
; ---------------------------------------------------------------------------

loc_1EF:				; CODE XREF: _X509_REQ_print_ex+1BAj
		push	0
		push	10h
		push	esi
		push	edi
		call	_EVP_PKEY_print_public
		push	esi
		call	_EVP_PKEY_free
		add	esp, 14h
		jmp	short loc_209
; ---------------------------------------------------------------------------

loc_205:				; CODE XREF: _X509_REQ_print_ex+142j
		mov	ebp, [esp+24h+arg_4]

loc_209:				; CODE XREF: _X509_REQ_print_ex+1D5j
					; _X509_REQ_print_ex+1EBj
		test	ebx, 800h
		jnz	loc_3D2
		push	offset ??_C@_00CNPNBAHC@?$AA@ ;	`string'
		push	offset ??_C@_0BA@KHLEDAJJ@?$CF8sAttributes?3?6?$AA@ ; "%8sAttributes:\n"
		push	edi
		call	_BIO_printf
		add	esp, 0Ch
		test	eax, eax
		jle	$err$89
		mov	eax, [ebp+0]
		mov	ebx, [eax+18h]
		push	ebx
		mov	[esp+28h+var_4], ebx
		call	_sk_num
		add	esp, 4
		test	eax, eax
		jnz	short loc_267
		push	offset ??_C@_00CNPNBAHC@?$AA@ ;	`string'
		push	offset ??_C@_0L@CKBPOPMH@?$CF12sa0?300?6?$AA@ ;	"%12sa0:00\n"
		push	edi
		call	_BIO_printf
		add	esp, 0Ch
		test	eax, eax
		jle	$err$89
		jmp	loc_3CE
; ---------------------------------------------------------------------------

loc_267:				; CODE XREF: _X509_REQ_print_ex+22Dj
		xor	esi, esi

loc_269:				; CODE XREF: _X509_REQ_print_ex+3ADj
		push	ebx
		mov	[esp+28h+var_8], esi
		call	_sk_num
		add	esp, 4
		cmp	esi, eax
		jge	loc_3CA
		push	esi
		push	[esp+28h+var_4]
		xor	eax, eax
		mov	[esp+2Ch+var_10], 1
		mov	[esp+2Ch+arg_8], eax
		xor	ebx, ebx
		xor	ebp, ebp
		call	_sk_value
		mov	esi, eax
		mov	[esp+2Ch+var_C], esi
		push	dword ptr [esi]
		call	_OBJ_obj2nid
		push	eax
		call	_X509_REQ_extension_nid
		add	esp, 10h
		test	eax, eax
		jnz	loc_3BC
		push	offset ??_C@_00CNPNBAHC@?$AA@ ;	`string'
		push	offset ??_C@_04FLJGCMJJ@?$CF12s?$AA@ ; "%12s"
		push	edi
		call	_BIO_printf
		add	esp, 0Ch
		test	eax, eax
		jle	$err$89
		push	dword ptr [esi]
		push	edi
		call	_i2a_ASN1_OBJECT
		mov	esi, eax
		add	esp, 8
		test	esi, esi
		jle	short loc_2F9
		mov	eax, [esp+24h+var_C]
		cmp	[eax+4], ebx
		jz	short loc_352
		mov	eax, [eax+8]

loc_2F0:				; CODE XREF: _X509_REQ_print_ex+35Bj
					; _X509_REQ_print_ex+39Fj
		mov	ebx, [eax]
		mov	eax, [eax+4]
		mov	[esp+24h+arg_8], eax

loc_2F9:				; CODE XREF: _X509_REQ_print_ex+2CAj
		mov	eax, 19h
		sub	eax, esi
		mov	esi, eax
		test	esi, esi
		jle	short loc_326
		xchg	ax, ax

loc_308:				; CODE XREF: _X509_REQ_print_ex+30Cj
		push	1
		push	offset ??_C@_01CLKCMJKC@?5?$AA@	; `string'
		push	edi
		call	_BIO_write
		add	esp, 0Ch
		cmp	eax, 1
		jnz	$err$89
		dec	esi
		test	esi, esi
		jg	short loc_308

loc_326:				; CODE XREF: _X509_REQ_print_ex+2ECj
		push	offset ??_C@_01JLIPDDHJ@?3?$AA@	; `string'
		push	edi
		call	_BIO_puts
		add	esp, 8
		test	eax, eax
		jle	$err$89
		cmp	ebx, 13h
		jz	short loc_378
		cmp	ebx, 14h
		jz	short loc_378
		cmp	ebx, 16h
		jz	short loc_378
		push	offset ??_C@_0BL@HDFPNKMO@unable?5to?5print?5attribute?6?$AA@ ;	"unable	to print attribute\n"
		jmp	short loc_397
; ---------------------------------------------------------------------------

loc_352:				; CODE XREF: _X509_REQ_print_ex+2D3j
		push	dword ptr [eax+8]
		xor	ebp, ebp
		call	_sk_num
		add	esp, 4
		mov	[esp+24h+var_10], eax
		mov	eax, [esp+24h+var_C]
		push	ebp
		push	dword ptr [eax+8]
		call	_sk_value
		add	esp, 8
		jmp	loc_2F0
; ---------------------------------------------------------------------------

loc_378:				; CODE XREF: _X509_REQ_print_ex+327j
					; _X509_REQ_print_ex+32Cj ...
		mov	ebx, [esp+24h+arg_8]
		push	dword ptr [ebx]
		push	dword ptr [ebx+8]
		push	edi
		call	_BIO_write
		add	esp, 0Ch
		cmp	eax, [ebx]
		jnz	$err$89
		push	offset ??_C@_01EEMJAFIK@?6?$AA@	; `string'

loc_397:				; CODE XREF: _X509_REQ_print_ex+338j
		push	edi
		call	_BIO_puts
		inc	ebp
		add	esp, 8
		cmp	ebp, [esp+24h+var_10]
		jge	short loc_3BC

$get_next$90:
		mov	eax, [esp+24h+var_C]
		push	ebp
		push	dword ptr [eax+8]
		call	_sk_value
		add	esp, 8
		jmp	loc_2F0
; ---------------------------------------------------------------------------

loc_3BC:				; CODE XREF: _X509_REQ_print_ex+29Aj
					; _X509_REQ_print_ex+38Dj
		mov	esi, [esp+24h+var_8]
		mov	ebx, [esp+24h+var_4]
		inc	esi
		jmp	loc_269
; ---------------------------------------------------------------------------

loc_3CA:				; CODE XREF: _X509_REQ_print_ex+260j
		mov	ebp, [esp+24h+arg_4]

loc_3CE:				; CODE XREF: _X509_REQ_print_ex+24Aj
		mov	ebx, [esp+24h+arg_C]

loc_3D2:				; CODE XREF: _X509_REQ_print_ex+1F7j
		test	ebx, 100h
		jnz	loc_4DD
		push	ebp
		call	_X509_REQ_get_extensions
		mov	ebp, eax
		add	esp, 4
		test	ebp, ebp
		jz	loc_4DD
		push	offset ??_C@_00CNPNBAHC@?$AA@ ;	`string'
		push	offset ??_C@_0BK@JLPJCDIH@?$CF8sRequested?5Extensions?3?6?$AA@ ; "%8sRequested Extensions:\n"
		push	edi
		call	_BIO_printf
		push	ebp
		xor	esi, esi
		call	_sk_num
		add	esp, 10h
		test	eax, eax
		jle	loc_4CF
		nop	dword ptr [eax+00h]

loc_418:				; CODE XREF: _X509_REQ_print_ex+4ADj
		push	esi
		push	ebp
		call	_sk_value
		push	offset ??_C@_00CNPNBAHC@?$AA@ ;	`string'
		push	offset ??_C@_04FLJGCMJJ@?$CF12s?$AA@ ; "%12s"
		push	edi
		mov	ebx, eax
		call	_BIO_printf
		add	esp, 14h
		test	eax, eax
		jle	$err$89
		push	ebx
		call	_X509_EXTENSION_get_object
		push	eax
		push	edi
		call	_i2a_ASN1_OBJECT
		push	ebx
		call	_X509_EXTENSION_get_critical
		test	eax, eax
		mov	ecx, offset ??_C@_08CBBMEOFB@critical?$AA@ ; "critical"
		mov	eax, offset ??_C@_00CNPNBAHC@?$AA@ ; `string'
		cmovz	ecx, eax
		push	ecx
		push	offset ??_C@_05BBKJDEBM@?3?5?$CFs?6?$AA@ ; ": %s\n"
		push	edi
		call	_BIO_printf
		add	esp, 1Ch
		test	eax, eax
		jle	$err$89
		push	10h
		push	[esp+28h+arg_C]
		push	ebx
		push	edi
		call	_X509V3_EXT_print
		add	esp, 10h
		test	eax, eax
		jnz	short loc_4A5
		push	offset ??_C@_00CNPNBAHC@?$AA@ ;	`string'
		push	offset ??_C@_04FMJPIEEF@?$CF16s?$AA@ ; "%16s"
		push	edi
		call	_BIO_printf
		push	dword ptr [ebx+8]
		push	edi
		call	_ASN1_STRING_print
		add	esp, 14h

loc_4A5:				; CODE XREF: _X509_REQ_print_ex+46Fj
		push	1
		push	offset ??_C@_01EEMJAFIK@?6?$AA@	; `string'
		push	edi
		call	_BIO_write
		add	esp, 0Ch
		test	eax, eax
		jle	short $err$89
		push	ebp
		inc	esi
		call	_sk_num
		add	esp, 4
		cmp	esi, eax
		jl	loc_418
		mov	ebx, [esp+24h+arg_C]

loc_4CF:				; CODE XREF: _X509_REQ_print_ex+3F6j
		push	offset _X509_EXTENSION_free
		push	ebp
		call	_sk_pop_free
		add	esp, 8

loc_4DD:				; CODE XREF: _X509_REQ_print_ex+3C0j
					; _X509_REQ_print_ex+3D3j
		test	ebx, 200h
		jnz	short loc_51E
		mov	eax, [esp+24h+arg_4]
		push	dword ptr [eax+8]
		push	dword ptr [eax+4]
		push	edi
		call	_X509_signature_print
		add	esp, 0Ch
		test	eax, eax
		jnz	short loc_51E

$err$89:				; CODE XREF: _X509_REQ_print_ex+63j
					; _X509_REQ_print_ex+7Bj ...
		push	0F7h ; '÷'
		push	offset ??_C@_0BG@IBJJPJCL@?4?2crypto?2asn1?2t_req?4c?$AA@ ; ".\\crypto\\asn1\\t_req.c"
		push	7
		push	79h ; 'y'
		push	0Bh
		call	_ERR_put_error
		add	esp, 14h
		xor	eax, eax
		pop	edi
		pop	esi
		pop	ebp
		pop	ebx
		add	esp, 14h
		retn
; ---------------------------------------------------------------------------

loc_51E:				; CODE XREF: _X509_REQ_print_ex+4CBj
					; _X509_REQ_print_ex+4E2j
		pop	edi
		pop	esi
		pop	ebp
		mov	eax, 1
		pop	ebx
		add	esp, 14h
		retn
_X509_REQ_print_ex endp

; ---------------------------------------------------------------------------
		align 4
_text$mn	ends

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_text$mn	segment	para public 'CODE' use32
		assume cs:_text$mn
		;org 52Ch
; COMDAT (pick no duplicate)
		assume es:nothing, ss:nothing, ds:_rdata, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================


		public _X509_REQ_print_fp
_X509_REQ_print_fp proc	near

arg_0		= dword	ptr  4
arg_4		= dword	ptr  8

		push	edi
		call	_BIO_s_file
		push	eax
		call	_BIO_new
		mov	edi, eax
		add	esp, 4
		test	edi, edi
		jnz	short loc_55A
		push	50h ; 'P'
		push	offset ??_C@_0BG@IBJJPJCL@?4?2crypto?2asn1?2t_req?4c?$AA@ ; ".\\crypto\\asn1\\t_req.c"
		push	7
		push	7Ah ; 'z'
		push	0Bh
		call	_ERR_put_error
		add	esp, 14h
		xor	eax, eax
		pop	edi
		retn
; ---------------------------------------------------------------------------

loc_55A:				; CODE XREF: _X509_REQ_print_fp+13j
		push	esi
		push	[esp+8+arg_0]
		push	0
		push	6Ah ; 'j'
		push	edi
		call	_BIO_ctrl
		push	0
		push	0
		push	[esp+20h+arg_4]
		push	edi
		call	_X509_REQ_print_ex
		push	edi
		mov	esi, eax
		call	_BIO_free
		add	esp, 24h
		mov	eax, esi
		pop	esi
		pop	edi
		retn
_X509_REQ_print_fp endp

; ---------------------------------------------------------------------------
		align 4
_text$mn	ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 588h
; COMDAT (pick any)
		public ??_C@_0BG@IBJJPJCL@?4?2crypto?2asn1?2t_req?4c?$AA@
; `string'
??_C@_0BG@IBJJPJCL@?4?2crypto?2asn1?2t_req?4c?$AA@ db '.\crypto\asn1\t_req.c',0
					; DATA XREF: _X509_REQ_print_ex+4E9o
					; _X509_REQ_print_fp+17o
		align 10h
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 5A0h
; COMDAT (pick any)
		public ??_C@_0BG@FLGIJJOD@Certificate?5Request?3?6?$AA@
; `string'
??_C@_0BG@FLGIJJOD@Certificate?5Request?3?6?$AA@ db 'Certificate Request:',0Ah,0
					; DATA XREF: _X509_REQ_print_ex+53o
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 5B8h
; COMDAT (pick any)
		public ??_C@_0L@JAJPBNB@?5?5?5?5Data?3?6?$AA@
; `string'
??_C@_0L@JAJPBNB@?5?5?5?5Data?3?6?$AA@ db '    Data:',0Ah,0
					; DATA XREF: _X509_REQ_print_ex+6Bo
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 5C4h
; COMDAT (pick any)
		public ??_C@_01JOAMLHOP@?9?$AA@
; `string'
??_C@_01JOAMLHOP@?9?$AA@ db 2Dh, 0	; DATA XREF: _X509_REQ_print_ex+91o
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	byte public 'DATA' use32
		assume cs:_rdata
		;org 5C8h
; COMDAT (pick any)
		public ??_C@_00CNPNBAHC@?$AA@
; `string'
??_C@_00CNPNBAHC@?$AA@ db 0		; DATA XREF: _X509_REQ_print_ex:loc_9Do
					; _X509_REQ_print_ex+CBo ...
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 5CCh
; COMDAT (pick any)
		public ??_C@_0BN@MPJOBKLA@?$CF8sVersion?3?5?$CFs?$CFlu?5?$CI?$CFs0x?$CFlx?$CJ?6?$AA@
; `string'
??_C@_0BN@MPJOBKLA@?$CF8sVersion?3?5?$CFs?$CFlu?5?$CI?$CFs0x?$CFlx?$CJ?6?$AA@ db '%8sVersion: %s%lu (%s0x%lx)',0Ah,0
					; DATA XREF: _X509_REQ_print_ex+D0o
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 5ECh
; COMDAT (pick any)
		public ??_C@_0BD@PPLJHLMD@?5?5?5?5?5?5?5?5Subject?3?$CFc?$AA@
; `string'
??_C@_0BD@PPLJHLMD@?5?5?5?5?5?5?5?5Subject?3?$CFc?$AA@ db '        Subject:%c',0
					; DATA XREF: _X509_REQ_print_ex+F8o
		align 10h
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 600h
; COMDAT (pick any)
		public ??_C@_01EEMJAFIK@?6?$AA@
; `string'
??_C@_01EEMJAFIK@?6?$AA@ db 0Ah, 0	; DATA XREF: _X509_REQ_print_ex+126o
					; _X509_REQ_print_ex+193o ...
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 604h
; COMDAT (pick any)
		public ??_C@_0CC@MHFIINFH@?5?5?5?5?5?5?5?5Subject?5Public?5Key?5Info?3@
; `string'
??_C@_0CC@MHFIINFH@?5?5?5?5?5?5?5?5Subject?5Public?5Key?5Info?3@ db '        Subject Public Key Info:',0Ah,0
					; DATA XREF: _X509_REQ_print_ex+14Ao
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 628h
; COMDAT (pick any)
		public ??_C@_0BL@FFNOEEIC@?$CF12sPublic?5Key?5Algorithm?3?5?$AA@
; `string'
??_C@_0BL@FFNOEEIC@?$CF12sPublic?5Key?5Algorithm?3?5?$AA@ db '%12sPublic Key Algorithm: ',0
					; DATA XREF: _X509_REQ_print_ex+165o
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 644h
; COMDAT (pick any)
		public ??_C@_0BP@GNNOMHLK@?$CF12sUnable?5to?5load?5Public?5Key?6?$AA@
; `string'
??_C@_0BP@GNNOMHLK@?$CF12sUnable?5to?5load?5Public?5Key?6?$AA@ db '%12sUnable to load Public Key',0Ah,0
					; DATA XREF: _X509_REQ_print_ex+1C1o
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 664h
; COMDAT (pick any)
		public ??_C@_0BA@KHLEDAJJ@?$CF8sAttributes?3?6?$AA@
; `string'
??_C@_0BA@KHLEDAJJ@?$CF8sAttributes?3?6?$AA@ db	'%8sAttributes:',0Ah,0
					; DATA XREF: _X509_REQ_print_ex+202o
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 674h
; COMDAT (pick any)
		public ??_C@_0L@CKBPOPMH@?$CF12sa0?300?6?$AA@
; `string'
??_C@_0L@CKBPOPMH@?$CF12sa0?300?6?$AA@ db '%12sa0:00',0Ah,0
					; DATA XREF: _X509_REQ_print_ex+234o
		align 10h
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 680h
; COMDAT (pick any)
		public ??_C@_04FLJGCMJJ@?$CF12s?$AA@
; `string'
??_C@_04FLJGCMJJ@?$CF12s?$AA@ db '%12s',0 ; DATA XREF: _X509_REQ_print_ex+2A5o
					; _X509_REQ_print_ex+40Co
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 688h
; COMDAT (pick any)
		public ??_C@_01CLKCMJKC@?5?$AA@
; `string'
??_C@_01CLKCMJKC@?5?$AA@ db 20h, 0	; DATA XREF: _X509_REQ_print_ex+2F2o
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 68Ch
; COMDAT (pick any)
		public ??_C@_01JLIPDDHJ@?3?$AA@
; `string'
??_C@_01JLIPDDHJ@?3?$AA@ db 3Ah, 0	; DATA XREF: _X509_REQ_print_ex:loc_326o
		align 10h
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 690h
; COMDAT (pick any)
		public ??_C@_0BL@HDFPNKMO@unable?5to?5print?5attribute?6?$AA@
; `string'
??_C@_0BL@HDFPNKMO@unable?5to?5print?5attribute?6?$AA@ db 'unable to print attribute',0Ah,0
					; DATA XREF: _X509_REQ_print_ex+333o
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 6ACh
; COMDAT (pick any)
		public ??_C@_0BK@JLPJCDIH@?$CF8sRequested?5Extensions?3?6?$AA@
; `string'
??_C@_0BK@JLPJCDIH@?$CF8sRequested?5Extensions?3?6?$AA@	db '%8sRequested Extensions:',0Ah,0
					; DATA XREF: _X509_REQ_print_ex+3DEo
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 6C8h
; COMDAT (pick any)
		public ??_C@_08CBBMEOFB@critical?$AA@
; `string'
??_C@_08CBBMEOFB@critical?$AA@ db 'critical',0 ; DATA XREF: _X509_REQ_print_ex+439o
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 6D4h
; COMDAT (pick any)
		public ??_C@_05BBKJDEBM@?3?5?$CFs?6?$AA@
; `string'
??_C@_05BBKJDEBM@?3?5?$CFs?6?$AA@ db ': %s',0Ah,0 ; DATA XREF: _X509_REQ_print_ex+447o
		align 4
_rdata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	dword public 'DATA' use32
		assume cs:_rdata
		;org 6DCh
; COMDAT (pick any)
		public ??_C@_04FMJPIEEF@?$CF16s?$AA@
; `string'
??_C@_04FMJPIEEF@?$CF16s?$AA@ db '%16s',0 ; DATA XREF: _X509_REQ_print_ex+476o
_rdata		ends

; ===========================================================================

; Segment type:	Externs
; UNDEF
		extrn _sk_num:near	; CODE XREF: _X509_REQ_print_ex+223p
					; _X509_REQ_print_ex+256p ...
		extrn _sk_value:near	; CODE XREF: _X509_REQ_print_ex+27Dp
					; _X509_REQ_print_ex+353p ...
		extrn _sk_pop_free:near	; CODE XREF: _X509_REQ_print_ex+4BDp
		extrn _BIO_s_file:near	; CODE XREF: _X509_REQ_print_fp+1p
		extrn _BIO_new:near	; CODE XREF: _X509_REQ_print_fp+7p
		extrn _BIO_free:near	; CODE XREF: _X509_REQ_print_fp+4Ep
		extrn _BIO_write:near	; CODE XREF: _X509_REQ_print_ex+59p
					; _X509_REQ_print_ex+71p ...
		extrn _BIO_puts:near	; CODE XREF: _X509_REQ_print_ex+199p
					; _X509_REQ_print_ex+314p ...
		extrn _BIO_ctrl:near	; CODE XREF: _X509_REQ_print_fp+38p
		extrn _BIO_printf:near	; CODE XREF: _X509_REQ_print_ex+D6p
					; _X509_REQ_print_ex+FEp ...
		extrn _ERR_put_error:near ; CODE XREF: _X509_REQ_print_ex+4F4p
					; _X509_REQ_print_fp+22p
		extrn _ERR_print_errors:near ; CODE XREF: _X509_REQ_print_ex+1CDp
		extrn _i2a_ASN1_OBJECT:near ; CODE XREF: _X509_REQ_print_ex+183p
					; _X509_REQ_print_ex+2BEp ...
		extrn _ASN1_STRING_print:near ;	CODE XREF: _X509_REQ_print_ex+485p
		extrn _OBJ_obj2nid:near	; CODE XREF: _X509_REQ_print_ex+28Ap
		extrn _EVP_PKEY_free:near ; CODE XREF: _X509_REQ_print_ex+1E3p
		extrn _EVP_PKEY_print_public:near ; CODE XREF: _X509_REQ_print_ex+1DDp
		extrn _X509_signature_print:near ; CODE	XREF: _X509_REQ_print_ex+4D8p
		extrn _X509_EXTENSION_free:near	; DATA XREF: _X509_REQ_print_ex:loc_4CFo
		extrn _X509_REQ_get_pubkey:near	; CODE XREF: _X509_REQ_print_ex+1AEp
		extrn _X509_REQ_extension_nid:near ; CODE XREF:	_X509_REQ_print_ex+290p
		extrn _X509_REQ_get_extensions:near ; CODE XREF: _X509_REQ_print_ex+3C7p
		extrn _X509_NAME_print_ex:near ; CODE XREF: _X509_REQ_print_ex+114p
		extrn _X509_EXTENSION_get_object:near ;	CODE XREF: _X509_REQ_print_ex+425p
		extrn _X509_EXTENSION_get_critical:near	; CODE XREF: _X509_REQ_print_ex+432p
		extrn _X509V3_EXT_print:near ; CODE XREF: _X509_REQ_print_ex+465p
		extrn __chkstk:near	; CODE XREF: _X509_REQ_print_ex+5p


		end
