endp
_main		proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0CCh']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_CC]']
mov ['ecx,', '33h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['[ebp+var_8],', '0']
call ['_u_getDataDirectory_56']
mov ['ds:Source,', 'eax']
push ['offset', '_options']
push ['5']
mov ['eax,', '[ebp+argv]']
push ['eax']
mov ['ecx,', '[ebp+argc]']
push ['ecx']
call ['_u_parseArgs']
add ['esp,', '10h']
mov ['[ebp+argc],', 'eax']
cmp ['[ebp+argc],', '0']
jge ['short', 'loc_121']
mov ['eax,', '[ebp+argc]']
neg ['eax']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+argv]']
mov ['edx,', '[ecx+eax*4]']
push ['edx']
push ['offset', '??_C@_0CF@BGPNLJEE@error?5in?5command?5line?5argument?5?$CC@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
cmp ['[ebp+argc],', '0']
jl ['short', 'loc_13D']
movsx ['eax,', 'ds:byte_4A']
test ['eax,', 'eax']
jnz ['short', 'loc_13D']
movsx ['eax,', 'ds:byte_5E']
test ['eax,', 'eax']
jz ['short', 'loc_178']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+argv]']
mov ['ecx,', '[eax]']
push ['ecx']
push ['offset', '??_C@_0BFK@GGPHOHNE@usage?3?5?$CFs?5?$FL?9options?$FN?6?7create?5the@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['eax,', 'eax']
cmp ['[ebp+argc],', '0']
setl ['al']
jmp ['short', 'loc_1DA']
movsx ['eax,', 'ds:byte_9A']
test ['eax,', 'eax']
jz ['short', 'loc_19B']
mov ['eax,', 'ds:Source']
push ['eax']
mov ['ecx,', '[ebp+argv]']
mov ['edx,', '[ecx]']
push ['edx']
call ['_outputJavaStuff']
add ['esp,', '8']
jmp ['short', 'loc_1DA']
jmp ['short', 'loc_1D1']
movsx ['eax,', 'ds:byte_86']
test ['eax,', 'eax']
jz ['short', 'loc_1BE']
mov ['eax,', 'ds:Source']
push ['eax']
mov ['ecx,', '[ebp+argv]']
mov ['edx,', '[ecx]']
push ['edx']
call ['_genres32']
add ['esp,', '8']
jmp ['short', 'loc_1DA']
jmp ['short', 'loc_1D1']
lea ['eax,', '[ebp+var_8]']
push ['eax']
mov ['ecx,', 'ds:Source']
push ['ecx']
call ['_createData']
add ['esp,', '8']
xor ['eax,', 'eax']
cmp ['[ebp+var_8],', '0']
setnle ['al']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN12']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '0CCh']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['10h']
dd ['offset', '$LN11']
dd ['offset', '$LN10']
align ['10h']
assume ['cs:_rdata']
public ['??_C@_0BFK@GGPHOHNE@usage?3?5?$CFs?5?$FL?9options?$FN?6?7create?5the@']
db ["9,'create", 'the', 'test', 'file', 'test.icu', 'unless', 'the', '-r', 'option', 'is', "given.',0Ah"]
db ["9,'options:',0Ah"]
db ["9,9,'-h", 'or', '-?', 'or', '--help', 'this', 'usage', "text',0Ah"]
db ["9,9,'-d", 'or', '--destdir', 'destination', 'directory,', 'followed', 'by', 'the', "path'"]
db ['0Ah']
db ["9,9,'-r", 'or', '--genres', 'generate', 'resource', 'file', 'testtable32.txt', "inst'"]
db ["'ead", 'of', 'UData', 'test', "',0Ah"]
db ["9,9,'-j", 'or', '--javastuff', 'generate', 'Java', 'source', 'for', 'DebugUtilities.', "',0Ah"]
db ['0']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CF@BGPNLJEE@error?5in?5command?5line?5argument?5?$CC@']
align ['4']
assume ['cs:_rtc$TMZ']
assume ['cs:_rtc$IMZ']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_rdata,', 'fs:nothing,', 'gs:nothing']
endp
_createData	proc near		
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '104h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_104]']
mov ['ecx,', '41h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_4],', 'eax']
mov ['[ebp+var_1C],', '59h']
mov ['[ebp+var_1B],', '45h']
mov ['[ebp+var_1A],', '41h']
mov ['[ebp+var_19],', '52h']
mov ['[ebp+var_18],', '0']
mov ['eax,', '7D0h']
mov ['[ebp+var_28],', 'ax']
mov ['eax,', '[ebp+arg_4]']
push ['eax']
push ['offset', '??_C@_0GD@IBBFEJOD@?5Copyright?5?$CIC?$CJ?52015?0?5Internation@']
push ['offset', '_dataInfo']
push ['offset', '??_C@_04CEJDCDCH@test?$AA@']
push ['offset', '??_C@_03IAEMGAKA@icu?$AA@']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
call ['_udata_create']
add ['esp,', '18h']
mov ['[ebp+var_C],', 'eax']
mov ['eax,', '[ebp+arg_4]']
cmp ['dword', 'ptr', '[eax],', '0']
jle ['short', 'loc_46E']
mov ['eax,', '[ebp+arg_4]']
mov ['ecx,', '[eax]']
push ['ecx']
call ['_u_errorName_56']
add ['esp,', '4']
mov ['esi,', 'esp']
push ['eax']
push ['offset', '??_C@_0CL@GPFFOBCM@gentest?3?5unable?5to?5create?5data?5m@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+arg_4]']
mov ['ecx,', '[eax]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
movzx ['eax,', '[ebp+var_28]']
push ['eax']
mov ['ecx,', '[ebp+var_C]']
push ['ecx']
call ['_udata_write16']
add ['esp,', '8']
push ['5']
lea ['eax,', '[ebp+var_1C]']
push ['eax']
mov ['ecx,', '[ebp+var_C]']
push ['ecx']
call ['_udata_writeString']
add ['esp,', '0Ch']
mov ['eax,', '[ebp+arg_4]']
push ['eax']
mov ['ecx,', '[ebp+var_C]']
push ['ecx']
call ['_udata_finish']
add ['esp,', '8']
mov ['[ebp+var_34],', 'eax']
mov ['eax,', '[ebp+arg_4]']
cmp ['dword', 'ptr', '[eax],', '0']
jle ['short', 'loc_4F1']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+arg_4]']
mov ['ecx,', '[eax]']
push ['ecx']
push ['offset', '??_C@_0CL@FHPPBNJP@gentest?3?5error?5?$CFd?5writing?5the?5ou@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+arg_4]']
mov ['ecx,', '[eax]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_40],', '7']
mov ['eax,', '[ebp+var_34]']
cmp ['eax,', '[ebp+var_40]']
jz ['short', 'loc_543']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_40]']
push ['eax']
mov ['ecx,', '[ebp+var_34]']
push ['ecx']
push ['offset', '??_C@_0DB@EHKIAHJD@gentest?3?5data?5length?5?$CFld?5?$CB?$DN?5calc@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['5']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN8']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
pop ['ebx']
mov ['ecx,', '[ebp+var_4]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '104h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['4']
dd ['offset', '$LN7']
dd ['offset', '$LN6']
assume ['cs:_rdata']
public ['??_C@_0DB@EHKIAHJD@gentest?3?5data?5length?5?$CFld?5?$CB?$DN?5calc@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CL@FHPPBNJP@gentest?3?5error?5?$CFd?5writing?5the?5ou@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CL@GPFFOBCM@gentest?3?5unable?5to?5create?5data?5m@']
align ['10h']
assume ['cs:_rdata']
public ['??_C@_03IAEMGAKA@icu?$AA@']
assume ['cs:_rdata']
public ['??_C@_04CEJDCDCH@test?$AA@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0GD@IBBFEJOD@?5Copyright?5?$CIC?$CJ?52015?0?5Internation@']
db ["'and", 'others.', 'All', 'Rights', 'Reserved.', "',0"]
align ['10h']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_rdata,', 'fs:nothing,', 'gs:nothing']
endp
_outputJavaStuff proc near		
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '30Ch']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_30C]']
mov ['ecx,', '0C3h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_4],', 'eax']
call ['_getCurrentYear']
mov ['[ebp+var_244],', 'eax']
mov ['eax,', '[ebp+Source]']
push ['eax']
lea ['ecx,', '[ebp+Dest]']
push ['ecx']
call ['_strcpy']
add ['esp,', '8']
mov ['eax,', '[ebp+Source]']
movsx ['ecx,', 'byte', 'ptr', '[eax]']
test ['ecx,', 'ecx']
jz ['short', 'loc_710']
lea ['eax,', '[ebp+Dest]']
push ['eax']
call ['_strlen']
add ['esp,', '4']
movsx ['ecx,', '[ebp+eax+var_22D]']
cmp ['ecx,', '5Ch']
jz ['short', 'loc_710']
push ['offset', '??_C@_01KICIPPFI@?2?$AA@']
lea ['eax,', '[ebp+Dest]']
push ['eax']
call ['_strcat']
add ['esp,', '8']
push ['offset', '??_C@_0BI@KHJFOGDK@DebugUtilitiesData?4java?$AA@']
lea ['eax,', '[ebp+Dest]']
push ['eax']
call ['_strcat']
add ['esp,', '8']
mov ['esi,', 'esp']
push ['offset', '??_C@_01NOFIACDB@w?$AA@']
lea ['eax,', '[ebp+Dest]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fopen']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+File],', 'eax']
mov ['esi,', 'esp']
lea ['eax,', '[ebp+Dest]']
push ['eax']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
push ['offset', '??_C@_0BD@NBBLDIIG@?$CFs?3?5Generating?5?$CFs?6?$AA@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
cmp ['[ebp+File],', '0']
jnz ['short', 'loc_7B2']
mov ['esi,', 'esp']
lea ['eax,', '[ebp+Dest]']
push ['eax']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
push ['offset', '??_C@_0CL@JEAIBBLK@?$CFs?3?5Couldn?8t?5create?5resource?5tes@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '1']
jmp ['loc_C89']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_244]']
push ['eax']
push ['offset', '??_C@_0GO@ONAIJNMC@?1?$CK?$CK?5Copyright?5?$CIC?$CJ?52007?9?$CFd?0?5Inter@']
mov ['ecx,', '[ebp+File]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['offset', '??_C@_0IF@CGMDDOC@?1?$CK?5NOTE?3?5this?5file?5is?5AUTOMATICA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['offset', '??_C@_0CF@MKMNJIPJ@package?5com?4ibm?4icu?4dev?4test?4uti@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['offset', '??_C@_0DC@HPJGNNPG@public?5class?5DebugUtilitiesData?5@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['offset', '??_C@_04HBNCPEDB@56?41?$AA@']
push ['offset', '??_C@_0DE@GEDBOIKO@?5?5?5?5public?5static?5final?5String?5I@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_18],', '0']
jmp ['short', 'loc_866']
mov ['eax,', '[ebp+var_18]']
add ['eax,', '1']
mov ['[ebp+var_18],', 'eax']
cmp ['[ebp+var_18],', '6']
jge ['short', 'loc_89F']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_18]']
push ['eax']
mov ['ecx,', '[ebp+var_18]']
push ['ecx']
push ['0']
call ['_udbg_enumName']
add ['esp,', '8']
push ['eax']
push ['offset', '??_C@_0CG@HIFHPGBG@?5?5?5?5public?5static?5final?5int?5?$CFs?5?$DN@']
mov ['edx,', '[ebp+File]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['short', 'loc_85D']
mov ['esi,', 'esp']
push ['offset', '??_C@_0CO@HIOAAPGG@?5?5?5?5public?5static?5final?5String?5?$FL@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_18],', '0']
jmp ['short', 'loc_8CF']
mov ['eax,', '[ebp+var_18]']
add ['eax,', '1']
mov ['[ebp+var_18],', 'eax']
cmp ['[ebp+var_18],', '6']
jge ['short', 'loc_908']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_18]']
push ['eax']
mov ['ecx,', '[ebp+var_18]']
push ['ecx']
push ['0']
call ['_udbg_enumName']
add ['esp,', '8']
push ['eax']
push ['offset', '??_C@_0BI@JMDOJDDO@?5?5?5?5?5?5?5?5?$CC?$CFs?$CC?0?5?1?$CK?5?$CFd?5?$CK?1?6?$AA@']
mov ['edx,', '[ebp+File]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['short', 'loc_8C6']
mov ['esi,', 'esp']
push ['offset', '??_C@_08HLHAABIM@?5?5?5?5?$HN?$DL?6?6?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['offset', '??_C@_0DA@JPKFFGJF@?5?5?5?5public?5static?5final?5String?5?$FL@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_18],', '0']
jmp ['short', 'loc_956']
mov ['eax,', '[ebp+var_18]']
add ['eax,', '1']
mov ['[ebp+var_18],', 'eax']
cmp ['[ebp+var_18],', '6']
jge ['loc_A30']
mov ['eax,', '[ebp+var_18]']
push ['eax']
call ['_udbg_enumCount']
add ['esp,', '4']
mov ['[ebp+var_24],', 'eax']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_18]']
push ['eax']
mov ['ecx,', '[ebp+var_18]']
push ['ecx']
push ['0']
call ['_udbg_enumName']
add ['esp,', '8']
push ['eax']
push ['offset', '??_C@_0BG@CMFAPGKG@?5?5?5?5?5?5?5?5?1?$CK?5?$CFs?0?5?$CFd?5?$CK?1?6?$AA@']
mov ['edx,', '[ebp+File]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['offset', '??_C@_0M@FJBBBEMD@?5?5?5?5?5?5?5?5?$HL?5?6?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_C],', '0']
jmp ['short', 'loc_9D0']
mov ['eax,', '[ebp+var_C]']
add ['eax,', '1']
mov ['[ebp+var_C],', 'eax']
mov ['eax,', '[ebp+var_C]']
cmp ['eax,', '[ebp+var_24]']
jge ['short', 'loc_A0D']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_C]']
push ['eax']
mov ['ecx,', '[ebp+var_C]']
push ['ecx']
mov ['edx,', '[ebp+var_18]']
push ['edx']
call ['_udbg_enumName']
add ['esp,', '8']
push ['eax']
push ['offset', '??_C@_0BM@GCPEDEFJ@?5?5?5?5?5?5?5?5?5?5?5?$CC?$CFs?$CC?0?5?1?$CK?5?$CFd?5?$CK?1?5?6?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['short', 'loc_9C7']
mov ['esi,', 'esp']
push ['offset', '??_C@_0M@HFGALCHL@?5?5?5?5?5?5?5?5?$HN?0?6?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['loc_94D']
mov ['esi,', 'esp']
push ['offset', '??_C@_08HLHAABIM@?5?5?5?5?$HN?$DL?6?6?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['offset', '??_C@_0CO@ICBACKIC@?5?5?5?5public?5static?5final?5int?5?$FL?$FN?$FL?$FN@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_18],', '0']
jmp ['short', 'loc_A7E']
mov ['eax,', '[ebp+var_18]']
add ['eax,', '1']
mov ['[ebp+var_18],', 'eax']
cmp ['[ebp+var_18],', '6']
jge ['loc_C32']
mov ['eax,', '[ebp+var_18]']
push ['eax']
call ['_udbg_enumCount']
add ['esp,', '4']
mov ['[ebp+var_24],', 'eax']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_18]']
push ['eax']
mov ['ecx,', '[ebp+var_18]']
push ['ecx']
push ['0']
call ['_udbg_enumName']
add ['esp,', '8']
push ['eax']
push ['offset', '??_C@_0BG@CMFAPGKG@?5?5?5?5?5?5?5?5?1?$CK?5?$CFs?0?5?$CFd?5?$CK?1?6?$AA@']
mov ['edx,', '[ebp+File]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['offset', '??_C@_0M@FJBBBEMD@?5?5?5?5?5?5?5?5?$HL?5?6?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_C],', '0']
jmp ['short', 'loc_AF8']
mov ['eax,', '[ebp+var_C]']
add ['eax,', '1']
mov ['[ebp+var_C],', 'eax']
mov ['eax,', '[ebp+var_C]']
cmp ['eax,', '[ebp+var_24]']
jge ['loc_C0F']
mov ['esi,', 'esp']
push ['offset', '??_C@_0M@CKHGFAEI@?5?5?5?5?5?5?5?5?5?5?5?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+var_18]']
mov ['[ebp+var_30C],', 'eax']
cmp ['[ebp+var_30C],', '0']
jle ['loc_BB9']
cmp ['[ebp+var_30C],', '2']
jle ['short', 'loc_B43']
jmp ['short', 'loc_BB9']
cmp ['[ebp+var_18],', '1']
jnz ['short', 'loc_B84']
cmp ['[ebp+var_C],', '16h']
jnz ['short', 'loc_B84']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_C]']
push ['eax']
mov ['ecx,', '[ebp+var_C]']
push ['ecx']
mov ['edx,', '[ebp+var_18]']
push ['edx']
call ['_udbg_enumName']
add ['esp,', '8']
push ['eax']
push ['offset', '??_C@_0CO@LBJNCNFB@com?4ibm?4icu?4util?4ChineseCalendar@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['short', 'loc_BB7']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_C]']
push ['eax']
mov ['ecx,', '[ebp+var_C]']
push ['ecx']
mov ['edx,', '[ebp+var_18]']
push ['edx']
call ['_udbg_enumName']
add ['esp,', '8']
push ['eax']
push ['offset', '??_C@_0CH@JNGKOBOB@com?4ibm?4icu?4util?4Calendar?4?$CFs?0?5?1?$CK@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['short', 'loc_BEC']
mov ['eax,', '[ebp+var_C]']
push ['eax']
mov ['ecx,', '[ebp+var_18]']
push ['ecx']
call ['_udbg_enumName']
add ['esp,', '8']
mov ['esi,', 'esp']
push ['eax']
mov ['edx,', '[ebp+var_C]']
push ['edx']
push ['offset', '??_C@_0N@CCPBFIKD@?$CFd?0?5?1?$CK?5?$CFs?5?$CK?1?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['offset', '??_C@_01EEMJAFIK@?6?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['loc_AEF']
mov ['esi,', 'esp']
push ['offset', '??_C@_0M@HFGALCHL@?5?5?5?5?5?5?5?5?$HN?0?6?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['loc_A75']
mov ['esi,', 'esp']
push ['offset', '??_C@_08HLHAABIM@?5?5?5?5?$HN?$DL?6?6?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['offset', '??_C@_02KGHIDFGE@?$HN?6?$AA@']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fclose']
add ['esp,', '4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['eax,', 'eax']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN31']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
pop ['ebx']
mov ['ecx,', '[ebp+var_4]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '30Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
dd ['offset', '$LN30']
dd ['offset', '$LN29']
align ['4']
assume ['cs:_rdata']
public ['??_C@_02KGHIDFGE@?$HN?6?$AA@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_01EEMJAFIK@?6?$AA@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0N@CCPBFIKD@?$CFd?0?5?1?$CK?5?$CFs?5?$CK?1?$AA@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CH@JNGKOBOB@com?4ibm?4icu?4util?4Calendar?4?$CFs?0?5?1?$CK@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CO@LBJNCNFB@com?4ibm?4icu?4util?4ChineseCalendar@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0M@CKHGFAEI@?5?5?5?5?5?5?5?5?5?5?5?$AA@']
assume ['cs:_rdata']
public ['??_C@_0CO@ICBACKIC@?5?5?5?5public?5static?5final?5int?5?$FL?$FN?$FL?$FN@']
align ['10h']
assume ['cs:_rdata']
public ['??_C@_0M@HFGALCHL@?5?5?5?5?5?5?5?5?$HN?0?6?$AA@']
assume ['cs:_rdata']
public ['??_C@_0BM@GCPEDEFJ@?5?5?5?5?5?5?5?5?5?5?5?$CC?$CFs?$CC?0?5?1?$CK?5?$CFd?5?$CK?1?5?6?$AA@']
assume ['cs:_rdata']
public ['??_C@_0M@FJBBBEMD@?5?5?5?5?5?5?5?5?$HL?5?6?$AA@']
assume ['cs:_rdata']
public ['??_C@_0BG@CMFAPGKG@?5?5?5?5?5?5?5?5?1?$CK?5?$CFs?0?5?$CFd?5?$CK?1?6?$AA@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0DA@JPKFFGJF@?5?5?5?5public?5static?5final?5String?5?$FL@']
assume ['cs:_rdata']
public ['??_C@_08HLHAABIM@?5?5?5?5?$HN?$DL?6?6?$AA@']
db ['0Ah,0']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0BI@JMDOJDDO@?5?5?5?5?5?5?5?5?$CC?$CFs?$CC?0?5?1?$CK?5?$CFd?5?$CK?1?6?$AA@']
assume ['cs:_rdata']
public ['??_C@_0CO@HIOAAPGG@?5?5?5?5public?5static?5final?5String?5?$FL@']
align ['10h']
assume ['cs:_rdata']
public ['??_C@_0CG@HIFHPGBG@?5?5?5?5public?5static?5final?5int?5?$CFs?5?$DN@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0DE@GEDBOIKO@?5?5?5?5public?5static?5final?5String?5I@']
assume ['cs:_rdata']
public ['??_C@_04HBNCPEDB@56?41?$AA@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0DC@HPJGNNPG@public?5class?5DebugUtilitiesData?5@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CF@MKMNJIPJ@package?5com?4ibm?4icu?4dev?4test?4uti@']
db ['0Ah,0']
align ['10h']
assume ['cs:_rdata']
public ['??_C@_0IF@CGMDDOC@?1?$CK?5NOTE?3?5this?5file?5is?5AUTOMATICA@']
db ["'", '*', 'See:', '{ICU4C}/source/data/icu4j-readme.txt', 'for', 'more', "information'"]
db ["'.", "',0Ah"]
db ["'", "**/',0Ah"]
db ['0Ah,0']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0GO@ONAIJNMC@?1?$CK?$CK?5Copyright?5?$CIC?$CJ?52007?9?$CFd?0?5Inter@']
db ["'ation", 'and', 'Others.', 'All', 'Rights', 'Reserved.', "**/',0Ah"]
db ['0Ah,0']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CL@JEAIBBLK@?$CFs?3?5Couldn?8t?5create?5resource?5tes@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0BD@NBBLDIIG@?$CFs?3?5Generating?5?$CFs?6?$AA@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_01NOFIACDB@w?$AA@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0BI@KHJFOGDK@DebugUtilitiesData?4java?$AA@']
assume ['cs:_rdata']
public ['??_C@_01KICIPPFI@?2?$AA@']
extrn ['_genres32:near']
extrn ['__imp__fprintf:near']
extrn ['__imp____iob_func:near']
extrn ['_u_parseArgs:near']
extrn ['_u_getDataDirectory_56:near']
extrn ['@_RTC_CheckStackVars@8:near']
extrn ['__RTC_CheckEsp:near']
extrn ['__RTC_Shutdown:near']
extrn ['__RTC_InitBase:near']
extrn ['_udata_finish:near']
extrn ['_udata_writeString:near']
extrn ['_udata_write16:near']
extrn ['__imp__exit:near']
extrn ['_u_errorName_56:near']
extrn ['_udata_create:near']
extrn ['___security_cookie:near']
extrn ['@__security_check_cookie@4:near']
extrn ['__imp__fclose:near']
extrn ['_udbg_enumCount:near']
extrn ['_udbg_enumName:near']
extrn ['__imp__printf:near']
extrn ['__imp__fopen:near']
extrn ['_strcat:near']
extrn ['_strlen:near']
extrn ['_strcpy:near']
extrn ['_getCurrentYear:near']
end
