_==@8
original code :
push|mov|mov|push|mov|push|call|cmp|call|pop|ret|
disassembled code :

end _==@8
?Extract@CHandler@NLzma@NArchive@@UAGJPBIIHPAUIArchiveExtractCallback@@@Z
original code :
push|mov|push|push|mov|push|push|sub|push|push|push|lea|mov|mov|rep|mov|xor|mov|push|lea|mov|mov|mov|cmp|jne|xor|jmp|cmp|je|cmp|jne|mov|cmp|je|mov|jmp|mov|movzx|test|je|mov|mov|mov|push|mov|push|mov|push|mov|mov|mov|call|cmp|call|lea|call|mov|mov|xor|cmp|setne|mov|lea|call|mov|mov|mov|push|mov|push|push|mov|push|mov|mov|mov|call|cmp|call|mov|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|jmp|cmp|jne|lea|call|mov|movzx|test|je|mov|mov|lea|call|mov|jmp|mov|mov|push|mov|push|mov|mov|mov|call|cmp|call|push|call|add|mov|mov|mov|mov|cmp|je|mov|call|mov|mov|mov|jmp|mov|mov|mov|mov|mov|mov|mov|push|lea|call|mov|lea|call|mov|mov|push|mov|call|mov|call|lea|call|push|call|add|mov|mov|mov|mov|cmp|je|mov|call|mov|mov|mov|jmp|mov|mov|mov|mov|mov|mov|mov|push|lea|call|mov|push|mov|push|mov|call|mov|movzx|test|je|mov|add|call|mov|movzx|test|je|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|mov|add|call|mov|mov|mov|mov|push|push|push|push|mov|push|mov|mov|mov|call|cmp|call|mov|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|jmp|mov|mov|lea|call|mov|mov|mov|add|call|mov|mov|push|mov|movzx|push|lea|call|mov|mov|mov|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|call|mov|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|mov|mov|call|mov|mov|mov|lea|push|mov|push|lea|push|lea|call|mov|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|mov|cmp|je|cmp|je|mov|jmp|mov|movzx|push|lea|push|lea|call|mov|movzx|test|jne|mov|jmp|mov|add|mov|adc|mov|mov|mov|lea|call|mov|lea|call|mov|mov|push|mov|push|lea|push|lea|call|mov|mov|mov|lea|call|mov|mov|mov|mov|mov|mov|mov|call|mov|mov|mov|mov|mov|mov|cmp|jne|mov|mov|mov|jmp|cmp|jne|jmp|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|jmp|movzx|test|je|mov|mov|mov|jmp|cmp|je|cmp|jne|movzx|test|je|mov|mov|jmp|mov|movzx|test|je|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|movzx|test|jne|mov|jmp|mov|movzx|test|je|mov|jmp|mov|movzx|test|je|mov|jmp|mov|movzx|test|je|mov|jmp|cmp|jne|mov|jmp|cmp|jne|mov|jmp|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|lea|call|mov|mov|push|mov|push|mov|mov|mov|call|cmp|call|mov|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|mov|mov|mov|ret|mov|ret|mov|jmp|mov|push|mov|push|lea|call|pop|pop|mov|mov|pop|pop|pop|pop|mov|xor|call|add|cmp|call|mov|pop|ret|
disassembled code :
push|mov|push|push|mov|push|push|sub|push|push|push|lea|mov|mov|rep|mov|xor|mov|push|lea|mov|mov|mov|cmp|jne|xor|jmp|cmp|je|cmp|jne|mov|cmp|je|mov|jmp|mov|movzx|test|je|mov|mov|mov|push|mov|push|mov|push|mov|mov|mov|call|cmp|call|lea|call|mov|mov|xor|cmp|setne|mov|lea|call|mov|mov|mov|push|mov|push|push|mov|push|mov|mov|mov|call|cmp|call|mov|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|jmp|cmp|jne|lea|call|mov|movzx|test|je|mov|mov|lea|call|mov|jmp|mov|mov|push|mov|push|mov|mov|mov|call|cmp|call|push|call|add|mov|mov|mov|mov|cmp|je|mov|call|mov|mov|mov|jmp|mov|mov|mov|mov|mov|mov|mov|push|lea|call|mov|lea|call|mov|mov|push|mov|call|mov|call|lea|call|push|call|add|mov|mov|mov|mov|cmp|je|mov|call|mov|mov|mov|jmp|mov|mov|mov|mov|mov|mov|mov|push|lea|call|mov|push|mov|push|mov|call|mov|movzx|test|je|mov|add|call|mov|movzx|test|je|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|mov|add|call|mov|mov|mov|mov|push|push|push|push|mov|push|mov|mov|mov|call|cmp|call|mov|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|jmp|mov|mov|lea|call|mov|mov|mov|add|call|mov|mov|push|mov|movzx|push|lea|call|mov|mov|mov|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|call|mov|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|mov|mov|call|mov|mov|mov|lea|push|mov|push|lea|push|lea|call|mov|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|mov|cmp|je|cmp|je|mov|jmp|mov|movzx|push|lea|push|lea|call|mov|movzx|test|jne|mov|jmp|mov|add|mov|adc|mov|mov|mov|lea|call|mov|lea|call|mov|mov|push|mov|push|lea|push|lea|call|mov|mov|mov|lea|call|mov|mov|mov|mov|mov|mov|mov|call|mov|mov|mov|mov|mov|mov|cmp|jne|mov|mov|mov|jmp|cmp|jne|jmp|mov|mov|cmp|je|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|jmp|movzx|test|je|mov|mov|mov|jmp|cmp|je|cmp|jne|movzx|test|je|mov|mov|jmp|mov|movzx|test|je|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|mov|movzx|test|jne|mov|jmp|mov|movzx|test|je|mov|jmp|mov|movzx|test|je|mov|jmp|mov|movzx|test|je|mov|jmp|cmp|jne|mov|jmp|cmp|jne|mov|jmp|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|lea|call|mov|mov|push|mov|push|mov|mov|mov|call|cmp|call|mov|mov|mov|mov|lea|call|mov|lea|call|mov|lea|call|mov|lea|call|mov|jmp|

end ?Extract@CHandler@NLzma@NArchive@@UAGJPBIIHPAUIArchiveExtractCallback@@@Z
