; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	D:\mozilla\intl\icu\source\i18n\coptccal.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?value@?$integral_constant@_N$0A@@tr1@std@@2_NB	; std::tr1::integral_constant<bool,0>::value
PUBLIC	?value@?$integral_constant@_N$00@tr1@std@@2_NB	; std::tr1::integral_constant<bool,1>::value
PUBLIC	?value@?$integral_constant@I$0A@@tr1@std@@2IB	; std::tr1::integral_constant<unsigned int,0>::value
PUBLIC	?_Rank@?$_Arithmetic_traits@_N@std@@2HB		; std::_Arithmetic_traits<bool>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@D@std@@2HB		; std::_Arithmetic_traits<char>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@C@std@@2HB		; std::_Arithmetic_traits<signed char>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@E@std@@2HB		; std::_Arithmetic_traits<unsigned char>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@F@std@@2HB		; std::_Arithmetic_traits<short>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@G@std@@2HB		; std::_Arithmetic_traits<unsigned short>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@H@std@@2HB		; std::_Arithmetic_traits<int>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@I@std@@2HB		; std::_Arithmetic_traits<unsigned int>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@J@std@@2HB		; std::_Arithmetic_traits<long>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@K@std@@2HB		; std::_Arithmetic_traits<unsigned long>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@_J@std@@2HB		; std::_Arithmetic_traits<__int64>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@_K@std@@2HB		; std::_Arithmetic_traits<unsigned __int64>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@M@std@@2HB		; std::_Arithmetic_traits<float>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@N@std@@2HB		; std::_Arithmetic_traits<double>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@O@std@@2HB		; std::_Arithmetic_traits<long double>::_Rank
PUBLIC	?collate@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::collate
PUBLIC	?ctype@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::ctype
PUBLIC	?monetary@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::monetary
PUBLIC	?numeric@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::numeric
PUBLIC	?time@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::time
PUBLIC	?messages@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::messages
PUBLIC	?all@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::all
PUBLIC	?none@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::none
PUBLIC	?skipws@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::skipws
PUBLIC	?unitbuf@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::unitbuf
PUBLIC	?uppercase@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::uppercase
PUBLIC	?showbase@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::showbase
PUBLIC	?showpoint@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::showpoint
PUBLIC	?showpos@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::showpos
PUBLIC	?left@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::left
PUBLIC	?right@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::right
PUBLIC	?internal@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::internal
PUBLIC	?dec@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::dec
PUBLIC	?oct@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::oct
PUBLIC	?hex@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::hex
PUBLIC	?scientific@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::scientific
PUBLIC	?fixed@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::fixed
PUBLIC	?hexfloat@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::hexfloat
PUBLIC	?boolalpha@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::boolalpha
PUBLIC	?_Stdio@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::_Stdio
PUBLIC	?adjustfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::adjustfield
PUBLIC	?basefield@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::basefield
PUBLIC	?floatfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::floatfield
PUBLIC	?goodbit@?$_Iosb@H@std@@2W4_Iostate@12@B	; std::_Iosb<int>::goodbit
PUBLIC	?eofbit@?$_Iosb@H@std@@2W4_Iostate@12@B		; std::_Iosb<int>::eofbit
PUBLIC	?failbit@?$_Iosb@H@std@@2W4_Iostate@12@B	; std::_Iosb<int>::failbit
PUBLIC	?badbit@?$_Iosb@H@std@@2W4_Iostate@12@B		; std::_Iosb<int>::badbit
PUBLIC	?_Hardfail@?$_Iosb@H@std@@2W4_Iostate@12@B	; std::_Iosb<int>::_Hardfail
PUBLIC	?in@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::in
PUBLIC	?out@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::out
PUBLIC	?ate@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::ate
PUBLIC	?app@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::app
PUBLIC	?trunc@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::trunc
PUBLIC	?_Nocreate@?$_Iosb@H@std@@2W4_Openmode@12@B	; std::_Iosb<int>::_Nocreate
PUBLIC	?_Noreplace@?$_Iosb@H@std@@2W4_Openmode@12@B	; std::_Iosb<int>::_Noreplace
PUBLIC	?binary@?$_Iosb@H@std@@2W4_Openmode@12@B	; std::_Iosb<int>::binary
PUBLIC	?beg@?$_Iosb@H@std@@2W4_Seekdir@12@B		; std::_Iosb<int>::beg
PUBLIC	?cur@?$_Iosb@H@std@@2W4_Seekdir@12@B		; std::_Iosb<int>::cur
PUBLIC	?end@?$_Iosb@H@std@@2W4_Seekdir@12@B		; std::_Iosb<int>::end
_BSS	SEGMENT
?classID@?1??getStaticClassID@CopticCalendar@icu_56@@SAPAXXZ@4DA DB 01H DUP (?) ; `icu_56::CopticCalendar::getStaticClassID'::`2'::classID
	ALIGN	4

_gSystemDefaultCenturyInit DQ 01H DUP (?)
_BSS	ENDS
_DATA	SEGMENT
_gSystemDefaultCenturyStart DQ 00010000000000000r ; 2.22507e-308
_gSystemDefaultCenturyStartYear DD 0ffffffffH
_DATA	ENDS
;	COMDAT ?end@?$_Iosb@H@std@@2W4_Seekdir@12@B
CONST	SEGMENT
?end@?$_Iosb@H@std@@2W4_Seekdir@12@B DD 02H		; std::_Iosb<int>::end
CONST	ENDS
;	COMDAT ?cur@?$_Iosb@H@std@@2W4_Seekdir@12@B
CONST	SEGMENT
?cur@?$_Iosb@H@std@@2W4_Seekdir@12@B DD 01H		; std::_Iosb<int>::cur
CONST	ENDS
;	COMDAT ?beg@?$_Iosb@H@std@@2W4_Seekdir@12@B
CONST	SEGMENT
?beg@?$_Iosb@H@std@@2W4_Seekdir@12@B DD 00H		; std::_Iosb<int>::beg
CONST	ENDS
;	COMDAT ?binary@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?binary@?$_Iosb@H@std@@2W4_Openmode@12@B DD 020H	; std::_Iosb<int>::binary
CONST	ENDS
;	COMDAT ?_Noreplace@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?_Noreplace@?$_Iosb@H@std@@2W4_Openmode@12@B DD 080H	; std::_Iosb<int>::_Noreplace
CONST	ENDS
;	COMDAT ?_Nocreate@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?_Nocreate@?$_Iosb@H@std@@2W4_Openmode@12@B DD 040H	; std::_Iosb<int>::_Nocreate
CONST	ENDS
;	COMDAT ?trunc@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?trunc@?$_Iosb@H@std@@2W4_Openmode@12@B DD 010H		; std::_Iosb<int>::trunc
CONST	ENDS
;	COMDAT ?app@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?app@?$_Iosb@H@std@@2W4_Openmode@12@B DD 08H		; std::_Iosb<int>::app
CONST	ENDS
;	COMDAT ?ate@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?ate@?$_Iosb@H@std@@2W4_Openmode@12@B DD 04H		; std::_Iosb<int>::ate
CONST	ENDS
;	COMDAT ?out@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?out@?$_Iosb@H@std@@2W4_Openmode@12@B DD 02H		; std::_Iosb<int>::out
CONST	ENDS
;	COMDAT ?in@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?in@?$_Iosb@H@std@@2W4_Openmode@12@B DD 01H		; std::_Iosb<int>::in
CONST	ENDS
;	COMDAT ?_Hardfail@?$_Iosb@H@std@@2W4_Iostate@12@B
CONST	SEGMENT
?_Hardfail@?$_Iosb@H@std@@2W4_Iostate@12@B DD 010H	; std::_Iosb<int>::_Hardfail
CONST	ENDS
;	COMDAT ?badbit@?$_Iosb@H@std@@2W4_Iostate@12@B
CONST	SEGMENT
?badbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 04H		; std::_Iosb<int>::badbit
CONST	ENDS
;	COMDAT ?failbit@?$_Iosb@H@std@@2W4_Iostate@12@B
CONST	SEGMENT
?failbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 02H		; std::_Iosb<int>::failbit
CONST	ENDS
;	COMDAT ?eofbit@?$_Iosb@H@std@@2W4_Iostate@12@B
CONST	SEGMENT
?eofbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 01H		; std::_Iosb<int>::eofbit
CONST	ENDS
;	COMDAT ?goodbit@?$_Iosb@H@std@@2W4_Iostate@12@B
CONST	SEGMENT
?goodbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 00H		; std::_Iosb<int>::goodbit
CONST	ENDS
;	COMDAT ?floatfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?floatfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 03000H	; std::_Iosb<int>::floatfield
CONST	ENDS
;	COMDAT ?basefield@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?basefield@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0e00H	; std::_Iosb<int>::basefield
CONST	ENDS
;	COMDAT ?adjustfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?adjustfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 01c0H	; std::_Iosb<int>::adjustfield
CONST	ENDS
;	COMDAT ?_Stdio@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?_Stdio@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 08000H	; std::_Iosb<int>::_Stdio
CONST	ENDS
;	COMDAT ?boolalpha@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?boolalpha@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 04000H	; std::_Iosb<int>::boolalpha
CONST	ENDS
;	COMDAT ?hexfloat@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?hexfloat@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 03000H	; std::_Iosb<int>::hexfloat
CONST	ENDS
;	COMDAT ?fixed@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?fixed@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 02000H	; std::_Iosb<int>::fixed
CONST	ENDS
;	COMDAT ?scientific@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?scientific@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 01000H	; std::_Iosb<int>::scientific
CONST	ENDS
;	COMDAT ?hex@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?hex@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0800H		; std::_Iosb<int>::hex
CONST	ENDS
;	COMDAT ?oct@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?oct@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0400H		; std::_Iosb<int>::oct
CONST	ENDS
;	COMDAT ?dec@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?dec@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0200H		; std::_Iosb<int>::dec
CONST	ENDS
;	COMDAT ?internal@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?internal@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0100H	; std::_Iosb<int>::internal
CONST	ENDS
;	COMDAT ?right@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?right@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 080H		; std::_Iosb<int>::right
CONST	ENDS
;	COMDAT ?left@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?left@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 040H		; std::_Iosb<int>::left
CONST	ENDS
;	COMDAT ?showpos@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?showpos@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 020H	; std::_Iosb<int>::showpos
CONST	ENDS
;	COMDAT ?showpoint@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?showpoint@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 010H	; std::_Iosb<int>::showpoint
CONST	ENDS
;	COMDAT ?showbase@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?showbase@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 08H	; std::_Iosb<int>::showbase
CONST	ENDS
;	COMDAT ?uppercase@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?uppercase@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 04H	; std::_Iosb<int>::uppercase
CONST	ENDS
;	COMDAT ?unitbuf@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?unitbuf@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 02H	; std::_Iosb<int>::unitbuf
CONST	ENDS
;	COMDAT ?skipws@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?skipws@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 01H		; std::_Iosb<int>::skipws
CONST	ENDS
;	COMDAT ?none@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?none@?$_Locbase@H@std@@2HB DD 00H			; std::_Locbase<int>::none
CONST	ENDS
;	COMDAT ?all@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?all@?$_Locbase@H@std@@2HB DD 03fH			; std::_Locbase<int>::all
CONST	ENDS
;	COMDAT ?messages@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?messages@?$_Locbase@H@std@@2HB DD 020H			; std::_Locbase<int>::messages
CONST	ENDS
;	COMDAT ?time@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?time@?$_Locbase@H@std@@2HB DD 010H			; std::_Locbase<int>::time
CONST	ENDS
;	COMDAT ?numeric@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?numeric@?$_Locbase@H@std@@2HB DD 08H			; std::_Locbase<int>::numeric
CONST	ENDS
;	COMDAT ?monetary@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?monetary@?$_Locbase@H@std@@2HB DD 04H			; std::_Locbase<int>::monetary
CONST	ENDS
;	COMDAT ?ctype@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?ctype@?$_Locbase@H@std@@2HB DD 02H			; std::_Locbase<int>::ctype
CONST	ENDS
;	COMDAT ?collate@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?collate@?$_Locbase@H@std@@2HB DD 01H			; std::_Locbase<int>::collate
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@O@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@O@std@@2HB DD 09H		; std::_Arithmetic_traits<long double>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@N@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@N@std@@2HB DD 08H		; std::_Arithmetic_traits<double>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@M@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@M@std@@2HB DD 07H		; std::_Arithmetic_traits<float>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@_K@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@_K@std@@2HB DD 06H		; std::_Arithmetic_traits<unsigned __int64>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@_J@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@_J@std@@2HB DD 06H		; std::_Arithmetic_traits<__int64>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@K@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@K@std@@2HB DD 05H		; std::_Arithmetic_traits<unsigned long>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@J@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@J@std@@2HB DD 05H		; std::_Arithmetic_traits<long>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@I@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@I@std@@2HB DD 04H		; std::_Arithmetic_traits<unsigned int>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@H@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@H@std@@2HB DD 04H		; std::_Arithmetic_traits<int>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@G@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@G@std@@2HB DD 03H		; std::_Arithmetic_traits<unsigned short>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@F@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@F@std@@2HB DD 03H		; std::_Arithmetic_traits<short>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@E@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@E@std@@2HB DD 02H		; std::_Arithmetic_traits<unsigned char>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@C@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@C@std@@2HB DD 02H		; std::_Arithmetic_traits<signed char>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@D@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@D@std@@2HB DD 02H		; std::_Arithmetic_traits<char>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@_N@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@_N@std@@2HB DD 01H		; std::_Arithmetic_traits<bool>::_Rank
CONST	ENDS
;	COMDAT ?value@?$integral_constant@I$0A@@tr1@std@@2IB
CONST	SEGMENT
?value@?$integral_constant@I$0A@@tr1@std@@2IB DD 00H	; std::tr1::integral_constant<unsigned int,0>::value
CONST	ENDS
;	COMDAT ?value@?$integral_constant@_N$00@tr1@std@@2_NB
CONST	SEGMENT
?value@?$integral_constant@_N$00@tr1@std@@2_NB DB 01H	; std::tr1::integral_constant<bool,1>::value
CONST	ENDS
;	COMDAT ?value@?$integral_constant@_N$0A@@tr1@std@@2_NB
CONST	SEGMENT
?value@?$integral_constant@_N$0A@@tr1@std@@2_NB DB 00H	; std::tr1::integral_constant<bool,0>::value
CONST	ENDS
PUBLIC	??2@YAPAXI@Z					; operator new
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File d:\mozilla\intl\icu\include\unicode\utypes.h
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT ??2@YAPAXI@Z
_TEXT	SEGMENT
_q$ = -8						; size = 4
___formal$ = 8						; size = 4
??2@YAPAXI@Z PROC					; operator new, COMDAT
; Line 411
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 412
	mov	DWORD PTR _q$[ebp], 0
; Line 413
	mov	eax, DWORD PTR _q$[ebp]
	mov	BYTE PTR [eax], 5
; Line 414
	mov	eax, DWORD PTR _q$[ebp]
; Line 415
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
??2@YAPAXI@Z ENDP					; operator new
_TEXT	ENDS
PUBLIC	??3@YAXPAX@Z					; operator delete
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??3@YAXPAX@Z
_TEXT	SEGMENT
_q$ = -8						; size = 4
___formal$ = 8						; size = 4
??3@YAXPAX@Z PROC					; operator delete, COMDAT
; Line 439
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 440
	mov	DWORD PTR _q$[ebp], 0
; Line 441
	mov	eax, DWORD PTR _q$[ebp]
	mov	BYTE PTR [eax], 5
; Line 442
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
??3@YAXPAX@Z ENDP					; operator delete
_TEXT	ENDS
PUBLIC	??9TimeZone@icu_56@@QBECABV01@@Z		; icu_56::TimeZone::operator!=
EXTRN	__RTC_CheckEsp:PROC
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??9TimeZone@icu_56@@QBECABV01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_that$ = 8						; size = 4
??9TimeZone@icu_56@@QBECABV01@@Z PROC			; icu_56::TimeZone::operator!=, COMDAT
; _this$ = ecx
; File d:\mozilla\intl\icu\source\i18n\unicode\timezone.h
; Line 455
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	esi, esp
	mov	eax, DWORD PTR _that$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+8]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	movsx	ecx, al
	test	ecx, ecx
	sete	al
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??9TimeZone@icu_56@@QBECABV01@@Z ENDP			; icu_56::TimeZone::operator!=
_TEXT	ENDS
PUBLIC	?getID@TimeZone@icu_56@@QBEAAVUnicodeString@2@AAV32@@Z ; icu_56::TimeZone::getID
EXTRN	__imp_??4UnicodeString@icu_56@@QAEAAV01@ABV01@@Z:PROC
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?getID@TimeZone@icu_56@@QBEAAVUnicodeString@2@AAV32@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_ID$ = 8						; size = 4
?getID@TimeZone@icu_56@@QBEAAVUnicodeString@2@AAV32@@Z PROC ; icu_56::TimeZone::getID, COMDAT
; _this$ = ecx
; Line 951
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 952
	mov	eax, DWORD PTR _this$[ebp]
	add	eax, 4
	mov	esi, esp
	push	eax
	mov	ecx, DWORD PTR _ID$[ebp]
	call	DWORD PTR __imp_??4UnicodeString@icu_56@@QAEAAV01@ABV01@@Z
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 953
	mov	eax, DWORD PTR _ID$[ebp]
; Line 954
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?getID@TimeZone@icu_56@@QBEAAVUnicodeString@2@AAV32@@Z ENDP ; icu_56::TimeZone::getID
_TEXT	ENDS
PUBLIC	?setID@TimeZone@icu_56@@QAEXABVUnicodeString@2@@Z ; icu_56::TimeZone::setID
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?setID@TimeZone@icu_56@@QAEXABVUnicodeString@2@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_ID$ = 8						; size = 4
?setID@TimeZone@icu_56@@QAEXABVUnicodeString@2@@Z PROC	; icu_56::TimeZone::setID, COMDAT
; _this$ = ecx
; Line 960
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 961
	mov	esi, esp
	mov	eax, DWORD PTR _ID$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	DWORD PTR __imp_??4UnicodeString@icu_56@@QAEAAV01@ABV01@@Z
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 962
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?setID@TimeZone@icu_56@@QAEXABVUnicodeString@2@@Z ENDP	; icu_56::TimeZone::setID
_TEXT	ENDS
PUBLIC	?getTime@Calendar@icu_56@@QBENAAW4UErrorCode@@@Z ; icu_56::Calendar::getTime
EXTRN	?getTimeInMillis@Calendar@icu_56@@IBENAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::getTimeInMillis
EXTRN	__fltused:DWORD
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?getTime@Calendar@icu_56@@QBENAAW4UErrorCode@@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_status$ = 8						; size = 4
?getTime@Calendar@icu_56@@QBENAAW4UErrorCode@@@Z PROC	; icu_56::Calendar::getTime, COMDAT
; _this$ = ecx
; File d:\mozilla\intl\icu\source\i18n\unicode\calendar.h
; Line 441
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _status$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?getTimeInMillis@Calendar@icu_56@@IBENAAW4UErrorCode@@@Z ; icu_56::Calendar::getTimeInMillis
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?getTime@Calendar@icu_56@@QBENAAW4UErrorCode@@@Z ENDP	; icu_56::Calendar::getTime
_TEXT	ENDS
PUBLIC	?setTime@Calendar@icu_56@@QAEXNAAW4UErrorCode@@@Z ; icu_56::Calendar::setTime
EXTRN	?setTimeInMillis@Calendar@icu_56@@IAEXNAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::setTimeInMillis
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?setTime@Calendar@icu_56@@QAEXNAAW4UErrorCode@@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_date$ = 8						; size = 8
_status$ = 16						; size = 4
?setTime@Calendar@icu_56@@QAEXNAAW4UErrorCode@@@Z PROC	; icu_56::Calendar::setTime, COMDAT
; _this$ = ecx
; Line 453
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _status$[ebp]
	push	eax
	sub	esp, 8
	fld	QWORD PTR _date$[ebp]
	fstp	QWORD PTR [esp]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?setTimeInMillis@Calendar@icu_56@@IAEXNAAW4UErrorCode@@@Z ; icu_56::Calendar::setTimeInMillis
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?setTime@Calendar@icu_56@@QAEXNAAW4UErrorCode@@@Z ENDP	; icu_56::Calendar::setTime
_TEXT	ENDS
PUBLIC	??9Calendar@icu_56@@QBECABV01@@Z		; icu_56::Calendar::operator!=
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??9Calendar@icu_56@@QBECABV01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_that$ = 8						; size = 4
??9Calendar@icu_56@@QBECABV01@@Z PROC			; icu_56::Calendar::operator!=, COMDAT
; _this$ = ecx
; Line 476
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	esi, esp
	mov	eax, DWORD PTR _that$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+12]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	movsx	ecx, al
	test	ecx, ecx
	sete	al
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??9Calendar@icu_56@@QBECABV01@@Z ENDP			; icu_56::Calendar::operator!=
_TEXT	ENDS
PUBLIC	?internalGet@Calendar@icu_56@@IBEHW4EDateFields@12@@Z ; icu_56::Calendar::internalGet
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?internalGet@Calendar@icu_56@@IBEHW4EDateFields@12@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_field$ = 8						; size = 4
?internalGet@Calendar@icu_56@@IBEHW4EDateFields@12@@Z PROC ; icu_56::Calendar::internalGet, COMDAT
; _this$ = ecx
; Line 1545
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _field$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [ecx+eax*4+8]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
?internalGet@Calendar@icu_56@@IBEHW4EDateFields@12@@Z ENDP ; icu_56::Calendar::internalGet
_TEXT	ENDS
PUBLIC	?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalGet
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@H@Z
_TEXT	SEGMENT
tv71 = -208						; size = 4
_this$ = -8						; size = 4
_field$ = 8						; size = 4
_defaultValue$ = 12					; size = 4
?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@H@Z PROC ; icu_56::Calendar::internalGet, COMDAT
; _this$ = ecx
; Line 1559
	push	ebp
	mov	ebp, esp
	sub	esp, 208				; 000000d0H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-208]
	mov	ecx, 52					; 00000034H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _field$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [ecx+eax*4+124], 0
	jle	SHORT $LN3@internalGe
	mov	edx, DWORD PTR _field$[ebp]
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+edx*4+8]
	mov	DWORD PTR tv71[ebp], ecx
	jmp	SHORT $LN4@internalGe
$LN3@internalGe:
	mov	edx, DWORD PTR _defaultValue$[ebp]
	mov	DWORD PTR tv71[ebp], edx
$LN4@internalGe:
	mov	eax, DWORD PTR tv71[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	8
?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@H@Z ENDP ; icu_56::Calendar::internalGet
_TEXT	ENDS
PUBLIC	?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@@Z ; icu_56::Calendar::internalGet
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_field$ = 8						; size = 4
?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@@Z PROC ; icu_56::Calendar::internalGet, COMDAT
; _this$ = ecx
; Line 1569
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _field$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [ecx+eax*4+8]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@@Z ENDP ; icu_56::Calendar::internalGet
_TEXT	ENDS
PUBLIC	?internalGetTime@Calendar@icu_56@@IBENXZ	; icu_56::Calendar::internalGetTime
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?internalGetTime@Calendar@icu_56@@IBENXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?internalGetTime@Calendar@icu_56@@IBENXZ PROC		; icu_56::Calendar::internalGetTime, COMDAT
; _this$ = ecx
; Line 1898
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	fld	QWORD PTR [eax+224]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?internalGetTime@Calendar@icu_56@@IBENXZ ENDP		; icu_56::Calendar::internalGetTime
_TEXT	ENDS
PUBLIC	?internalSetTime@Calendar@icu_56@@IAEXN@Z	; icu_56::Calendar::internalSetTime
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?internalSetTime@Calendar@icu_56@@IAEXN@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_time$ = 8						; size = 8
?internalSetTime@Calendar@icu_56@@IAEXN@Z PROC		; icu_56::Calendar::internalSetTime, COMDAT
; _this$ = ecx
; Line 1907
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	fld	QWORD PTR _time$[ebp]
	fstp	QWORD PTR [eax+224]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	8
?internalSetTime@Calendar@icu_56@@IAEXN@Z ENDP		; icu_56::Calendar::internalSetTime
_TEXT	ENDS
PUBLIC	?getGregorianYear@Calendar@icu_56@@IBEHXZ	; icu_56::Calendar::getGregorianYear
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?getGregorianYear@Calendar@icu_56@@IBEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?getGregorianYear@Calendar@icu_56@@IBEHXZ PROC		; icu_56::Calendar::getGregorianYear, COMDAT
; _this$ = ecx
; Line 1970
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 1971
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+272]
; Line 1972
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?getGregorianYear@Calendar@icu_56@@IBEHXZ ENDP		; icu_56::Calendar::getGregorianYear
_TEXT	ENDS
PUBLIC	?getGregorianMonth@Calendar@icu_56@@IBEHXZ	; icu_56::Calendar::getGregorianMonth
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?getGregorianMonth@Calendar@icu_56@@IBEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?getGregorianMonth@Calendar@icu_56@@IBEHXZ PROC		; icu_56::Calendar::getGregorianMonth, COMDAT
; _this$ = ecx
; Line 1979
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 1980
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+276]
; Line 1981
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?getGregorianMonth@Calendar@icu_56@@IBEHXZ ENDP		; icu_56::Calendar::getGregorianMonth
_TEXT	ENDS
PUBLIC	?getGregorianDayOfYear@Calendar@icu_56@@IBEHXZ	; icu_56::Calendar::getGregorianDayOfYear
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?getGregorianDayOfYear@Calendar@icu_56@@IBEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?getGregorianDayOfYear@Calendar@icu_56@@IBEHXZ PROC	; icu_56::Calendar::getGregorianDayOfYear, COMDAT
; _this$ = ecx
; Line 1988
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 1989
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+280]
; Line 1990
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?getGregorianDayOfYear@Calendar@icu_56@@IBEHXZ ENDP	; icu_56::Calendar::getGregorianDayOfYear
_TEXT	ENDS
PUBLIC	?getGregorianDayOfMonth@Calendar@icu_56@@IBEHXZ	; icu_56::Calendar::getGregorianDayOfMonth
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?getGregorianDayOfMonth@Calendar@icu_56@@IBEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?getGregorianDayOfMonth@Calendar@icu_56@@IBEHXZ PROC	; icu_56::Calendar::getGregorianDayOfMonth, COMDAT
; _this$ = ecx
; Line 1997
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 1998
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+284]
; Line 1999
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?getGregorianDayOfMonth@Calendar@icu_56@@IBEHXZ ENDP	; icu_56::Calendar::getGregorianDayOfMonth
_TEXT	ENDS
PUBLIC	?createInstance@Calendar@icu_56@@SAPAV12@PAVTimeZone@2@AAW4UErrorCode@@@Z ; icu_56::Calendar::createInstance
EXTRN	?createInstance@Calendar@icu_56@@SAPAV12@PAVTimeZone@2@ABVLocale@2@AAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::createInstance
EXTRN	__imp_?getDefault@Locale@icu_56@@SAABV12@XZ:PROC
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?createInstance@Calendar@icu_56@@SAPAV12@PAVTimeZone@2@AAW4UErrorCode@@@Z
_TEXT	SEGMENT
_zone$ = 8						; size = 4
_errorCode$ = 12					; size = 4
?createInstance@Calendar@icu_56@@SAPAV12@PAVTimeZone@2@AAW4UErrorCode@@@Z PROC ; icu_56::Calendar::createInstance, COMDAT
; Line 2500
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 2502
	mov	eax, DWORD PTR _errorCode$[ebp]
	push	eax
	mov	esi, esp
	call	DWORD PTR __imp_?getDefault@Locale@icu_56@@SAABV12@XZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	push	eax
	mov	ecx, DWORD PTR _zone$[ebp]
	push	ecx
	call	?createInstance@Calendar@icu_56@@SAPAV12@PAVTimeZone@2@ABVLocale@2@AAW4UErrorCode@@@Z ; icu_56::Calendar::createInstance
	add	esp, 12					; 0000000cH
; Line 2503
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?createInstance@Calendar@icu_56@@SAPAV12@PAVTimeZone@2@AAW4UErrorCode@@@Z ENDP ; icu_56::Calendar::createInstance
_TEXT	ENDS
PUBLIC	?roll@Calendar@icu_56@@QAEXW4UCalendarDateFields@@CAAW4UErrorCode@@@Z ; icu_56::Calendar::roll
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?roll@Calendar@icu_56@@QAEXW4UCalendarDateFields@@CAAW4UErrorCode@@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_field$ = 8						; size = 4
_up$ = 12						; size = 1
_status$ = 16						; size = 4
?roll@Calendar@icu_56@@QAEXW4UCalendarDateFields@@CAAW4UErrorCode@@@Z PROC ; icu_56::Calendar::roll, COMDAT
; _this$ = ecx
; Line 2509
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 2510
	mov	esi, esp
	mov	eax, DWORD PTR _status$[ebp]
	push	eax
	movsx	ecx, BYTE PTR _up$[ebp]
	neg	ecx
	sbb	ecx, ecx
	and	ecx, 2
	add	ecx, -1
	push	ecx
	mov	edx, DWORD PTR _field$[ebp]
	push	edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+28]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 2511
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?roll@Calendar@icu_56@@QAEXW4UCalendarDateFields@@CAAW4UErrorCode@@@Z ENDP ; icu_56::Calendar::roll
_TEXT	ENDS
PUBLIC	?roll@Calendar@icu_56@@QAEXW4EDateFields@12@CAAW4UErrorCode@@@Z ; icu_56::Calendar::roll
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?roll@Calendar@icu_56@@QAEXW4EDateFields@12@CAAW4UErrorCode@@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_field$ = 8						; size = 4
_up$ = 12						; size = 1
_status$ = 16						; size = 4
?roll@Calendar@icu_56@@QAEXW4EDateFields@12@CAAW4UErrorCode@@@Z PROC ; icu_56::Calendar::roll, COMDAT
; _this$ = ecx
; Line 2516
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 2517
	mov	eax, DWORD PTR _status$[ebp]
	push	eax
	movzx	ecx, BYTE PTR _up$[ebp]
	push	ecx
	mov	edx, DWORD PTR _field$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?roll@Calendar@icu_56@@QAEXW4UCalendarDateFields@@CAAW4UErrorCode@@@Z ; icu_56::Calendar::roll
; Line 2518
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?roll@Calendar@icu_56@@QAEXW4EDateFields@12@CAAW4UErrorCode@@@Z ENDP ; icu_56::Calendar::roll
_TEXT	ENDS
PUBLIC	?internalSet@Calendar@icu_56@@IAEXW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalSet
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?internalSet@Calendar@icu_56@@IAEXW4UCalendarDateFields@@H@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_field$ = 8						; size = 4
_value$ = 12						; size = 4
?internalSet@Calendar@icu_56@@IAEXW4UCalendarDateFields@@H@Z PROC ; icu_56::Calendar::internalSet, COMDAT
; _this$ = ecx
; Line 2531
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 2532
	mov	eax, DWORD PTR _field$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _value$[ebp]
	mov	DWORD PTR [ecx+eax*4+8], edx
; Line 2533
	mov	eax, DWORD PTR _field$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+eax*4+124], 1
; Line 2534
	mov	eax, DWORD PTR _this$[ebp]
	add	eax, DWORD PTR _field$[ebp]
	mov	BYTE PTR [eax+100], 1
; Line 2535
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	8
?internalSet@Calendar@icu_56@@IAEXW4UCalendarDateFields@@H@Z ENDP ; icu_56::Calendar::internalSet
_TEXT	ENDS
PUBLIC	?weekNumber@Calendar@icu_56@@IAEHHH@Z		; icu_56::Calendar::weekNumber
EXTRN	?weekNumber@Calendar@icu_56@@IAEHHHH@Z:PROC	; icu_56::Calendar::weekNumber
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?weekNumber@Calendar@icu_56@@IAEHHH@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_dayOfPeriod$ = 8					; size = 4
_dayOfWeek$ = 12					; size = 4
?weekNumber@Calendar@icu_56@@IAEHHH@Z PROC		; icu_56::Calendar::weekNumber, COMDAT
; _this$ = ecx
; Line 2540
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 2541
	mov	eax, DWORD PTR _dayOfWeek$[ebp]
	push	eax
	mov	ecx, DWORD PTR _dayOfPeriod$[ebp]
	push	ecx
	mov	edx, DWORD PTR _dayOfPeriod$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?weekNumber@Calendar@icu_56@@IAEHHHH@Z	; icu_56::Calendar::weekNumber
; Line 2542
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?weekNumber@Calendar@icu_56@@IAEHHH@Z ENDP		; icu_56::Calendar::weekNumber
_TEXT	ENDS
PUBLIC	?getStaticClassID@CopticCalendar@icu_56@@SAPAXXZ ; icu_56::CopticCalendar::getStaticClassID
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?getStaticClassID@CopticCalendar@icu_56@@SAPAXXZ
_TEXT	SEGMENT
?getStaticClassID@CopticCalendar@icu_56@@SAPAXXZ PROC	; icu_56::CopticCalendar::getStaticClassID, COMDAT
; File d:\mozilla\intl\icu\source\i18n\coptccal.cpp
; Line 19
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, OFFSET ?classID@?1??getStaticClassID@CopticCalendar@icu_56@@SAPAXXZ@4DA
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?getStaticClassID@CopticCalendar@icu_56@@SAPAXXZ ENDP	; icu_56::CopticCalendar::getStaticClassID
_TEXT	ENDS
PUBLIC	?getDynamicClassID@CopticCalendar@icu_56@@UBEPAXXZ ; icu_56::CopticCalendar::getDynamicClassID
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?getDynamicClassID@CopticCalendar@icu_56@@UBEPAXXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?getDynamicClassID@CopticCalendar@icu_56@@UBEPAXXZ PROC	; icu_56::CopticCalendar::getDynamicClassID, COMDAT
; _this$ = ecx
; Line 19
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	call	?getStaticClassID@CopticCalendar@icu_56@@SAPAXXZ ; icu_56::CopticCalendar::getStaticClassID
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?getDynamicClassID@CopticCalendar@icu_56@@UBEPAXXZ ENDP	; icu_56::CopticCalendar::getDynamicClassID
_TEXT	ENDS
PUBLIC	??_7CopticCalendar@icu_56@@6B@			; icu_56::CopticCalendar::`vftable'
PUBLIC	??0CopticCalendar@icu_56@@QAE@ABVLocale@1@AAW4UErrorCode@@@Z ; icu_56::CopticCalendar::CopticCalendar
PUBLIC	??_R4CopticCalendar@icu_56@@6B@			; icu_56::CopticCalendar::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCopticCalendar@icu_56@@@8		; icu_56::CopticCalendar `RTTI Type Descriptor'
PUBLIC	??_R3CopticCalendar@icu_56@@8			; icu_56::CopticCalendar::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CopticCalendar@icu_56@@8			; icu_56::CopticCalendar::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CopticCalendar@icu_56@@8		; icu_56::CopticCalendar::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@CECalendar@icu_56@@8		; icu_56::CECalendar::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCECalendar@icu_56@@@8			; icu_56::CECalendar `RTTI Type Descriptor'
PUBLIC	??_R3CECalendar@icu_56@@8			; icu_56::CECalendar::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CECalendar@icu_56@@8			; icu_56::CECalendar::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@Calendar@icu_56@@8		; icu_56::Calendar::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCalendar@icu_56@@@8			; icu_56::Calendar `RTTI Type Descriptor'
PUBLIC	??_R3Calendar@icu_56@@8				; icu_56::Calendar::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2Calendar@icu_56@@8				; icu_56::Calendar::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@UObject@icu_56@@8			; icu_56::UObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVUObject@icu_56@@@8			; icu_56::UObject `RTTI Type Descriptor'
PUBLIC	??_R3UObject@icu_56@@8				; icu_56::UObject::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2UObject@icu_56@@8				; icu_56::UObject::`RTTI Base Class Array'
PUBLIC	??_R13?0A@EA@UMemory@icu_56@@8			; icu_56::UMemory::`RTTI Base Class Descriptor at (4,-1,0,64)'
PUBLIC	??_R0?AVUMemory@icu_56@@@8			; icu_56::UMemory `RTTI Type Descriptor'
PUBLIC	??_R3UMemory@icu_56@@8				; icu_56::UMemory::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2UMemory@icu_56@@8				; icu_56::UMemory::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@UMemory@icu_56@@8			; icu_56::UMemory::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ ; icu_56::CopticCalendar::clone
PUBLIC	?getType@CopticCalendar@icu_56@@UBEPBDXZ	; icu_56::CopticCalendar::getType
PUBLIC	?handleGetExtendedYear@CopticCalendar@icu_56@@MAEHXZ ; icu_56::CopticCalendar::handleGetExtendedYear
PUBLIC	?handleComputeFields@CopticCalendar@icu_56@@MAEXHAAW4UErrorCode@@@Z ; icu_56::CopticCalendar::handleComputeFields
PUBLIC	?defaultCenturyStart@CopticCalendar@icu_56@@MBENXZ ; icu_56::CopticCalendar::defaultCenturyStart
PUBLIC	?defaultCenturyStartYear@CopticCalendar@icu_56@@MBEHXZ ; icu_56::CopticCalendar::defaultCenturyStartYear
PUBLIC	?getJDEpochOffset@CopticCalendar@icu_56@@MBEHXZ	; icu_56::CopticCalendar::getJDEpochOffset
EXTRN	??0CECalendar@icu_56@@IAE@ABVLocale@1@AAW4UErrorCode@@@Z:PROC ; icu_56::CECalendar::CECalendar
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	??_ECopticCalendar@icu_56@@UAEPAXI@Z:PROC	; icu_56::CopticCalendar::`vector deleting destructor'
EXTRN	??8Calendar@icu_56@@UBECABV01@@Z:PROC		; icu_56::Calendar::operator==
EXTRN	?isEquivalentTo@Calendar@icu_56@@UBECABV12@@Z:PROC ; icu_56::Calendar::isEquivalentTo
EXTRN	?add@Calendar@icu_56@@UAEXW4UCalendarDateFields@@HAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::add
EXTRN	?add@Calendar@icu_56@@UAEXW4EDateFields@12@HAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::add
EXTRN	?roll@Calendar@icu_56@@UAEXW4UCalendarDateFields@@HAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::roll
EXTRN	?roll@Calendar@icu_56@@UAEXW4EDateFields@12@HAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::roll
EXTRN	?fieldDifference@Calendar@icu_56@@UAEHNW4UCalendarDateFields@@AAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::fieldDifference
EXTRN	?fieldDifference@Calendar@icu_56@@UAEHNW4EDateFields@12@AAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::fieldDifference
EXTRN	?inDaylightTime@CECalendar@icu_56@@MBECAAW4UErrorCode@@@Z:PROC ; icu_56::CECalendar::inDaylightTime
EXTRN	?getMinimum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@@Z:PROC ; icu_56::Calendar::getMinimum
EXTRN	?getMinimum@Calendar@icu_56@@UBEHW4EDateFields@12@@Z:PROC ; icu_56::Calendar::getMinimum
EXTRN	?getMaximum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@@Z:PROC ; icu_56::Calendar::getMaximum
EXTRN	?getMaximum@Calendar@icu_56@@UBEHW4EDateFields@12@@Z:PROC ; icu_56::Calendar::getMaximum
EXTRN	?getGreatestMinimum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@@Z:PROC ; icu_56::Calendar::getGreatestMinimum
EXTRN	?getGreatestMinimum@Calendar@icu_56@@UBEHW4EDateFields@12@@Z:PROC ; icu_56::Calendar::getGreatestMinimum
EXTRN	?getLeastMaximum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@@Z:PROC ; icu_56::Calendar::getLeastMaximum
EXTRN	?getLeastMaximum@Calendar@icu_56@@UBEHW4EDateFields@12@@Z:PROC ; icu_56::Calendar::getLeastMaximum
EXTRN	?getActualMinimum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@AAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::getActualMinimum
EXTRN	?getActualMaximum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@AAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::getActualMaximum
EXTRN	?getDayOfWeekType@Calendar@icu_56@@UBE?AW4UCalendarWeekdayType@@W4UCalendarDaysOfWeek@@AAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::getDayOfWeekType
EXTRN	?getWeekendTransition@Calendar@icu_56@@UBEHW4UCalendarDaysOfWeek@@AAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::getWeekendTransition
EXTRN	?isWeekend@Calendar@icu_56@@UBECXZ:PROC		; icu_56::Calendar::isWeekend
EXTRN	?isWeekend@Calendar@icu_56@@UBECNAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::isWeekend
EXTRN	?computeTime@Calendar@icu_56@@MAEXAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::computeTime
EXTRN	?computeFields@Calendar@icu_56@@MAEXAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::computeFields
EXTRN	?prepareGetActual@Calendar@icu_56@@MAEXW4UCalendarDateFields@@CAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::prepareGetActual
EXTRN	?handleGetLimit@CECalendar@icu_56@@MBEHW4UCalendarDateFields@@W4ELimitType@Calendar@2@@Z:PROC ; icu_56::CECalendar::handleGetLimit
EXTRN	?getLimit@Calendar@icu_56@@MBEHW4UCalendarDateFields@@W4ELimitType@12@@Z:PROC ; icu_56::Calendar::getLimit
EXTRN	?handleComputeMonthStart@CECalendar@icu_56@@MBEHHHC@Z:PROC ; icu_56::CECalendar::handleComputeMonthStart
EXTRN	?handleGetMonthLength@Calendar@icu_56@@MBEHHH@Z:PROC ; icu_56::Calendar::handleGetMonthLength
EXTRN	?handleGetYearLength@Calendar@icu_56@@MBEHH@Z:PROC ; icu_56::Calendar::handleGetYearLength
EXTRN	?handleComputeJulianDay@Calendar@icu_56@@MAEHW4UCalendarDateFields@@@Z:PROC ; icu_56::Calendar::handleComputeJulianDay
EXTRN	?handleGetExtendedYearFromWeekFields@Calendar@icu_56@@MAEHHH@Z:PROC ; icu_56::Calendar::handleGetExtendedYearFromWeekFields
EXTRN	?validateField@Calendar@icu_56@@MAEXW4UCalendarDateFields@@AAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::validateField
EXTRN	?getFieldResolutionTable@Calendar@icu_56@@MBEPAY1M@7$$CBHXZ:PROC ; icu_56::Calendar::getFieldResolutionTable
EXTRN	?getDefaultMonthInYear@Calendar@icu_56@@MAEHH@Z:PROC ; icu_56::Calendar::getDefaultMonthInYear
EXTRN	?getDefaultDayInMonth@Calendar@icu_56@@MAEHHH@Z:PROC ; icu_56::Calendar::getDefaultDayInMonth
EXTRN	?pinField@Calendar@icu_56@@MAEXW4UCalendarDateFields@@AAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::pinField
EXTRN	?haveDefaultCentury@CECalendar@icu_56@@MBECXZ:PROC ; icu_56::CECalendar::haveDefaultCentury
EXTRN	?getRelatedYear@Calendar@icu_56@@UBEHAAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::getRelatedYear
EXTRN	?setRelatedYear@Calendar@icu_56@@UAEXH@Z:PROC	; icu_56::Calendar::setRelatedYear
;	COMDAT ??_R1A@?0A@EA@UMemory@icu_56@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@UMemory@icu_56@@8 DD FLAT:??_R0?AVUMemory@icu_56@@@8 ; icu_56::UMemory::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3UMemory@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R2UMemory@icu_56@@8
rdata$r	SEGMENT
??_R2UMemory@icu_56@@8 DD FLAT:??_R1A@?0A@EA@UMemory@icu_56@@8 ; icu_56::UMemory::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3UMemory@icu_56@@8
rdata$r	SEGMENT
??_R3UMemory@icu_56@@8 DD 00H				; icu_56::UMemory::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2UMemory@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVUMemory@icu_56@@@8
_DATA	SEGMENT
??_R0?AVUMemory@icu_56@@@8 DD FLAT:??_7type_info@@6B@	; icu_56::UMemory `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVUMemory@icu_56@@', 00H
_DATA	ENDS
;	COMDAT ??_R13?0A@EA@UMemory@icu_56@@8
rdata$r	SEGMENT
??_R13?0A@EA@UMemory@icu_56@@8 DD FLAT:??_R0?AVUMemory@icu_56@@@8 ; icu_56::UMemory::`RTTI Base Class Descriptor at (4,-1,0,64)'
	DD	00H
	DD	04H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3UMemory@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R2UObject@icu_56@@8
rdata$r	SEGMENT
??_R2UObject@icu_56@@8 DD FLAT:??_R1A@?0A@EA@UObject@icu_56@@8 ; icu_56::UObject::`RTTI Base Class Array'
	DD	FLAT:??_R13?0A@EA@UMemory@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R3UObject@icu_56@@8
rdata$r	SEGMENT
??_R3UObject@icu_56@@8 DD 00H				; icu_56::UObject::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2UObject@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVUObject@icu_56@@@8
_DATA	SEGMENT
??_R0?AVUObject@icu_56@@@8 DD FLAT:??_7type_info@@6B@	; icu_56::UObject `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVUObject@icu_56@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@UObject@icu_56@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@UObject@icu_56@@8 DD FLAT:??_R0?AVUObject@icu_56@@@8 ; icu_56::UObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3UObject@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R2Calendar@icu_56@@8
rdata$r	SEGMENT
??_R2Calendar@icu_56@@8 DD FLAT:??_R1A@?0A@EA@Calendar@icu_56@@8 ; icu_56::Calendar::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@UObject@icu_56@@8
	DD	FLAT:??_R13?0A@EA@UMemory@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R3Calendar@icu_56@@8
rdata$r	SEGMENT
??_R3Calendar@icu_56@@8 DD 00H				; icu_56::Calendar::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	FLAT:??_R2Calendar@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCalendar@icu_56@@@8
_DATA	SEGMENT
??_R0?AVCalendar@icu_56@@@8 DD FLAT:??_7type_info@@6B@	; icu_56::Calendar `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCalendar@icu_56@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@Calendar@icu_56@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@Calendar@icu_56@@8 DD FLAT:??_R0?AVCalendar@icu_56@@@8 ; icu_56::Calendar::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3Calendar@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R2CECalendar@icu_56@@8
rdata$r	SEGMENT
??_R2CECalendar@icu_56@@8 DD FLAT:??_R1A@?0A@EA@CECalendar@icu_56@@8 ; icu_56::CECalendar::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@Calendar@icu_56@@8
	DD	FLAT:??_R1A@?0A@EA@UObject@icu_56@@8
	DD	FLAT:??_R13?0A@EA@UMemory@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R3CECalendar@icu_56@@8
rdata$r	SEGMENT
??_R3CECalendar@icu_56@@8 DD 00H			; icu_56::CECalendar::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	04H
	DD	FLAT:??_R2CECalendar@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCECalendar@icu_56@@@8
_DATA	SEGMENT
??_R0?AVCECalendar@icu_56@@@8 DD FLAT:??_7type_info@@6B@ ; icu_56::CECalendar `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCECalendar@icu_56@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@CECalendar@icu_56@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CECalendar@icu_56@@8 DD FLAT:??_R0?AVCECalendar@icu_56@@@8 ; icu_56::CECalendar::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	03H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CECalendar@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CopticCalendar@icu_56@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CopticCalendar@icu_56@@8 DD FLAT:??_R0?AVCopticCalendar@icu_56@@@8 ; icu_56::CopticCalendar::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	04H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CopticCalendar@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R2CopticCalendar@icu_56@@8
rdata$r	SEGMENT
??_R2CopticCalendar@icu_56@@8 DD FLAT:??_R1A@?0A@EA@CopticCalendar@icu_56@@8 ; icu_56::CopticCalendar::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CECalendar@icu_56@@8
	DD	FLAT:??_R1A@?0A@EA@Calendar@icu_56@@8
	DD	FLAT:??_R1A@?0A@EA@UObject@icu_56@@8
	DD	FLAT:??_R13?0A@EA@UMemory@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R3CopticCalendar@icu_56@@8
rdata$r	SEGMENT
??_R3CopticCalendar@icu_56@@8 DD 00H			; icu_56::CopticCalendar::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	05H
	DD	FLAT:??_R2CopticCalendar@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCopticCalendar@icu_56@@@8
_DATA	SEGMENT
??_R0?AVCopticCalendar@icu_56@@@8 DD FLAT:??_7type_info@@6B@ ; icu_56::CopticCalendar `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCopticCalendar@icu_56@@', 00H
_DATA	ENDS
;	COMDAT ??_R4CopticCalendar@icu_56@@6B@
rdata$r	SEGMENT
??_R4CopticCalendar@icu_56@@6B@ DD 00H			; icu_56::CopticCalendar::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCopticCalendar@icu_56@@@8
	DD	FLAT:??_R3CopticCalendar@icu_56@@8
rdata$r	ENDS
;	COMDAT ??_7CopticCalendar@icu_56@@6B@
CONST	SEGMENT
??_7CopticCalendar@icu_56@@6B@ DD FLAT:??_R4CopticCalendar@icu_56@@6B@ ; icu_56::CopticCalendar::`vftable'
	DD	FLAT:??_ECopticCalendar@icu_56@@UAEPAXI@Z
	DD	FLAT:?getDynamicClassID@CopticCalendar@icu_56@@UBEPAXXZ
	DD	FLAT:?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ
	DD	FLAT:??8Calendar@icu_56@@UBECABV01@@Z
	DD	FLAT:?isEquivalentTo@Calendar@icu_56@@UBECABV12@@Z
	DD	FLAT:?add@Calendar@icu_56@@UAEXW4UCalendarDateFields@@HAAW4UErrorCode@@@Z
	DD	FLAT:?add@Calendar@icu_56@@UAEXW4EDateFields@12@HAAW4UErrorCode@@@Z
	DD	FLAT:?roll@Calendar@icu_56@@UAEXW4UCalendarDateFields@@HAAW4UErrorCode@@@Z
	DD	FLAT:?roll@Calendar@icu_56@@UAEXW4EDateFields@12@HAAW4UErrorCode@@@Z
	DD	FLAT:?fieldDifference@Calendar@icu_56@@UAEHNW4UCalendarDateFields@@AAW4UErrorCode@@@Z
	DD	FLAT:?fieldDifference@Calendar@icu_56@@UAEHNW4EDateFields@12@AAW4UErrorCode@@@Z
	DD	FLAT:?inDaylightTime@CECalendar@icu_56@@MBECAAW4UErrorCode@@@Z
	DD	FLAT:?getMinimum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@@Z
	DD	FLAT:?getMinimum@Calendar@icu_56@@UBEHW4EDateFields@12@@Z
	DD	FLAT:?getMaximum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@@Z
	DD	FLAT:?getMaximum@Calendar@icu_56@@UBEHW4EDateFields@12@@Z
	DD	FLAT:?getGreatestMinimum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@@Z
	DD	FLAT:?getGreatestMinimum@Calendar@icu_56@@UBEHW4EDateFields@12@@Z
	DD	FLAT:?getLeastMaximum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@@Z
	DD	FLAT:?getLeastMaximum@Calendar@icu_56@@UBEHW4EDateFields@12@@Z
	DD	FLAT:?getActualMinimum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@AAW4UErrorCode@@@Z
	DD	FLAT:?getActualMaximum@Calendar@icu_56@@UBEHW4UCalendarDateFields@@AAW4UErrorCode@@@Z
	DD	FLAT:?getType@CopticCalendar@icu_56@@UBEPBDXZ
	DD	FLAT:?getDayOfWeekType@Calendar@icu_56@@UBE?AW4UCalendarWeekdayType@@W4UCalendarDaysOfWeek@@AAW4UErrorCode@@@Z
	DD	FLAT:?getWeekendTransition@Calendar@icu_56@@UBEHW4UCalendarDaysOfWeek@@AAW4UErrorCode@@@Z
	DD	FLAT:?isWeekend@Calendar@icu_56@@UBECXZ
	DD	FLAT:?isWeekend@Calendar@icu_56@@UBECNAAW4UErrorCode@@@Z
	DD	FLAT:?computeTime@Calendar@icu_56@@MAEXAAW4UErrorCode@@@Z
	DD	FLAT:?computeFields@Calendar@icu_56@@MAEXAAW4UErrorCode@@@Z
	DD	FLAT:?prepareGetActual@Calendar@icu_56@@MAEXW4UCalendarDateFields@@CAAW4UErrorCode@@@Z
	DD	FLAT:?handleGetLimit@CECalendar@icu_56@@MBEHW4UCalendarDateFields@@W4ELimitType@Calendar@2@@Z
	DD	FLAT:?getLimit@Calendar@icu_56@@MBEHW4UCalendarDateFields@@W4ELimitType@12@@Z
	DD	FLAT:?handleComputeMonthStart@CECalendar@icu_56@@MBEHHHC@Z
	DD	FLAT:?handleGetMonthLength@Calendar@icu_56@@MBEHHH@Z
	DD	FLAT:?handleGetYearLength@Calendar@icu_56@@MBEHH@Z
	DD	FLAT:?handleGetExtendedYear@CopticCalendar@icu_56@@MAEHXZ
	DD	FLAT:?handleComputeJulianDay@Calendar@icu_56@@MAEHW4UCalendarDateFields@@@Z
	DD	FLAT:?handleGetExtendedYearFromWeekFields@Calendar@icu_56@@MAEHHH@Z
	DD	FLAT:?validateField@Calendar@icu_56@@MAEXW4UCalendarDateFields@@AAW4UErrorCode@@@Z
	DD	FLAT:?getFieldResolutionTable@Calendar@icu_56@@MBEPAY1M@7$$CBHXZ
	DD	FLAT:?handleComputeFields@CopticCalendar@icu_56@@MAEXHAAW4UErrorCode@@@Z
	DD	FLAT:?getDefaultMonthInYear@Calendar@icu_56@@MAEHH@Z
	DD	FLAT:?getDefaultDayInMonth@Calendar@icu_56@@MAEHHH@Z
	DD	FLAT:?pinField@Calendar@icu_56@@MAEXW4UCalendarDateFields@@AAW4UErrorCode@@@Z
	DD	FLAT:?haveDefaultCentury@CECalendar@icu_56@@MBECXZ
	DD	FLAT:?defaultCenturyStart@CopticCalendar@icu_56@@MBENXZ
	DD	FLAT:?defaultCenturyStartYear@CopticCalendar@icu_56@@MBEHXZ
	DD	FLAT:?getRelatedYear@Calendar@icu_56@@UBEHAAW4UErrorCode@@@Z
	DD	FLAT:?setRelatedYear@Calendar@icu_56@@UAEXH@Z
	DD	FLAT:?getJDEpochOffset@CopticCalendar@icu_56@@MBEHXZ
; Function compile flags: /Odtp /RTCsu /ZI
CONST	ENDS
;	COMDAT ??0CopticCalendar@icu_56@@QAE@ABVLocale@1@AAW4UErrorCode@@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_aLocale$ = 8						; size = 4
_success$ = 12						; size = 4
??0CopticCalendar@icu_56@@QAE@ABVLocale@1@AAW4UErrorCode@@@Z PROC ; icu_56::CopticCalendar::CopticCalendar, COMDAT
; _this$ = ecx
; Line 29
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _success$[ebp]
	push	eax
	mov	ecx, DWORD PTR _aLocale$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0CECalendar@icu_56@@IAE@ABVLocale@1@AAW4UErrorCode@@@Z ; icu_56::CECalendar::CECalendar
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CopticCalendar@icu_56@@6B@
; Line 30
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
??0CopticCalendar@icu_56@@QAE@ABVLocale@1@AAW4UErrorCode@@@Z ENDP ; icu_56::CopticCalendar::CopticCalendar
_TEXT	ENDS
PUBLIC	??1CopticCalendar@icu_56@@UAE@XZ		; icu_56::CopticCalendar::~CopticCalendar
EXTRN	__imp_??3UMemory@icu_56@@SAXPAX@Z:PROC
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??_GCopticCalendar@icu_56@@UAEPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___flags$ = 8						; size = 4
??_GCopticCalendar@icu_56@@UAEPAXI@Z PROC		; icu_56::CopticCalendar::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CopticCalendar@icu_56@@UAE@XZ	; icu_56::CopticCalendar::~CopticCalendar
	mov	eax, DWORD PTR ___flags$[ebp]
	and	eax, 1
	je	SHORT $LN1@scalar
	mov	esi, esp
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	call	DWORD PTR __imp_??3UMemory@icu_56@@SAXPAX@Z
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@scalar:
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??_GCopticCalendar@icu_56@@UAEPAXI@Z ENDP		; icu_56::CopticCalendar::`scalar deleting destructor'
_TEXT	ENDS
PUBLIC	??0CopticCalendar@icu_56@@QAE@ABV01@@Z		; icu_56::CopticCalendar::CopticCalendar
EXTRN	??0CECalendar@icu_56@@IAE@ABV01@@Z:PROC		; icu_56::CECalendar::CECalendar
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??0CopticCalendar@icu_56@@QAE@ABV01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_other$ = 8						; size = 4
??0CopticCalendar@icu_56@@QAE@ABV01@@Z PROC		; icu_56::CopticCalendar::CopticCalendar, COMDAT
; _this$ = ecx
; Line 34
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _other$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0CECalendar@icu_56@@IAE@ABV01@@Z	; icu_56::CECalendar::CECalendar
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CopticCalendar@icu_56@@6B@
; Line 35
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??0CopticCalendar@icu_56@@QAE@ABV01@@Z ENDP		; icu_56::CopticCalendar::CopticCalendar
_TEXT	ENDS
EXTRN	??1CECalendar@icu_56@@MAE@XZ:PROC		; icu_56::CECalendar::~CECalendar
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??1CopticCalendar@icu_56@@UAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??1CopticCalendar@icu_56@@UAE@XZ PROC			; icu_56::CopticCalendar::~CopticCalendar, COMDAT
; _this$ = ecx
; Line 38
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CopticCalendar@icu_56@@6B@
; Line 39
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CECalendar@icu_56@@MAE@XZ		; icu_56::CECalendar::~CECalendar
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??1CopticCalendar@icu_56@@UAE@XZ ENDP			; icu_56::CopticCalendar::~CopticCalendar
_TEXT	ENDS
EXTRN	__imp_??2UMemory@icu_56@@SAPAXI@Z:PROC
EXTRN	___security_cookie:DWORD
EXTRN	___CxxFrameHandler3:PROC
EXTRN	@__security_check_cookie@4:PROC
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ$0
__ehfuncinfo$?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Odtp /RTCsu /ZI
xdata$x	ENDS
;	COMDAT ?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ
_TEXT	SEGMENT
tv75 = -244						; size = 4
$T75936 = -236						; size = 4
$T75937 = -224						; size = 4
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ PROC	; icu_56::CopticCalendar::clone, COMDAT
; _this$ = ecx
; Line 43
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 232				; 000000e8H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-244]
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
; Line 44
	mov	esi, esp
	push	608					; 00000260H
	call	DWORD PTR __imp_??2UMemory@icu_56@@SAPAXI@Z
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR $T75937[ebp], eax
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	cmp	DWORD PTR $T75937[ebp], 0
	je	SHORT $LN3@clone
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	mov	ecx, DWORD PTR $T75937[ebp]
	call	??0CopticCalendar@icu_56@@QAE@ABV01@@Z	; icu_56::CopticCalendar::CopticCalendar
	mov	DWORD PTR tv75[ebp], eax
	jmp	SHORT $LN4@clone
$LN3@clone:
	mov	DWORD PTR tv75[ebp], 0
$LN4@clone:
	mov	ecx, DWORD PTR tv75[ebp]
	mov	DWORD PTR $T75936[ebp], ecx
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	mov	eax, DWORD PTR $T75936[ebp]
; Line 45
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 244				; 000000f4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ$0:
	mov	esi, esp
	mov	eax, DWORD PTR $T75937[ebp]
	push	eax
	call	DWORD PTR __imp_??3UMemory@icu_56@@SAXPAX@Z
	add	esp, 4
	cmp	esi, esp
	jmp	__RTC_CheckEsp
__ehhandler$?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-248]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?clone@CopticCalendar@icu_56@@UBEPAVCalendar@2@XZ ENDP	; icu_56::CopticCalendar::clone
PUBLIC	??_C@_06DFDGNELJ@coptic?$AA@			; `string'
;	COMDAT ??_C@_06DFDGNELJ@coptic?$AA@
CONST	SEGMENT
??_C@_06DFDGNELJ@coptic?$AA@ DB 'coptic', 00H		; `string'
; Function compile flags: /Odtp /RTCsu /ZI
CONST	ENDS
;	COMDAT ?getType@CopticCalendar@icu_56@@UBEPBDXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?getType@CopticCalendar@icu_56@@UBEPBDXZ PROC		; icu_56::CopticCalendar::getType, COMDAT
; _this$ = ecx
; Line 49
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 50
	mov	eax, OFFSET ??_C@_06DFDGNELJ@coptic?$AA@
; Line 51
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?getType@CopticCalendar@icu_56@@UBEPBDXZ ENDP		; icu_56::CopticCalendar::getType
_TEXT	ENDS
EXTRN	?newerField@Calendar@icu_56@@IBE?AW4UCalendarDateFields@@W43@0@Z:PROC ; icu_56::Calendar::newerField
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?handleGetExtendedYear@CopticCalendar@icu_56@@MAEHXZ
_TEXT	SEGMENT
_era$69160 = -32					; size = 4
_eyear$ = -20						; size = 4
_this$ = -8						; size = 4
?handleGetExtendedYear@CopticCalendar@icu_56@@MAEHXZ PROC ; icu_56::CopticCalendar::handleGetExtendedYear, COMDAT
; _this$ = ecx
; Line 59
	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 61
	push	1
	push	19					; 00000013H
	mov	ecx, DWORD PTR _this$[ebp]
	call	?newerField@Calendar@icu_56@@IBE?AW4UCalendarDateFields@@W43@0@Z ; icu_56::Calendar::newerField
	cmp	eax, 19					; 00000013H
	jne	SHORT $LN4@handleGetE
; Line 62
	push	1
	push	19					; 00000013H
	mov	ecx, DWORD PTR _this$[ebp]
	call	?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalGet
	mov	DWORD PTR _eyear$[ebp], eax
; Line 63
	jmp	SHORT $LN3@handleGetE
$LN4@handleGetE:
; Line 65
	push	1
	push	0
	mov	ecx, DWORD PTR _this$[ebp]
	call	?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalGet
	mov	DWORD PTR _era$69160[ebp], eax
; Line 66
	cmp	DWORD PTR _era$69160[ebp], 0
	jne	SHORT $LN2@handleGetE
; Line 67
	push	1
	push	1
	mov	ecx, DWORD PTR _this$[ebp]
	call	?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalGet
	mov	ecx, 1
	sub	ecx, eax
	mov	DWORD PTR _eyear$[ebp], ecx
; Line 68
	jmp	SHORT $LN3@handleGetE
$LN2@handleGetE:
; Line 69
	push	1
	push	1
	mov	ecx, DWORD PTR _this$[ebp]
	call	?internalGet@Calendar@icu_56@@IBEHW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalGet
	mov	DWORD PTR _eyear$[ebp], eax
$LN3@handleGetE:
; Line 72
	mov	eax, DWORD PTR _eyear$[ebp]
; Line 73
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 228				; 000000e4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?handleGetExtendedYear@CopticCalendar@icu_56@@MAEHXZ ENDP ; icu_56::CopticCalendar::handleGetExtendedYear
_TEXT	ENDS
EXTRN	?jdToCE@CECalendar@icu_56@@KAXHHAAH00@Z:PROC	; icu_56::CECalendar::jdToCE
EXTRN	@_RTC_CheckStackVars@8:PROC
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?handleComputeFields@CopticCalendar@icu_56@@MAEXHAAW4UErrorCode@@@Z
_TEXT	SEGMENT
_year$ = -68						; size = 4
_era$ = -56						; size = 4
_day$ = -44						; size = 4
_month$ = -32						; size = 4
_eyear$ = -20						; size = 4
_this$ = -8						; size = 4
_julianDay$ = 8						; size = 4
___formal$ = 12						; size = 4
?handleComputeFields@CopticCalendar@icu_56@@MAEXHAAW4UErrorCode@@@Z PROC ; icu_56::CopticCalendar::handleComputeFields, COMDAT
; _this$ = ecx
; Line 77
	push	ebp
	mov	ebp, esp
	sub	esp, 264				; 00000108H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-264]
	mov	ecx, 66					; 00000042H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 79
	lea	eax, DWORD PTR _day$[ebp]
	push	eax
	lea	ecx, DWORD PTR _month$[ebp]
	push	ecx
	lea	edx, DWORD PTR _eyear$[ebp]
	push	edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax]
	mov	esi, esp
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+196]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	push	eax
	mov	ecx, DWORD PTR _julianDay$[ebp]
	push	ecx
	call	?jdToCE@CECalendar@icu_56@@KAXHHAAH00@Z	; icu_56::CECalendar::jdToCE
	add	esp, 20					; 00000014H
; Line 81
	cmp	DWORD PTR _eyear$[ebp], 0
	jg	SHORT $LN2@handleComp
; Line 82
	mov	DWORD PTR _era$[ebp], 0
; Line 83
	mov	eax, 1
	sub	eax, DWORD PTR _eyear$[ebp]
	mov	DWORD PTR _year$[ebp], eax
; Line 84
	jmp	SHORT $LN1@handleComp
$LN2@handleComp:
; Line 85
	mov	DWORD PTR _era$[ebp], 1
; Line 86
	mov	eax, DWORD PTR _eyear$[ebp]
	mov	DWORD PTR _year$[ebp], eax
$LN1@handleComp:
; Line 89
	mov	eax, DWORD PTR _eyear$[ebp]
	push	eax
	push	19					; 00000013H
	mov	ecx, DWORD PTR _this$[ebp]
	call	?internalSet@Calendar@icu_56@@IAEXW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalSet
; Line 90
	mov	eax, DWORD PTR _era$[ebp]
	push	eax
	push	0
	mov	ecx, DWORD PTR _this$[ebp]
	call	?internalSet@Calendar@icu_56@@IAEXW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalSet
; Line 91
	mov	eax, DWORD PTR _year$[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _this$[ebp]
	call	?internalSet@Calendar@icu_56@@IAEXW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalSet
; Line 92
	mov	eax, DWORD PTR _month$[ebp]
	push	eax
	push	2
	mov	ecx, DWORD PTR _this$[ebp]
	call	?internalSet@Calendar@icu_56@@IAEXW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalSet
; Line 93
	mov	eax, DWORD PTR _day$[ebp]
	push	eax
	push	5
	mov	ecx, DWORD PTR _this$[ebp]
	call	?internalSet@Calendar@icu_56@@IAEXW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalSet
; Line 94
	mov	eax, DWORD PTR _month$[ebp]
	imul	eax, 30					; 0000001eH
	add	eax, DWORD PTR _day$[ebp]
	push	eax
	push	6
	mov	ecx, DWORD PTR _this$[ebp]
	call	?internalSet@Calendar@icu_56@@IAEXW4UCalendarDateFields@@H@Z ; icu_56::Calendar::internalSet
; Line 95
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN9@handleComp
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 264				; 00000108H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
	npad	3
$LN9@handleComp:
	DD	3
	DD	$LN8@handleComp
$LN8@handleComp:
	DD	-20					; ffffffecH
	DD	4
	DD	$LN5@handleComp
	DD	-32					; ffffffe0H
	DD	4
	DD	$LN6@handleComp
	DD	-44					; ffffffd4H
	DD	4
	DD	$LN7@handleComp
$LN7@handleComp:
	DB	100					; 00000064H
	DB	97					; 00000061H
	DB	121					; 00000079H
	DB	0
$LN6@handleComp:
	DB	109					; 0000006dH
	DB	111					; 0000006fH
	DB	110					; 0000006eH
	DB	116					; 00000074H
	DB	104					; 00000068H
	DB	0
$LN5@handleComp:
	DB	101					; 00000065H
	DB	121					; 00000079H
	DB	101					; 00000065H
	DB	97					; 00000061H
	DB	114					; 00000072H
	DB	0
?handleComputeFields@CopticCalendar@icu_56@@MAEXHAAW4UErrorCode@@@Z ENDP ; icu_56::CopticCalendar::handleComputeFields
_TEXT	ENDS
PUBLIC	?umtx_initOnce@icu_56@@YAXAAUUInitOnce@1@P6AXXZ@Z ; icu_56::umtx_initOnce
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?defaultCenturyStart@CopticCalendar@icu_56@@MBENXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?defaultCenturyStart@CopticCalendar@icu_56@@MBENXZ PROC	; icu_56::CopticCalendar::defaultCenturyStart, COMDAT
; _this$ = ecx
; Line 122
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 124
	push	OFFSET ?initializeSystemDefaultCentury@icu_56@@YAXXZ ; icu_56::initializeSystemDefaultCentury
	push	OFFSET _gSystemDefaultCenturyInit
	call	?umtx_initOnce@icu_56@@YAXAAUUInitOnce@1@P6AXXZ@Z ; icu_56::umtx_initOnce
	add	esp, 8
; Line 125
	fld	QWORD PTR _gSystemDefaultCenturyStart
; Line 126
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?defaultCenturyStart@CopticCalendar@icu_56@@MBENXZ ENDP	; icu_56::CopticCalendar::defaultCenturyStart
_TEXT	ENDS
PUBLIC	?umtx_loadAcquire@icu_56@@YAHACJ@Z		; icu_56::umtx_loadAcquire
EXTRN	__imp_?umtx_initImplPostInit@icu_56@@YAXAAUUInitOnce@1@@Z:PROC
EXTRN	__imp_?umtx_initImplPreInit@icu_56@@YACAAUUInitOnce@1@@Z:PROC
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?umtx_initOnce@icu_56@@YAXAAUUInitOnce@1@P6AXXZ@Z
_TEXT	SEGMENT
_uio$ = 8						; size = 4
_fp$ = 12						; size = 4
?umtx_initOnce@icu_56@@YAXAAUUInitOnce@1@P6AXXZ@Z PROC	; icu_56::umtx_initOnce, COMDAT
; File d:\mozilla\intl\icu\source\common\umutex.h
; Line 245
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 246
	mov	eax, DWORD PTR _uio$[ebp]
	push	eax
	call	?umtx_loadAcquire@icu_56@@YAHACJ@Z	; icu_56::umtx_loadAcquire
	add	esp, 4
	cmp	eax, 2
	jne	SHORT $LN2@umtx_initO
; Line 247
	jmp	SHORT $LN3@umtx_initO
$LN2@umtx_initO:
; Line 249
	mov	esi, esp
	mov	eax, DWORD PTR _uio$[ebp]
	push	eax
	call	DWORD PTR __imp_?umtx_initImplPreInit@icu_56@@YACAAUUInitOnce@1@@Z
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	movsx	ecx, al
	test	ecx, ecx
	je	SHORT $LN3@umtx_initO
; Line 250
	mov	esi, esp
	call	DWORD PTR _fp$[ebp]
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 251
	mov	esi, esp
	mov	eax, DWORD PTR _uio$[ebp]
	push	eax
	call	DWORD PTR __imp_?umtx_initImplPostInit@icu_56@@YAXAAUUInitOnce@1@@Z
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN3@umtx_initO:
; Line 253
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?umtx_initOnce@icu_56@@YAXAAUUInitOnce@1@P6AXXZ@Z ENDP	; icu_56::umtx_initOnce
_TEXT	ENDS
EXTRN	__imp__InterlockedCompareExchange@12:PROC
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?umtx_loadAcquire@icu_56@@YAHACJ@Z
_TEXT	SEGMENT
_var$ = 8						; size = 4
?umtx_loadAcquire@icu_56@@YAHACJ@Z PROC			; icu_56::umtx_loadAcquire, COMDAT
; Line 102
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 103
	mov	esi, esp
	push	0
	push	0
	mov	eax, DWORD PTR _var$[ebp]
	push	eax
	call	DWORD PTR __imp__InterlockedCompareExchange@12
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 104
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?umtx_loadAcquire@icu_56@@YAHACJ@Z ENDP			; icu_56::umtx_loadAcquire
_TEXT	ENDS
PUBLIC	??_C@_0BB@LNJNNHKE@?$EAcalendar?$DNcoptic?$AA@	; `string'
PUBLIC	__$ArrayPad$
EXTRN	?get@Calendar@icu_56@@QBEHW4UCalendarDateFields@@AAW4UErrorCode@@@Z:PROC ; icu_56::Calendar::get
EXTRN	?getNow@Calendar@icu_56@@SANXZ:PROC		; icu_56::Calendar::getNow
EXTRN	__imp_??1Locale@icu_56@@UAE@XZ:PROC
EXTRN	__imp_??0Locale@icu_56@@QAE@PBD000@Z:PROC
;	COMDAT ??_C@_0BB@LNJNNHKE@?$EAcalendar?$DNcoptic?$AA@
; File d:\mozilla\intl\icu\source\i18n\coptccal.cpp
CONST	SEGMENT
??_C@_0BB@LNJNNHKE@?$EAcalendar?$DNcoptic?$AA@ DB '@calendar=coptic', 00H ; `string'
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?initializeSystemDefaultCentury@icu_56@@YAXXZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?initializeSystemDefaultCentury@icu_56@@YAXXZ$0
	DD	00H
	DD	FLAT:__unwindfunclet$?initializeSystemDefaultCentury@icu_56@@YAXXZ$1
	DD	0ffffffffH
	DD	FLAT:__unwindfunclet$?initializeSystemDefaultCentury@icu_56@@YAXXZ$1
__ehfuncinfo$?initializeSystemDefaultCentury@icu_56@@YAXXZ DD 019930522H
	DD	03H
	DD	FLAT:__unwindtable$?initializeSystemDefaultCentury@icu_56@@YAXXZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Odtp /RTCsu /ZI
xdata$x	ENDS
;	COMDAT ?initializeSystemDefaultCentury@icu_56@@YAXXZ
_TEXT	SEGMENT
tv145 = -1056						; size = 4
tv147 = -1052						; size = 4
$T69181 = -1044						; size = 204
_calendar$ = -640					; size = 608
_status$ = -24						; size = 4
__$ArrayPad$ = -16					; size = 4
__$EHRec$ = -12						; size = 12
?initializeSystemDefaultCentury@icu_56@@YAXXZ PROC	; icu_56::initializeSystemDefaultCentury, COMDAT
; Line 107
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?initializeSystemDefaultCentury@icu_56@@YAXXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 1044				; 00000414H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-1056]
	mov	ecx, 261				; 00000105H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
; Line 108
	mov	DWORD PTR _status$[ebp], 0
; Line 109
	lea	eax, DWORD PTR _status$[ebp]
	push	eax
	mov	esi, esp
	push	0
	push	0
	push	0
	push	OFFSET ??_C@_0BB@LNJNNHKE@?$EAcalendar?$DNcoptic?$AA@
	lea	ecx, DWORD PTR $T69181[ebp]
	call	DWORD PTR __imp_??0Locale@icu_56@@QAE@PBD000@Z
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR tv147[ebp], eax
	mov	ecx, DWORD PTR tv147[ebp]
	mov	DWORD PTR tv145[ebp], ecx
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	mov	edx, DWORD PTR tv145[ebp]
	push	edx
	lea	ecx, DWORD PTR _calendar$[ebp]
	call	??0CopticCalendar@icu_56@@QAE@ABVLocale@1@AAW4UErrorCode@@@Z ; icu_56::CopticCalendar::CopticCalendar
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	mov	esi, esp
	lea	ecx, DWORD PTR $T69181[ebp]
	call	DWORD PTR __imp_??1Locale@icu_56@@UAE@XZ
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 110
	mov	eax, DWORD PTR _status$[ebp]
	push	eax
	call	?U_SUCCESS@@YACW4UErrorCode@@@Z		; U_SUCCESS
	add	esp, 4
	movsx	ecx, al
	test	ecx, ecx
	je	SHORT $LN1@initialize
; Line 111
	lea	eax, DWORD PTR _status$[ebp]
	push	eax
	call	?getNow@Calendar@icu_56@@SANXZ		; icu_56::Calendar::getNow
	sub	esp, 8
	fstp	QWORD PTR [esp]
	lea	ecx, DWORD PTR _calendar$[ebp]
	call	?setTime@Calendar@icu_56@@QAEXNAAW4UErrorCode@@@Z ; icu_56::Calendar::setTime
; Line 112
	lea	eax, DWORD PTR _status$[ebp]
	push	eax
	push	-80					; ffffffb0H
	push	1
	lea	ecx, DWORD PTR _calendar$[ebp]
	call	?add@Calendar@icu_56@@UAEXW4UCalendarDateFields@@HAAW4UErrorCode@@@Z ; icu_56::Calendar::add
; Line 113
	lea	eax, DWORD PTR _status$[ebp]
	push	eax
	lea	ecx, DWORD PTR _calendar$[ebp]
	call	?getTime@Calendar@icu_56@@QBENAAW4UErrorCode@@@Z ; icu_56::Calendar::getTime
	fstp	QWORD PTR _gSystemDefaultCenturyStart
; Line 114
	lea	eax, DWORD PTR _status$[ebp]
	push	eax
	push	1
	lea	ecx, DWORD PTR _calendar$[ebp]
	call	?get@Calendar@icu_56@@QBEHW4UCalendarDateFields@@AAW4UErrorCode@@@Z ; icu_56::Calendar::get
	mov	DWORD PTR _gSystemDefaultCenturyStartYear, eax
$LN1@initialize:
; Line 118
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR _calendar$[ebp]
	call	??1CopticCalendar@icu_56@@UAE@XZ	; icu_56::CopticCalendar::~CopticCalendar
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN10@initialize
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 1056				; 00000420H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	2
$LN10@initialize:
	DD	2
	DD	$LN9@initialize
$LN9@initialize:
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN6@initialize
	DD	-640					; fffffd80H
	DD	608					; 00000260H
	DD	$LN7@initialize
$LN7@initialize:
	DB	99					; 00000063H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	101					; 00000065H
	DB	110					; 0000006eH
	DB	100					; 00000064H
	DB	97					; 00000061H
	DB	114					; 00000072H
	DB	0
$LN6@initialize:
	DB	115					; 00000073H
	DB	116					; 00000074H
	DB	97					; 00000061H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	115					; 00000073H
	DB	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?initializeSystemDefaultCentury@icu_56@@YAXXZ$0:
	mov	esi, esp
	lea	ecx, DWORD PTR $T69181[ebp]
	call	DWORD PTR __imp_??1Locale@icu_56@@UAE@XZ
	cmp	esi, esp
	jmp	__RTC_CheckEsp
__unwindfunclet$?initializeSystemDefaultCentury@icu_56@@YAXXZ$1:
	lea	ecx, DWORD PTR _calendar$[ebp]
	jmp	??1CopticCalendar@icu_56@@UAE@XZ	; icu_56::CopticCalendar::~CopticCalendar
__ehhandler$?initializeSystemDefaultCentury@icu_56@@YAXXZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-1060]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	ecx, DWORD PTR [edx-4]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?initializeSystemDefaultCentury@icu_56@@YAXXZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?initializeSystemDefaultCentury@icu_56@@YAXXZ ENDP	; icu_56::initializeSystemDefaultCentury
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?U_SUCCESS@@YACW4UErrorCode@@@Z
_TEXT	SEGMENT
_code$ = 8						; size = 4
?U_SUCCESS@@YACW4UErrorCode@@@Z PROC			; U_SUCCESS, COMDAT
; File d:\mozilla\intl\icu\include\unicode\utypes.h
; Line 699
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	cmp	DWORD PTR _code$[ebp], 0
	setle	al
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?U_SUCCESS@@YACW4UErrorCode@@@Z ENDP			; U_SUCCESS
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT ?defaultCenturyStartYear@CopticCalendar@icu_56@@MBEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?defaultCenturyStartYear@CopticCalendar@icu_56@@MBEHXZ PROC ; icu_56::CopticCalendar::defaultCenturyStartYear, COMDAT
; _this$ = ecx
; File d:\mozilla\intl\icu\source\i18n\coptccal.cpp
; Line 130
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 132
	push	OFFSET ?initializeSystemDefaultCentury@icu_56@@YAXXZ ; icu_56::initializeSystemDefaultCentury
	push	OFFSET _gSystemDefaultCenturyInit
	call	?umtx_initOnce@icu_56@@YAXAAUUInitOnce@1@P6AXXZ@Z ; icu_56::umtx_initOnce
	add	esp, 8
; Line 133
	mov	eax, DWORD PTR _gSystemDefaultCenturyStartYear
; Line 134
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?defaultCenturyStartYear@CopticCalendar@icu_56@@MBEHXZ ENDP ; icu_56::CopticCalendar::defaultCenturyStartYear
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT ?getJDEpochOffset@CopticCalendar@icu_56@@MBEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?getJDEpochOffset@CopticCalendar@icu_56@@MBEHXZ PROC	; icu_56::CopticCalendar::getJDEpochOffset, COMDAT
; _this$ = ecx
; Line 139
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 140
	mov	eax, 1824665				; 001bd799H
; Line 141
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?getJDEpochOffset@CopticCalendar@icu_56@@MBEHXZ ENDP	; icu_56::CopticCalendar::getJDEpochOffset
_TEXT	ENDS
END
