endp
_setUnicodeVersion proc	near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0CCh']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_CC]']
mov ['ecx,', '33h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
lea ['ecx,', '[ebp+Src]']
push ['ecx']
call ['_u_versionFromString_56']
add ['esp,', '8']
push ['1']
lea ['eax,', '[ebp+Src]']
push ['eax']
call ['_uprv_checkValidMemory']
add ['esp,', '8']
push ['4']
lea ['ecx,', '[ebp+Src]']
push ['ecx']
push ['offset', 'off_1870C']
call ['_memcpy']
add ['esp,', '0Ch']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN5']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '0CCh']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
dd ['offset', '$LN4']
dd ['offset', '$LN3']
assume ['cs:_rtc$TMZ']
assume ['cs:_rtc$IMZ']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_setUnicodeVersionNC proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0CCh']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_CC]']
mov ['ecx,', '33h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', '[ebp+arg_0]']
movzx ['ecx,', 'byte', 'ptr', '[eax]']
shl ['ecx,', '18h']
mov ['[ebp+var_8],', 'ecx']
mov ['eax,', '[ebp+arg_0]']
movzx ['ecx,', 'byte', 'ptr', '[eax+1]']
shl ['ecx,', '10h']
add ['ecx,', '[ebp+var_8]']
mov ['[ebp+var_8],', 'ecx']
mov ['eax,', '[ebp+arg_0]']
movzx ['ecx,', 'byte', 'ptr', '[eax+2]']
shl ['ecx,', '8']
add ['ecx,', '[ebp+var_8]']
mov ['[ebp+var_8],', 'ecx']
mov ['eax,', '[ebp+arg_0]']
movzx ['ecx,', 'byte', 'ptr', '[eax+3]']
add ['ecx,', '[ebp+var_8]']
mov ['[ebp+var_8],', 'ecx']
mov ['eax,', '[ebp+var_8]']
mov ['ds:dword_186B0,', 'eax']
pop ['edi']
pop ['esi']
pop ['ebx']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['10h']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_init		proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0C0h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_C0]']
mov ['ecx,', '30h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
push ['4409Ch']
push ['1']
call ['_uprv_calloc_56']
add ['esp,', '8']
mov ['ds:_sprepTrie,', 'eax']
push ['0']
push ['0']
push ['0']
push ['2CECh']
push ['0']
mov ['eax,', 'ds:_sprepTrie']
push ['eax']
call ['_utrie_open_56']
add ['esp,', '18h']
test ['eax,', 'eax']
jnz ['short', 'loc_1889C']
mov ['esi,', 'esp']
push ['offset', '??_C@_0CD@LDDOHHKB@error?3?5failed?5to?5initialize?5trie@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['7']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '0C0h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
assume ['cs:_rdata']
public ['??_C@_0CD@LDDOHHKB@error?3?5failed?5to?5initialize?5trie@']
align ['4']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_setOptions	proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0C0h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_C0]']
mov ['ecx,', '30h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', '[ebp+arg_0]']
mov ['ds:dword_186C4,', 'eax']
pop ['edi']
pop ['esi']
pop ['ebx']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['4']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_storeMapping	proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '120h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_120]']
mov ['ecx,', '48h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['[ebp+var_8],', '0']
xor ['eax,', 'eax']
mov ['[ebp+var_14],', 'ax']
xor ['eax,', 'eax']
mov ['[ebp+var_38],', 'ax']
mov ['[ebp+var_44],', '0']
mov ['[ebp+var_50],', '0']
cmp ['ds:_hashTable,', '0']
jnz ['short', 'loc_1897C']
mov ['eax,', '[ebp+arg_10]']
push ['eax']
push ['0']
push ['offset', '_compareEntries']
push ['offset', '_hashEntry']
call ['_uhash_open_56']
add ['esp,', '10h']
mov ['ds:_hashTable,', 'eax']
push ['offset', '_valueDeleter']
mov ['eax,', 'ds:_hashTable']
push ['eax']
call ['_uhash_setValueDeleter_56']
add ['esp,', '8']
push ['0']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
mov ['ecx,', 'ds:_sprepTrie']
push ['ecx']
call ['_utrie_get32_56']
add ['esp,', '0Ch']
mov ['[ebp+var_50],', 'eax']
cmp ['[ebp+var_50],', '0']
jz ['short', 'loc_189F3']
mov ['eax,', '[ebp+var_50]']
sub ['eax,', '0FFF0h']
cmp ['eax,', '2']
jnz ['short', 'loc_189B4']
movzx ['eax,', '[ebp+var_38]']
add ['eax,', '1']
mov ['[ebp+var_38],', 'ax']
jmp ['short', 'loc_189F3']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
push ['offset', '??_C@_0CJ@IHNBFCKN@Type?5for?5codepoint?5?2U?$CF08X?5alread@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['1']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['eax,', 'eax']
mov ['[ebp+var_20],', 'ax']
jmp ['short', 'loc_18A07']
mov ['ax,', '[ebp+var_20]']
add ['ax,', '1']
mov ['[ebp+var_20],', 'ax']
movsx ['eax,', '[ebp+var_20]']
cmp ['eax,', '[ebp+arg_8]']
jge ['short', 'loc_18A32']
movsx ['eax,', '[ebp+var_20]']
mov ['ecx,', '[ebp+arg_4]']
mov ['edx,', '0FFFFh']
cmp ['edx,', '[ecx+eax*4]']
sbb ['eax,', 'eax']
neg ['eax']
add ['eax,', '1']
movsx ['ecx,', '[ebp+var_14]']
add ['ecx,', 'eax']
mov ['[ebp+var_14],', 'cx']
jmp ['short', 'loc_189FB']
movsx ['eax,', '[ebp+var_14]']
test ['eax,', 'eax']
jnz ['loc_18AF3']
mov ['eax,', '0FEFCh']
mov ['[ebp+var_38],', 'ax']
movzx ['eax,', '[ebp+var_38]']
cmp ['eax,', '0FFF0h']
jge ['short', 'loc_18AB3']
movzx ['eax,', '[ebp+var_38]']
push ['eax']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
mov ['edx,', 'ds:_sprepTrie']
push ['edx']
call ['_utrie_set32_56']
add ['esp,', '0Ch']
movsx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_18AAC']
mov ['esi,', 'esp']
push ['offset', '??_C@_0CJ@FKJENIIC@Could?5not?5set?5the?5value?5for?5code@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['1']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['loc_18D8F']
jmp ['short', 'loc_18AF3']
mov ['esi,', 'esp']
push ['0FFF0h']
push ['offset', '??_C@_0DO@PGDIEDKM@trieWord?5cannot?5contain?5value?5gr@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['0Ch']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
movsx ['eax,', '[ebp+var_14]']
cmp ['eax,', '1']
jnz ['loc_18BE6']
mov ['eax,', '[ebp+arg_4]']
movsx ['ecx,', 'word', 'ptr', '[eax]']
mov ['edx,', '[ebp+arg_0]']
sub ['edx,', 'ecx']
mov ['[ebp+var_5C],', 'dx']
movsx ['eax,', '[ebp+var_5C]']
cmp ['eax,', '0FFFFE000h']
jl ['loc_18BE6']
movsx ['eax,', '[ebp+var_5C]']
cmp ['eax,', '1FFFh']
jg ['loc_18BE6']
movsx ['eax,', '[ebp+var_5C]']
shl ['eax,', '2']
mov ['[ebp+var_38],', 'ax']
movzx ['eax,', '[ebp+var_38]']
and ['eax,', '2']
jz ['short', 'loc_18B7C']
mov ['esi,', 'esp']
push ['offset', '??_C@_0EE@MJJFGPJO@The?5second?5bit?5in?5the?5trie?5word?5@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['5']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
movzx ['eax,', '[ebp+var_38]']
cmp ['eax,', '0FFF0h']
jge ['short', 'loc_18BE6']
movzx ['eax,', '[ebp+var_38]']
push ['eax']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
mov ['edx,', 'ds:_sprepTrie']
push ['edx']
call ['_utrie_set32_56']
add ['esp,', '0Ch']
movsx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_18BE1']
mov ['esi,', 'esp']
push ['offset', '??_C@_0CJ@FKJENIIC@Could?5not?5set?5the?5value?5for?5code@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['1']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['loc_18D8F']
push ['2']
movsx ['eax,', '[ebp+var_14]']
add ['eax,', '1']
push ['eax']
call ['_uprv_calloc_56']
add ['esp,', '8']
mov ['[ebp+var_8],', 'eax']
xor ['eax,', 'eax']
mov ['[ebp+var_20],', 'ax']
xor ['ecx,', 'ecx']
mov ['[ebp+var_2C],', 'cx']
jmp ['short', 'loc_18C15']
mov ['ax,', '[ebp+var_20]']
add ['ax,', '1']
mov ['[ebp+var_20],', 'ax']
movsx ['eax,', '[ebp+var_20]']
cmp ['eax,', '[ebp+arg_8]']
jge ['loc_18CB2']
movsx ['eax,', '[ebp+var_20]']
mov ['ecx,', '[ebp+arg_4]']
cmp ['dword', 'ptr', '[ecx+eax*4],', '0FFFFh']
ja ['short', 'loc_18C56']
movsx ['eax,', '[ebp+var_20]']
movsx ['ecx,', '[ebp+var_2C]']
mov ['edx,', '[ebp+var_8]']
mov ['esi,', '[ebp+arg_4]']
mov ['ax,', '[esi+eax*4]']
mov ['[edx+ecx*2],', 'ax']
mov ['cx,', '[ebp+var_2C]']
add ['cx,', '1']
mov ['[ebp+var_2C],', 'cx']
jmp ['short', 'loc_18CAD']
movsx ['eax,', '[ebp+var_20]']
mov ['ecx,', '[ebp+arg_4]']
mov ['edx,', '[ecx+eax*4]']
shr ['edx,', '0Ah']
add ['edx,', '0D7C0h']
movsx ['eax,', '[ebp+var_2C]']
mov ['ecx,', '[ebp+var_8]']
mov ['[ecx+eax*2],', 'dx']
mov ['dx,', '[ebp+var_2C]']
add ['dx,', '1']
mov ['[ebp+var_2C],', 'dx']
movsx ['eax,', '[ebp+var_20]']
mov ['ecx,', '[ebp+arg_4]']
mov ['edx,', '[ecx+eax*4]']
and ['edx,', '3FFh']
or ['edx,', '0DC00h']
movsx ['eax,', '[ebp+var_2C]']
mov ['ecx,', '[ebp+var_8]']
mov ['[ecx+eax*2],', 'dx']
mov ['dx,', '[ebp+var_2C]']
add ['dx,', '1']
mov ['[ebp+var_2C],', 'dx']
jmp ['loc_18C09']
push ['0Ch']
call ['_uprv_malloc_56']
add ['esp,', '4']
mov ['[ebp+var_44],', 'eax']
mov ['eax,', '[ebp+var_44]']
mov ['ecx,', '[ebp+var_8]']
mov ['[eax],', 'ecx']
mov ['eax,', '[ebp+var_44]']
mov ['ecx,', '[ebp+arg_C]']
mov ['[eax+8],', 'ecx']
mov ['eax,', '[ebp+var_44]']
mov ['cx,', '[ebp+var_14]']
mov ['[eax+4],', 'cx']
mov ['eax,', '[ebp+var_44]']
movsx ['ecx,', 'word', 'ptr', '[eax+4]']
cmp ['ecx,', '3']
jle ['short', 'loc_18CF4']
mov ['eax,', 'ds:_mappingDataCapacity']
add ['eax,', '1']
mov ['ds:_mappingDataCapacity,', 'eax']
mov ['eax,', '[ebp+var_44]']
movsx ['ecx,', 'word', 'ptr', '[eax+4]']
cmp ['ds:_maxLength,', 'ecx']
jge ['short', 'loc_18D10']
mov ['eax,', '[ebp+var_44]']
movsx ['ecx,', 'word', 'ptr', '[eax+4]']
mov ['ds:_maxLength,', 'ecx']
mov ['eax,', '[ebp+arg_10]']
push ['eax']
mov ['ecx,', '[ebp+var_44]']
push ['ecx']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
mov ['eax,', 'ds:_hashTable']
push ['eax']
call ['_uhash_iput_56']
add ['esp,', '10h']
movsx ['eax,', '[ebp+var_14]']
add ['eax,', 'ds:_mappingDataCapacity']
mov ['ds:_mappingDataCapacity,', 'eax']
mov ['eax,', '[ebp+arg_10]']
cmp ['dword', 'ptr', '[eax],', '0']
jle ['short', 'loc_18D8F']
mov ['eax,', '[ebp+arg_10]']
mov ['ecx,', '[eax]']
push ['ecx']
call ['_u_errorName_56']
add ['esp,', '4']
mov ['esi,', 'esp']
push ['eax']
push ['offset', '??_C@_0DE@HFOBNBND@Failed?5to?5put?5entries?5into?5the?5h@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+arg_10]']
mov ['ecx,', '[eax]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '120h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['4']
assume ['cs:_rdata']
public ['??_C@_0DE@HFOBNBND@Failed?5to?5put?5entries?5into?5the?5h@']
assume ['cs:_rdata']
public ['??_C@_0EE@MJJFGPJO@The?5second?5bit?5in?5the?5trie?5word?5@']
db ["'.',0Ah,0"]
assume ['cs:_rdata']
public ['??_C@_0DO@PGDIEDKM@trieWord?5cannot?5contain?5value?5gr@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CJ@FKJENIIC@Could?5not?5set?5the?5value?5for?5code@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CJ@IHNBFCKN@Type?5for?5codepoint?5?2U?$CF08X?5alread@']
align ['4']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_valueDeleter	proc near		
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0CCh']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_CC]']
mov ['ecx,', '33h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', '[ebp+arg_0]']
mov ['[ebp+var_8],', 'eax']
mov ['eax,', '[ebp+var_8]']
mov ['ecx,', '[eax]']
push ['ecx']
call ['_uprv_free_56']
add ['esp,', '4']
mov ['eax,', '[ebp+var_8]']
push ['eax']
call ['_uprv_free_56']
add ['esp,', '4']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '0CCh']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['4']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_hashEntry	proc near		
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0C0h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_C0]']
mov ['ecx,', '30h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', '[ebp+arg_0]']
pop ['edi']
pop ['esi']
pop ['ebx']
mov ['esp,', 'ebp']
pop ['ebp']
retn
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_compareEntries	proc near		
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0C0h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_C0]']
mov ['ecx,', '30h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', '[ebp+arg_0]']
cmp ['eax,', '[ebp+arg_4]']
setnz ['al']
pop ['edi']
pop ['esi']
pop ['ebx']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['10h']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_storeRange	proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0D8h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_D8]']
mov ['ecx,', '36h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
xor ['eax,', 'eax']
mov ['[ebp+var_8],', 'ax']
mov ['eax,', '[ebp+arg_8]']
add ['eax,', '0FFF0h']
cmp ['eax,', '0FFFFh']
jle ['short', 'loc_18FCE']
mov ['esi,', 'esp']
push ['offset', '??_C@_0DE@DKOMPLMK@trieWord?5cannot?5contain?5value?5gr@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['0Ch']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+arg_8]']
add ['eax,', '0FFF0h']
mov ['[ebp+var_8],', 'ax']
mov ['eax,', '[ebp+arg_0]']
cmp ['eax,', '[ebp+arg_4]']
jnz ['loc_19186']
push ['0']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
mov ['ecx,', 'ds:_sprepTrie']
push ['ecx']
call ['_utrie_get32_56']
add ['esp,', '0Ch']
mov ['[ebp+var_14],', 'eax']
cmp ['[ebp+var_14],', '0']
jbe ['loc_19126']
cmp ['[ebp+var_14],', '0FFF0h']
jnb ['loc_190DE']
cmp ['[ebp+arg_8],', '2']
jnz ['loc_190DE']
mov ['eax,', '[ebp+var_14]']
add ['eax,', '1']
mov ['[ebp+var_14],', 'eax']
mov ['ax,', 'word', 'ptr', '[ebp+var_14]']
mov ['[ebp+var_8],', 'ax']
movzx ['eax,', '[ebp+var_8]']
cmp ['eax,', '0FFF0h']
jge ['short', 'loc_1909C']
movzx ['eax,', '[ebp+var_8]']
push ['eax']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
mov ['edx,', 'ds:_sprepTrie']
push ['edx']
call ['_utrie_set32_56']
add ['esp,', '0Ch']
movsx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_19095']
mov ['esi,', 'esp']
push ['offset', '??_C@_0CJ@FKJENIIC@Could?5not?5set?5the?5value?5for?5code@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['1']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['loc_191E8']
jmp ['short', 'loc_190DC']
mov ['esi,', 'esp']
push ['0FFF0h']
push ['offset', '??_C@_0DO@PGDIEDKM@trieWord?5cannot?5contain?5value?5gr@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['0Ch']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['short', 'loc_19126']
movzx ['eax,', '[ebp+var_8]']
cmp ['[ebp+var_14],', 'eax']
jz ['short', 'loc_19126']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
push ['offset', '??_C@_0CK@BHONEHGJ@Value?5for?5codepoint?5?2U?$CF08X?5alrea@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['1']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
movzx ['eax,', '[ebp+var_8]']
push ['eax']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
mov ['edx,', 'ds:_sprepTrie']
push ['edx']
call ['_utrie_set32_56']
add ['esp,', '0Ch']
movsx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_19184']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
push ['offset', '??_C@_0DA@KNLOLIJO@Could?5not?5set?5the?5value?5for?5code@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['1']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['short', 'loc_191E8']
push ['0']
movzx ['eax,', '[ebp+var_8]']
push ['eax']
mov ['ecx,', '[ebp+arg_4]']
add ['ecx,', '1']
push ['ecx']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
mov ['eax,', 'ds:_sprepTrie']
push ['eax']
call ['_utrie_setRange32_56']
add ['esp,', '14h']
movsx ['ecx,', 'al']
test ['ecx,', 'ecx']
jnz ['short', 'loc_191E8']
mov ['esi,', 'esp']
push ['offset', '??_C@_0CK@FFJAJPDB@Value?5for?5certain?5codepoint?5alre@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['0Ch']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '0D8h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
assume ['cs:_rdata']
public ['??_C@_0CK@FFJAJPDB@Value?5for?5certain?5codepoint?5alre@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0DA@KNLOLIJO@Could?5not?5set?5the?5value?5for?5code@']
assume ['cs:_rdata']
public ['??_C@_0CK@BHONEHGJ@Value?5for?5codepoint?5?2U?$CF08X?5alrea@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0DE@DKOMPLMK@trieWord?5cannot?5contain?5value?5gr@']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_generateData	proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '108h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_108]']
mov ['ecx,', '42h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['[ebp+Code],', '0']
mov ['eax,', '[ebp+Str]']
push ['eax']
call ['_strlen']
add ['esp,', '4']
add ['eax,', '64h']
push ['eax']
call ['_uprv_malloc_56']
add ['esp,', '4']
mov ['[ebp+Dest],', 'eax']
call ['_storeMappingData']
lea ['eax,', '[ebp+Code]']
push ['eax']
push ['1']
push ['offset', '_getFoldedValue']
push ['offset', 'dword_186A0']
push ['offset', '?sprepTrieBlock@?1??generateData@@9@9']
mov ['ecx,', 'ds:_sprepTrie']
push ['ecx']
call ['_utrie_serialize_56']
add ['esp,', '18h']
mov ['[ebp+var_44],', 'eax']
cmp ['[ebp+Code],', '0']
jle ['short', 'loc_19374']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['_u_errorName_56']
add ['esp,', '4']
mov ['esi,', 'esp']
push ['eax']
push ['offset', '??_C@_0CP@KLJAJOJM@error?3?5utrie_serialize?$CIsprep?5tri@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', 'ds:_mappingDataCapacity']
mov ['ecx,', '[ebp+var_44]']
lea ['edx,', '[ecx+eax*2+40h]']
mov ['[ebp+var_20],', 'edx']
movsx ['eax,', 'byte', 'ptr', 'ds:_beVerbose']
test ['eax,', 'eax']
jz ['loc_19427']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_44]']
push ['eax']
push ['offset', '??_C@_0CL@INDLCEOH@size?5of?5sprep?5trie?5?5?5?5?5?5?5?5?5?5?5?5?5?5@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_20]']
push ['eax']
mov ['ecx,', '[ebp+Str]']
push ['ecx']
push ['offset', '??_C@_0CN@MLJLFMOK@size?5of?5icudt56l_?$CFs?4spp?5contents@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', 'ds:_mappingDataCapacity']
shl ['eax,', '1']
mov ['esi,', 'esp']
push ['eax']
push ['offset', '??_C@_0CG@LFECKODH@size?5of?5mapping?5data?5array?5?$CF5u?5b@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
movsx ['eax,', 'ds:_currentIndex']
mov ['esi,', 'esp']
push ['eax']
push ['offset', '??_C@_0DN@LMAGICM@Number?5of?5code?5units?5in?5mappingD@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', 'ds:_maxLength']
push ['eax']
push ['offset', '??_C@_0CP@IEOANGJF@Maximum?5length?5of?5the?5mapping?5st@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+Dest]']
mov ['byte', 'ptr', '[eax],', '0']
mov ['eax,', '[ebp+Str]']
push ['eax']
mov ['ecx,', '[ebp+Dest]']
push ['ecx']
call ['_strcat']
add ['esp,', '8']
lea ['eax,', '[ebp+Code]']
push ['eax']
movsx ['ecx,', 'byte', 'ptr', 'ds:_haveCopyright']
neg ['ecx']
sbb ['ecx,', 'ecx']
and ['ecx,', 'offset', '??_C@_0GD@IBBFEJOD@?5Copyright?5?$CIC?$CJ?52015?0?5Internation@']
push ['ecx']
push ['offset', '_dataInfo']
mov ['edx,', '[ebp+Dest]']
push ['edx']
push ['offset', '??_C@_03NMPPDODH@spp?$AA@']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['_udata_create']
add ['esp,', '18h']
mov ['[ebp+var_8],', 'eax']
cmp ['[ebp+Code],', '0']
jle ['short', 'loc_194B7']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
push ['offset', '??_C@_0DG@DKEHGGJM@gensprep?3?5unable?5to?5create?5the?5o@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+var_44]']
mov ['ds:_indexes,', 'eax']
mov ['eax,', 'ds:_mappingDataCapacity']
shl ['eax,', '1']
mov ['ds:dword_186AC,', 'eax']
push ['40h']
push ['offset', '_indexes']
mov ['eax,', '[ebp+var_8]']
push ['eax']
call ['_udata_writeBlock']
add ['esp,', '0Ch']
mov ['eax,', '[ebp+var_44]']
push ['eax']
push ['offset', '?sprepTrieBlock@?1??generateData@@9@9']
mov ['ecx,', '[ebp+var_8]']
push ['ecx']
call ['_udata_writeBlock']
add ['esp,', '0Ch']
mov ['eax,', 'ds:dword_186AC']
push ['eax']
mov ['ecx,', 'ds:_mappingData']
push ['ecx']
mov ['edx,', '[ebp+var_8]']
push ['edx']
call ['_udata_writeBlock']
add ['esp,', '0Ch']
lea ['eax,', '[ebp+Code]']
push ['eax']
mov ['ecx,', '[ebp+var_8]']
push ['ecx']
call ['_udata_finish']
add ['esp,', '8']
mov ['[ebp+var_2C],', 'eax']
cmp ['[ebp+Code],', '0']
jle ['short', 'loc_19566']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
push ['offset', '??_C@_0CM@JCBHAMFP@gensprep?3?5error?5?$CFd?5writing?5the?5o@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+var_2C]']
cmp ['eax,', '[ebp+var_20]']
jz ['short', 'loc_195B1']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_20]']
push ['eax']
mov ['ecx,', '[ebp+var_2C]']
push ['ecx']
push ['offset', '??_C@_0DI@KPMHJOEI@gensprep?5error?3?5data?5length?5?$CFld?5@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['5']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
cmp ['ds:_hashTable,', '0']
jz ['short', 'loc_195C8']
mov ['eax,', 'ds:_hashTable']
push ['eax']
call ['_uhash_close_56']
add ['esp,', '4']
mov ['eax,', '[ebp+Dest]']
push ['eax']
call ['_uprv_free_56']
add ['esp,', '4']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN11']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '108h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['4']
dd ['offset', '$LN10']
dd ['offset', '$LN9']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0DI@KPMHJOEI@gensprep?5error?3?5data?5length?5?$CFld?5@']
assume ['cs:_rdata']
public ['??_C@_0CM@JCBHAMFP@gensprep?3?5error?5?$CFd?5writing?5the?5o@']
assume ['cs:_rdata']
public ['??_C@_0DG@DKEHGGJM@gensprep?3?5unable?5to?5create?5the?5o@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_03NMPPDODH@spp?$AA@']
assume ['cs:_rdata']
public ['??_C@_0GD@IBBFEJOD@?5Copyright?5?$CIC?$CJ?52015?0?5Internation@']
db ["'and", 'others.', 'All', 'Rights', 'Reserved.', "',0"]
align ['10h']
assume ['cs:_rdata']
public ['??_C@_0CP@IEOANGJF@Maximum?5length?5of?5the?5mapping?5st@']
align ['10h']
assume ['cs:_rdata']
public ['??_C@_0DN@LMAGICM@Number?5of?5code?5units?5in?5mappingD@']
align ['10h']
assume ['cs:_rdata']
public ['??_C@_0CG@LFECKODH@size?5of?5mapping?5data?5array?5?$CF5u?5b@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CN@MLJLFMOK@size?5of?5icudt56l_?$CFs?4spp?5contents@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CL@INDLCEOH@size?5of?5sprep?5trie?5?5?5?5?5?5?5?5?5?5?5?5?5?5@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CP@KLJAJOJM@error?3?5utrie_serialize?$CIsprep?5tri@']
align ['4']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_storeMappingData proc near		
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '144h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_144]']
mov ['ecx,', '51h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['[ebp+var_8],', '0FFFFFFFFh']
mov ['[ebp+var_14],', '0']
mov ['[ebp+var_20],', '0']
mov ['[ebp+var_2C],', '0']
mov ['[ebp+var_38],', '0']
mov ['[ebp+var_44],', '0']
mov ['[ebp+var_50],', '1']
mov ['[ebp+var_5C],', '0']
xor ['eax,', 'eax']
mov ['[ebp+var_68],', 'ax']
mov ['[ebp+var_74],', '0']
cmp ['ds:_hashTable,', '0']
jnz ['short', 'loc_198B5']
jmp ['loc_19C2E']
mov ['eax,', 'ds:_hashTable']
push ['eax']
call ['_uhash_count_56']
add ['esp,', '4']
mov ['[ebp+var_38],', 'eax']
push ['2']
mov ['eax,', 'ds:_mappingDataCapacity']
push ['eax']
call ['_uprv_calloc_56']
add ['esp,', '8']
mov ['ds:_mappingData,', 'eax']
mov ['eax,', '[ebp+var_44]']
cmp ['eax,', '[ebp+var_38]']
jge ['loc_19C0A']
lea ['eax,', '[ebp+var_8]']
push ['eax']
mov ['ecx,', 'ds:_hashTable']
push ['ecx']
call ['_uhash_nextElement_56']
add ['esp,', '8']
mov ['[ebp+var_14],', 'eax']
cmp ['[ebp+var_14],', '0']
jz ['loc_19BF5']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[eax+8]']
mov ['[ebp+var_2C],', 'ecx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[eax+4]']
mov ['[ebp+var_20],', 'ecx']
mov ['eax,', '[ebp+var_5C]']
cmp ['eax,', '[ebp+var_50]']
jz ['short', 'loc_19954']
cmp ['[ebp+var_5C],', '3']
jg ['short', 'loc_19938']
movsx ['eax,', 'ds:_currentIndex']
mov ['ecx,', '[ebp+var_50]']
mov ['ds:dword_186B0[ecx*4],', 'eax']
cmp ['[ebp+var_5C],', '3']
jg ['short', 'loc_1994E']
cmp ['[ebp+var_50],', '4']
jnz ['short', 'loc_1994E']
movsx ['eax,', 'ds:_currentIndex']
mov ['[ebp+var_74],', 'eax']
mov ['eax,', '[ebp+var_50]']
mov ['[ebp+var_5C],', 'eax']
mov ['eax,', '[ebp+var_20]']
movsx ['ecx,', 'word', 'ptr', '[eax+4]']
cmp ['ecx,', '[ebp+var_50]']
jnz ['loc_19BF0']
mov ['[ebp+var_80],', '0']
movsx ['eax,', 'ds:_currentIndex']
shl ['eax,', '2']
mov ['[ebp+var_68],', 'ax']
movzx ['eax,', '[ebp+var_68]']
add ['eax,', '2']
mov ['[ebp+var_68],', 'ax']
movzx ['eax,', '[ebp+var_68]']
cmp ['eax,', '0FFF0h']
jle ['short', 'loc_199CF']
mov ['esi,', 'esp']
push ['0FFF0h']
push ['offset', '??_C@_0DE@GOBNNAGN@trieWord?5cannot?5contain?5value?5gr@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['0Ch']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
push ['0']
mov ['eax,', '[ebp+var_2C]']
push ['eax']
mov ['ecx,', 'ds:_sprepTrie']
push ['ecx']
call ['_utrie_get32_56']
add ['esp,', '0Ch']
mov ['[ebp+var_80],', 'eax']
cmp ['[ebp+var_80],', '0']
jz ['short', 'loc_19A46']
mov ['eax,', '[ebp+var_80]']
sub ['eax,', '0FFF0h']
cmp ['eax,', '2']
jnz ['short', 'loc_19A07']
movzx ['eax,', '[ebp+var_68]']
add ['eax,', '1']
mov ['[ebp+var_68],', 'ax']
jmp ['short', 'loc_19A46']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_2C]']
push ['eax']
push ['offset', '??_C@_0CJ@IHNBFCKN@Type?5for?5codepoint?5?2U?$CF08X?5alread@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['1']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
movzx ['eax,', '[ebp+var_68]']
push ['eax']
mov ['ecx,', '[ebp+var_2C]']
push ['ecx']
mov ['edx,', 'ds:_sprepTrie']
push ['edx']
call ['_utrie_set32_56']
add ['esp,', '0Ch']
movsx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_19AA0']
mov ['esi,', 'esp']
push ['offset', '??_C@_0CJ@FKJENIIC@Could?5not?5set?5the?5value?5for?5code@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['1']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+var_44]']
add ['eax,', '1']
mov ['[ebp+var_44],', 'eax']
movsx ['eax,', 'ds:_currentIndex']
mov ['ecx,', '[ebp+var_20]']
movsx ['edx,', 'word', 'ptr', '[ecx+4]']
lea ['eax,', '[eax+edx+1]']
cmp ['eax,', '3FBFh']
jle ['short', 'loc_19B13']
mov ['esi,', 'esp']
push ['3FBFh']
movsx ['eax,', 'ds:_currentIndex']
mov ['ecx,', '[ebp+var_20]']
movsx ['edx,', 'word', 'ptr', '[ecx+4]']
add ['eax,', 'edx']
push ['eax']
push ['offset', '??_C@_0EB@GDLIIAFA@Too?5many?5entries?5in?5the?5mapping?5@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['8']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
cmp ['[ebp+var_50],', '3']
jle ['short', 'loc_19B3E']
movsx ['eax,', 'ds:_currentIndex']
mov ['ecx,', 'ds:_mappingData']
mov ['dx,', 'word', 'ptr', '[ebp+var_50]']
mov ['[ecx+eax*2],', 'dx']
mov ['ax,', 'ds:_currentIndex']
add ['ax,', '1']
mov ['ds:_currentIndex,', 'ax']
push ['1']
mov ['eax,', '[ebp+var_20]']
mov ['ecx,', '[eax]']
push ['ecx']
call ['_uprv_checkValidMemory']
add ['esp,', '8']
mov ['edx,', '[ebp+var_20]']
movsx ['eax,', 'word', 'ptr', '[edx+4]']
shl ['eax,', '1']
mov ['esi,', 'esp']
push ['eax']
mov ['ecx,', '[ebp+var_20]']
mov ['edx,', '[ecx]']
push ['edx']
movsx ['eax,', 'ds:_currentIndex']
mov ['ecx,', 'ds:_mappingData']
lea ['edx,', '[ecx+eax*2]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__memmove']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+var_20]']
movsx ['ecx,', 'word', 'ptr', '[eax+4]']
movsx ['edx,', 'ds:_currentIndex']
add ['edx,', 'ecx']
mov ['ds:_currentIndex,', 'dx']
movsx ['eax,', 'ds:_currentIndex']
cmp ['eax,', 'ds:_mappingDataCapacity']
jle ['short', 'loc_19BF0']
mov ['eax,', 'ds:?__LINE__Var@?1??storeMappingData@@9@9@39dcc198']
add ['eax,', '60h']
mov ['esi,', 'esp']
push ['eax']
push ['offset', '??_C@_0DC@POONMHLH@d?3?2mozilla?2intl?2icu?2source?2tools@']
push ['offset', '??_C@_0CN@DLNFECPO@gensprep?0?5fatal?5error?5at?5?$CFs?0?5?$CFd?4@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['5']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['loc_198E7']
mov ['eax,', '[ebp+var_50]']
add ['eax,', '1']
mov ['[ebp+var_50],', 'eax']
mov ['[ebp+var_8],', '0FFFFFFFFh']
jmp ['loc_198DB']
cmp ['[ebp+var_50],', '3']
jg ['short', 'loc_19C26']
movsx ['eax,', 'ds:_currentIndex']
add ['eax,', '1']
mov ['ecx,', '[ebp+var_50]']
mov ['ds:dword_186B0[ecx*4],', 'eax']
jmp ['short', 'loc_19C2E']
mov ['eax,', '[ebp+var_74]']
mov ['ds:dword_186C0,', 'eax']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN24']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '144h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['4']
dd ['offset', '$LN23']
dd ['offset', '$LN22']
assume ['cs:_rdata']
public ['??_C@_0CN@DLNFECPO@gensprep?0?5fatal?5error?5at?5?$CFs?0?5?$CFd?4@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0DC@POONMHLH@d?3?2mozilla?2intl?2icu?2source?2tools@']
align ['10h']
assume ['cs:_data']
public ['?__LINE__Var@?1??storeMappingData@@9@9@39dcc198']
assume ['cs:_rdata']
public ['??_C@_0EB@GDLIIAFA@Too?5many?5entries?5in?5the?5mapping?5@']
db ['0']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0DE@GOBNNAGN@trieWord?5cannot?5contain?5value?5gr@']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_getFoldedValue	proc near		
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0E4h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_E4]']
mov ['ecx,', '39h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['[ebp+var_14],', '0']
mov ['eax,', '[ebp+arg_4]']
add ['eax,', '400h']
mov ['[ebp+var_14],', 'eax']
mov ['eax,', '[ebp+arg_4]']
cmp ['eax,', '[ebp+var_14]']
jge ['short', 'loc_19DC6']
lea ['eax,', '[ebp+var_1D]']
push ['eax']
mov ['ecx,', '[ebp+arg_4]']
push ['ecx']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
call ['_utrie_get32_56']
add ['esp,', '0Ch']
mov ['[ebp+var_8],', 'eax']
movsx ['eax,', '[ebp+var_1D]']
test ['eax,', 'eax']
jz ['short', 'loc_19DAE']
mov ['eax,', '[ebp+arg_4]']
add ['eax,', '20h']
mov ['[ebp+arg_4],', 'eax']
jmp ['short', 'loc_19DC4']
cmp ['[ebp+var_8],', '0']
jz ['short', 'loc_19DBB']
mov ['eax,', '[ebp+arg_8]']
jmp ['short', 'loc_19DC8']
jmp ['short', 'loc_19DC4']
mov ['eax,', '[ebp+arg_4]']
add ['eax,', '1']
mov ['[ebp+arg_4],', 'eax']
jmp ['short', 'loc_19D7C']
xor ['eax,', 'eax']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN11_0']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '0E4h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['10h']
dd ['offset', '$LN10_0']
dd ['offset', '$LN9_0']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_data,', 'fs:nothing,', 'gs:nothing']
endp
_cleanUpData	proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0C0h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_C0]']
mov ['ecx,', '30h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'ds:_mappingData']
push ['eax']
call ['_uprv_free_56']
add ['esp,', '4']
mov ['eax,', 'ds:_sprepTrie']
push ['eax']
call ['_utrie_close_56']
add ['esp,', '4']
mov ['eax,', 'ds:_sprepTrie']
push ['eax']
call ['_uprv_free_56']
add ['esp,', '4']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '0C0h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
extrn ['_memcpy:near']
extrn ['_uprv_checkValidMemory:near']
extrn ['_u_versionFromString_56:near']
extrn ['__RTC_CheckEsp:near']
extrn ['@_RTC_CheckStackVars@8:near']
extrn ['__RTC_Shutdown:near']
extrn ['__RTC_InitBase:near']
extrn ['__imp__exit:near']
extrn ['__imp__fprintf:near']
extrn ['__imp____iob_func:near']
extrn ['_utrie_open_56:near']
extrn ['_uprv_calloc_56:near']
extrn ['_u_errorName_56:near']
extrn ['_uhash_iput_56:near']
extrn ['_uprv_malloc_56:near']
extrn ['_utrie_set32_56:near']
extrn ['_utrie_get32_56:near']
extrn ['_uhash_setValueDeleter_56:near']
extrn ['_uhash_open_56:near']
extrn ['_uprv_free_56:near']
extrn ['_utrie_setRange32_56:near']
extrn ['_uhash_close_56:near']
extrn ['_udata_finish:near']
extrn ['_udata_writeBlock:near']
extrn ['_udata_create:near']
extrn ['_haveCopyright:near']
extrn ['_strcat:near']
extrn ['__imp__printf:near']
extrn ['_beVerbose:near']
extrn ['_utrie_serialize_56:near']
extrn ['_strlen:near']
extrn ['__imp__memmove:near']
extrn ['_uhash_nextElement_56:near']
extrn ['_uhash_count_56:near']
extrn ['_utrie_close_56:near']
end
