endp
_uprv_mapFile_56 proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '114h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_114]']
mov ['ecx,', '45h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['[ebp+lpFileMappingAttributes],', '0']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['_UDataMemory_init_56']
add ['esp,', '4']
mov ['esi,', 'esp']
push ['0']
push ['10000080h']
push ['3']
push ['0']
push ['1']
push ['80000000h']
mov ['eax,', '[ebp+lpFileName]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__CreateFileA@28']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+hFile],', 'eax']
cmp ['[ebp+hFile],', '0FFFFFFFFh']
jnz ['short', 'loc_66']
xor ['al,', 'al']
jmp ['loc_151']
mov ['esi,', 'esp']
push ['1']
lea ['eax,', '[ebp+pSecurityDescriptor]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__InitializeSecurityDescriptor@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jz ['short', 'loc_C6']
mov ['esi,', 'esp']
push ['0']
push ['0']
push ['1']
lea ['eax,', '[ebp+pSecurityDescriptor]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__SetSecurityDescriptorDacl@16']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jz ['short', 'loc_C6']
push ['0Ch']
push ['0']
lea ['eax,', '[ebp+Dst]']
push ['eax']
call ['_memset']
add ['esp,', '0Ch']
mov ['[ebp+Dst],', '0Ch']
lea ['eax,', '[ebp+pSecurityDescriptor]']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', '0']
lea ['eax,', '[ebp+Dst]']
mov ['[ebp+lpFileMappingAttributes],', 'eax']
mov ['esi,', 'esp']
push ['0']
push ['0']
push ['0']
push ['2']
mov ['eax,', '[ebp+lpFileMappingAttributes]']
push ['eax']
mov ['ecx,', '[ebp+hFile]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__CreateFileMappingA@24']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+hFileMappingObject],', 'eax']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+hFile]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__CloseHandle@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
cmp ['[ebp+hFileMappingObject],', '0']
jnz ['short', 'loc_105']
xor ['al,', 'al']
jmp ['short', 'loc_151']
mov ['esi,', 'esp']
push ['0']
push ['0']
push ['0']
push ['4']
mov ['eax,', '[ebp+hFileMappingObject]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__MapViewOfFile@20']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['ecx,', '[ebp+arg_0]']
mov ['[ecx+4],', 'eax']
mov ['eax,', '[ebp+arg_0]']
cmp ['dword', 'ptr', '[eax+4],', '0']
jnz ['short', 'loc_146']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+hFileMappingObject]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__CloseHandle@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['al,', 'al']
jmp ['short', 'loc_151']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[ebp+hFileMappingObject]']
mov ['[eax+14h],', 'ecx']
mov ['al,', '1']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN11']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '114h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['4']
dd ['offset', '$LN10']
dd ['offset', '$LN8']
dd ['0FFFFFFB0h,', '14h']
dd ['offset', '$LN9']
align ['4']
assume ['cs:_rtc$TMZ']
assume ['cs:_rtc$IMZ']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_rtc$TMZ,', 'fs:nothing,', 'gs:nothing']
endp
_uprv_unmapFile_56 proc	near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0C0h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_C0]']
mov ['ecx,', '30h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
cmp ['[ebp+arg_0],', '0']
jz ['short', 'loc_22D']
mov ['eax,', '[ebp+arg_0]']
cmp ['dword', 'ptr', '[eax+14h],', '0']
jz ['short', 'loc_22D']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax+4]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__UnmapViewOfFile@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax+14h]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__CloseHandle@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+arg_0]']
mov ['dword', 'ptr', '[eax+4],', '0']
mov ['eax,', '[ebp+arg_0]']
mov ['dword', 'ptr', '[eax+14h],', '0']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '0C0h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
extrn ['__imp__MapViewOfFile@20:near']
extrn ['__imp__CloseHandle@4:near']
extrn ['__imp__CreateFileMappingA@24:near']
extrn ['_memset:near']
extrn ['__imp__SetSecurityDescriptorDacl@16:near']
extrn ['__imp__InitializeSecurityDescriptor@8:near']
extrn ['__imp__CreateFileA@28:near']
extrn ['_UDataMemory_init_56:near']
extrn ['@_RTC_CheckStackVars@8:near']
extrn ['__RTC_CheckEsp:near']
extrn ['__RTC_Shutdown:near']
extrn ['__RTC_InitBase:near']
extrn ['__imp__UnmapViewOfFile@4:near']
end
