@AesCbc_Encode_Intel@12 proc near
push ['ebx']
mov ['ebx,', 'esp']
sub ['esp,', '8']
and ['esp,', '0FFFFFFF0h']
add ['esp,', '4']
push ['ebp']
mov ['ebp,', '[ebx+4]']
mov ['[esp+0Ch+var_8],', 'ebp']
mov ['ebp,', 'esp']
sub ['esp,', '30h']
push ['edi']
push ['ecx']
lea ['edi,', '[ebp-30h]']
mov ['ecx,', '0Ch']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
pop ['ecx']
mov ['[ebp-8],', 'edx']
mov ['[ebp-4],', 'ecx']
mov ['eax,', '[ebp-4]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax]']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm0']
jmp ['short', 'loc_51']
mov ['ecx,', '[ebx+8]']
sub ['ecx,', '1']
mov ['[ebx+8],', 'ecx']
mov ['edx,', '[ebp-8]']
add ['edx,', '10h']
mov ['[ebp-8],', 'edx']
cmp ['dword', 'ptr', '[ebx+8],', '0']
jz ['loc_11A']
mov ['eax,', '[ebp-4]']
mov ['ecx,', '[eax+10h]']
sub ['ecx,', '1']
mov ['[ebp-24h],', 'ecx']
mov ['edx,', '[ebp-4]']
add ['edx,', '30h']
mov ['[ebp-28h],', 'edx']
mov ['eax,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm1']
mov ['ecx,', '[ebp-4]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx+20h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm1']
mov ['edx,', '[ebp-28h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[edx]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm1']
mov ['eax,', '[ebp-28h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax+10h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm1']
mov ['ecx,', '[ebp-28h]']
add ['ecx,', '20h']
mov ['[ebp-28h],', 'ecx']
mov ['edx,', '[ebp-24h]']
sub ['edx,', '1']
mov ['[ebp-24h],', 'edx']
jnz ['short', 'loc_9B']
mov ['eax,', '[ebp-28h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm1']
mov ['ecx,', '[ebp-28h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx+10h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
aesenclast ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm1']
mov ['edx,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-20h]']
movdqa ['xmmword', 'ptr', '[edx],', 'xmm0']
jmp ['loc_3F']
mov ['eax,', '[ebp-4]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-20h]']
movdqa ['xmmword', 'ptr', '[eax],', 'xmm0']
pop ['edi']
mov ['esp,', 'ebp']
pop ['ebp']
mov ['esp,', 'ebx']
pop ['ebx']
retn ['4']
endp
@AesCbc_Decode_Intel@12 proc near
push ['ebx']
mov ['ebx,', 'esp']
sub ['esp,', '8']
and ['esp,', '0FFFFFFF0h']
add ['esp,', '4']
push ['ebp']
mov ['ebp,', '[ebx+4]']
mov ['[esp+0Ch+var_8],', 'ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0E0h']
push ['edi']
push ['ecx']
lea ['edi,', '[ebp-0E0h]']
mov ['ecx,', '38h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
pop ['ecx']
mov ['[ebp-8],', 'edx']
mov ['[ebp-4],', 'ecx']
mov ['eax,', '[ebp-4]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax]']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm0']
jmp ['short', 'loc_187']
mov ['ecx,', '[ebx+8]']
sub ['ecx,', '3']
mov ['[ebx+8],', 'ecx']
mov ['edx,', '[ebp-8]']
add ['edx,', '30h']
mov ['[ebp-8],', 'edx']
cmp ['dword', 'ptr', '[ebx+8],', '3']
jb ['loc_3F9']
mov ['eax,', '[ebp-4]']
mov ['ecx,', '[eax+10h]']
mov ['[ebp-24h],', 'ecx']
mov ['edx,', '[ebp-24h]']
shl ['edx,', '1']
shl ['edx,', '4']
add ['edx,', '[ebp-4]']
mov ['[ebp-28h],', 'edx']
mov ['eax,', '[ebp-28h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax+20h]']
movdqa ['xmmword', 'ptr', '[ebp-70h],', 'xmm0']
mov ['ecx,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-70h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-40h],', 'xmm1']
mov ['edx,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[edx+10h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-70h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-50h],', 'xmm1']
mov ['eax,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax+20h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-70h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-60h],', 'xmm1']
mov ['ecx,', '[ebp-24h]']
sub ['ecx,', '1']
mov ['[ebp-24h],', 'ecx']
mov ['edx,', '[ebp-28h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[edx+10h]']
movdqa ['xmmword', 'ptr', '[ebp-80h],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-80h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-40h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-40h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-80h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-50h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-50h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-80h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-60h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-60h],', 'xmm1']
mov ['eax,', '[ebp-28h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax]']
movdqa ['xmmword', 'ptr', '[ebp-90h],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-90h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-40h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-40h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-90h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-50h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-50h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-90h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-60h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-60h],', 'xmm1']
mov ['ecx,', '[ebp-28h]']
sub ['ecx,', '20h']
mov ['[ebp-28h],', 'ecx']
mov ['edx,', '[ebp-24h]']
sub ['edx,', '1']
mov ['[ebp-24h],', 'edx']
jnz ['loc_1FF']
mov ['eax,', '[ebp-28h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax+10h]']
movdqa ['xmmword', 'ptr', '[ebp-0A0h],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0A0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-40h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-40h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0A0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-50h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-50h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0A0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-60h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-60h],', 'xmm1']
mov ['ecx,', '[ebp-28h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx]']
movdqa ['xmmword', 'ptr', '[ebp-0B0h],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0B0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-40h]']
aesdeclast ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-40h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0B0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-50h]']
aesdeclast ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-50h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0B0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-60h]']
aesdeclast ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-60h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-20h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-40h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0C0h],', 'xmm1']
mov ['edx,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[edx]']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm0']
mov ['eax,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0C0h]']
movdqa ['xmmword', 'ptr', '[eax],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-20h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-50h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0C0h],', 'xmm1']
mov ['ecx,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx+10h]']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm0']
mov ['edx,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0C0h]']
movdqa ['xmmword', 'ptr', '[edx+10h],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-20h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-60h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0C0h],', 'xmm1']
mov ['eax,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax+20h]']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm0']
mov ['ecx,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0C0h]']
movdqa ['xmmword', 'ptr', '[ecx+20h],', 'xmm0']
jmp ['loc_175']
jmp ['short', 'loc_40D']
mov ['edx,', '[ebx+8]']
sub ['edx,', '1']
mov ['[ebx+8],', 'edx']
mov ['eax,', '[ebp-8]']
add ['eax,', '10h']
mov ['[ebp-8],', 'eax']
cmp ['dword', 'ptr', '[ebx+8],', '0']
jz ['loc_53B']
mov ['ecx,', '[ebp-4]']
mov ['edx,', '[ecx+10h]']
mov ['[ebp-0C4h],', 'edx']
mov ['eax,', '[ebp-0C4h]']
shl ['eax,', '1']
shl ['eax,', '4']
add ['eax,', '[ebp-4]']
mov ['[ebp-0C8h],', 'eax']
mov ['ecx,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx]']
mov ['edx,', '[ebp-0C8h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[edx+20h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
mov ['eax,', '[ebp-0C4h]']
sub ['eax,', '1']
mov ['[ebp-0C4h],', 'eax']
mov ['ecx,', '[ebp-0C8h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx+10h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-0E0h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
mov ['edx,', '[ebp-0C8h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[edx]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-0E0h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
mov ['eax,', '[ebp-0C8h]']
sub ['eax,', '20h']
mov ['[ebp-0C8h],', 'eax']
mov ['ecx,', '[ebp-0C4h]']
sub ['ecx,', '1']
mov ['[ebp-0C4h],', 'ecx']
jnz ['short', 'loc_464']
mov ['edx,', '[ebp-0C8h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[edx+10h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-0E0h]']
aesdec ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
mov ['eax,', '[ebp-0C8h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-0E0h]']
aesdeclast ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-20h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-0E0h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
mov ['ecx,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx]']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm0']
mov ['edx,', '[ebp-8]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0E0h]']
movdqa ['xmmword', 'ptr', '[edx],', 'xmm0']
jmp ['loc_3FB']
mov ['eax,', '[ebp-4]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-20h]']
movdqa ['xmmword', 'ptr', '[eax],', 'xmm0']
pop ['edi']
mov ['esp,', 'ebp']
pop ['ebp']
mov ['esp,', 'ebx']
pop ['ebx']
retn ['4']
endp
@AesCtr_Code_Intel@12 proc near
push ['ebx']
mov ['ebx,', 'esp']
sub ['esp,', '8']
and ['esp,', '0FFFFFFF0h']
add ['esp,', '4']
push ['ebp']
mov ['ebp,', '[ebx+4]']
mov ['[esp+0Ch+var_8],', 'ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0E0h']
push ['edi']
push ['ecx']
lea ['edi,', '[ebp-0E0h]']
mov ['ecx,', '38h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
pop ['ecx']
mov ['[ebp-8],', 'edx']
mov ['[ebp-4],', 'ecx']
mov ['eax,', '[ebp-4]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax]']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm0']
mov ['dword', 'ptr', '[ebp-30h],', '1']
mov ['dword', 'ptr', '[ebp-2Ch],', '0']
mov ['dword', 'ptr', '[ebp-28h],', '0']
mov ['dword', 'ptr', '[ebp-24h],', '0']
jmp ['short', 'loc_5D3']
mov ['ecx,', '[ebx+8]']
sub ['ecx,', '3']
mov ['[ebx+8],', 'ecx']
mov ['edx,', '[ebp-8]']
add ['edx,', '30h']
mov ['[ebp-8],', 'edx']
cmp ['dword', 'ptr', '[ebx+8],', '3']
jb ['loc_82F']
mov ['eax,', '[ebp-4]']
mov ['ecx,', '[eax+10h]']
sub ['ecx,', '1']
mov ['[ebp-34h],', 'ecx']
mov ['edx,', '[ebp-4]']
mov ['[ebp-38h],', 'edx']
mov ['eax,', '[ebp-38h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax+20h]']
movdqa ['xmmword', 'ptr', '[ebp-80h],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-30h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
paddq ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-80h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-50h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-30h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
paddq ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-80h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-60h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-30h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
paddq ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-80h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-70h],', 'xmm1']
mov ['ecx,', '[ebp-38h]']
add ['ecx,', '30h']
mov ['[ebp-38h],', 'ecx']
mov ['edx,', '[ebp-38h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[edx]']
movdqa ['xmmword', 'ptr', '[ebp-90h],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-90h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-50h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-50h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-90h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-60h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-60h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-90h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-70h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-70h],', 'xmm1']
mov ['eax,', '[ebp-38h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax+10h]']
movdqa ['xmmword', 'ptr', '[ebp-0A0h],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0A0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-50h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-50h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0A0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-60h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-60h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0A0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-70h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-70h],', 'xmm1']
mov ['ecx,', '[ebp-38h]']
add ['ecx,', '20h']
mov ['[ebp-38h],', 'ecx']
mov ['edx,', '[ebp-34h]']
sub ['edx,', '1']
mov ['[ebp-34h],', 'edx']
jnz ['loc_677']
mov ['eax,', '[ebp-38h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax]']
movdqa ['xmmword', 'ptr', '[ebp-0B0h],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0B0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-50h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-50h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0B0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-60h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-60h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0B0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-70h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-70h],', 'xmm1']
mov ['ecx,', '[ebp-38h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx+10h]']
movdqa ['xmmword', 'ptr', '[ebp-0C0h],', 'xmm0']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0C0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-50h]']
aesenclast ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-50h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0C0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-60h]']
aesenclast ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-60h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0C0h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-70h]']
aesenclast ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-70h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-50h]']
mov ['edx,', '[ebp-8]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[edx]']
pxor ['xmm1,', 'xmm0']
mov ['eax,', '[ebp-8]']
movdqa ['xmmword', 'ptr', '[eax],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-60h]']
mov ['ecx,', '[ebp-8]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ecx+10h]']
pxor ['xmm1,', 'xmm0']
mov ['edx,', '[ebp-8]']
movdqa ['xmmword', 'ptr', '[edx+10h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-70h]']
mov ['eax,', '[ebp-8]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[eax+20h]']
pxor ['xmm1,', 'xmm0']
mov ['ecx,', '[ebp-8]']
movdqa ['xmmword', 'ptr', '[ecx+20h],', 'xmm1']
jmp ['loc_5C1']
jmp ['short', 'loc_843']
mov ['edx,', '[ebx+8]']
sub ['edx,', '1']
mov ['[ebx+8],', 'edx']
mov ['eax,', '[ebp-8]']
add ['eax,', '10h']
mov ['[ebp-8],', 'eax']
cmp ['dword', 'ptr', '[ebx+8],', '0']
jz ['loc_95D']
mov ['ecx,', '[ebp-4]']
mov ['edx,', '[ecx+10h]']
sub ['edx,', '1']
mov ['[ebp-0C4h],', 'edx']
mov ['eax,', '[ebp-4]']
mov ['[ebp-0C8h],', 'eax']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-30h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
paddq ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-20h],', 'xmm1']
mov ['ecx,', '[ebp-4]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx+20h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-20h]']
pxor ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
mov ['edx,', '[ebp-0C8h]']
add ['edx,', '30h']
mov ['[ebp-0C8h],', 'edx']
mov ['eax,', '[ebp-0C8h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[eax]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-0E0h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
mov ['ecx,', '[ebp-0C8h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx+10h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-0E0h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
mov ['edx,', '[ebp-0C8h]']
add ['edx,', '20h']
mov ['[ebp-0C8h],', 'edx']
mov ['eax,', '[ebp-0C4h]']
sub ['eax,', '1']
mov ['[ebp-0C4h],', 'eax']
jnz ['short', 'loc_8A0']
mov ['ecx,', '[ebp-0C8h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ecx]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-0E0h]']
aesenc ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
mov ['edx,', '[ebp-0C8h]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[edx+10h]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[ebp-0E0h]']
aesenclast ['xmm1,', 'xmm0']
movdqa ['xmmword', 'ptr', '[ebp-0E0h],', 'xmm1']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-0E0h]']
mov ['eax,', '[ebp-8]']
movdqa ['xmm1,', 'xmmword', 'ptr', '[eax]']
pxor ['xmm1,', 'xmm0']
mov ['ecx,', '[ebp-8]']
movdqa ['xmmword', 'ptr', '[ecx],', 'xmm1']
jmp ['loc_831']
mov ['edx,', '[ebp-4]']
movdqa ['xmm0,', 'xmmword', 'ptr', '[ebp-20h]']
movdqa ['xmmword', 'ptr', '[edx],', 'xmm0']
pop ['edi']
mov ['esp,', 'ebp']
pop ['ebp']
mov ['esp,', 'ebx']
pop ['ebx']
retn ['4']
endp
