_MyAlloc@4      proc near               
push ['ebp']
mov ['ebp,', 'esp']
push ['esi']
cmp ['[ebp+Size],', '0']
jnz ['short', 'loc_46']
xor ['eax,', 'eax']
jmp ['short', 'loc_5C']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Size]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__malloc']
add ['esp,', '4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
pop ['esi']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['4']
endp
_MyFree@4       proc near               
push ['ebp']
mov ['ebp,', 'esp']
push ['esi']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Memory]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__free']
add ['esp,', '4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
pop ['esi']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['4']
endp
_MidAlloc@4     proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['esi']
cmp ['[ebp+dwSize],', '0']
jnz ['short', 'loc_A6']
xor ['eax,', 'eax']
jmp ['short', 'loc_C2']
mov ['esi,', 'esp']
push ['4']
push ['1000h']
mov ['eax,', '[ebp+dwSize]']
push ['eax']
push ['0']
call ['dword', 'ptr', 'ds:__imp__VirtualAlloc@16']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
pop ['esi']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['4']
endp
_MidFree@4      proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['esi']
cmp ['[ebp+lpAddress],', '0']
jnz ['short', 'loc_E4']
jmp ['short', 'loc_FE']
mov ['esi,', 'esp']
push ['8000h']
push ['0']
mov ['eax,', '[ebp+lpAddress]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__VirtualFree@12']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
pop ['esi']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['4']
endp
_SetLargePageSize@0 proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
push ['esi']
push ['edi']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0']
mov ['esi,', 'esp']
push ['offset', '$SG80036']
mov ['edi,', 'esp']
push ['offset', '$SG80037']
call ['dword', 'ptr', 'ds:__imp__GetModuleHandleA@4']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__GetProcAddress@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_8],', 'eax']
cmp ['[ebp+var_8],', '0']
jnz ['short', 'loc_169']
jmp ['short', 'loc_194']
mov ['esi,', 'esp']
call ['[ebp+var_8]']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_4],', 'eax']
cmp ['[ebp+var_4],', '0']
jz ['short', 'loc_189']
mov ['eax,', '[ebp+var_4]']
sub ['eax,', '1']
and ['eax,', '[ebp+var_4]']
jz ['short', 'loc_18B']
jmp ['short', 'loc_194']
mov ['ecx,', '[ebp+var_4]']
mov ['ds:_g_LargePageSize,', 'ecx']
pop ['edi']
pop ['esi']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_BigAlloc@4     proc near               
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
push ['esi']
mov ['[ebp+var_4],', '0CCCCCCCCh']
cmp ['[ebp+dwSize],', '0']
jnz ['short', 'loc_1BE']
xor ['eax,', 'eax']
jmp ['short', 'loc_237']
cmp ['ds:_g_LargePageSize,', '0']
jz ['short', 'loc_21B']
cmp ['ds:_g_LargePageSize,', '40000000h']
ja ['short', 'loc_21B']
cmp ['[ebp+dwSize],', '40000h']
jb ['short', 'loc_21B']
mov ['esi,', 'esp']
push ['4']
push ['20001000h']
mov ['eax,', 'ds:_g_LargePageSize']
mov ['ecx,', '[ebp+dwSize]']
lea ['edx,', '[ecx+eax-1]']
mov ['eax,', 'ds:_g_LargePageSize']
sub ['eax,', '1']
not ['eax']
and ['edx,', 'eax']
push ['edx']
push ['0']
call ['dword', 'ptr', 'ds:__imp__VirtualAlloc@16']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_4],', 'eax']
cmp ['[ebp+var_4],', '0']
jz ['short', 'loc_21B']
mov ['eax,', '[ebp+var_4]']
jmp ['short', 'loc_237']
mov ['esi,', 'esp']
push ['4']
push ['1000h']
mov ['ecx,', '[ebp+dwSize]']
push ['ecx']
push ['0']
call ['dword', 'ptr', 'ds:__imp__VirtualAlloc@16']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
pop ['esi']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
_BigFree@4      proc near               
push ['ebp']
mov ['ebp,', 'esp']
push ['esi']
cmp ['[ebp+lpAddress],', '0']
jnz ['short', 'loc_254']
jmp ['short', 'loc_26E']
mov ['esi,', 'esp']
push ['8000h']
push ['0']
mov ['eax,', '[ebp+lpAddress]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__VirtualFree@12']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
pop ['esi']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['4']
endp
_SzAlloc@8      proc near               
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+Size]']
push ['eax']
call ['_MyAlloc@4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
_SzFree@8       proc near               
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+Memory]']
push ['eax']
call ['_MyFree@4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
_SzBigAlloc@8   proc near               
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+dwSize]']
push ['eax']
call ['_BigAlloc@4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
_SzBigFree@8    proc near               
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+lpAddress]']
push ['eax']
call ['_BigFree@4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
