?InitTable@CBZip2Crc@@SGXXZ proc near   
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '10h']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_C],', 'eax']
mov ['[ebp+var_8],', 'eax']
mov ['[ebp+var_4],', 'eax']
mov ['[ebp+var_4],', '0']
jmp ['short', 'loc_42D']
mov ['eax,', '[ebp+var_4]']
add ['eax,', '1']
mov ['[ebp+var_4],', 'eax']
cmp ['[ebp+var_4],', '100h']
jnb ['short', 'loc_490']
mov ['ecx,', '[ebp+var_4]']
shl ['ecx,', '18h']
mov ['[ebp+var_8],', 'ecx']
mov ['[ebp+var_C],', '8']
jmp ['short', 'loc_451']
mov ['edx,', '[ebp+var_C]']
sub ['edx,', '1']
mov ['[ebp+var_C],', 'edx']
cmp ['[ebp+var_C],', '0']
jle ['short', 'loc_481']
mov ['eax,', '[ebp+var_8]']
and ['eax,', '80000000h']
jz ['short', 'loc_471']
mov ['ecx,', '[ebp+var_8]']
shl ['ecx,', '1']
xor ['ecx,', '4C11DB7h']
mov ['[ebp+var_10],', 'ecx']
jmp ['short', 'loc_479']
mov ['edx,', '[ebp+var_8]']
shl ['edx,', '1']
mov ['[ebp+var_10],', 'edx']
mov ['eax,', '[ebp+var_10]']
mov ['[ebp+var_8],', 'eax']
jmp ['short', 'loc_448']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_8]']
mov ['ds:?Table@CBZip2Crc@@0PAIA[ecx*4],', 'edx']
jmp ['short', 'loc_424']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??__Eg_BZip2CrcTableInit@@YAXXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
mov ['ecx,', 'offset', '?g_BZip2CrcTableInit@@3VCBZip2CrcTableInit@@A']
call ['??0CBZip2CrcTableInit@@QAE@XZ']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
??0CBZip2CrcTableInit@@QAE@XZ proc near 
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
call ['?InitTable@CBZip2Crc@@SGXXZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
