?GetWindowsDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?GetWindowsDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '350h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_35C]']
mov ['ecx,', '0D4h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_10],', 'eax']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['loc_11F']
mov ['[ebp+Buffer],', '0']
mov ['esi,', 'esp']
push ['105h']
lea ['ecx,', '[ebp+Buffer]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__GetWindowsDirectoryA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
lea ['edx,', '[ebp+Buffer]']
push ['edx']
lea ['ecx,', '[ebp+var_344]']
call ['??0AString@@QAE@PBD@Z']
mov ['[ebp+var_4],', '0']
lea ['eax,', '[ebp+var_344]']
push ['eax']
lea ['ecx,', '[ebp+var_350]']
push ['ecx']
call ['?fas2fs@@YG?AVUString@@ABVAString@@@Z']
mov ['[ebp+var_354],', 'eax']
mov ['edx,', '[ebp+var_354]']
mov ['[ebp+var_358],', 'edx']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
mov ['eax,', '[ebp+var_358]']
push ['eax']
mov ['ecx,', '[ebp+this]']
call ['??4UString@@QAEAAV0@ABV0@@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_350]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_344]']
call ['??1AString@@QAE@XZ']
jmp ['short', 'loc_155']
xor ['ecx,', 'ecx']
mov ['[ebp+var_334],', 'cx']
mov ['esi,', 'esp']
push ['105h']
lea ['edx,', '[ebp+var_334]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__GetWindowsDirectoryW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
lea ['eax,', '[ebp+var_334]']
push ['eax']
mov ['ecx,', '[ebp+this]']
call ['??4UString@@QAEAAV0@PB_W@Z']
cmp ['[ebp+var_14],', '0']
jbe ['short', 'loc_170']
cmp ['[ebp+var_14],', '104h']
ja ['short', 'loc_170']
mov ['[ebp+var_35C],', '1']
jmp ['short', 'loc_17A']
mov ['[ebp+var_35C],', '0']
mov ['al,', 'byte', 'ptr', '[ebp+var_35C]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN13']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_10]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '35Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?GetSystemDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?GetSystemDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '350h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_35C]']
mov ['ecx,', '0D4h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_10],', 'eax']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['loc_2CF']
mov ['[ebp+Buffer],', '0']
mov ['esi,', 'esp']
push ['105h']
lea ['ecx,', '[ebp+Buffer]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__GetSystemDirectoryA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
lea ['edx,', '[ebp+Buffer]']
push ['edx']
lea ['ecx,', '[ebp+var_344]']
call ['??0AString@@QAE@PBD@Z']
mov ['[ebp+var_4],', '0']
lea ['eax,', '[ebp+var_344]']
push ['eax']
lea ['ecx,', '[ebp+var_350]']
push ['ecx']
call ['?fas2fs@@YG?AVUString@@ABVAString@@@Z']
mov ['[ebp+var_354],', 'eax']
mov ['edx,', '[ebp+var_354]']
mov ['[ebp+var_358],', 'edx']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
mov ['eax,', '[ebp+var_358]']
push ['eax']
mov ['ecx,', '[ebp+this]']
call ['??4UString@@QAEAAV0@ABV0@@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_350]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_344]']
call ['??1AString@@QAE@XZ']
jmp ['short', 'loc_305']
xor ['ecx,', 'ecx']
mov ['[ebp+var_334],', 'cx']
mov ['esi,', 'esp']
push ['105h']
lea ['edx,', '[ebp+var_334]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__GetSystemDirectoryW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
lea ['eax,', '[ebp+var_334]']
push ['eax']
mov ['ecx,', '[ebp+this]']
call ['??4UString@@QAEAAV0@PB_W@Z']
cmp ['[ebp+var_14],', '0']
jbe ['short', 'loc_320']
cmp ['[ebp+var_14],', '104h']
ja ['short', 'loc_320']
mov ['[ebp+var_35C],', '1']
jmp ['short', 'loc_32A']
mov ['[ebp+var_35C],', '0']
mov ['al,', 'byte', 'ptr', '[ebp+var_35C]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN13_0']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_10]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '35Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?SetDirTime@NDir@NFile@NWindows@@YG_NPB_WPBU_FILETIME@@11@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
push ['esi']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+hFile],', '0CCCCCCCCh']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_3CD']
mov ['esi,', 'esp']
push ['78h']
call ['dword', 'ptr', 'ds:__imp__SetLastError@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['al,', 'al']
jmp ['short', 'loc_444']
mov ['[ebp+hFile],', '0FFFFFFFFh']
mov ['esi,', 'esp']
push ['0']
push ['2000000h']
push ['3']
push ['0']
push ['3']
push ['40000000h']
mov ['ecx,', '[ebp+lpFileName]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__CreateFileW@28']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+hFile],', 'eax']
mov ['byte', 'ptr', '[ebp+var_8+3],', '0']
cmp ['[ebp+hFile],', '0FFFFFFFFh']
jz ['short', 'loc_441']
mov ['esi,', 'esp']
mov ['edx,', '[ebp+lpLastWriteTime]']
push ['edx']
mov ['eax,', '[ebp+lpLastAccessTime]']
push ['eax']
mov ['ecx,', '[ebp+lpCreationTime]']
push ['ecx']
mov ['edx,', '[ebp+hFile]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__SetFileTime@16']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
push ['eax']
call ['?BOOLToBool@@YG_NH@Z']
mov ['byte', 'ptr', '[ebp+var_8+3],', 'al']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+hFile]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__CloseHandle@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['al,', 'byte', 'ptr', '[ebp+var_8+3]']
pop ['esi']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['10h']
endp
?SetFileAttrib@NDir@NFile@NWindows@@YG_NPB_WK@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?SetFileAttrib@NDir@NFile@NWindows@@YG_NPB_WK@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '18h']
push ['esi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+var_1C],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_4F7']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+dwFileAttributes]']
push ['ecx']
mov ['edx,', '[ebp+lpFileName]']
push ['edx']
lea ['eax,', '[ebp+var_1C]']
push ['eax']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_20],', 'eax']
mov ['ecx,', '[ebp+var_20]']
mov ['[ebp+var_24],', 'ecx']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_24]']
call ['??BAString@@QBEPBDXZ']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__SetFileAttributesA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_1C]']
call ['??1AString@@QAE@XZ']
cmp ['[ebp+var_10],', '0']
jz ['short', 'loc_4F5']
mov ['al,', '1']
jmp ['short', 'loc_518']
jmp ['short', 'loc_516']
mov ['esi,', 'esp']
mov ['edx,', '[ebp+dwFileAttributes]']
push ['edx']
mov ['eax,', '[ebp+lpFileName]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__SetFileAttributesW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jz ['short', 'loc_516']
mov ['al,', '1']
jmp ['short', 'loc_518']
xor ['al,', 'al']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['esi']
add ['esp,', '24h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?RemoveDir@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?RemoveDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '18h']
push ['esi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+var_1C],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_5D3']
mov ['ecx,', '[ebp+lpPathName]']
push ['ecx']
lea ['edx,', '[ebp+var_1C]']
push ['edx']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_20],', 'eax']
mov ['eax,', '[ebp+var_20]']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_24]']
call ['??BAString@@QBEPBDXZ']
mov ['esi,', 'esp']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__RemoveDirectoryA@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_1C]']
call ['??1AString@@QAE@XZ']
cmp ['[ebp+var_10],', '0']
jz ['short', 'loc_5D1']
mov ['al,', '1']
jmp ['short', 'loc_5F0']
jmp ['short', 'loc_5EE']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+lpPathName]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__RemoveDirectoryW@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jz ['short', 'loc_5EE']
mov ['al,', '1']
jmp ['short', 'loc_5F0']
xor ['al,', 'al']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['esi']
add ['esp,', '24h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?MyMoveFile@NDir@NFile@NWindows@@YG_NPB_W0@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?MyMoveFile@NDir@NFile@NWindows@@YG_NPB_W0@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '2Ch']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_38]']
mov ['ecx,', '0Bh']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['loc_6DF']
mov ['ecx,', '[ebp+lpNewFileName]']
push ['ecx']
lea ['edx,', '[ebp+var_1C]']
push ['edx']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_2C],', 'eax']
mov ['eax,', '[ebp+var_2C]']
mov ['[ebp+var_30],', 'eax']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_30]']
call ['??BAString@@QBEPBDXZ']
mov ['esi,', 'esp']
push ['eax']
mov ['ecx,', '[ebp+lpExistingFileName]']
push ['ecx']
lea ['edx,', '[ebp+NewFileName]']
push ['edx']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_34],', 'eax']
mov ['eax,', '[ebp+var_34]']
mov ['[ebp+var_38],', 'eax']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
mov ['ecx,', '[ebp+var_38]']
call ['??BAString@@QBEPBDXZ']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__MoveFileA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_10],', 'eax']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+NewFileName]']
call ['??1AString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_1C]']
call ['??1AString@@QAE@XZ']
cmp ['[ebp+var_10],', '0']
jz ['short', 'loc_6DD']
mov ['al,', '1']
jmp ['short', 'loc_700']
jmp ['short', 'loc_6FE']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+lpNewFileName]']
push ['ecx']
mov ['edx,', '[ebp+lpExistingFileName]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__MoveFileW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jz ['short', 'loc_6FE']
mov ['al,', '1']
jmp ['short', 'loc_700']
xor ['al,', 'al']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
add ['esp,', '38h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?MyCreateHardLink@NDir@NFile@NWindows@@YG_NPB_W0@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
push ['esi']
push ['edi']
mov ['[ebp+var_4],', '0CCCCCCCCh']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_757']
mov ['esi,', 'esp']
push ['78h']
call ['dword', 'ptr', 'ds:__imp__SetLastError@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['al,', 'al']
jmp ['short', 'loc_7AD']
jmp ['short', 'loc_7AB']
mov ['esi,', 'esp']
push ['offset', '$SG68041']
mov ['edi,', 'esp']
push ['offset', '$SG68042']
call ['dword', 'ptr', 'ds:__imp__GetModuleHandleW@4']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__GetProcAddress@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_4],', 'eax']
cmp ['[ebp+var_4],', '0']
jnz ['short', 'loc_78D']
xor ['al,', 'al']
jmp ['short', 'loc_7AD']
mov ['esi,', 'esp']
push ['0']
mov ['ecx,', '[ebp+arg_4]']
push ['ecx']
mov ['edx,', '[ebp+this]']
push ['edx']
call ['[ebp+var_4]']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jz ['short', 'loc_7AB']
mov ['al,', '1']
jmp ['short', 'loc_7AD']
xor ['al,', 'al']
pop ['edi']
pop ['esi']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?CreateDir@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?CreateDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '18h']
push ['esi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+SecurityAttributes.nLength],', 'eax']
mov ['[ebp+SecurityAttributes.lpSecurityDescriptor],', 'eax']
mov ['[ebp+SecurityAttributes.bInheritHandle],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_865']
mov ['esi,', 'esp']
push ['0']
mov ['ecx,', '[ebp+lpPathName]']
push ['ecx']
lea ['edx,', '[ebp+SecurityAttributes]']
push ['edx']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_20],', 'eax']
mov ['eax,', '[ebp+var_20]']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_24]']
call ['??BAString@@QBEPBDXZ']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__CreateDirectoryA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+SecurityAttributes]']
call ['??1AString@@QAE@XZ']
cmp ['[ebp+var_10],', '0']
jz ['short', 'loc_863']
mov ['al,', '1']
jmp ['short', 'loc_884']
jmp ['short', 'loc_882']
mov ['esi,', 'esp']
push ['0']
mov ['ecx,', '[ebp+lpPathName]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__CreateDirectoryW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jz ['short', 'loc_882']
mov ['al,', '1']
jmp ['short', 'loc_884']
xor ['al,', 'al']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['esi']
add ['esp,', '24h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?CreateComplexDir@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?CreateComplexDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '40h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_4C]']
mov ['ecx,', '10h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['eax,', '[ebp+this]']
push ['eax']
call ['?GetFileAttrib@NFind@NFile@NWindows@@YGKPB_W@Z']
mov ['[ebp+var_10],', 'eax']
cmp ['[ebp+var_10],', '0FFFFFFFFh']
jz ['short', 'loc_8FF']
mov ['ecx,', '[ebp+var_10]']
and ['ecx,', '10h']
jz ['short', 'loc_8FF']
mov ['al,', '1']
jmp ['loc_B84']
mov ['edx,', '[ebp+this]']
push ['edx']
call ['?IsDriveRootPath_SuperAllowed@NName@NFile@NWindows@@YG_NPB_W@Z']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jz ['short', 'loc_916']
xor ['al,', 'al']
jmp ['loc_B84']
mov ['ecx,', '[ebp+this]']
push ['ecx']
call ['?GetRootPrefixSize@NName@NFile@NWindows@@YGIPB_W@Z']
mov ['[ebp+var_14],', 'eax']
mov ['edx,', '[ebp+this]']
push ['edx']
lea ['ecx,', '[ebp+var_24]']
call ['??0UString@@QAE@PB_W@Z']
mov ['[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_24]']
call ['?ReverseFind_PathSepar@UString@@QBEHXZ']
mov ['[ebp+var_2C],', 'eax']
cmp ['[ebp+var_2C],', '0']
jl ['short', 'loc_986']
lea ['ecx,', '[ebp+var_24]']
call ['?Len@UString@@QBEIXZ']
sub ['eax,', '1']
cmp ['[ebp+var_2C],', 'eax']
jnz ['short', 'loc_986']
lea ['ecx,', '[ebp+var_24]']
call ['?Len@UString@@QBEIXZ']
cmp ['eax,', '1']
jnz ['short', 'loc_97E']
mov ['[ebp+var_45],', '1']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_24]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_45]']
jmp ['loc_B84']
lea ['ecx,', '[ebp+var_24]']
call ['?DeleteBack@UString@@QAEXXZ']
lea ['eax,', '[ebp+var_24]']
push ['eax']
lea ['ecx,', '[ebp+var_3C]']
call ['??0UString@@QAE@ABV0@@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_24]']
call ['?Len@UString@@QBEIXZ']
mov ['[ebp+var_2C],', 'eax']
lea ['ecx,', '[ebp+var_24]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?CreateDir2@NDir@NFile@NWindows@@YG_NPB_W@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_9BB']
jmp ['loc_AC6']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
cmp ['eax,', '0B7h']
jnz ['short', 'loc_9F8']
mov ['[ebp+var_46],', '0']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_3C]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_24]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_46]']
jmp ['loc_B84']
lea ['ecx,', '[ebp+var_24]']
call ['?ReverseFind_PathSepar@UString@@QBEHXZ']
mov ['[ebp+var_2C],', 'eax']
cmp ['[ebp+var_2C],', '0']
jl ['short', 'loc_A0F']
cmp ['[ebp+var_2C],', '0']
jnz ['short', 'loc_A36']
mov ['[ebp+var_47],', '0']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_3C]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_24]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_47]']
jmp ['loc_B84']
cmp ['[ebp+var_2C],', '1']
jnz ['short', 'loc_A83']
lea ['ecx,', '[ebp+var_24]']
call ['??BUString@@QBEPB_WXZ']
movzx ['edx,', 'word', 'ptr', '[eax]']
cmp ['edx,', '5Ch']
jz ['short', 'loc_A5C']
lea ['ecx,', '[ebp+var_24]']
call ['??BUString@@QBEPB_WXZ']
movzx ['eax,', 'word', 'ptr', '[eax]']
cmp ['eax,', '2Fh']
jnz ['short', 'loc_A83']
mov ['[ebp+var_48],', '0']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_3C]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_24]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_48]']
jmp ['loc_B84']
mov ['ecx,', '[ebp+var_2C]']
add ['ecx,', '1']
cmp ['[ebp+var_14],', 'ecx']
jb ['short', 'loc_AB5']
mov ['[ebp+var_49],', '0']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_3C]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_24]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_49]']
jmp ['loc_B84']
mov ['edx,', '[ebp+var_2C]']
push ['edx']
lea ['ecx,', '[ebp+var_24]']
call ['?DeleteFrom@UString@@QAEXI@Z']
jmp ['loc_9A1']
lea ['ecx,', '[ebp+var_3C]']
call ['?Len@UString@@QBEIXZ']
cmp ['[ebp+var_2C],', 'eax']
jge ['loc_B62']
mov ['eax,', '[ebp+var_2C]']
add ['eax,', '1']
push ['eax']
lea ['ecx,', '[ebp+var_3C]']
call ['?Ptr@UString@@QBEPB_WI@Z']
push ['eax']
call ['?FindSepar@NName@NFile@NWindows@@YGHPB_W@Z']
mov ['[ebp+var_44],', 'eax']
cmp ['[ebp+var_44],', '0']
jge ['short', 'loc_B02']
lea ['ecx,', '[ebp+var_3C]']
call ['?Len@UString@@QBEIXZ']
mov ['[ebp+var_2C],', 'eax']
jmp ['short', 'loc_B0F']
mov ['ecx,', '[ebp+var_44]']
mov ['edx,', '[ebp+var_2C]']
lea ['eax,', '[edx+ecx+1]']
mov ['[ebp+var_2C],', 'eax']
mov ['ecx,', '[ebp+var_2C]']
push ['ecx']
lea ['ecx,', '[ebp+var_3C]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
lea ['ecx,', '[ebp+var_24]']
call ['?SetFrom@UString@@QAEXPB_WI@Z']
lea ['ecx,', '[ebp+var_24]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?CreateDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jnz ['short', 'loc_B5D']
mov ['[ebp+var_4A],', '0']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_3C]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_24]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_4A]']
jmp ['short', 'loc_B84']
jmp ['loc_AC6']
mov ['[ebp+var_4B],', '1']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_3C]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_24]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_4B]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN27']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
add ['esp,', '4Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?CreateDir2@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?CreateDir2@NDir@NFile@NWindows@@YG_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '5Ch']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_68]']
mov ['ecx,', '17h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_C81']
mov ['esi,', 'esp']
push ['0']
mov ['ecx,', '[ebp+lpPathName]']
push ['ecx']
lea ['edx,', '[ebp+SecurityAttributes]']
push ['edx']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_64],', 'eax']
mov ['eax,', '[ebp+var_64]']
mov ['[ebp+var_68],', 'eax']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_68]']
call ['??BAString@@QBEPBDXZ']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__CreateDirectoryA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_50],', 'eax']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+SecurityAttributes]']
call ['??1AString@@QAE@XZ']
cmp ['[ebp+var_50],', '0']
jz ['short', 'loc_C7F']
mov ['al,', '1']
jmp ['loc_D0F']
jmp ['short', 'loc_C9E']
mov ['esi,', 'esp']
push ['0']
mov ['ecx,', '[ebp+lpPathName]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__CreateDirectoryW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jz ['short', 'loc_C9E']
mov ['al,', '1']
jmp ['short', 'loc_D0F']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
cmp ['eax,', '0B7h']
jz ['short', 'loc_CB8']
xor ['al,', 'al']
jmp ['short', 'loc_D0F']
lea ['ecx,', '[ebp+var_48]']
call ['??0CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '1']
mov ['edx,', '[ebp+lpPathName]']
push ['edx']
lea ['ecx,', '[ebp+var_48]']
call ['?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_CF2']
mov ['[ebp+var_5D],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_48]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_5D]']
jmp ['short', 'loc_D0F']
lea ['ecx,', '[ebp+var_48]']
call ['?IsDir@CFileInfoBase@NFind@NFile@NWindows@@QBE_NXZ']
mov ['[ebp+var_5E],', 'al']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_48]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_5E]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN14']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
add ['esp,', '68h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?DeleteFileAlways@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?DeleteFileAlways@NDir@NFile@NWindows@@YG_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '1Ch']
push ['esi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_28],', 'eax']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+var_1C],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['eax,', '[ebp+lpFileName]']
push ['eax']
call ['?GetFileAttrib@NFind@NFile@NWindows@@YGKPB_W@Z']
mov ['[ebp+var_10],', 'eax']
cmp ['[ebp+var_10],', '0FFFFFFFFh']
jz ['short', 'loc_DD5']
mov ['ecx,', '[ebp+var_10]']
and ['ecx,', '10h']
jnz ['short', 'loc_DD5']
mov ['edx,', '[ebp+var_10]']
and ['edx,', '1']
jz ['short', 'loc_DD5']
mov ['eax,', '[ebp+var_10]']
and ['eax,', '0FFFFFFFEh']
push ['eax']
mov ['ecx,', '[ebp+lpFileName]']
push ['ecx']
call ['?SetFileAttrib@NDir@NFile@NWindows@@YG_NPB_WK@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jnz ['short', 'loc_DD5']
xor ['al,', 'al']
jmp ['short', 'loc_E50']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_E33']
mov ['ecx,', '[ebp+lpFileName]']
push ['ecx']
lea ['edx,', '[ebp+var_20]']
push ['edx']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_24],', 'eax']
mov ['eax,', '[ebp+var_24]']
mov ['[ebp+var_28],', 'eax']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_28]']
call ['??BAString@@QBEPBDXZ']
mov ['esi,', 'esp']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__DeleteFileA@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_20]']
call ['??1AString@@QAE@XZ']
cmp ['[ebp+var_14],', '0']
jz ['short', 'loc_E31']
mov ['al,', '1']
jmp ['short', 'loc_E50']
jmp ['short', 'loc_E4E']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+lpFileName]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__DeleteFileW@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jz ['short', 'loc_E4E']
mov ['al,', '1']
jmp ['short', 'loc_E50']
xor ['al,', 'al']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['esi']
add ['esp,', '28h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?RemoveDirWithSubItems@NDir@NFile@NWindows@@YG_NABVUString@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?RemoveDirWithSubItems@NDir@NFile@NWindows@@YG_NABVUString@@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '0B8h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_C4]']
mov ['ecx,', '2Eh']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_D],', '1']
lea ['ecx,', '[ebp+var_4C]']
call ['??0CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+this]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
lea ['ecx,', '[ebp+var_4C]']
call ['?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_F00']
mov ['[ebp+var_C1],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_4C]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_C1]']
jmp ['loc_10FC']
lea ['ecx,', '[ebp+var_4C]']
call ['?IsDir@CFileInfoBase@NFind@NFile@NWindows@@QBE_NXZ']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jnz ['short', 'loc_F44']
mov ['esi,', 'esp']
push ['10Bh']
call ['dword', 'ptr', 'ds:__imp__SetLastError@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_C2],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_4C]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_C2]']
jmp ['loc_10FC']
lea ['ecx,', '[ebp+var_4C]']
call ['?HasReparsePoint@CFileInfoBase@NFind@NFile@NWindows@@QBE_NXZ']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jz ['short', 'loc_F57']
mov ['[ebp+var_D],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_4C]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
movzx ['eax,', '[ebp+var_D]']
test ['eax,', 'eax']
jz ['loc_10D3']
mov ['ecx,', '[ebp+this]']
push ['ecx']
lea ['ecx,', '[ebp+var_60]']
call ['??0UString@@QAE@ABV0@@Z']
mov ['[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_60]']
call ['?Add_PathSepar@UString@@QAEXXZ']
lea ['ecx,', '[ebp+var_60]']
call ['?Len@UString@@QBEIXZ']
mov ['[ebp+var_68],', 'eax']
push ['2Ah']
lea ['ecx,', '[ebp+var_60]']
call ['??YUString@@QAEAAV0@_W@Z']
lea ['edx,', '[ebp+var_60]']
push ['edx']
lea ['ecx,', '[ebp+var_7C]']
call ['??0CEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '2']
lea ['ecx,', '[ebp+var_BC]']
call ['??0CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '3']
lea ['eax,', '[ebp+var_BC]']
push ['eax']
lea ['ecx,', '[ebp+var_7C]']
call ['?Next@CEnumerator@NFind@NFile@NWindows@@QAE_NAAUCFileInfo@234@@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['loc_10A9']
mov ['edx,', '[ebp+var_68]']
push ['edx']
lea ['ecx,', '[ebp+var_60]']
call ['?DeleteFrom@UString@@QAEXI@Z']
lea ['eax,', '[ebp+var_94]']
push ['eax']
lea ['ecx,', '[ebp+var_60]']
call ['??YUString@@QAEAAV0@ABV0@@Z']
lea ['ecx,', '[ebp+var_BC]']
call ['?IsDir@CFileInfoBase@NFind@NFile@NWindows@@QBE_NXZ']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_1056']
lea ['edx,', '[ebp+var_60]']
push ['edx']
call ['?RemoveDirWithSubItems@NDir@NFile@NWindows@@YG_NABVUString@@@Z']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_1054']
mov ['[ebp+var_C3],', '0']
mov ['byte', 'ptr', '[ebp+var_4],', '2']
lea ['ecx,', '[ebp+var_BC]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_7C]']
call ['??1CEnumerator@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_60]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_C3]']
jmp ['loc_10FC']
jmp ['short', 'loc_10A4']
lea ['ecx,', '[ebp+var_60]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?DeleteFileAlways@NDir@NFile@NWindows@@YG_NPB_W@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jnz ['short', 'loc_10A4']
mov ['[ebp+var_C4],', '0']
mov ['byte', 'ptr', '[ebp+var_4],', '2']
lea ['ecx,', '[ebp+var_BC]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_7C]']
call ['??1CEnumerator@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_60]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_C4]']
jmp ['short', 'loc_10FC']
jmp ['loc_FC1']
mov ['byte', 'ptr', '[ebp+var_4],', '2']
lea ['ecx,', '[ebp+var_BC]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_7C]']
call ['??1CEnumerator@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_60]']
call ['??1UString@@QAE@XZ']
push ['0']
mov ['ecx,', '[ebp+this]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?SetFileAttrib@NDir@NFile@NWindows@@YG_NPB_WK@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jnz ['short', 'loc_10EE']
xor ['al,', 'al']
jmp ['short', 'loc_10FC']
mov ['ecx,', '[ebp+this]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?RemoveDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN24_0']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
add ['esp,', '0C4h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?MyGetFullPathName@NDir@NFile@NWindows@@YG_NPB_WAAVUString@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+arg_4]']
push ['eax']
mov ['ecx,', '[ebp+this]']
push ['ecx']
call ['?GetFullPath@NName@NFile@NWindows@@YG_NPB_WAAVUString@@@Z']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
?SetCurrentDir@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?SetCurrentDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '18h']
push ['esi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+var_1C],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_1244']
mov ['ecx,', '[ebp+lpPathName]']
push ['ecx']
lea ['edx,', '[ebp+var_1C]']
push ['edx']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_20],', 'eax']
mov ['eax,', '[ebp+var_20]']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_24]']
call ['??BAString@@QBEPBDXZ']
mov ['esi,', 'esp']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__SetCurrentDirectoryA@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
push ['eax']
call ['?BOOLToBool@@YG_NH@Z']
mov ['byte', 'ptr', '[ebp+var_10+3],', 'al']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_1C]']
call ['??1AString@@QAE@XZ']
mov ['al,', 'byte', 'ptr', '[ebp+var_10+3]']
jmp ['short', 'loc_125D']
jmp ['short', 'loc_125D']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+lpPathName]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__SetCurrentDirectoryW@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
push ['eax']
call ['?BOOLToBool@@YG_NH@Z']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['esi']
add ['esp,', '24h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?GetCurrentDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?GetCurrentDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '350h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_35C]']
mov ['ecx,', '0D4h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_10],', 'eax']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['ecx,', '[ebp+this]']
call ['?Empty@UString@@QAEXXZ']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['loc_1377']
mov ['[ebp+Buffer],', '0']
mov ['esi,', 'esp']
lea ['ecx,', '[ebp+Buffer]']
push ['ecx']
push ['105h']
call ['dword', 'ptr', 'ds:__imp__GetCurrentDirectoryA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
lea ['edx,', '[ebp+Buffer]']
push ['edx']
lea ['ecx,', '[ebp+var_344]']
call ['??0AString@@QAE@PBD@Z']
mov ['[ebp+var_4],', '0']
lea ['eax,', '[ebp+var_344]']
push ['eax']
lea ['ecx,', '[ebp+var_350]']
push ['ecx']
call ['?fas2fs@@YG?AVUString@@ABVAString@@@Z']
mov ['[ebp+var_354],', 'eax']
mov ['edx,', '[ebp+var_354]']
mov ['[ebp+var_358],', 'edx']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
mov ['eax,', '[ebp+var_358]']
push ['eax']
mov ['ecx,', '[ebp+this]']
call ['??4UString@@QAEAAV0@ABV0@@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_350]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_344]']
call ['??1AString@@QAE@XZ']
jmp ['short', 'loc_13AD']
xor ['ecx,', 'ecx']
mov ['[ebp+var_334],', 'cx']
mov ['esi,', 'esp']
lea ['edx,', '[ebp+var_334]']
push ['edx']
push ['105h']
call ['dword', 'ptr', 'ds:__imp__GetCurrentDirectoryW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
lea ['eax,', '[ebp+var_334]']
push ['eax']
mov ['ecx,', '[ebp+this]']
call ['??4UString@@QAEAAV0@PB_W@Z']
cmp ['[ebp+var_14],', '0']
jbe ['short', 'loc_13C8']
cmp ['[ebp+var_14],', '104h']
ja ['short', 'loc_13C8']
mov ['[ebp+var_35C],', '1']
jmp ['short', 'loc_13D2']
mov ['[ebp+var_35C],', '0']
mov ['al,', 'byte', 'ptr', '[ebp+var_35C]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN13_2']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_10]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '35Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?GetFullPathAndSplit@NDir@NFile@NWindows@@YG_NPB_WAAVUString@@1@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['eax,', '[ebp+arg_4]']
push ['eax']
mov ['ecx,', '[ebp+this]']
push ['ecx']
call ['?MyGetFullPathName@NDir@NFile@NWindows@@YG_NPB_WAAVUString@@@Z']
mov ['byte', 'ptr', '[ebp+var_4+3],', 'al']
movzx ['edx,', 'byte', 'ptr', '[ebp+var_4+3]']
test ['edx,', 'edx']
jnz ['short', 'loc_1470']
mov ['eax,', '[ebp+this]']
push ['eax']
mov ['ecx,', '[ebp+arg_4]']
call ['??4UString@@QAEAAV0@PB_W@Z']
mov ['ecx,', '[ebp+arg_4]']
call ['?ReverseFind_PathSepar@UString@@QBEHXZ']
mov ['[ebp+var_8],', 'eax']
mov ['ecx,', '[ebp+var_8]']
add ['ecx,', '1']
push ['ecx']
mov ['ecx,', '[ebp+arg_4]']
call ['?Ptr@UString@@QBEPB_WI@Z']
push ['eax']
mov ['ecx,', '[ebp+arg_8]']
call ['??4UString@@QAEAAV0@PB_W@Z']
mov ['edx,', '[ebp+var_8]']
add ['edx,', '1']
push ['edx']
mov ['ecx,', '[ebp+arg_4]']
call ['?DeleteFrom@UString@@QAEXI@Z']
mov ['al,', 'byte', 'ptr', '[ebp+var_4+3]']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['0Ch']
endp
?GetOnlyDirPrefix@NDir@NFile@NWindows@@YG_NPB_WAAVUString@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?GetOnlyDirPrefix@NDir@NFile@NWindows@@YG_NPB_WAAVUString@@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '18h']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+var_1C],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
lea ['ecx,', '[ebp+var_1C]']
call ['??0UString@@QAE@XZ']
mov ['[ebp+var_4],', '0']
lea ['eax,', '[ebp+var_1C]']
push ['eax']
mov ['ecx,', '[ebp+arg_4]']
push ['ecx']
mov ['edx,', '[ebp+this]']
push ['edx']
call ['?GetFullPathAndSplit@NDir@NFile@NWindows@@YG_NPB_WAAVUString@@1@Z']
mov ['byte', 'ptr', '[ebp+var_24+3],', 'al']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_1C]']
call ['??1UString@@QAE@XZ']
mov ['al,', 'byte', 'ptr', '[ebp+var_24+3]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN7']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
add ['esp,', '24h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?MyGetTempPath@NDir@NFile@NWindows@@YG_NAAVUString@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?MyGetTempPath@NDir@NFile@NWindows@@YG_NAAVUString@@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '350h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_35C]']
mov ['ecx,', '0D4h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_10],', 'eax']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['ecx,', '[ebp+this]']
call ['?Empty@UString@@QAEXXZ']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['loc_1667']
mov ['[ebp+Buffer],', '0']
mov ['esi,', 'esp']
lea ['ecx,', '[ebp+Buffer]']
push ['ecx']
push ['105h']
call ['dword', 'ptr', 'ds:__imp__GetTempPathA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
lea ['edx,', '[ebp+Buffer]']
push ['edx']
lea ['ecx,', '[ebp+var_344]']
call ['??0AString@@QAE@PBD@Z']
mov ['[ebp+var_4],', '0']
lea ['eax,', '[ebp+var_344]']
push ['eax']
lea ['ecx,', '[ebp+var_350]']
push ['ecx']
call ['?fas2fs@@YG?AVUString@@ABVAString@@@Z']
mov ['[ebp+var_354],', 'eax']
mov ['edx,', '[ebp+var_354]']
mov ['[ebp+var_358],', 'edx']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
mov ['eax,', '[ebp+var_358]']
push ['eax']
mov ['ecx,', '[ebp+this]']
call ['??4UString@@QAEAAV0@ABV0@@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_350]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_344]']
call ['??1AString@@QAE@XZ']
jmp ['short', 'loc_169D']
xor ['ecx,', 'ecx']
mov ['[ebp+var_334],', 'cx']
mov ['esi,', 'esp']
lea ['edx,', '[ebp+var_334]']
push ['edx']
push ['105h']
call ['dword', 'ptr', 'ds:__imp__GetTempPathW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
lea ['eax,', '[ebp+var_334]']
push ['eax']
mov ['ecx,', '[ebp+this]']
call ['??4UString@@QAEAAV0@PB_W@Z']
cmp ['[ebp+var_14],', '0']
jbe ['short', 'loc_16B8']
cmp ['[ebp+var_14],', '104h']
ja ['short', 'loc_16B8']
mov ['[ebp+var_35C],', '1']
jmp ['short', 'loc_16C2']
mov ['[ebp+var_35C],', '0']
mov ['al,', 'byte', 'ptr', '[ebp+var_35C]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN13_3']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_10]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '35Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Create@CTempFile@NDir@NFile@NWindows@@QAE_NPB_WPAVCOutFile@NIO@34@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?Remove@CTempFile@NDir@NFile@NWindows@@QAE_NXZ']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_1749']
xor ['al,', 'al']
jmp ['short', 'loc_1772']
mov ['ecx,', '[ebp+arg_4]']
push ['ecx']
mov ['edx,', '[ebp+var_4]']
add ['edx,', '4']
push ['edx']
push ['0']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['?CreateTempFile@NDir@NFile@NWindows@@YG_NPB_W_NAAVUString@@PAVCOutFile@NIO@23@@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jnz ['short', 'loc_176A']
xor ['al,', 'al']
jmp ['short', 'loc_1772']
mov ['edx,', '[ebp+var_4]']
mov ['byte', 'ptr', '[edx],', '1']
mov ['al,', '1']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?CreateTempFile@NDir@NFile@NWindows@@YG_NPB_W_NAAVUString@@PAVCOutFile@NIO@23@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '4Ch']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_4C]']
mov ['ecx,', '13h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_4],', 'eax']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetTickCount@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'eax']
shl ['esi,', '0Ch']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetCurrentThreadId@0']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
shl ['eax,', '0Eh']
xor ['esi,', 'eax']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetCurrentProcessId@0']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
xor ['esi,', 'eax']
mov ['[ebp+var_8],', 'esi']
mov ['[ebp+var_C],', '0']
jmp ['short', 'loc_17F7']
mov ['eax,', '[ebp+var_C]']
add ['eax,', '1']
mov ['[ebp+var_C],', 'eax']
cmp ['[ebp+var_C],', '64h']
jnb ['loc_196A']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
mov ['ecx,', '[ebp+arg_8]']
call ['??4UString@@QAEAAV0@PB_W@Z']
movzx ['edx,', '[ebp+arg_4]']
test ['edx,', 'edx']
jz ['loc_18BE']
mov ['eax,', '[ebp+var_8]']
mov ['[ebp+var_38],', 'eax']
mov ['[ebp+var_3C],', '0']
jmp ['short', 'loc_1831']
mov ['ecx,', '[ebp+var_3C]']
add ['ecx,', '1']
mov ['[ebp+var_3C],', 'ecx']
cmp ['[ebp+var_3C],', '8']
jnb ['short', 'loc_1871']
mov ['edx,', '[ebp+var_38]']
and ['edx,', '0Fh']
mov ['[ebp+var_40],', 'edx']
mov ['eax,', '[ebp+var_38]']
shr ['eax,', '4']
mov ['[ebp+var_38],', 'eax']
cmp ['[ebp+var_40],', '0Ah']
jnb ['short', 'loc_185A']
mov ['ecx,', '[ebp+var_40]']
add ['ecx,', '30h']
mov ['[ebp+var_4C],', 'ecx']
jmp ['short', 'loc_1863']
mov ['edx,', '[ebp+var_40]']
add ['edx,', '37h']
mov ['[ebp+var_4C],', 'edx']
mov ['eax,', '[ebp+var_3C]']
mov ['cx,', 'word', 'ptr', '[ebp+var_4C]']
mov ['[ebp+eax*2+var_30],', 'cx']
jmp ['short', 'loc_1828']
xor ['edx,', 'edx']
mov ['eax,', '[ebp+var_3C]']
mov ['[ebp+eax*2+var_30],', 'dx']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_188B']
push ['2Eh']
mov ['ecx,', '[ebp+arg_8]']
call ['??YUString@@QAEAAV0@_W@Z']
lea ['ecx,', '[ebp+var_30]']
push ['ecx']
mov ['ecx,', '[ebp+arg_8]']
call ['??YUString@@QAEAAV0@PB_W@Z']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetTickCount@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '2']
mov ['[ebp+var_44],', 'eax']
jnz ['short', 'loc_18B5']
mov ['[ebp+var_44],', '1']
mov ['edx,', '[ebp+var_8]']
add ['edx,', '[ebp+var_44]']
mov ['[ebp+var_8],', 'edx']
mov ['[ebp+arg_4],', '1']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_18D5']
push ['offset', '$SG68221']
mov ['ecx,', '[ebp+arg_8]']
call ['??YUString@@QAEAAV0@PB_W@Z']
mov ['ecx,', '[ebp+arg_8]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?DoesFileOrDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jz ['short', 'loc_1903']
mov ['esi,', 'esp']
push ['0B7h']
call ['dword', 'ptr', 'ds:__imp__SetLastError@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['loc_17EE']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_1929']
push ['0']
mov ['ecx,', '[ebp+arg_8]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
mov ['ecx,', '[ebp+arg_C]']
call ['?Create@COutFile@NIO@NFile@NWindows@@QAE_NPB_W_N@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_1927']
mov ['al,', '1']
jmp ['short', 'loc_1974']
jmp ['short', 'loc_1942']
mov ['ecx,', '[ebp+arg_8]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?CreateDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jz ['short', 'loc_1942']
mov ['al,', '1']
jmp ['short', 'loc_1974']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_48],', 'eax']
cmp ['[ebp+var_48],', '50h']
jz ['short', 'loc_1965']
cmp ['[ebp+var_48],', '0B7h']
jz ['short', 'loc_1965']
jmp ['short', 'loc_196A']
jmp ['loc_17EE']
mov ['ecx,', '[ebp+arg_8]']
call ['?Empty@UString@@QAEXXZ']
xor ['al,', 'al']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN23_1']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_4]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '4Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['10h']
endp
?CreateRandomInTempFolder@CTempFile@NDir@NFile@NWindows@@QAE_NPB_WPAVCOutFile@NIO@34@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?CreateRandomInTempFolder@CTempFile@NDir@NFile@NWindows@@QAE_NPB_WPAVCOutFile@NIO@34@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '34h']
push ['edi']
push ['ecx']
lea ['edi,', '[ebp+var_40]']
mov ['ecx,', '0Dh']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
pop ['ecx']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_10],', 'ecx']
mov ['ecx,', '[ebp+var_10]']
call ['?Remove@CTempFile@NDir@NFile@NWindows@@QAE_NXZ']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_1A18']
xor ['al,', 'al']
jmp ['loc_1AE0']
lea ['ecx,', '[ebp+var_20]']
call ['??0UString@@QAE@XZ']
mov ['[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_20]']
push ['ecx']
call ['?MyGetTempPath@NDir@NFile@NWindows@@YG_NAAVUString@@@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jnz ['short', 'loc_1A52']
mov ['[ebp+var_25],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_20]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_25]']
jmp ['loc_1AE0']
mov ['eax,', '[ebp+arg_4]']
push ['eax']
mov ['ecx,', '[ebp+var_10]']
add ['ecx,', '4']
push ['ecx']
push ['1']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
lea ['eax,', '[ebp+var_20]']
push ['eax']
lea ['ecx,', '[ebp+var_34]']
push ['ecx']
call ['??H@YG?AVUString@@ABV0@PB_W@Z']
mov ['[ebp+var_3C],', 'eax']
mov ['edx,', '[ebp+var_3C]']
mov ['[ebp+var_40],', 'edx']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
mov ['ecx,', '[ebp+var_40]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?CreateTempFile@NDir@NFile@NWindows@@YG_NPB_W_NAAVUString@@PAVCOutFile@NIO@23@@Z']
movzx ['eax,', 'al']
neg ['eax']
sbb ['eax,', 'eax']
add ['eax,', '1']
mov ['[ebp+var_26],', 'al']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_34]']
call ['??1UString@@QAE@XZ']
movzx ['ecx,', '[ebp+var_26]']
test ['ecx,', 'ecx']
jz ['short', 'loc_1AC4']
mov ['[ebp+var_35],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_20]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_35]']
jmp ['short', 'loc_1AE0']
mov ['edx,', '[ebp+var_10]']
mov ['byte', 'ptr', '[edx],', '1']
mov ['[ebp+var_36],', '1']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_20]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_36]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN11_0']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
add ['esp,', '40h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?Remove@CTempFile@NDir@NFile@NWindows@@QAE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
movzx ['ecx,', 'byte', 'ptr', '[eax]']
test ['ecx,', 'ecx']
jnz ['short', 'loc_1B54']
mov ['al,', '1']
jmp ['short', 'loc_1B81']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '4']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?DeleteFileAlways@NDir@NFile@NWindows@@YG_NPB_W@Z']
movzx ['edx,', 'al']
neg ['edx']
sbb ['edx,', 'edx']
add ['edx,', '1']
mov ['eax,', '[ebp+var_4]']
mov ['[eax],', 'dl']
mov ['ecx,', '[ebp+var_4]']
movzx ['eax,', 'byte', 'ptr', '[ecx]']
neg ['eax']
sbb ['eax,', 'eax']
add ['eax,', '1']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?MoveTo@CTempFile@NDir@NFile@NWindows@@QAE_NPB_W_N@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
movzx ['eax,', '[ebp+arg_4]']
test ['eax,', 'eax']
jz ['short', 'loc_1BD2']
mov ['ecx,', '[ebp+lpNewFileName]']
push ['ecx']
call ['?DoesFileExist@NFind@NFile@NWindows@@YG_NPB_W@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jz ['short', 'loc_1BD2']
mov ['eax,', '[ebp+lpNewFileName]']
push ['eax']
call ['?DeleteFileAlways@NDir@NFile@NWindows@@YG_NPB_W@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jnz ['short', 'loc_1BD2']
xor ['al,', 'al']
jmp ['short', 'loc_1BEF']
mov ['ecx,', '[ebp+var_4]']
call ['?DisableDeleting@CTempFile@NDir@NFile@NWindows@@AAEXXZ']
mov ['edx,', '[ebp+lpNewFileName]']
push ['edx']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '4']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?MyMoveFile@NDir@NFile@NWindows@@YG_NPB_W0@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?Create@CTempDir@NDir@NFile@NWindows@@QAE_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?Create@CTempDir@NDir@NFile@NWindows@@QAE_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '34h']
push ['edi']
push ['ecx']
lea ['edi,', '[ebp+var_40]']
mov ['ecx,', '0Dh']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
pop ['ecx']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_10],', 'ecx']
mov ['ecx,', '[ebp+var_10]']
call ['?Remove@CTempDir@NDir@NFile@NWindows@@QAE_NXZ']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_1C58']
xor ['al,', 'al']
jmp ['loc_1D1E']
lea ['ecx,', '[ebp+var_20]']
call ['??0UString@@QAE@XZ']
mov ['[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_20]']
push ['ecx']
call ['?MyGetTempPath@NDir@NFile@NWindows@@YG_NAAVUString@@@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jnz ['short', 'loc_1C92']
mov ['[ebp+var_25],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_20]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_25]']
jmp ['loc_1D1E']
push ['0']
mov ['eax,', '[ebp+var_10]']
add ['eax,', '4']
push ['eax']
push ['1']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
lea ['edx,', '[ebp+var_20]']
push ['edx']
lea ['eax,', '[ebp+var_34]']
push ['eax']
call ['??H@YG?AVUString@@ABV0@PB_W@Z']
mov ['[ebp+var_3C],', 'eax']
mov ['ecx,', '[ebp+var_3C]']
mov ['[ebp+var_40],', 'ecx']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
mov ['ecx,', '[ebp+var_40]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?CreateTempFile@NDir@NFile@NWindows@@YG_NPB_W_NAAVUString@@PAVCOutFile@NIO@23@@Z']
movzx ['edx,', 'al']
neg ['edx']
sbb ['edx,', 'edx']
add ['edx,', '1']
mov ['[ebp+var_26],', 'dl']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_34]']
call ['??1UString@@QAE@XZ']
movzx ['eax,', '[ebp+var_26]']
test ['eax,', 'eax']
jz ['short', 'loc_1D02']
mov ['[ebp+var_35],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_20]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_35]']
jmp ['short', 'loc_1D1E']
mov ['ecx,', '[ebp+var_10]']
mov ['byte', 'ptr', '[ecx],', '1']
mov ['[ebp+var_36],', '1']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_20]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_36]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN11_1']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
add ['esp,', '40h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Remove@CTempDir@NDir@NFile@NWindows@@QAE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
movzx ['ecx,', 'byte', 'ptr', '[eax]']
test ['ecx,', 'ecx']
jnz ['short', 'loc_1D94']
mov ['al,', '1']
jmp ['short', 'loc_1DBC']
mov ['edx,', '[ebp+var_4]']
add ['edx,', '4']
push ['edx']
call ['?RemoveDirWithSubItems@NDir@NFile@NWindows@@YG_NABVUString@@@Z']
movzx ['eax,', 'al']
neg ['eax']
sbb ['eax,', 'eax']
add ['eax,', '1']
mov ['ecx,', '[ebp+var_4]']
mov ['[ecx],', 'al']
mov ['edx,', '[ebp+var_4]']
movzx ['eax,', 'byte', 'ptr', '[edx]']
neg ['eax']
sbb ['eax,', 'eax']
add ['eax,', '1']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
__unwindfunclet$?GetWindowsDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z$0 proc near
lea ['ecx,', '[ebp-344h]']
jmp ['??1AString@@QAE@XZ']
endp
__unwindfunclet$?GetWindowsDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z$1 proc near
lea ['ecx,', '[ebp-350h]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?GetWindowsDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-35Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['ecx,', '[edx-4]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?GetWindowsDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?GetSystemDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z$0 proc near
lea ['ecx,', '[ebp-344h]']
jmp ['??1AString@@QAE@XZ']
endp
__unwindfunclet$?GetSystemDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z$1 proc near
lea ['ecx,', '[ebp-350h]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?GetSystemDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-35Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['ecx,', '[edx-4]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?GetSystemDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?SetFileAttrib@NDir@NFile@NWindows@@YG_NPB_WK@Z$0 proc near
lea ['ecx,', '[ebp-1Ch]']
jmp ['??1AString@@QAE@XZ']
endp
__ehhandler$?SetFileAttrib@NDir@NFile@NWindows@@YG_NPB_WK@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-20h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?SetFileAttrib@NDir@NFile@NWindows@@YG_NPB_WK@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?RemoveDir@NDir@NFile@NWindows@@YG_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-1Ch]']
jmp ['??1AString@@QAE@XZ']
endp
__ehhandler$?RemoveDir@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-20h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?RemoveDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?MyMoveFile@NDir@NFile@NWindows@@YG_NPB_W0@Z$0 proc near
lea ['ecx,', '[ebp-1Ch]']
jmp ['??1AString@@QAE@XZ']
endp
__unwindfunclet$?MyMoveFile@NDir@NFile@NWindows@@YG_NPB_W0@Z$1 proc near
lea ['ecx,', '[ebp-28h]']
jmp ['??1AString@@QAE@XZ']
endp
__ehhandler$?MyMoveFile@NDir@NFile@NWindows@@YG_NPB_W0@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-38h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?MyMoveFile@NDir@NFile@NWindows@@YG_NPB_W0@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?CreateDir@NDir@NFile@NWindows@@YG_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-1Ch]']
jmp ['??1AString@@QAE@XZ']
endp
__ehhandler$?CreateDir@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-20h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?CreateDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?CreateComplexDir@NDir@NFile@NWindows@@YG_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-24h]']
jmp ['??1UString@@QAE@XZ']
endp
__unwindfunclet$?CreateComplexDir@NDir@NFile@NWindows@@YG_NPB_W@Z$1 proc near
lea ['ecx,', '[ebp-3Ch]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?CreateComplexDir@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-4Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?CreateComplexDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?CreateDir2@NDir@NFile@NWindows@@YG_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-5Ch]']
jmp ['??1AString@@QAE@XZ']
endp
__unwindfunclet$?CreateDir2@NDir@NFile@NWindows@@YG_NPB_W@Z$1 proc near
lea ['ecx,', '[ebp-48h]']
jmp ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
endp
__ehhandler$?CreateDir2@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-68h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?CreateDir2@NDir@NFile@NWindows@@YG_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?DeleteFileAlways@NDir@NFile@NWindows@@YG_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-20h]']
jmp ['??1AString@@QAE@XZ']
endp
__ehhandler$?DeleteFileAlways@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-24h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?DeleteFileAlways@NDir@NFile@NWindows@@YG_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?RemoveDirWithSubItems@NDir@NFile@NWindows@@YG_NABVUString@@@Z$0 proc near
lea ['ecx,', '[ebp-4Ch]']
jmp ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
endp
__unwindfunclet$?RemoveDirWithSubItems@NDir@NFile@NWindows@@YG_NABVUString@@@Z$1 proc near
lea ['ecx,', '[ebp-60h]']
jmp ['??1UString@@QAE@XZ']
endp
__unwindfunclet$?RemoveDirWithSubItems@NDir@NFile@NWindows@@YG_NABVUString@@@Z$2 proc near
lea ['ecx,', '[ebp-7Ch]']
jmp ['??1CEnumerator@NFind@NFile@NWindows@@QAE@XZ']
endp
__unwindfunclet$?RemoveDirWithSubItems@NDir@NFile@NWindows@@YG_NABVUString@@@Z$3 proc near
lea ['ecx,', '[ebp-0BCh]']
jmp ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
endp
__ehhandler$?RemoveDirWithSubItems@NDir@NFile@NWindows@@YG_NABVUString@@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-0C4h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?RemoveDirWithSubItems@NDir@NFile@NWindows@@YG_NABVUString@@@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?SetCurrentDir@NDir@NFile@NWindows@@YG_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-1Ch]']
jmp ['??1AString@@QAE@XZ']
endp
__ehhandler$?SetCurrentDir@NDir@NFile@NWindows@@YG_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-20h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?SetCurrentDir@NDir@NFile@NWindows@@YG_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?GetCurrentDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z$0 proc near
lea ['ecx,', '[ebp-344h]']
jmp ['??1AString@@QAE@XZ']
endp
__unwindfunclet$?GetCurrentDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z$1 proc near
lea ['ecx,', '[ebp-350h]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?GetCurrentDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-35Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['ecx,', '[edx-4]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?GetCurrentDir@NDir@NFile@NWindows@@YG_NAAVUString@@@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?GetOnlyDirPrefix@NDir@NFile@NWindows@@YG_NPB_WAAVUString@@@Z$0 proc near
lea ['ecx,', '[ebp-1Ch]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?GetOnlyDirPrefix@NDir@NFile@NWindows@@YG_NPB_WAAVUString@@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-1Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?GetOnlyDirPrefix@NDir@NFile@NWindows@@YG_NPB_WAAVUString@@@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?MyGetTempPath@NDir@NFile@NWindows@@YG_NAAVUString@@@Z$0 proc near
lea ['ecx,', '[ebp-344h]']
jmp ['??1AString@@QAE@XZ']
endp
__unwindfunclet$?MyGetTempPath@NDir@NFile@NWindows@@YG_NAAVUString@@@Z$1 proc near
lea ['ecx,', '[ebp-350h]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?MyGetTempPath@NDir@NFile@NWindows@@YG_NAAVUString@@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-35Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['ecx,', '[edx-4]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?MyGetTempPath@NDir@NFile@NWindows@@YG_NAAVUString@@@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?CreateRandomInTempFolder@CTempFile@NDir@NFile@NWindows@@QAE_NPB_WPAVCOutFile@NIO@34@@Z$0 proc near
lea ['ecx,', '[ebp-20h]']
jmp ['??1UString@@QAE@XZ']
endp
__unwindfunclet$?CreateRandomInTempFolder@CTempFile@NDir@NFile@NWindows@@QAE_NPB_WPAVCOutFile@NIO@34@@Z$1 proc near
lea ['ecx,', '[ebp-34h]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?CreateRandomInTempFolder@CTempFile@NDir@NFile@NWindows@@QAE_NPB_WPAVCOutFile@NIO@34@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-3Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?CreateRandomInTempFolder@CTempFile@NDir@NFile@NWindows@@QAE_NPB_WPAVCOutFile@NIO@34@@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?Create@CTempDir@NDir@NFile@NWindows@@QAE_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-20h]']
jmp ['??1UString@@QAE@XZ']
endp
__unwindfunclet$?Create@CTempDir@NDir@NFile@NWindows@@QAE_NPB_W@Z$1 proc near
lea ['ecx,', '[ebp-34h]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?Create@CTempDir@NDir@NFile@NWindows@@QAE_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-3Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?Create@CTempDir@NDir@NFile@NWindows@@QAE_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
??1AString@@QAE@XZ proc near            
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_8]']
push ['edx']
call ['??3@YAXPAX@Z']
add ['esp,', '4']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1UString@@QAE@XZ proc near            
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_8]']
push ['edx']
call ['??3@YAXPAX@Z']
add ['esp,', '4']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?BOOLToBool@@YG_NH@Z proc near          
push ['ebp']
mov ['ebp,', 'esp']
xor ['eax,', 'eax']
cmp ['[ebp+arg_0],', '0']
setnz ['al']
pop ['ebp']
retn ['4']
endp
??BAString@@QBEPBDXZ proc near          
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?Len@UString@@QBEIXZ proc near          
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax+4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??BUString@@QBEPB_WXZ proc near         
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?Ptr@UString@@QBEPB_WI@Z proc near      
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ebp+arg_0]']
lea ['eax,', '[ecx+edx*2]']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?DeleteBack@UString@@QAEXXZ proc near   
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+4]']
sub ['ecx,', '1']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_8]']
mov ['[edx+4],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
xor ['eax,', 'eax']
mov ['ecx,', '[ebp+var_8]']
mov ['[edx+ecx*2],', 'ax']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?DeleteFrom@UString@@QAEXI@Z proc near  
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+arg_0]']
cmp ['ecx,', '[eax+4]']
jnb ['short', 'loc_2538']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+arg_0]']
mov ['[edx+4],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
xor ['eax,', 'eax']
mov ['ecx,', '[ebp+arg_0]']
mov ['[edx+ecx*2],', 'ax']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?IsDir@CFileInfoBase@NFind@NFile@NWindows@@QBE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
push ['10h']
mov ['ecx,', '[ebp+var_4]']
call ['?MatchesMask@CFileInfoBase@NFind@NFile@NWindows@@ABE_NI@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?MatchesMask@CFileInfoBase@NFind@NFile@NWindows@@ABE_NI@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax+20h]']
and ['eax,', '[ebp+arg_0]']
neg ['eax']
sbb ['eax,', 'eax']
neg ['eax']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
??0CFileInfo@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0CFileInfoBase@NFind@NFile@NWindows@@QAE@XZ']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '28h']
call ['??0UString@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CFileInfoBase@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?ClearBase@CFileInfoBase@NFind@NFile@NWindows@@QAEXXZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '28h']
call ['??1UString@@QAE@XZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??YUString@@QAEAAV0@_W@Z proc near      
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0Ch']
mov ['[ebp+var_C],', '0CCCCCCCCh']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[eax+8]']
cmp ['edx,', '[ecx+4]']
jnz ['short', 'loc_2644']
mov ['ecx,', '[ebp+var_4]']
call ['?Grow_1@UString@@AAEXXZ']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+4]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
mov ['[ebp+var_C],', 'eax']
mov ['ecx,', '[ebp+var_8]']
mov ['edx,', '[ebp+var_C]']
mov ['ax,', '[ebp+arg_0]']
mov ['[edx+ecx*2],', 'ax']
mov ['ecx,', '[ebp+var_8]']
add ['ecx,', '1']
mov ['[ebp+var_8],', 'ecx']
xor ['edx,', 'edx']
mov ['eax,', '[ebp+var_8]']
mov ['ecx,', '[ebp+var_C]']
mov ['[ecx+eax*2],', 'dx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_8]']
mov ['[edx+4],', 'eax']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '0Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Add_PathSepar@UString@@QAEXXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
push ['5Ch']
mov ['ecx,', '[ebp+var_4]']
call ['??YUString@@QAEAAV0@_W@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?HasReparsePoint@CFileInfoBase@NFind@NFile@NWindows@@QBE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
push ['400h']
mov ['ecx,', '[ebp+var_4]']
call ['?MatchesMask@CFileInfoBase@NFind@NFile@NWindows@@ABE_NI@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$??0CEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
push ['ecx']
mov ['[ebp+var_10],', '0CCCCCCCCh']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_10],', 'ecx']
mov ['ecx,', '[ebp+var_10]']
call ['??0CFindFile@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '0']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
mov ['ecx,', '[ebp+var_10]']
add ['ecx,', '4']
call ['??0UString@@QAE@ABV0@@Z']
mov ['[ebp+var_4],', '0FFFFFFFFh']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
add ['esp,', '10h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
__unwindfunclet$??0CEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z$0 proc near
mov ['ecx,', '[ebp-10h]']
jmp ['??1CFindFile@NFind@NFile@NWindows@@QAE@XZ']
endp
__ehhandler$??0CEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-8]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$??0CEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z']
jmp ['___CxxFrameHandler3']
endp
??0CFindFile@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0CFindFileBase@NFind@NFile@NWindows@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CFindFileBase@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0FFFFFFFFh']
mov ['eax,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CFindFile@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??1CFindFileBase@NFind@NFile@NWindows@@QAE@XZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CFindFileBase@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?Close@CFindFileBase@NFind@NFile@NWindows@@QAE_NXZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CEnumerator@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$??1CEnumerator@NFind@NFile@NWindows@@QAE@XZ']
mov ['eax,', 'large', 'fs:0']
push ['eax']
push ['ecx']
mov ['[ebp+var_10],', '0CCCCCCCCh']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_10],', 'ecx']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_10]']
add ['ecx,', '4']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
mov ['ecx,', '[ebp+var_10]']
call ['??1CFindFile@NFind@NFile@NWindows@@QAE@XZ']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
add ['esp,', '10h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
__unwindfunclet$??1CEnumerator@NFind@NFile@NWindows@@QAE@XZ$0 proc near
mov ['ecx,', '[ebp-10h]']
jmp ['??1CFindFile@NFind@NFile@NWindows@@QAE@XZ']
endp
__ehhandler$??1CEnumerator@NFind@NFile@NWindows@@QAE@XZ proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-8]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$??1CEnumerator@NFind@NFile@NWindows@@QAE@XZ']
jmp ['___CxxFrameHandler3']
endp
?Empty@UString@@QAEXXZ proc near        
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+4],', '0']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
xor ['eax,', 'eax']
mov ['[edx],', 'ax']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?DisableDeleting@CTempFile@NDir@NFile@NWindows@@AAEXXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['byte', 'ptr', '[eax],', '0']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
