??0CInFileStream@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0IInStream@@QAE@XZ']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '4']
call ['??0IStreamGetSize@@QAE@XZ']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '8']
call ['??0IStreamGetProps@@QAE@XZ']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '0Ch']
call ['??0IStreamGetProps2@@QAE@XZ']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '10h']
call ['??0CMyUnknownImp@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', 'offset', '??_7CInFileStream@@6BIInStream@@@']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+4],', 'offset', '??_7CInFileStream@@6BIStreamGetSize@@@']
mov ['edx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[edx+8],', 'offset', '??_7CInFileStream@@6BIStreamGetProps@@@']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+0Ch],', 'offset', '??_7CInFileStream@@6BIStreamGetProps2@@@']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '18h']
call ['??0CInFile@NIO@NFile@NWindows@@QAE@XZ']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+28h],', '0']
mov ['dword', 'ptr', '[ecx+2Ch],', '0']
mov ['edx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[edx+30h],', '0']
mov ['dword', 'ptr', '[edx+34h],', '0']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+40h],', '0']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+44h],', '0']
mov ['edx,', '[ebp+var_4]']
mov ['byte', 'ptr', '[edx+48h],', '0']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+4Ch],', '0']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+50h],', '0']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CInFileStream@@UAE@XZ proc near      
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$??1CInFileStream@@UAE@XZ']
mov ['eax,', 'large', 'fs:0']
push ['eax']
push ['ecx']
push ['esi']
mov ['[ebp+var_10],', '0CCCCCCCCh']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_10],', 'ecx']
mov ['eax,', '[ebp+var_10]']
mov ['dword', 'ptr', '[eax],', 'offset', '??_7CInFileStream@@6BIInStream@@@']
mov ['ecx,', '[ebp+var_10]']
mov ['dword', 'ptr', '[ecx+4],', 'offset', '??_7CInFileStream@@6BIStreamGetSize@@@']
mov ['edx,', '[ebp+var_10]']
mov ['dword', 'ptr', '[edx+8],', 'offset', '??_7CInFileStream@@6BIStreamGetProps@@@']
mov ['eax,', '[ebp+var_10]']
mov ['dword', 'ptr', '[eax+0Ch],', 'offset', '??_7CInFileStream@@6BIStreamGetProps2@@@']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_10]']
mov ['edx,', '[ecx+40h]']
push ['edx']
call ['_MidFree@4']
mov ['eax,', '[ebp+var_10]']
cmp ['dword', 'ptr', '[eax+4Ch],', '0']
jz ['short', 'loc_176']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+var_10]']
mov ['edx,', '[ecx+50h]']
push ['edx']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[eax+4Ch]']
mov ['edx,', '[ebp+var_10]']
mov ['eax,', '[edx+4Ch]']
mov ['edx,', '[ecx]']
mov ['ecx,', 'eax']
mov ['eax,', '[edx+4]']
call ['eax']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_4],', '0FFFFFFFFh']
mov ['ecx,', '[ebp+var_10]']
add ['ecx,', '18h']
call ['??1CInFile@NIO@NFile@NWindows@@QAE@XZ']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['esi']
add ['esp,', '10h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?Read@CInFileStream@@UAGJPAXIPAI@Z proc near 
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0B4h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_B4]']
mov ['ecx,', '2Dh']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_1DC']
mov ['eax,', '[ebp+arg_C]']
mov ['dword', 'ptr', '[eax],', '0']
cmp ['[ebp+arg_8],', '0']
jnz ['short', 'loc_1E9']
xor ['eax,', 'eax']
jmp ['loc_715']
mov ['ecx,', '[ebp+this]']
movzx ['edx,', 'byte', 'ptr', '[ecx+1Ch]']
test ['edx,', 'edx']
jz ['loc_658']
mov ['eax,', '[ebp+this]']
movzx ['ecx,', 'byte', 'ptr', '[eax+1Dh]']
test ['ecx,', 'ecx']
jz ['loc_2CA']
mov ['edx,', '[ebp+this]']
mov ['eax,', '[ebp+this]']
mov ['[ebp+var_78],', 'edx']
mov ['[ebp+var_7C],', 'eax']
mov ['ecx,', '[ebp+var_78]']
mov ['edx,', '[ebp+var_7C]']
mov ['eax,', '[ecx+2Ch]']
cmp ['eax,', '[edx+24h]']
jb ['short', 'loc_283']
ja ['short', 'loc_231']
mov ['ecx,', '[ebp+var_78]']
mov ['edx,', '[ebp+var_7C]']
mov ['eax,', '[ecx+28h]']
cmp ['eax,', '[edx+20h]']
jb ['short', 'loc_283']
mov ['ecx,', '[ebp+this]']
mov ['edx,', '[ebp+this]']
mov ['[ebp+var_80],', 'ecx']
mov ['[ebp+var_84],', 'edx']
mov ['eax,', '[ebp+var_80]']
mov ['ecx,', '[ebp+var_84]']
mov ['edx,', '[eax+28h]']
cmp ['edx,', '[ecx+20h]']
jnz ['short', 'loc_26E']
mov ['eax,', '[ebp+var_80]']
mov ['ecx,', '[ebp+var_84]']
mov ['edx,', '[eax+2Ch]']
cmp ['edx,', '[ecx+24h]']
jnz ['short', 'loc_26E']
mov ['[ebp+var_88],', '0']
jmp ['short', 'loc_278']
mov ['[ebp+var_88],', '80004005h']
mov ['eax,', '[ebp+var_88]']
jmp ['loc_715']
mov ['eax,', '[ebp+this]']
mov ['ecx,', '[ebp+this]']
mov ['edx,', '[eax+20h]']
sub ['edx,', '[ecx+28h]']
mov ['eax,', '[eax+24h]']
sbb ['eax,', '[ecx+2Ch]']
mov ['[ebp+var_8],', 'edx']
mov ['[ebp+var_4],', 'eax']
mov ['ecx,', '[ebp+arg_8]']
xor ['edx,', 'edx']
mov ['[ebp+var_90],', 'ecx']
mov ['[ebp+var_8C],', 'edx']
mov ['eax,', '[ebp+var_8C]']
cmp ['eax,', '[ebp+var_4]']
jb ['short', 'loc_2CA']
ja ['short', 'loc_2C4']
mov ['ecx,', '[ebp+var_90]']
cmp ['ecx,', '[ebp+var_8]']
jbe ['short', 'loc_2CA']
mov ['edx,', '[ebp+var_8]']
mov ['[ebp+arg_8],', 'edx']
mov ['[ebp+var_C],', '3FFFFh']
mov ['[ebp+var_14],', '0FFFC0000h']
mov ['[ebp+var_10],', '0FFFFFFFFh']
mov ['eax,', '[ebp+this]']
mov ['ecx,', '[eax+28h]']
and ['ecx,', '0FFFC0000h']
mov ['edx,', '[eax+2Ch]']
mov ['dword', 'ptr', '[ebp+var_1C],', 'ecx']
mov ['dword', 'ptr', '[ebp+var_1C+4],', 'edx']
mov ['eax,', '[ebp+this]']
cmp ['dword', 'ptr', '[eax+44h],', '0']
jbe ['loc_3B0']
mov ['ecx,', '[ebp+this]']
mov ['[ebp+var_94],', 'ecx']
mov ['edx,', '[ebp+var_94]']
mov ['eax,', '[edx+38h]']
cmp ['eax,', 'dword', 'ptr', '[ebp+var_1C]']
jnz ['loc_3B0']
mov ['ecx,', '[ebp+var_94]']
mov ['edx,', '[ecx+3Ch]']
cmp ['edx,', 'dword', 'ptr', '[ebp+var_1C+4]']
jnz ['loc_3B0']
mov ['eax,', '[ebp+this]']
mov ['ecx,', '[eax+28h]']
and ['ecx,', '3FFFFh']
mov ['[ebp+var_20],', 'ecx']
mov ['edx,', '[ebp+this]']
mov ['eax,', '[ebp+var_20]']
cmp ['eax,', '[edx+44h]']
jb ['short', 'loc_34F']
xor ['eax,', 'eax']
jmp ['loc_715']
mov ['ecx,', '[ebp+arg_8]']
push ['ecx']
mov ['edx,', '[ebp+this]']
mov ['eax,', '[edx+44h]']
sub ['eax,', '[ebp+var_20]']
push ['eax']
call ['??$MyMin@I@@YGIII@Z']
mov ['[ebp+Size],', 'eax']
mov ['ecx,', '[ebp+Size]']
push ['ecx']
mov ['edx,', '[ebp+this]']
mov ['eax,', '[edx+40h]']
add ['eax,', '[ebp+var_20]']
push ['eax']
mov ['ecx,', '[ebp+Dst]']
push ['ecx']
call ['_memcpy']
add ['esp,', '0Ch']
mov ['edx,', '[ebp+Size]']
xor ['eax,', 'eax']
mov ['ecx,', '[ebp+this]']
add ['edx,', '[ecx+28h]']
adc ['eax,', '[ecx+2Ch]']
mov ['ecx,', '[ebp+this]']
mov ['[ecx+28h],', 'edx']
mov ['[ecx+2Ch],', 'eax']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_3A9']
mov ['edx,', '[ebp+arg_C]']
mov ['eax,', '[edx]']
add ['eax,', '[ebp+Size]']
mov ['ecx,', '[ebp+arg_C]']
mov ['[ecx],', 'eax']
xor ['eax,', 'eax']
jmp ['loc_715']
mov ['[ebp+var_25],', '0']
mov ['edx,', '[ebp+this]']
mov ['eax,', '[edx+28h]']
and ['eax,', '3FFFFh']
mov ['ecx,', '[edx+2Ch]']
and ['ecx,', '0']
mov ['[ebp+var_9C],', 'eax']
mov ['[ebp+var_98],', 'ecx']
mov ['edx,', '[ebp+var_9C]']
or ['edx,', '[ebp+var_98]']
jnz ['short', 'loc_3E9']
mov ['eax,', '[ebp+Dst]']
and ['eax,', '3FFFFh']
jz ['short', 'loc_3F2']
mov ['[ebp+var_25],', '1']
jmp ['loc_480']
mov ['ecx,', '[ebp+arg_8]']
xor ['edx,', 'edx']
mov ['eax,', '[ebp+this]']
add ['ecx,', '[eax+28h]']
adc ['edx,', '[eax+2Ch]']
mov ['[ebp+var_30],', 'ecx']
mov ['[ebp+var_2C],', 'edx']
mov ['ecx,', '[ebp+var_30]']
and ['ecx,', '3FFFFh']
mov ['edx,', '[ebp+var_2C]']
and ['edx,', '0']
mov ['[ebp+var_A4],', 'ecx']
mov ['[ebp+var_A0],', 'edx']
mov ['eax,', '[ebp+var_A4]']
or ['eax,', '[ebp+var_A0]']
jz ['short', 'loc_480']
mov ['ecx,', '[ebp+var_30]']
and ['ecx,', '0FFFC0000h']
mov ['edx,', '[ebp+var_2C]']
mov ['[ebp+var_30],', 'ecx']
mov ['[ebp+var_2C],', 'edx']
mov ['eax,', '[ebp+this]']
mov ['[ebp+var_A8],', 'eax']
mov ['ecx,', '[ebp+var_A8]']
mov ['edx,', '[ebp+var_2C]']
cmp ['edx,', '[ecx+2Ch]']
ja ['short', 'loc_46E']
jb ['short', 'loc_468']
mov ['eax,', '[ebp+var_A8]']
mov ['ecx,', '[ebp+var_30]']
cmp ['ecx,', '[eax+28h]']
ja ['short', 'loc_46E']
mov ['[ebp+var_25],', '1']
jmp ['short', 'loc_480']
mov ['edx,', '[ebp+this]']
mov ['eax,', '[ebp+var_30]']
sub ['eax,', '[edx+28h]']
mov ['ecx,', '[ebp+var_2C]']
sbb ['ecx,', '[edx+2Ch]']
mov ['[ebp+arg_8],', 'eax']
movzx ['edx,', '[ebp+var_25]']
test ['edx,', 'edx']
jnz ['short', 'loc_48D']
jmp ['loc_5CA']
mov ['eax,', '[ebp+this]']
mov ['[ebp+var_AC],', 'eax']
mov ['ecx,', '[ebp+var_AC]']
mov ['edx,', 'dword', 'ptr', '[ebp+var_1C]']
cmp ['edx,', '[ecx+30h]']
jnz ['short', 'loc_4B2']
mov ['eax,', '[ebp+var_AC]']
mov ['ecx,', 'dword', 'ptr', '[ebp+var_1C+4]']
cmp ['ecx,', '[eax+34h]']
jz ['short', 'loc_4F4']
lea ['edx,', '[ebp+var_3C]']
push ['edx']
push ['0']
mov ['eax,', 'dword', 'ptr', '[ebp+var_1C+4]']
push ['eax']
mov ['ecx,', 'dword', 'ptr', '[ebp+var_1C]']
push ['ecx']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '18h']
call ['?Seek@CFileBase@NIO@NFile@NWindows@@QBE_N_JKAA_K@Z']
mov ['[ebp+var_41],', 'al']
movzx ['edx,', '[ebp+var_41]']
test ['edx,', 'edx']
jnz ['short', 'loc_4E5']
movzx ['eax,', '[ebp+var_41]']
push ['eax']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
jmp ['loc_715']
mov ['ecx,', '[ebp+this]']
mov ['edx,', 'dword', 'ptr', '[ebp+var_3C]']
mov ['[ecx+30h],', 'edx']
mov ['eax,', 'dword', 'ptr', '[ebp+var_3C+4]']
mov ['[ecx+34h],', 'eax']
mov ['ecx,', '[ebp+this]']
mov ['edx,', 'dword', 'ptr', '[ebp+var_1C]']
mov ['[ecx+38h],', 'edx']
mov ['eax,', 'dword', 'ptr', '[ebp+var_1C+4]']
mov ['[ecx+3Ch],', 'eax']
mov ['[ebp+var_48],', '40000h']
mov ['ecx,', '[ebp+this]']
movzx ['edx,', 'byte', 'ptr', '[ecx+1Dh]']
test ['edx,', 'edx']
jz ['short', 'loc_538']
push ['0']
push ['40000h']
mov ['eax,', '[ebp+this]']
mov ['ecx,', '[ebp+this]']
mov ['edx,', '[eax+20h]']
sub ['edx,', '[ecx+30h]']
mov ['eax,', '[eax+24h]']
sbb ['eax,', '[ecx+34h]']
push ['eax']
push ['edx']
call ['??$MyMin@_K@@YG_K_K0@Z']
mov ['[ebp+var_48],', 'eax']
mov ['ecx,', '[ebp+this]']
cmp ['dword', 'ptr', '[ecx+40h],', '0']
jnz ['short', 'loc_564']
push ['40000h']
call ['_MidAlloc@4']
mov ['edx,', '[ebp+this]']
mov ['[edx+40h],', 'eax']
mov ['eax,', '[ebp+this]']
cmp ['dword', 'ptr', '[eax+40h],', '0']
jnz ['short', 'loc_564']
mov ['eax,', '8007000Eh']
jmp ['loc_715']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '44h']
push ['ecx']
mov ['edx,', '[ebp+var_48]']
push ['edx']
mov ['eax,', '[ebp+this]']
mov ['ecx,', '[eax+40h]']
push ['ecx']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '18h']
call ['?Read1@CInFile@NIO@NFile@NWindows@@QAE_NPAXIAAI@Z']
mov ['[ebp+var_49],', 'al']
movzx ['edx,', '[ebp+var_49]']
test ['edx,', 'edx']
jnz ['short', 'loc_59B']
movzx ['eax,', '[ebp+var_49]']
push ['eax']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
jmp ['loc_715']
mov ['ecx,', '[ebp+this]']
cmp ['dword', 'ptr', '[ecx+44h],', '0']
jnz ['short', 'loc_5AB']
xor ['eax,', 'eax']
jmp ['loc_715']
mov ['edx,', '[ebp+this]']
mov ['eax,', '[edx+44h]']
xor ['ecx,', 'ecx']
mov ['edx,', '[ebp+this]']
add ['eax,', '[edx+30h]']
adc ['ecx,', '[edx+34h]']
mov ['edx,', '[ebp+this]']
mov ['[edx+30h],', 'eax']
mov ['[edx+34h],', 'ecx']
jmp ['loc_2CA']
mov ['eax,', '[ebp+this]']
mov ['ecx,', '[ebp+this]']
mov ['[ebp+var_B0],', 'eax']
mov ['[ebp+var_B4],', 'ecx']
mov ['edx,', '[ebp+var_B0]']
mov ['eax,', '[ebp+var_B4]']
mov ['ecx,', '[edx+28h]']
cmp ['ecx,', '[eax+30h]']
jnz ['short', 'loc_604']
mov ['edx,', '[ebp+var_B0]']
mov ['eax,', '[ebp+var_B4]']
mov ['ecx,', '[edx+2Ch]']
cmp ['ecx,', '[eax+34h]']
jz ['short', 'loc_658']
lea ['edx,', '[ebp+var_58]']
push ['edx']
push ['0']
mov ['eax,', '[ebp+this]']
mov ['ecx,', '[eax+2Ch]']
push ['ecx']
mov ['edx,', '[eax+28h]']
push ['edx']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '18h']
call ['?Seek@CFileBase@NIO@NFile@NWindows@@QBE_N_JKAA_K@Z']
mov ['[ebp+var_5D],', 'al']
movzx ['eax,', '[ebp+var_5D]']
test ['eax,', 'eax']
jnz ['short', 'loc_63A']
movzx ['ecx,', '[ebp+var_5D]']
push ['ecx']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
jmp ['loc_715']
mov ['edx,', '[ebp+this]']
mov ['eax,', 'dword', 'ptr', '[ebp+var_58]']
mov ['[edx+28h],', 'eax']
mov ['ecx,', 'dword', 'ptr', '[ebp+var_58+4]']
mov ['[edx+2Ch],', 'ecx']
mov ['edx,', '[ebp+this]']
mov ['eax,', 'dword', 'ptr', '[ebp+var_58]']
mov ['[edx+30h],', 'eax']
mov ['ecx,', 'dword', 'ptr', '[ebp+var_58+4]']
mov ['[edx+34h],', 'ecx']
lea ['edx,', '[ebp+var_68]']
push ['edx']
mov ['eax,', '[ebp+arg_8]']
push ['eax']
mov ['ecx,', '[ebp+Dst]']
push ['ecx']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '18h']
call ['?ReadPart@CInFile@NIO@NFile@NWindows@@QAE_NPAXIAAI@Z']
mov ['[ebp+var_6D],', 'al']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_680']
mov ['edx,', '[ebp+arg_C]']
mov ['eax,', '[ebp+var_68]']
mov ['[edx],', 'eax']
mov ['ecx,', '[ebp+var_68]']
xor ['edx,', 'edx']
mov ['eax,', '[ebp+this]']
add ['ecx,', '[eax+28h]']
adc ['edx,', '[eax+2Ch]']
mov ['eax,', '[ebp+this]']
mov ['[eax+28h],', 'ecx']
mov ['[eax+2Ch],', 'edx']
mov ['ecx,', '[ebp+var_68]']
xor ['edx,', 'edx']
mov ['eax,', '[ebp+this]']
add ['ecx,', '[eax+30h]']
adc ['edx,', '[eax+34h]']
mov ['eax,', '[ebp+this]']
mov ['[eax+30h],', 'ecx']
mov ['[eax+34h],', 'edx']
movzx ['ecx,', '[ebp+var_6D]']
test ['ecx,', 'ecx']
jz ['short', 'loc_6BA']
xor ['eax,', 'eax']
jmp ['short', 'loc_715']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_74],', 'eax']
mov ['edx,', '[ebp+this]']
cmp ['dword', 'ptr', '[edx+4Ch],', '0']
jz ['short', 'loc_6FF']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_74]']
push ['eax']
mov ['ecx,', '[ebp+this]']
mov ['edx,', '[ecx+50h]']
push ['edx']
mov ['eax,', '[ebp+this]']
mov ['ecx,', '[eax+4Ch]']
mov ['edx,', '[ebp+this]']
mov ['eax,', '[edx+4Ch]']
mov ['edx,', '[ecx]']
mov ['ecx,', 'eax']
mov ['eax,', '[edx]']
call ['eax']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
jmp ['short', 'loc_715']
cmp ['[ebp+var_74],', '0']
jnz ['short', 'loc_70C']
mov ['eax,', '80004005h']
jmp ['short', 'loc_715']
mov ['ecx,', '[ebp+var_74]']
push ['ecx']
call ['_HRESULT_FROM_WIN32@4']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN45']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
add ['esp,', '0B4h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['10h']
endp
?ConvertBoolToHRESULT@@YGJ_N@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
push ['esi']
mov ['[ebp+var_4],', '0CCCCCCCCh']
movzx ['eax,', '[ebp+arg_0]']
test ['eax,', 'eax']
jz ['short', 'loc_7B8']
xor ['eax,', 'eax']
jmp ['short', 'loc_7E0']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_4],', 'eax']
cmp ['[ebp+var_4],', '0']
jnz ['short', 'loc_7D7']
mov ['eax,', '80004005h']
jmp ['short', 'loc_7E0']
mov ['ecx,', '[ebp+var_4]']
push ['ecx']
call ['_HRESULT_FROM_WIN32@4']
pop ['esi']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Read@CStdInFileStream@@UAGJPAXIPAI@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '14h']
push ['esi']
push ['edi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+nNumberOfBytesToRead],', 'eax']
mov ['[ebp+var_C],', 'eax']
mov ['[ebp+NumberOfBytesRead],', 'eax']
mov ['[ebp+var_4],', 'eax']
mov ['[ebp+nNumberOfBytesToRead],', '100000h']
mov ['eax,', '[ebp+nNumberOfBytesToRead]']
cmp ['eax,', '[ebp+arg_8]']
jbe ['short', 'loc_831']
mov ['ecx,', '[ebp+arg_8]']
mov ['[ebp+nNumberOfBytesToRead],', 'ecx']
mov ['esi,', 'esp']
push ['0']
lea ['edx,', '[ebp+NumberOfBytesRead]']
push ['edx']
mov ['eax,', '[ebp+nNumberOfBytesToRead]']
push ['eax']
mov ['ecx,', '[ebp+lpBuffer]']
push ['ecx']
mov ['edi,', 'esp']
push ['0FFFFFFF6h']
call ['dword', 'ptr', 'ds:__imp__GetStdHandle@4']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__ReadFile@20']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_871']
mov ['edx,', '[ebp+arg_C]']
mov ['eax,', '[ebp+NumberOfBytesRead]']
mov ['[edx],', 'eax']
cmp ['[ebp+var_14],', '0']
jnz ['short', 'loc_88F']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
cmp ['eax,', '6Dh']
jnz ['short', 'loc_88F']
xor ['eax,', 'eax']
jmp ['short', 'loc_89F']
cmp ['[ebp+var_14],', '0']
setnz ['cl']
movzx ['edx,', 'cl']
push ['edx']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN8']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
add ['esp,', '14h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['10h']
endp
?Seek@CInFileStream@@UAGJ_JIPA_K@Z proc near 
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '18h']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['dword', 'ptr', '[ebp+var_C],', 'eax']
mov ['dword', 'ptr', '[ebp+var_C+4],', 'eax']
mov ['[ebp+var_4],', 'eax']
cmp ['[ebp+arg_C],', '3']
jb ['short', 'loc_91D']
mov ['eax,', '80030001h']
jmp ['loc_A2E']
mov ['eax,', '[ebp+this]']
movzx ['ecx,', 'byte', 'ptr', '[eax+1Ch]']
test ['ecx,', 'ecx']
jz ['loc_9D4']
mov ['edx,', '[ebp+this]']
movzx ['eax,', 'byte', 'ptr', '[edx+1Dh]']
test ['eax,', 'eax']
jnz ['short', 'loc_941']
cmp ['[ebp+arg_C],', '2']
jz ['loc_9D4']
mov ['ecx,', '[ebp+arg_C]']
mov ['[ebp+var_18],', 'ecx']
cmp ['[ebp+var_18],', '0']
jz ['short', 'loc_95B']
cmp ['[ebp+var_18],', '1']
jz ['short', 'loc_95D']
cmp ['[ebp+var_18],', '2']
jz ['short', 'loc_974']
jmp ['short', 'loc_98B']
jmp ['short', 'loc_995']
mov ['edx,', '[ebp+this]']
mov ['eax,', 'dword', 'ptr', '[ebp+arg_4]']
add ['eax,', '[edx+28h]']
mov ['ecx,', 'dword', 'ptr', '[ebp+arg_4+4]']
adc ['ecx,', '[edx+2Ch]']
mov ['dword', 'ptr', '[ebp+arg_4],', 'eax']
mov ['dword', 'ptr', '[ebp+arg_4+4],', 'ecx']
jmp ['short', 'loc_995']
mov ['edx,', '[ebp+this]']
mov ['eax,', 'dword', 'ptr', '[ebp+arg_4]']
add ['eax,', '[edx+20h]']
mov ['ecx,', 'dword', 'ptr', '[ebp+arg_4+4]']
adc ['ecx,', '[edx+24h]']
mov ['dword', 'ptr', '[ebp+arg_4],', 'eax']
mov ['dword', 'ptr', '[ebp+arg_4+4],', 'ecx']
jmp ['short', 'loc_995']
mov ['eax,', '80030001h']
jmp ['loc_A2E']
cmp ['dword', 'ptr', '[ebp+arg_4+4],', '0']
jg ['short', 'loc_9AD']
jl ['short', 'loc_9A3']
cmp ['dword', 'ptr', '[ebp+arg_4],', '0']
jnb ['short', 'loc_9AD']
mov ['eax,', '80070083h']
jmp ['loc_A2E']
mov ['edx,', '[ebp+this]']
mov ['eax,', 'dword', 'ptr', '[ebp+arg_4]']
mov ['[edx+28h],', 'eax']
mov ['ecx,', 'dword', 'ptr', '[ebp+arg_4+4]']
mov ['[edx+2Ch],', 'ecx']
cmp ['[ebp+arg_10],', '0']
jz ['short', 'loc_9D0']
mov ['edx,', '[ebp+arg_10]']
mov ['eax,', 'dword', 'ptr', '[ebp+arg_4]']
mov ['[edx],', 'eax']
mov ['ecx,', 'dword', 'ptr', '[ebp+arg_4+4]']
mov ['[edx+4],', 'ecx']
xor ['eax,', 'eax']
jmp ['short', 'loc_A2E']
lea ['edx,', '[ebp+var_C]']
push ['edx']
mov ['eax,', '[ebp+arg_C]']
push ['eax']
mov ['ecx,', 'dword', 'ptr', '[ebp+arg_4+4]']
push ['ecx']
mov ['edx,', 'dword', 'ptr', '[ebp+arg_4]']
push ['edx']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '18h']
call ['?Seek@CFileBase@NIO@NFile@NWindows@@QBE_N_JKAA_K@Z']
mov ['byte', 'ptr', '[ebp+var_14+3],', 'al']
mov ['eax,', '[ebp+this]']
mov ['ecx,', 'dword', 'ptr', '[ebp+var_C]']
mov ['[eax+28h],', 'ecx']
mov ['edx,', 'dword', 'ptr', '[ebp+var_C+4]']
mov ['[eax+2Ch],', 'edx']
mov ['eax,', '[ebp+this]']
mov ['ecx,', 'dword', 'ptr', '[ebp+var_C]']
mov ['[eax+30h],', 'ecx']
mov ['edx,', 'dword', 'ptr', '[ebp+var_C+4]']
mov ['[eax+34h],', 'edx']
cmp ['[ebp+arg_10],', '0']
jz ['short', 'loc_A24']
mov ['eax,', '[ebp+arg_10]']
mov ['ecx,', 'dword', 'ptr', '[ebp+var_C]']
mov ['[eax],', 'ecx']
mov ['edx,', 'dword', 'ptr', '[ebp+var_C+4]']
mov ['[eax+4],', 'edx']
movzx ['eax,', 'byte', 'ptr', '[ebp+var_14+3]']
push ['eax']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN18']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
add ['esp,', '18h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['14h']
endp
?GetSize@CInFileStream@@UAGJPA_K@Z proc near 
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+arg_4]']
push ['eax']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '14h']
call ['?GetLength@CFileBase@NIO@NFile@NWindows@@QBE_NAA_K@Z']
movzx ['ecx,', 'al']
push ['ecx']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
?GetProps@CInFileStream@@UAGJPA_KPAU_FILETIME@@11PAI@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '40h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_40]']
mov ['ecx,', '10h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_4],', 'eax']
lea ['eax,', '[ebp+var_3C]']
push ['eax']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '10h']
call ['?GetFileInformation@CFileBase@NIO@NFile@NWindows@@QBE_NPAU_BY_HANDLE_FILE_INFORMATION@@@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_B58']
cmp ['[ebp+arg_4],', '0']
jz ['short', 'loc_B0A']
mov ['eax,', '[ebp+var_3C.nFileSizeHigh]']
xor ['edx,', 'edx']
mov ['cl,', '20h']
call ['__allshl']
mov ['ecx,', '[ebp+var_3C.nFileSizeLow]']
xor ['esi,', 'esi']
add ['eax,', 'ecx']
adc ['edx,', 'esi']
mov ['ecx,', '[ebp+arg_4]']
mov ['[ecx],', 'eax']
mov ['[ecx+4],', 'edx']
cmp ['[ebp+arg_8],', '0']
jz ['short', 'loc_B1E']
mov ['edx,', '[ebp+arg_8]']
mov ['eax,', '[ebp+var_3C.ftCreationTime.dwLowDateTime]']
mov ['[edx],', 'eax']
mov ['ecx,', '[ebp+var_3C.ftCreationTime.dwHighDateTime]']
mov ['[edx+4],', 'ecx']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_B32']
mov ['edx,', '[ebp+arg_C]']
mov ['eax,', '[ebp+var_3C.ftLastAccessTime.dwLowDateTime]']
mov ['[edx],', 'eax']
mov ['ecx,', '[ebp+var_3C.ftLastAccessTime.dwHighDateTime]']
mov ['[edx+4],', 'ecx']
cmp ['[ebp+arg_10],', '0']
jz ['short', 'loc_B46']
mov ['edx,', '[ebp+arg_10]']
mov ['eax,', '[ebp+var_3C.ftLastWriteTime.dwLowDateTime]']
mov ['[edx],', 'eax']
mov ['ecx,', '[ebp+var_3C.ftLastWriteTime.dwHighDateTime]']
mov ['[edx+4],', 'ecx']
cmp ['[ebp+arg_14],', '0']
jz ['short', 'loc_B54']
mov ['edx,', '[ebp+arg_14]']
mov ['eax,', '[ebp+var_3C.dwFileAttributes]']
mov ['[edx],', 'eax']
xor ['eax,', 'eax']
jmp ['short', 'loc_B67']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN11']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_4]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '40h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['18h']
endp
?GetProps2@CInFileStream@@UAGJPAUCStreamFileProps@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '44h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_44]']
mov ['ecx,', '11h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_4],', 'eax']
lea ['eax,', '[ebp+var_3C]']
push ['eax']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '0Ch']
call ['?GetFileInformation@CFileBase@NIO@NFile@NWindows@@QBE_NPAU_BY_HANDLE_FILE_INFORMATION@@@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['loc_CA2']
mov ['eax,', '[ebp+var_3C.nFileSizeHigh]']
xor ['edx,', 'edx']
mov ['cl,', '20h']
call ['__allshl']
mov ['ecx,', '[ebp+var_3C.nFileSizeLow]']
xor ['esi,', 'esi']
add ['eax,', 'ecx']
adc ['edx,', 'esi']
mov ['ecx,', '[ebp+arg_4]']
mov ['[ecx],', 'eax']
mov ['[ecx+4],', 'edx']
mov ['edx,', '[ebp+var_3C.dwVolumeSerialNumber]']
xor ['eax,', 'eax']
mov ['ecx,', '[ebp+arg_4]']
mov ['[ecx+8],', 'edx']
mov ['[ecx+0Ch],', 'eax']
mov ['eax,', '[ebp+var_3C.nFileIndexHigh]']
xor ['edx,', 'edx']
mov ['cl,', '20h']
call ['__allshl']
mov ['ecx,', '[ebp+var_3C.nFileIndexLow]']
xor ['esi,', 'esi']
add ['eax,', 'ecx']
adc ['edx,', 'esi']
mov ['ecx,', '[ebp+arg_4]']
mov ['[ecx+10h],', 'eax']
mov ['[ecx+14h],', 'edx']
mov ['edx,', '[ebp+arg_4]']
mov ['dword', 'ptr', '[edx+18h],', '0']
mov ['dword', 'ptr', '[edx+1Ch],', '0']
mov ['eax,', '[ebp+this]']
movzx ['ecx,', 'byte', 'ptr', '[eax+3Ch]']
test ['ecx,', 'ecx']
jz ['short', 'loc_C58']
mov ['edx,', '[ebp+var_3C.nNumberOfLinks]']
mov ['[ebp+var_44],', 'edx']
jmp ['short', 'loc_C5F']
mov ['[ebp+var_44],', '1']
mov ['eax,', '[ebp+arg_4]']
mov ['ecx,', '[ebp+var_44]']
mov ['[eax+20h],', 'ecx']
mov ['edx,', '[ebp+arg_4]']
mov ['eax,', '[ebp+var_3C.dwFileAttributes]']
mov ['[edx+24h],', 'eax']
mov ['ecx,', '[ebp+arg_4]']
mov ['edx,', '[ebp+var_3C.ftCreationTime.dwLowDateTime]']
mov ['[ecx+28h],', 'edx']
mov ['eax,', '[ebp+var_3C.ftCreationTime.dwHighDateTime]']
mov ['[ecx+2Ch],', 'eax']
mov ['ecx,', '[ebp+arg_4]']
mov ['edx,', '[ebp+var_3C.ftLastAccessTime.dwLowDateTime]']
mov ['[ecx+30h],', 'edx']
mov ['eax,', '[ebp+var_3C.ftLastAccessTime.dwHighDateTime]']
mov ['[ecx+34h],', 'eax']
mov ['ecx,', '[ebp+arg_4]']
mov ['edx,', '[ebp+var_3C.ftLastWriteTime.dwLowDateTime]']
mov ['[ecx+38h],', 'edx']
mov ['eax,', '[ebp+var_3C.ftLastWriteTime.dwHighDateTime]']
mov ['[ecx+3Ch],', 'eax']
xor ['eax,', 'eax']
jmp ['short', 'loc_CB1']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN8_0']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_4]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '44h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?Close@COutFileStream@@QAEJXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '8']
call ['?Close@CFileBase@NIO@NFile@NWindows@@QAE_NXZ']
movzx ['eax,', 'al']
push ['eax']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?Write@COutFileStream@@UAGJPBXIPAI@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '10h']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_C],', 'eax']
mov ['[ebp+var_8],', 'eax']
mov ['[ebp+var_4],', 'eax']
lea ['eax,', '[ebp+var_8]']
push ['eax']
mov ['ecx,', '[ebp+arg_8]']
push ['ecx']
mov ['edx,', '[ebp+arg_4]']
push ['edx']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '8']
call ['?Write@COutFile@NIO@NFile@NWindows@@QAE_NPBXIAAI@Z']
mov ['byte', 'ptr', '[ebp+var_10+3],', 'al']
mov ['eax,', '[ebp+var_8]']
xor ['ecx,', 'ecx']
mov ['edx,', '[ebp+this]']
add ['eax,', '[edx+18h]']
adc ['ecx,', '[edx+1Ch]']
mov ['edx,', '[ebp+this]']
mov ['[edx+18h],', 'eax']
mov ['[edx+1Ch],', 'ecx']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_D86']
mov ['eax,', '[ebp+arg_C]']
mov ['ecx,', '[ebp+var_8]']
mov ['[eax],', 'ecx']
movzx ['edx,', 'byte', 'ptr', '[ebp+var_10+3]']
push ['edx']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN6_1']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
add ['esp,', '10h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['10h']
endp
?Seek@COutFileStream@@UAGJ_JIPA_K@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '14h']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['dword', 'ptr', '[ebp+var_C],', 'eax']
mov ['dword', 'ptr', '[ebp+var_C+4],', 'eax']
mov ['[ebp+var_4],', 'eax']
cmp ['[ebp+arg_C],', '3']
jb ['short', 'loc_E07']
mov ['eax,', '80030001h']
jmp ['short', 'loc_E43']
lea ['eax,', '[ebp+var_C]']
push ['eax']
mov ['ecx,', '[ebp+arg_C]']
push ['ecx']
mov ['edx,', 'dword', 'ptr', '[ebp+arg_4+4]']
push ['edx']
mov ['eax,', 'dword', 'ptr', '[ebp+arg_4]']
push ['eax']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '8']
call ['?Seek@CFileBase@NIO@NFile@NWindows@@QBE_N_JKAA_K@Z']
mov ['byte', 'ptr', '[ebp+var_14+3],', 'al']
cmp ['[ebp+arg_10],', '0']
jz ['short', 'loc_E39']
mov ['ecx,', '[ebp+arg_10]']
mov ['edx,', 'dword', 'ptr', '[ebp+var_C]']
mov ['[ecx],', 'edx']
mov ['eax,', 'dword', 'ptr', '[ebp+var_C+4]']
mov ['[ecx+4],', 'eax']
movzx ['ecx,', 'byte', 'ptr', '[ebp+var_14+3]']
push ['ecx']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN7_1']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
add ['esp,', '14h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['14h']
endp
?SetSize@COutFileStream@@UAGJ_K@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '28h']
push ['edi']
lea ['edi,', '[ebp+var_28]']
mov ['ecx,', '0Ah']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
lea ['eax,', '[ebp+var_C]']
push ['eax']
push ['1']
push ['0']
push ['0']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '8']
call ['?Seek@CFileBase@NIO@NFile@NWindows@@QBE_N_JKAA_K@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jnz ['short', 'loc_EC9']
mov ['eax,', '80004005h']
jmp ['short', 'loc_F2D']
mov ['edx,', 'dword', 'ptr', '[ebp+arg_4+4]']
push ['edx']
mov ['eax,', 'dword', 'ptr', '[ebp+arg_4]']
push ['eax']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '8']
call ['?SetLength@COutFile@NIO@NFile@NWindows@@QAE_N_K@Z']
mov ['[ebp+var_11],', 'al']
movzx ['ecx,', '[ebp+var_11]']
test ['ecx,', 'ecx']
jz ['short', 'loc_F0E']
lea ['edx,', '[ebp+var_20]']
push ['edx']
mov ['eax,', 'dword', 'ptr', '[ebp+var_C+4]']
push ['eax']
mov ['ecx,', 'dword', 'ptr', '[ebp+var_C]']
push ['ecx']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '8']
call ['?Seek@CFileBase@NIO@NFile@NWindows@@QBE_N_KAA_K@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jz ['short', 'loc_F0E']
mov ['[ebp+var_28],', '1']
jmp ['short', 'loc_F15']
mov ['[ebp+var_28],', '0']
mov ['al,', 'byte', 'ptr', '[ebp+var_28]']
mov ['[ebp+var_11],', 'al']
movzx ['eax,', '[ebp+var_11]']
neg ['eax']
sbb ['eax,', 'eax']
and ['eax,', '7FFFBFFBh']
add ['eax,', '80004005h']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN9_0']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
add ['esp,', '28h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['0Ch']
endp
?GetSize@COutFileStream@@QAEJPA_K@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '8']
call ['?GetLength@CFileBase@NIO@NFile@NWindows@@QBE_NAA_K@Z']
movzx ['ecx,', 'al']
push ['ecx']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Write@CStdOutFileStream@@UAGJPBXIPAI@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '14h']
push ['esi']
push ['edi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+nNumberOfBytesToWrite],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_C],', 'eax']
mov ['[ebp+NumberOfBytesWritten],', 'eax']
mov ['[ebp+var_4],', 'eax']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_FFB']
mov ['eax,', '[ebp+arg_C]']
mov ['dword', 'ptr', '[eax],', '0']
mov ['[ebp+var_10],', '1']
cmp ['[ebp+arg_8],', '0']
jbe ['loc_108F']
mov ['[ebp+nNumberOfBytesToWrite],', '8000h']
mov ['ecx,', '[ebp+nNumberOfBytesToWrite]']
cmp ['ecx,', '[ebp+arg_8]']
jbe ['short', 'loc_1021']
mov ['edx,', '[ebp+arg_8]']
mov ['[ebp+nNumberOfBytesToWrite],', 'edx']
mov ['esi,', 'esp']
push ['0']
lea ['eax,', '[ebp+NumberOfBytesWritten]']
push ['eax']
mov ['ecx,', '[ebp+nNumberOfBytesToWrite]']
push ['ecx']
mov ['edx,', '[ebp+lpBuffer]']
push ['edx']
mov ['edi,', 'esp']
push ['0FFFFFFF5h']
call ['dword', 'ptr', 'ds:__imp__GetStdHandle@4']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__WriteFile@20']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', '[ebp+NumberOfBytesWritten]']
xor ['ecx,', 'ecx']
mov ['edx,', '[ebp+this]']
add ['eax,', '[edx+8]']
adc ['ecx,', '[edx+0Ch]']
mov ['edx,', '[ebp+this]']
mov ['[edx+8],', 'eax']
mov ['[edx+0Ch],', 'ecx']
mov ['eax,', '[ebp+arg_8]']
sub ['eax,', '[ebp+NumberOfBytesWritten]']
mov ['[ebp+arg_8],', 'eax']
mov ['ecx,', '[ebp+lpBuffer]']
add ['ecx,', '[ebp+NumberOfBytesWritten]']
mov ['[ebp+lpBuffer],', 'ecx']
cmp ['[ebp+arg_C],', '0']
jz ['short', 'loc_108F']
mov ['edx,', '[ebp+arg_C]']
mov ['eax,', '[edx]']
add ['eax,', '[ebp+NumberOfBytesWritten]']
mov ['ecx,', '[ebp+arg_C]']
mov ['[ecx],', 'eax']
cmp ['[ebp+var_10],', '0']
setnz ['dl']
movzx ['eax,', 'dl']
push ['eax']
call ['?ConvertBoolToHRESULT@@YGJ_N@Z']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN9_1']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
add ['esp,', '14h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['10h']
endp
??0CMyUnknownImp@@QAE@XZ proc near      
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0']
mov ['eax,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?QueryInterface@CInFileStream@@UAGJABU_GUID@@PAPAX@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0Ch']
mov ['[ebp+var_C],', '0CCCCCCCCh']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['eax,', '[ebp+arg_8]']
mov ['dword', 'ptr', '[eax],', '0']
push ['offset', '_IID_IUnknown']
mov ['ecx,', '[ebp+Buf1]']
push ['ecx']
call ['___@8']
test ['eax,', 'eax']
jz ['short', 'loc_15AB']
mov ['edx,', '[ebp+arg_8]']
mov ['eax,', '[ebp+this]']
mov ['[edx],', 'eax']
jmp ['loc_166D']
push ['offset', '_IID_IInStream']
mov ['ecx,', '[ebp+Buf1]']
push ['ecx']
call ['___@8']
test ['eax,', 'eax']
jz ['short', 'loc_15CA']
mov ['edx,', '[ebp+arg_8]']
mov ['eax,', '[ebp+this]']
mov ['[edx],', 'eax']
jmp ['loc_166D']
push ['offset', '_IID_IStreamGetSize']
mov ['ecx,', '[ebp+Buf1]']
push ['ecx']
call ['___@8']
test ['eax,', 'eax']
jz ['short', 'loc_15FE']
cmp ['[ebp+this],', '0']
jz ['short', 'loc_15ED']
mov ['edx,', '[ebp+this]']
add ['edx,', '4']
mov ['[ebp+var_4],', 'edx']
jmp ['short', 'loc_15F4']
mov ['[ebp+var_4],', '0']
mov ['eax,', '[ebp+arg_8]']
mov ['ecx,', '[ebp+var_4]']
mov ['[eax],', 'ecx']
jmp ['short', 'loc_166D']
push ['offset', '_IID_IStreamGetProps']
mov ['edx,', '[ebp+Buf1]']
push ['edx']
call ['___@8']
test ['eax,', 'eax']
jz ['short', 'loc_1632']
cmp ['[ebp+this],', '0']
jz ['short', 'loc_1621']
mov ['eax,', '[ebp+this]']
add ['eax,', '8']
mov ['[ebp+var_8],', 'eax']
jmp ['short', 'loc_1628']
mov ['[ebp+var_8],', '0']
mov ['ecx,', '[ebp+arg_8]']
mov ['edx,', '[ebp+var_8]']
mov ['[ecx],', 'edx']
jmp ['short', 'loc_166D']
push ['offset', '_IID_IStreamGetProps2']
mov ['eax,', '[ebp+Buf1]']
push ['eax']
call ['___@8']
test ['eax,', 'eax']
jz ['short', 'loc_1666']
cmp ['[ebp+this],', '0']
jz ['short', 'loc_1655']
mov ['ecx,', '[ebp+this]']
add ['ecx,', '0Ch']
mov ['[ebp+var_C],', 'ecx']
jmp ['short', 'loc_165C']
mov ['[ebp+var_C],', '0']
mov ['edx,', '[ebp+arg_8]']
mov ['eax,', '[ebp+var_C]']
mov ['[edx],', 'eax']
jmp ['short', 'loc_166D']
mov ['eax,', '80004002h']
jmp ['short', 'loc_167E']
mov ['ecx,', '[ebp+this]']
mov ['edx,', '[ecx+10h]']
add ['edx,', '1']
mov ['eax,', '[ebp+this]']
mov ['[eax+10h],', 'edx']
xor ['eax,', 'eax']
add ['esp,', '0Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['0Ch']
endp
___@8           proc near               
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+Buf2]']
push ['eax']
mov ['ecx,', '[ebp+Buf1]']
push ['ecx']
call ['_IsEqualGUID@8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
_IsEqualGUID@8  proc near               
push ['ebp']
mov ['ebp,', 'esp']
push ['10h']
mov ['eax,', '[ebp+Buf2]']
push ['eax']
mov ['ecx,', '[ebp+Buf1]']
push ['ecx']
call ['_memcmp']
add ['esp,', '0Ch']
neg ['eax']
sbb ['eax,', 'eax']
add ['eax,', '1']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
?AddRef@CInFileStream@@UAGKXZ proc near 
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['eax,', '[ebp+this]']
mov ['ecx,', '[eax+10h]']
add ['ecx,', '1']
mov ['[ebp+var_4],', 'ecx']
mov ['edx,', '[ebp+this]']
mov ['eax,', '[ebp+var_4]']
mov ['[edx+10h],', 'eax']
mov ['eax,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Release@CInFileStream@@UAGKXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '10h']
push ['esi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_C],', 'eax']
mov ['[ebp+var_8],', 'eax']
mov ['[ebp+var_4],', 'eax']
mov ['eax,', '[ebp+this]']
mov ['ecx,', '[eax+10h]']
sub ['ecx,', '1']
mov ['[ebp+var_C],', 'ecx']
mov ['edx,', '[ebp+this]']
mov ['eax,', '[ebp+var_C]']
mov ['[edx+10h],', 'eax']
cmp ['[ebp+var_C],', '0']
jz ['short', 'loc_173B']
mov ['ecx,', '[ebp+this]']
mov ['eax,', '[ecx+10h]']
jmp ['short', 'loc_1773']
mov ['edx,', '[ebp+this]']
mov ['[ebp+var_8],', 'edx']
mov ['eax,', '[ebp+var_8]']
mov ['[ebp+var_4],', 'eax']
cmp ['[ebp+var_4],', '0']
jz ['short', 'loc_176A']
mov ['esi,', 'esp']
push ['1']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
mov ['ecx,', '[ebp+var_4]']
mov ['eax,', '[edx+14h]']
call ['eax']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_10],', 'eax']
jmp ['short', 'loc_1771']
mov ['[ebp+var_10],', '0']
xor ['eax,', 'eax']
pop ['esi']
add ['esp,', '10h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
??_GCInFileStream@@UAEPAXI@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??1CInFileStream@@UAE@XZ']
mov ['eax,', '[ebp+arg_0]']
and ['eax,', '1']
jz ['short', 'loc_17AE']
mov ['ecx,', '[ebp+var_4]']
push ['ecx']
call ['??3@YAXPAX@Z']
add ['esp,', '4']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
??0IInStream@@QAE@XZ proc near          
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0ISequentialInStream@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', 'offset', '??_7IInStream@@6B@']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0IStreamGetSize@@QAE@XZ proc near     
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0IUnknown@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', 'offset', '??_7IStreamGetSize@@6B@']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0IUnknown@@QAE@XZ proc near           
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0IStreamGetProps@@QAE@XZ proc near    
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0IUnknown@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', 'offset', '??_7IStreamGetProps@@6B@']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0IStreamGetProps2@@QAE@XZ proc near   
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0IUnknown@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', 'offset', '??_7IStreamGetProps2@@6B@']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CInFile@NIO@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0CFileBase@NIO@NFile@NWindows@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CFileBase@NIO@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0FFFFFFFFh']
mov ['eax,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0ISequentialInStream@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0IUnknown@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', 'offset', '??_7ISequentialInStream@@6B@']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
__unwindfunclet$??1CInFileStream@@UAE@XZ$0 proc near
mov ['ecx,', '[ebp-10h]']
add ['ecx,', '18h']
jmp ['??1CInFile@NIO@NFile@NWindows@@QAE@XZ']
endp
__ehhandler$??1CInFileStream@@UAE@XZ proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-0Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$??1CInFileStream@@UAE@XZ']
jmp ['___CxxFrameHandler3']
endp
??1CInFile@NIO@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??1CFileBase@NIO@NFile@NWindows@@QAE@XZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CFileBase@NIO@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?Close@CFileBase@NIO@NFile@NWindows@@QAE_NXZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_HRESULT_FROM_WIN32@4 proc near         
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
cmp ['[ebp+arg_0],', '0']
jg ['short', 'loc_1A95']
mov ['eax,', '[ebp+arg_0]']
mov ['[ebp+var_4],', 'eax']
jmp ['short', 'loc_1AAD']
mov ['ecx,', '[ebp+arg_0]']
and ['ecx,', '0FFFFh']
or ['ecx,', '70000h']
or ['ecx,', '80000000h']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?GetFileInformation@CFileBase@NIO@NFile@NWindows@@QBE_NPAU_BY_HANDLE_FILE_INFORMATION@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
push ['esi']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+lpFileInformation]']
push ['eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__GetFileInformationByHandle@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
push ['eax']
call ['?BOOLToBool@@YG_NH@Z']
pop ['esi']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?BOOLToBool@@YG_NH@Z proc near          
push ['ebp']
mov ['ebp,', 'esp']
xor ['eax,', 'eax']
cmp ['[ebp+arg_0],', '0']
setnz ['al']
pop ['ebp']
retn ['4']
endp
??$MyMin@I@@YGIII@Z proc near           
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['eax,', '[ebp+arg_0]']
cmp ['eax,', '[ebp+arg_4]']
jnb ['short', 'loc_1B23']
mov ['ecx,', '[ebp+arg_0]']
mov ['[ebp+var_4],', 'ecx']
jmp ['short', 'loc_1B29']
mov ['edx,', '[ebp+arg_4]']
mov ['[ebp+var_4],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
??$MyMin@_K@@YG_K_K0@Z proc near        
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['eax,', '[ebp+arg_4]']
cmp ['eax,', '[ebp+arg_C]']
ja ['short', 'loc_1B68']
jb ['short', 'loc_1B5A']
mov ['ecx,', '[ebp+arg_0]']
cmp ['ecx,', '[ebp+arg_8]']
jnb ['short', 'loc_1B68']
mov ['edx,', '[ebp+arg_0]']
mov ['[ebp+var_8],', 'edx']
mov ['eax,', '[ebp+arg_4]']
mov ['[ebp+var_4],', 'eax']
jmp ['short', 'loc_1B74']
mov ['ecx,', '[ebp+arg_8]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+arg_C]']
mov ['[ebp+var_4],', 'edx']
mov ['eax,', '[ebp+var_8]']
mov ['edx,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['10h']
endp
?AddRef@CInFileStream@@WM@AGKXZ proc near 
sub ['[esp+arg_0],', '0Ch']
jmp ['?AddRef@CInFileStream@@UAGKXZ']
endp
?QueryInterface@CInFileStream@@W3AGJABU_GUID@@PAPAX@Z proc near
sub ['[esp+arg_0],', '4']
jmp ['?QueryInterface@CInFileStream@@UAGJABU_GUID@@PAPAX@Z']
endp
?QueryInterface@CInFileStream@@W7AGJABU_GUID@@PAPAX@Z proc near
sub ['[esp+arg_0],', '8']
jmp ['?QueryInterface@CInFileStream@@UAGJABU_GUID@@PAPAX@Z']
endp
?QueryInterface@CInFileStream@@WM@AGJABU_GUID@@PAPAX@Z proc near
sub ['[esp+arg_0],', '0Ch']
jmp ['?QueryInterface@CInFileStream@@UAGJABU_GUID@@PAPAX@Z']
endp
?Release@CInFileStream@@W3AGKXZ proc near 
sub ['[esp+arg_0],', '4']
jmp ['?Release@CInFileStream@@UAGKXZ']
endp
?Release@CInFileStream@@W7AGKXZ proc near 
sub ['[esp+arg_0],', '8']
jmp ['?Release@CInFileStream@@UAGKXZ']
endp
?AddRef@CInFileStream@@W3AGKXZ proc near 
sub ['[esp+arg_0],', '4']
jmp ['?AddRef@CInFileStream@@UAGKXZ']
endp
?Release@CInFileStream@@WM@AGKXZ proc near 
sub ['[esp+arg_0],', '0Ch']
jmp ['?Release@CInFileStream@@UAGKXZ']
endp
?AddRef@CInFileStream@@W7AGKXZ proc near 
sub ['[esp+arg_0],', '8']
jmp ['?AddRef@CInFileStream@@UAGKXZ']
endp
