?IsDots@CFileInfo@NFind@NFile@NWindows@@QBE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?IsDir@CFileInfoBase@NFind@NFile@NWindows@@QBE_NXZ']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jz ['short', 'loc_64']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '28h']
call ['?IsEmpty@UString@@QBE_NXZ']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_68']
xor ['al,', 'al']
jmp ['short', 'loc_C6']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '28h']
call ['??BUString@@QBEPB_WXZ']
movzx ['edx,', 'word', 'ptr', '[eax]']
cmp ['edx,', '2Eh']
jz ['short', 'loc_7F']
xor ['al,', 'al']
jmp ['short', 'loc_C6']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '28h']
call ['?Len@UString@@QBEIXZ']
cmp ['eax,', '1']
jz ['short', 'loc_BC']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '28h']
call ['?Len@UString@@QBEIXZ']
cmp ['eax,', '2']
jnz ['short', 'loc_B3']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '28h']
call ['??BUString@@QBEPB_WXZ']
movzx ['eax,', 'word', 'ptr', '[eax+2]']
cmp ['eax,', '2Eh']
jz ['short', 'loc_BC']
mov ['[ebp+var_8],', '0']
jmp ['short', 'loc_C3']
mov ['[ebp+var_8],', '1']
mov ['al,', 'byte', 'ptr', '[ebp+var_8]']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?Close@CFindFileBase@NFind@NFile@NWindows@@QAE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
push ['esi']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax],', '0FFFFFFFFh']
jnz ['short', 'loc_F7']
mov ['al,', '1']
jmp ['short', 'loc_11F']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__FindClose@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jnz ['short', 'loc_114']
xor ['al,', 'al']
jmp ['short', 'loc_11F']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0FFFFFFFFh']
mov ['al,', '1']
pop ['esi']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?FindFirst@CFindFile@NFind@NFile@NWindows@@QAE_NPB_WAAUCFileInfo@234@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?FindFirst@CFindFile@NFind@NFile@NWindows@@QAE_NPB_WAAUCFileInfo@234@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '3BCh']
push ['esi']
push ['edi']
push ['ecx']
lea ['edi,', '[ebp+var_3C8]']
mov ['ecx,', '0EFh']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
pop ['ecx']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_10],', 'eax']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_14],', 'ecx']
mov ['ecx,', '[ebp+var_14]']
call ['?Close@CFindFileBase@NFind@NFile@NWindows@@QAE_NXZ']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_196']
xor ['al,', 'al']
jmp ['loc_262']
movzx ['ecx,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['ecx,', 'ecx']
jnz ['loc_225']
mov ['esi,', 'esp']
lea ['edx,', '[ebp+FindFileData]']
push ['edx']
mov ['eax,', '[ebp+lpFileName]']
push ['eax']
lea ['ecx,', '[ebp+var_3C0]']
push ['ecx']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_3C4],', 'eax']
mov ['edx,', '[ebp+var_3C4]']
mov ['[ebp+var_3C8],', 'edx']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_3C8]']
call ['??BAString@@QBEPBDXZ']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__FindFirstFileA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['ecx,', '[ebp+var_14]']
mov ['[ecx],', 'eax']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_3C0]']
call ['??1AString@@QAE@XZ']
mov ['edx,', '[ebp+var_14]']
cmp ['dword', 'ptr', '[edx],', '0FFFFFFFFh']
jnz ['short', 'loc_213']
xor ['al,', 'al']
jmp ['short', 'loc_262']
mov ['eax,', '[ebp+arg_4]']
push ['eax']
lea ['ecx,', '[ebp+FindFileData]']
push ['ecx']
call ['?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAA@@AAUCFileInfo@123@@Z']
jmp ['short', 'loc_260']
mov ['esi,', 'esp']
lea ['edx,', '[ebp+var_3C0.ftLastAccessTime.dwHighDateTime]']
push ['edx']
mov ['eax,', '[ebp+lpFileName]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__FindFirstFileW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['ecx,', '[ebp+var_14]']
mov ['[ecx],', 'eax']
mov ['edx,', '[ebp+var_14]']
cmp ['dword', 'ptr', '[edx],', '0FFFFFFFFh']
jnz ['short', 'loc_250']
xor ['al,', 'al']
jmp ['short', 'loc_262']
mov ['eax,', '[ebp+arg_4]']
push ['eax']
lea ['ecx,', '[ebp+var_3C0.ftLastAccessTime.dwHighDateTime]']
push ['ecx']
call ['?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAW@@AAUCFileInfo@123@@Z']
mov ['al,', '1']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN13']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_10]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '3C8h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAW@@AAUCFileInfo@123@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['esi']
mov ['eax,', '[ebp+arg_4]']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['[eax+20h],', 'edx']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax+4]']
mov ['edx,', '[eax+8]']
mov ['eax,', '[ebp+arg_4]']
mov ['[eax+8],', 'ecx']
mov ['[eax+0Ch],', 'edx']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx+0Ch]']
mov ['eax,', '[ecx+10h]']
mov ['ecx,', '[ebp+arg_4]']
mov ['[ecx+10h],', 'edx']
mov ['[ecx+14h],', 'eax']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx+14h]']
mov ['ecx,', '[edx+18h]']
mov ['edx,', '[ebp+arg_4]']
mov ['[edx+18h],', 'eax']
mov ['[edx+1Ch],', 'ecx']
mov ['eax,', '[ebp+arg_0]']
mov ['eax,', '[eax+1Ch]']
xor ['edx,', 'edx']
mov ['cl,', '20h']
call ['__allshl']
mov ['ecx,', '[ebp+arg_0]']
mov ['ecx,', '[ecx+20h]']
xor ['esi,', 'esi']
add ['eax,', 'ecx']
adc ['edx,', 'esi']
mov ['ecx,', '[ebp+arg_4]']
mov ['[ecx],', 'eax']
mov ['[ecx+4],', 'edx']
mov ['edx,', '[ebp+arg_4]']
mov ['byte', 'ptr', '[edx+24h],', '0']
mov ['eax,', '[ebp+arg_4]']
mov ['byte', 'ptr', '[eax+25h],', '0']
mov ['ecx,', '[ebp+arg_0]']
add ['ecx,', '2Ch']
push ['ecx']
mov ['ecx,', '[ebp+arg_4]']
add ['ecx,', '28h']
call ['??4UString@@QAEAAV0@PB_W@Z']
pop ['esi']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAA@@AAUCFileInfo@123@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAA@@AAUCFileInfo@123@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '20h']
push ['esi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_2C],', 'eax']
mov ['[ebp+var_28],', 'eax']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+var_1C],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['eax,', '[ebp+arg_4]']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['[eax+20h],', 'edx']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax+4]']
mov ['edx,', '[eax+8]']
mov ['eax,', '[ebp+arg_4]']
mov ['[eax+8],', 'ecx']
mov ['[eax+0Ch],', 'edx']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx+0Ch]']
mov ['eax,', '[ecx+10h]']
mov ['ecx,', '[ebp+arg_4]']
mov ['[ecx+10h],', 'edx']
mov ['[ecx+14h],', 'eax']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx+14h]']
mov ['ecx,', '[edx+18h]']
mov ['edx,', '[ebp+arg_4]']
mov ['[edx+18h],', 'eax']
mov ['[edx+1Ch],', 'ecx']
mov ['eax,', '[ebp+arg_0]']
mov ['eax,', '[eax+1Ch]']
xor ['edx,', 'edx']
mov ['cl,', '20h']
call ['__allshl']
mov ['ecx,', '[ebp+arg_0]']
mov ['ecx,', '[ecx+20h]']
xor ['esi,', 'esi']
add ['eax,', 'ecx']
adc ['edx,', 'esi']
mov ['ecx,', '[ebp+arg_4]']
mov ['[ecx],', 'eax']
mov ['[ecx+4],', 'edx']
mov ['edx,', '[ebp+arg_4]']
mov ['byte', 'ptr', '[edx+24h],', '0']
mov ['eax,', '[ebp+arg_4]']
mov ['byte', 'ptr', '[eax+25h],', '0']
mov ['ecx,', '[ebp+arg_0]']
add ['ecx,', '2Ch']
push ['ecx']
lea ['ecx,', '[ebp+var_18]']
call ['??0AString@@QAE@PBD@Z']
mov ['[ebp+var_4],', '0']
lea ['edx,', '[ebp+var_18]']
push ['edx']
lea ['eax,', '[ebp+var_24]']
push ['eax']
call ['?fas2fs@@YG?AVUString@@ABVAString@@@Z']
mov ['[ebp+var_28],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['[ebp+var_2C],', 'ecx']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
mov ['edx,', '[ebp+var_2C]']
push ['edx']
mov ['ecx,', '[ebp+arg_4]']
add ['ecx,', '28h']
call ['??4UString@@QAEAAV0@ABV0@@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_24]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_18]']
call ['??1AString@@QAE@XZ']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['esi']
add ['esp,', '2Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?FindNext@CFindFile@NFind@NFile@NWindows@@QAE_NAAUCFileInfo@234@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '3A8h']
push ['esi']
push ['edi']
push ['ecx']
lea ['edi,', '[ebp+var_3A8]']
mov ['ecx,', '0EAh']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
pop ['ecx']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_4],', 'eax']
mov ['[ebp+var_8],', 'ecx']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_509']
mov ['esi,', 'esp']
lea ['ecx,', '[ebp+FindFileData]']
push ['ecx']
mov ['edx,', '[ebp+var_8]']
mov ['eax,', '[edx]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__FindNextFileA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jnz ['short', 'loc_4F7']
xor ['al,', 'al']
jmp ['short', 'loc_53F']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
lea ['edx,', '[ebp+FindFileData]']
push ['edx']
call ['?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAA@@AAUCFileInfo@123@@Z']
jmp ['short', 'loc_53D']
mov ['esi,', 'esp']
lea ['eax,', '[ebp+var_3A4]']
push ['eax']
mov ['ecx,', '[ebp+var_8]']
mov ['edx,', '[ecx]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__FindNextFileW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jnz ['short', 'loc_52D']
xor ['al,', 'al']
jmp ['short', 'loc_53F']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
lea ['ecx,', '[ebp+var_3A4]']
push ['ecx']
call ['?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAW@@AAUCFileInfo@123@@Z']
mov ['al,', '1']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN10_0']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_4]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '3A8h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?IsMainStream@CStreamInfo@NFind@NFile@NWindows@@QBE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
push ['offset', '$SG67970']
mov ['ecx,', '[ebp+var_4]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?StringsAreEqualNoCase_Ascii@@YG_NPB_WPBD@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?GetReducedName@CStreamInfo@NFind@NFile@NWindows@@QBE?AVUString@@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?GetReducedName@CStreamInfo@NFind@NFile@NWindows@@QBE?AVUString@@XZ']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '1Ch']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_28],', 'eax']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+var_1C],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_10],', 'ecx']
mov ['[ebp+var_28],', '0']
mov ['eax,', '[ebp+var_10]']
push ['eax']
lea ['ecx,', '[ebp+var_20]']
call ['??0UString@@QAE@ABV0@@Z']
mov ['[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_20]']
call ['?Len@UString@@QBEIXZ']
cmp ['eax,', '7']
jbe ['short', 'loc_665']
push ['offset', '$SG67977']
push ['6']
lea ['ecx,', '[ebp+var_20]']
call ['?RightPtr@UString@@QBEPB_WI@Z']
push ['eax']
call ['?StringsAreEqualNoCase_Ascii@@YG_NPB_WPBD@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_665']
lea ['ecx,', '[ebp+var_20]']
call ['?Len@UString@@QBEIXZ']
sub ['eax,', '6']
push ['eax']
lea ['ecx,', '[ebp+var_20]']
call ['?DeleteFrom@UString@@QAEXI@Z']
lea ['edx,', '[ebp+var_20]']
push ['edx']
mov ['ecx,', '[ebp+arg_0]']
call ['??0UString@@QAE@ABV0@@Z']
mov ['eax,', '[ebp+var_28]']
or ['eax,', '1']
mov ['[ebp+var_28],', 'eax']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_20]']
call ['??1UString@@QAE@XZ']
mov ['eax,', '[ebp+arg_0]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN10_1']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
add ['esp,', '28h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?FindFirst@CFindStream@NFind@NFile@NWindows@@QAE_NPB_WAAUCStreamInfo@234@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '268h']
push ['esi']
push ['edi']
push ['ecx']
lea ['edi,', '[ebp+var_268]']
mov ['ecx,', '9Ah']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
pop ['ecx']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_4],', 'eax']
mov ['[ebp+var_8],', 'ecx']
mov ['ecx,', '[ebp+var_8]']
call ['?Close@CFindFileBase@NFind@NFile@NWindows@@QAE_NXZ']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_71E']
xor ['al,', 'al']
jmp ['loc_7AE']
cmp ['ds:_g_FindFirstStreamW,', '0']
jnz ['short', 'loc_73C']
mov ['esi,', 'esp']
push ['78h']
call ['dword', 'ptr', 'ds:__imp__SetLastError@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['al,', 'al']
jmp ['short', 'loc_7AE']
mov ['esi,', 'esp']
push ['0']
call ['dword', 'ptr', 'ds:__imp__SetLastError@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['0']
lea ['ecx,', '[ebp+var_264]']
push ['ecx']
push ['0']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
call ['ds:_g_FindFirstStreamW']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['ecx,', '[ebp+var_8]']
mov ['[ecx],', 'eax']
mov ['edx,', '[ebp+var_8]']
cmp ['dword', 'ptr', '[edx],', '0FFFFFFFFh']
jnz ['short', 'loc_790']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
cmp ['eax,', '26h']
jnz ['short', 'loc_790']
xor ['al,', 'al']
jmp ['short', 'loc_7AE']
mov ['eax,', '[ebp+var_8]']
cmp ['dword', 'ptr', '[eax],', '0FFFFFFFFh']
jnz ['short', 'loc_79C']
xor ['al,', 'al']
jmp ['short', 'loc_7AE']
mov ['ecx,', '[ebp+arg_4]']
push ['ecx']
lea ['edx,', '[ebp+var_264]']
push ['edx']
call ['?Convert_WIN32_FIND_STREAM_DATA_to_StreamInfo@NFind@NFile@NWindows@@YGXABUMY_WIN32_FIND_STREAM_DATA@@AAUCStreamInfo@123@@Z']
mov ['al,', '1']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN10_2']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_4]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '268h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?Convert_WIN32_FIND_STREAM_DATA_to_StreamInfo@NFind@NFile@NWindows@@YGXABUMY_WIN32_FIND_STREAM_DATA@@AAUCStreamInfo@123@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+arg_4]']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['[eax+10h],', 'edx']
mov ['ecx,', '[ecx+4]']
mov ['[eax+14h],', 'ecx']
mov ['edx,', '[ebp+arg_0]']
add ['edx,', '8']
push ['edx']
mov ['ecx,', '[ebp+arg_4]']
call ['??4UString@@QAEAAV0@PB_W@Z']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
?FindNext@CFindStream@NFind@NFile@NWindows@@QAE_NAAUCStreamInfo@234@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '268h']
push ['esi']
push ['edi']
push ['ecx']
lea ['edi,', '[ebp+var_268]']
mov ['ecx,', '9Ah']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
pop ['ecx']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_4],', 'eax']
mov ['[ebp+var_8],', 'ecx']
cmp ['ds:_g_FindNextStreamW,', '0']
jnz ['short', 'loc_876']
mov ['esi,', 'esp']
push ['78h']
call ['dword', 'ptr', 'ds:__imp__SetLastError@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['al,', 'al']
jmp ['short', 'loc_8AC']
mov ['esi,', 'esp']
lea ['eax,', '[ebp+var_264]']
push ['eax']
mov ['ecx,', '[ebp+var_8]']
mov ['edx,', '[ecx]']
push ['edx']
call ['ds:_g_FindNextStreamW']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jnz ['short', 'loc_89A']
xor ['al,', 'al']
jmp ['short', 'loc_8AC']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
lea ['ecx,', '[ebp+var_264]']
push ['ecx']
call ['?Convert_WIN32_FIND_STREAM_DATA_to_StreamInfo@NFind@NFile@NWindows@@YGXABUMY_WIN32_FIND_STREAM_DATA@@AAUCStreamInfo@123@@Z']
mov ['al,', '1']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN7_1']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_4]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '268h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Next@CStreamEnumerator@NFind@NFile@NWindows@@QAE_NAAUCStreamInfo@234@AA_N@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
push ['esi']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?IsHandleAllocated@CFindFileBase@NFind@NFile@NWindows@@QBE_NXZ']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jz ['short', 'loc_934']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?FindNext@CFindStream@NFind@NFile@NWindows@@QAE_NAAUCStreamInfo@234@@Z']
mov ['byte', 'ptr', '[ebp+var_8+3],', 'al']
jmp ['short', 'loc_94F']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '4']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
mov ['ecx,', '[ebp+var_4]']
call ['?FindFirst@CFindStream@NFind@NFile@NWindows@@QAE_NPB_WAAUCStreamInfo@234@@Z']
mov ['byte', 'ptr', '[ebp+var_8+3],', 'al']
movzx ['eax,', 'byte', 'ptr', '[ebp+var_8+3]']
test ['eax,', 'eax']
jz ['short', 'loc_961']
mov ['ecx,', '[ebp+arg_4]']
mov ['byte', 'ptr', '[ecx],', '1']
mov ['al,', '1']
jmp ['short', 'loc_980']
mov ['edx,', '[ebp+arg_4]']
mov ['byte', 'ptr', '[edx],', '0']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['ecx,', 'ecx']
cmp ['eax,', '26h']
setz ['cl']
mov ['al,', 'cl']
pop ['esi']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?ClearBase@CFileInfoBase@NFind@NFile@NWindows@@QAEXXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0']
mov ['dword', 'ptr', '[eax+4],', '0']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+0Ch],', '0']
mov ['edx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[edx+8],', '0']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+14h],', '0']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+10h],', '0']
mov ['edx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[edx+1Ch],', '0']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+18h],', '0']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+20h],', '0']
mov ['edx,', '[ebp+var_4]']
mov ['byte', 'ptr', '[edx+24h],', '0']
mov ['eax,', '[ebp+var_4]']
mov ['byte', 'ptr', '[eax+25h],', '0']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?GetFileAttrib@NFind@NFile@NWindows@@YGKPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?GetFileAttrib@NFind@NFile@NWindows@@YGKPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '1Ch']
push ['esi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_28],', 'eax']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+var_1C],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_AB5']
mov ['ecx,', '[ebp+lpFileName]']
push ['ecx']
lea ['edx,', '[ebp+var_20]']
push ['edx']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_24],', 'eax']
mov ['eax,', '[ebp+var_24]']
mov ['[ebp+var_28],', 'eax']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_28]']
call ['??BAString@@QBEPBDXZ']
mov ['esi,', 'esp']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__GetFileAttributesA@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_20]']
call ['??1AString@@QAE@XZ']
mov ['eax,', '[ebp+var_14]']
jmp ['short', 'loc_AD9']
jmp ['short', 'loc_AD9']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+lpFileName]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__GetFileAttributesW@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_10],', 'eax']
cmp ['[ebp+var_10],', '0FFFFFFFFh']
jz ['short', 'loc_AD6']
mov ['eax,', '[ebp+var_10]']
jmp ['short', 'loc_AD9']
or ['eax,', '0FFFFFFFFh']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['esi']
add ['esp,', '28h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '120h']
push ['esi']
push ['edi']
push ['ecx']
lea ['edi,', '[ebp+var_12C]']
mov ['ecx,', '48h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
pop ['ecx']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_10],', 'eax']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_14],', 'ecx']
mov ['eax,', '[ebp+lpFileName]']
push ['eax']
call ['?IsDevicePath@NName@NFile@NWindows@@YG_NPB_W@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['loc_C61']
mov ['ecx,', '[ebp+var_14]']
call ['?ClearBase@CFileInfoBase@NFind@NFile@NWindows@@QAEXXZ']
mov ['edx,', '[ebp+lpFileName]']
add ['edx,', '8']
push ['edx']
mov ['ecx,', '[ebp+var_14]']
add ['ecx,', '28h']
call ['??4UString@@QAEAAV0@PB_W@Z']
mov ['eax,', '[ebp+var_14]']
mov ['byte', 'ptr', '[eax+25h],', '1']
mov ['ecx,', '[ebp+lpFileName]']
add ['ecx,', '8']
push ['ecx']
call ['?IsDrivePath2@NName@NFile@NWindows@@YG_NPB_W@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jz ['short', 'loc_BE7']
mov ['eax,', '[ebp+lpFileName]']
movzx ['ecx,', 'word', 'ptr', '[eax+0Ch]']
test ['ecx,', 'ecx']
jnz ['short', 'loc_BE7']
mov ['edx,', '[ebp+lpFileName]']
mov ['ax,', '[edx+8]']
mov ['[ebp+var_20],', 'ax']
mov ['ecx,', '3Ah']
mov ['[ebp+var_1E],', 'cx']
mov ['edx,', '5Ch']
mov ['[ebp+var_1C],', 'dx']
xor ['eax,', 'eax']
mov ['[ebp+var_1A],', 'ax']
lea ['ecx,', '[ebp+var_50]']
push ['ecx']
lea ['edx,', '[ebp+var_40]']
push ['edx']
lea ['eax,', '[ebp+var_30]']
push ['eax']
lea ['ecx,', '[ebp+var_20]']
push ['ecx']
call ['?MyGetDiskFreeSpace@NSystem@NFile@NWindows@@YG_NPB_WAA_K11@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jz ['short', 'loc_BE7']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', 'dword', 'ptr', '[ebp+var_40]']
mov ['[eax],', 'ecx']
mov ['edx,', 'dword', 'ptr', '[ebp+var_40+4]']
mov ['[eax+4],', 'edx']
mov ['al,', '1']
jmp ['loc_1393']
lea ['ecx,', '[ebp+var_68]']
call ['??0CInFile@NIO@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '0']
mov ['eax,', '[ebp+lpFileName]']
push ['eax']
lea ['ecx,', '[ebp+var_68]']
call ['?Open@CInFile@NIO@NFile@NWindows@@QAE_NPB_W@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jnz ['short', 'loc_C2A']
mov ['[ebp+var_121],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_68]']
call ['??1CInFile@NIO@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_121]']
jmp ['loc_1393']
movzx ['edx,', '[ebp+var_63]']
test ['edx,', 'edx']
jz ['short', 'loc_C40']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_60]']
mov ['[eax],', 'ecx']
mov ['edx,', '[ebp+var_5C]']
mov ['[eax+4],', 'edx']
mov ['[ebp+var_122],', '1']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_68]']
call ['??1CInFile@NIO@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_122]']
jmp ['loc_1393']
mov ['eax,', '[ebp+lpFileName]']
push ['eax']
call ['?FindAltStreamColon@NName@NFile@NWindows@@YGHPB_W@Z']
mov ['[ebp+var_70],', 'eax']
cmp ['[ebp+var_70],', '0']
jl ['loc_FBD']
mov ['ecx,', '[ebp+var_70]']
mov ['edx,', '[ebp+lpFileName]']
movzx ['eax,', 'word', 'ptr', '[edx+ecx*2+2]']
test ['eax,', 'eax']
jz ['loc_FBD']
mov ['ecx,', '[ebp+var_70]']
mov ['edx,', '[ebp+lpFileName]']
lea ['eax,', '[edx+ecx*2]']
push ['eax']
lea ['ecx,', '[ebp+var_80]']
call ['??0UString@@QAE@PB_W@Z']
mov ['[ebp+var_4],', '1']
mov ['ecx,', '[ebp+lpFileName]']
push ['ecx']
lea ['ecx,', '[ebp+var_94]']
call ['??0UString@@QAE@PB_W@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '2']
mov ['edx,', '[ebp+var_70]']
push ['edx']
lea ['ecx,', '[ebp+var_94]']
call ['?DeleteFrom@UString@@QAEXI@Z']
mov ['[ebp+var_9C],', '6']
lea ['ecx,', '[ebp+var_80]']
call ['?Len@UString@@QBEIXZ']
cmp ['eax,', '6']
jbe ['short', 'loc_CF8']
push ['offset', '$SG68052']
push ['6']
lea ['ecx,', '[ebp+var_80]']
call ['?RightPtr@UString@@QBEPB_WI@Z']
push ['eax']
call ['?StringsAreEqualNoCase_Ascii@@YG_NPB_WPBD@Z']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_D05']
push ['offset', '$SG68053']
lea ['ecx,', '[ebp+var_80]']
call ['??YUString@@QAEAAV0@PB_W@Z']
mov ['[ebp+var_9D],', '1']
lea ['ecx,', '[ebp+var_94]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['?IsDrivePath2@NName@NFile@NWindows@@YG_NPB_W@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_D71']
cmp ['[ebp+var_70],', '2']
jz ['short', 'loc_D44']
cmp ['[ebp+var_70],', '3']
jnz ['short', 'loc_D71']
lea ['ecx,', '[ebp+var_94]']
call ['??BUString@@QBEPB_WXZ']
movzx ['edx,', 'word', 'ptr', '[eax+4]']
cmp ['edx,', '5Ch']
jnz ['short', 'loc_D71']
mov ['ecx,', '[ebp+var_14]']
call ['?ClearBase@CFileInfoBase@NFind@NFile@NWindows@@QAEXXZ']
mov ['ecx,', '[ebp+var_14]']
add ['ecx,', '28h']
call ['?Empty@UString@@QAEXXZ']
cmp ['[ebp+var_70],', '2']
jnz ['short', 'loc_D6F']
lea ['eax,', '[ebp+var_94]']
push ['eax']
mov ['ecx,', '[ebp+var_14]']
add ['ecx,', '28h']
call ['??4UString@@QAEAAV0@ABV0@@Z']
jmp ['short', 'loc_D8B']
lea ['ecx,', '[ebp+var_94]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
mov ['ecx,', '[ebp+var_14]']
call ['?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z']
mov ['[ebp+var_9D],', 'al']
movzx ['ecx,', '[ebp+var_9D]']
test ['ecx,', 'ecx']
jz ['loc_F9F']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[edx+20h]']
and ['eax,', '0FFFFFBEFh']
mov ['ecx,', '[ebp+var_14]']
mov ['[ecx+20h],', 'eax']
mov ['edx,', '[ebp+var_14]']
mov ['dword', 'ptr', '[edx],', '0']
mov ['dword', 'ptr', '[edx+4],', '0']
lea ['eax,', '[ebp+var_94]']
push ['eax']
lea ['ecx,', '[ebp+var_B4]']
call ['??0CStreamEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '3']
lea ['ecx,', '[ebp+var_D4]']
call ['??0CStreamInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '4']
lea ['ecx,', '[ebp+var_DD]']
push ['ecx']
lea ['edx,', '[ebp+var_D4]']
push ['edx']
lea ['ecx,', '[ebp+var_B4]']
call ['?Next@CStreamEnumerator@NFind@NFile@NWindows@@QAE_NAAUCStreamInfo@234@AA_N@Z']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_E4E']
mov ['[ebp+var_123],', '0']
mov ['byte', 'ptr', '[ebp+var_4],', '3']
lea ['ecx,', '[ebp+var_D4]']
call ['??1CStreamInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '2']
lea ['ecx,', '[ebp+var_B4]']
call ['??1CStreamEnumerator@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_94]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_80]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_123]']
jmp ['loc_1393']
movzx ['ecx,', '[ebp+var_DD]']
test ['ecx,', 'ecx']
jnz ['short', 'loc_EB8']
mov ['esi,', 'esp']
push ['2']
call ['dword', 'ptr', 'ds:__imp__SetLastError@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_124],', '0']
mov ['byte', 'ptr', '[ebp+var_4],', '3']
lea ['ecx,', '[ebp+var_D4]']
call ['??1CStreamInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '2']
lea ['ecx,', '[ebp+var_B4]']
call ['??1CStreamEnumerator@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_94]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_80]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_124]']
jmp ['loc_1393']
lea ['ecx,', '[ebp+var_80]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
lea ['ecx,', '[ebp+var_D4]']
call ['?IsEqualTo_NoCase@UString@@QBE_NPB_W@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jz ['loc_F7C']
lea ['ecx,', '[ebp+var_D4]']
call ['?Len@UString@@QBEIXZ']
cmp ['eax,', '7']
jbe ['short', 'loc_F01']
lea ['ecx,', '[ebp+var_D4]']
call ['?Len@UString@@QBEIXZ']
sub ['eax,', '6']
push ['eax']
lea ['ecx,', '[ebp+var_D4]']
call ['?DeleteFrom@UString@@QAEXI@Z']
lea ['eax,', '[ebp+var_D4]']
push ['eax']
mov ['ecx,', '[ebp+var_14]']
add ['ecx,', '28h']
call ['??YUString@@QAEAAV0@ABV0@@Z']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ebp+var_C4]']
mov ['[ecx],', 'edx']
mov ['eax,', '[ebp+var_C0]']
mov ['[ecx+4],', 'eax']
mov ['ecx,', '[ebp+var_14]']
mov ['byte', 'ptr', '[ecx+24h],', '1']
mov ['[ebp+var_125],', '1']
mov ['byte', 'ptr', '[ebp+var_4],', '3']
lea ['ecx,', '[ebp+var_D4]']
call ['??1CStreamInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '2']
lea ['ecx,', '[ebp+var_B4]']
call ['??1CStreamEnumerator@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_94]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_80]']
call ['??1UString@@QAE@XZ']
mov ['al,', '[ebp+var_125]']
jmp ['loc_1393']
mov ['byte', 'ptr', '[ebp+var_4],', '3']
lea ['ecx,', '[ebp+var_D4]']
call ['??1CStreamInfo@NFind@NFile@NWindows@@QAE@XZ']
jmp ['loc_DD1']
mov ['byte', 'ptr', '[ebp+var_4],', '2']
lea ['ecx,', '[ebp+var_B4]']
call ['??1CStreamEnumerator@NFind@NFile@NWindows@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_94]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_80]']
call ['??1UString@@QAE@XZ']
lea ['ecx,', '[ebp+var_EC]']
call ['??0CFindFile@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '5']
mov ['edx,', '[ebp+var_14]']
push ['edx']
mov ['eax,', '[ebp+lpFileName]']
push ['eax']
lea ['ecx,', '[ebp+var_EC]']
call ['?FindFirst@CFindFile@NFind@NFile@NWindows@@QAE_NPB_WAAUCFileInfo@234@@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_100D']
mov ['[ebp+var_126],', '1']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_EC]']
call ['??1CFindFile@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_126]']
jmp ['loc_1393']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+dwErrCode],', 'eax']
cmp ['[ebp+dwErrCode],', '35h']
jz ['short', 'loc_1041']
cmp ['[ebp+dwErrCode],', '2']
jz ['short', 'loc_1041']
cmp ['[ebp+dwErrCode],', '7Bh']
jnz ['loc_1374']
mov ['[ebp+var_F8],', '0']
mov ['edx,', '[ebp+lpFileName]']
push ['edx']
call ['?IsSuperPath@NName@NFile@NWindows@@YG_NPB_W@Z']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jz ['short', 'loc_1065']
mov ['[ebp+var_F8],', '4']
mov ['ecx,', '[ebp+lpFileName]']
movzx ['edx,', 'word', 'ptr', '[ecx]']
cmp ['edx,', '5Ch']
jz ['short', 'loc_107B']
mov ['eax,', '[ebp+lpFileName]']
movzx ['ecx,', 'word', 'ptr', '[eax]']
cmp ['ecx,', '2Fh']
jnz ['short', 'loc_10F1']
mov ['edx,', '[ebp+lpFileName]']
movzx ['eax,', 'word', 'ptr', '[edx+2]']
test ['eax,', 'eax']
jnz ['short', 'loc_10F1']
mov ['ecx,', '[ebp+lpFileName]']
push ['ecx']
call ['?GetFileAttrib@NFind@NFile@NWindows@@YGKPB_W@Z']
mov ['[ebp+var_FC],', 'eax']
cmp ['[ebp+var_FC],', '0FFFFFFFFh']
jz ['short', 'loc_10EC']
mov ['edx,', '[ebp+var_FC]']
and ['edx,', '10h']
jz ['short', 'loc_10EC']
mov ['ecx,', '[ebp+var_14]']
call ['?ClearBase@CFileInfoBase@NFind@NFile@NWindows@@QAEXXZ']
mov ['ecx,', '[ebp+var_14]']
add ['ecx,', '28h']
call ['?Empty@UString@@QAEXXZ']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_FC]']
mov ['[eax+20h],', 'ecx']
mov ['[ebp+var_127],', '1']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_EC]']
call ['??1CFindFile@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_127]']
jmp ['loc_1393']
jmp ['loc_1374']
mov ['edx,', '[ebp+var_F8]']
mov ['eax,', '[ebp+lpFileName]']
lea ['ecx,', '[eax+edx*2]']
push ['ecx']
call ['?IsDrivePath@NName@NFile@NWindows@@YG_NPB_W@Z']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jz ['loc_11A9']
mov ['eax,', '[ebp+var_F8]']
mov ['ecx,', '[ebp+lpFileName]']
movzx ['edx,', 'word', 'ptr', '[ecx+eax*2+6]']
test ['edx,', 'edx']
jnz ['loc_11A9']
mov ['eax,', '[ebp+lpFileName]']
push ['eax']
call ['?GetFileAttrib@NFind@NFile@NWindows@@YGKPB_W@Z']
mov ['[ebp+var_100],', 'eax']
cmp ['[ebp+var_100],', '0FFFFFFFFh']
jz ['short', 'loc_11A4']
mov ['ecx,', '[ebp+var_100]']
and ['ecx,', '10h']
jz ['short', 'loc_11A4']
mov ['ecx,', '[ebp+var_14]']
call ['?ClearBase@CFileInfoBase@NFind@NFile@NWindows@@QAEXXZ']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[ebp+var_100]']
mov ['[edx+20h],', 'eax']
mov ['ecx,', '[ebp+var_F8]']
mov ['edx,', '[ebp+lpFileName]']
lea ['eax,', '[edx+ecx*2]']
push ['eax']
mov ['ecx,', '[ebp+var_14]']
add ['ecx,', '28h']
call ['??4UString@@QAEAAV0@PB_W@Z']
push ['2']
mov ['ecx,', '[ebp+var_14]']
add ['ecx,', '28h']
call ['?DeleteFrom@UString@@QAEXI@Z']
mov ['[ebp+var_128],', '1']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_EC]']
call ['??1CFindFile@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_128]']
jmp ['loc_1393']
jmp ['loc_1374']
mov ['ecx,', '[ebp+lpFileName]']
push ['ecx']
call ['?GetNetworkServerPrefixSize@NName@NFile@NWindows@@YGIPB_W@Z']
mov ['[ebp+var_104],', 'eax']
cmp ['[ebp+var_104],', '0']
jbe ['loc_1374']
mov ['edx,', '[ebp+var_104]']
mov ['eax,', '[ebp+lpFileName]']
movzx ['ecx,', 'word', 'ptr', '[eax+edx*2]']
test ['ecx,', 'ecx']
jz ['loc_1374']
mov ['edx,', '[ebp+var_104]']
mov ['eax,', '[ebp+lpFileName]']
lea ['ecx,', '[eax+edx*2]']
push ['ecx']
call ['?FindSepar@NName@NFile@NWindows@@YGHPB_W@Z']
test ['eax,', 'eax']
jge ['loc_1374']
mov ['edx,', '[ebp+lpFileName]']
push ['edx']
lea ['ecx,', '[ebp+var_114]']
call ['??0UString@@QAE@PB_W@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '6']
lea ['ecx,', '[ebp+var_114]']
call ['?Add_PathSepar@UString@@QAEXXZ']
push ['2Ah']
lea ['ecx,', '[ebp+var_114]']
call ['??YUString@@QAEAAV0@_W@Z']
mov ['[ebp+var_119],', '0']
mov ['eax,', '[ebp+var_14]']
push ['eax']
lea ['ecx,', '[ebp+var_114]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
lea ['ecx,', '[ebp+var_EC]']
call ['?FindFirst@CFindFile@NFind@NFile@NWindows@@QAE_NPB_WAAUCFileInfo@234@@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_12B2']
push ['offset', '$SG68101']
mov ['edx,', '[ebp+var_14]']
add ['edx,', '28h']
push ['edx']
call ['??8@YG_NABVUString@@PB_W@Z']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jz ['short', 'loc_12AB']
mov ['ecx,', '[ebp+var_104]']
mov ['edx,', '[ebp+lpFileName]']
lea ['eax,', '[edx+ecx*2]']
push ['eax']
mov ['ecx,', '[ebp+var_14]']
add ['ecx,', '28h']
call ['??4UString@@QAEAAV0@PB_W@Z']
mov ['[ebp+var_129],', '1']
mov ['byte', 'ptr', '[ebp+var_4],', '5']
lea ['ecx,', '[ebp+var_114]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_EC]']
call ['??1CFindFile@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_129]']
jmp ['loc_1393']
mov ['[ebp+var_119],', '1']
mov ['ecx,', '[ebp+lpFileName]']
push ['ecx']
call ['?GetFileAttrib@NFind@NFile@NWindows@@YGKPB_W@Z']
mov ['[ebp+var_120],', 'eax']
movzx ['edx,', '[ebp+var_119]']
test ['edx,', 'edx']
jnz ['short', 'loc_12E0']
cmp ['[ebp+var_120],', '0FFFFFFFFh']
jz ['short', 'loc_134F']
mov ['eax,', '[ebp+var_120]']
and ['eax,', '10h']
jz ['short', 'loc_134F']
mov ['ecx,', '[ebp+var_14]']
call ['?ClearBase@CFileInfoBase@NFind@NFile@NWindows@@QAEXXZ']
cmp ['[ebp+var_120],', '0FFFFFFFFh']
jz ['short', 'loc_12FF']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ebp+var_120]']
mov ['[ecx+20h],', 'edx']
jmp ['short', 'loc_1307']
mov ['ecx,', '[ebp+var_14]']
call ['?SetAsDir@CFileInfoBase@NFind@NFile@NWindows@@QAEXXZ']
mov ['eax,', '[ebp+var_104]']
mov ['ecx,', '[ebp+lpFileName]']
lea ['edx,', '[ecx+eax*2]']
push ['edx']
mov ['ecx,', '[ebp+var_14]']
add ['ecx,', '28h']
call ['??4UString@@QAEAAV0@PB_W@Z']
mov ['[ebp+var_12A],', '1']
mov ['byte', 'ptr', '[ebp+var_4],', '5']
lea ['ecx,', '[ebp+var_114]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_EC]']
call ['??1CFindFile@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_12A]']
jmp ['short', 'loc_1393']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+dwErrCode]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__SetLastError@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['byte', 'ptr', '[ebp+var_4],', '5']
lea ['ecx,', '[ebp+var_114]']
call ['??1UString@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_12C+1],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_EC]']
call ['??1CFindFile@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', 'byte', 'ptr', '[ebp+var_12C+1]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN62']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
mov ['ecx,', '[ebp+var_10]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '12Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?DoesFileExist@NFind@NFile@NWindows@@YG_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?DoesFileExist@NFind@NFile@NWindows@@YG_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '48h']
push ['edi']
lea ['edi,', '[ebp+var_54]']
mov ['ecx,', '12h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
lea ['ecx,', '[ebp+var_48]']
call ['??0CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '0']
mov ['eax,', '[ebp+this]']
push ['eax']
lea ['ecx,', '[ebp+var_48]']
call ['?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_153B']
lea ['ecx,', '[ebp+var_48]']
call ['?IsDir@CFileInfoBase@NFind@NFile@NWindows@@QBE_NXZ']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jnz ['short', 'loc_153B']
mov ['[ebp+var_54],', '1']
jmp ['short', 'loc_1542']
mov ['[ebp+var_54],', '0']
mov ['al,', 'byte', 'ptr', '[ebp+var_54]']
mov ['[ebp+var_4D],', 'al']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_48]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_4D]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN9_3']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
add ['esp,', '54h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?DoesDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?DoesDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '48h']
push ['edi']
lea ['edi,', '[ebp+var_54]']
mov ['ecx,', '12h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
lea ['ecx,', '[ebp+var_48]']
call ['??0CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '0']
mov ['eax,', '[ebp+this]']
push ['eax']
lea ['ecx,', '[ebp+var_48]']
call ['?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_161B']
lea ['ecx,', '[ebp+var_48]']
call ['?IsDir@CFileInfoBase@NFind@NFile@NWindows@@QBE_NXZ']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jz ['short', 'loc_161B']
mov ['[ebp+var_54],', '1']
jmp ['short', 'loc_1622']
mov ['[ebp+var_54],', '0']
mov ['al,', 'byte', 'ptr', '[ebp+var_54]']
mov ['[ebp+var_4D],', 'al']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_48]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_4D]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN9_4']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
add ['esp,', '54h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?DoesFileOrDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?DoesFileOrDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '44h']
push ['edi']
lea ['edi,', '[ebp+var_50]']
mov ['ecx,', '11h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
lea ['ecx,', '[ebp+var_48]']
call ['??0CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '0']
mov ['eax,', '[ebp+this]']
push ['eax']
lea ['ecx,', '[ebp+var_48]']
call ['?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z']
mov ['[ebp+var_4D],', 'al']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_48]']
call ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
mov ['al,', '[ebp+var_4D]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN7_2']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
add ['esp,', '50h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?NextAny@CEnumerator@NFind@NFile@NWindows@@AAE_NAAUCFileInfo@234@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?IsHandleAllocated@CFindFileBase@NFind@NFile@NWindows@@QBE_NXZ']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jz ['short', 'loc_1769']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?FindNext@CFindFile@NFind@NFile@NWindows@@QAE_NAAUCFileInfo@234@@Z']
jmp ['short', 'loc_1781']
jmp ['short', 'loc_1781']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '4']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
mov ['ecx,', '[ebp+var_4]']
call ['?FindFirst@CFindFile@NFind@NFile@NWindows@@QAE_NPB_WAAUCFileInfo@234@@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Next@CEnumerator@NFind@NFile@NWindows@@QAE_NAAUCFileInfo@234@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
mov ['ecx,', '[ebp+var_4]']
call ['?NextAny@CEnumerator@NFind@NFile@NWindows@@AAE_NAAUCFileInfo@234@@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jnz ['short', 'loc_17C1']
xor ['al,', 'al']
jmp ['short', 'loc_17D6']
mov ['ecx,', '[ebp+arg_0]']
call ['?IsDots@CFileInfo@NFind@NFile@NWindows@@QBE_NXZ']
movzx ['edx,', 'al']
test ['edx,', 'edx']
jnz ['short', 'loc_17D4']
mov ['al,', '1']
jmp ['short', 'loc_17D6']
jmp ['short', 'loc_17AA']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Next@CEnumerator@NFind@NFile@NWindows@@QAE_NAAUCFileInfo@234@AA_N@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
push ['esi']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
mov ['ecx,', '[ebp+var_4]']
call ['?Next@CEnumerator@NFind@NFile@NWindows@@QAE_NAAUCFileInfo@234@@Z']
movzx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_1818']
mov ['edx,', '[ebp+arg_4]']
mov ['byte', 'ptr', '[edx],', '1']
mov ['al,', '1']
jmp ['short', 'loc_1837']
mov ['eax,', '[ebp+arg_4]']
mov ['byte', 'ptr', '[eax],', '0']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetLastError@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['ecx,', 'ecx']
cmp ['eax,', '12h']
setz ['cl']
mov ['al,', 'cl']
pop ['esi']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['8']
endp
?Close@CFindChangeNotification@NFind@NFile@NWindows@@QAE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
push ['esi']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?IsHandleAllocated@CFindChangeNotification@NFind@NFile@NWindows@@QBE_NXZ']
movzx ['eax,', 'al']
test ['eax,', 'eax']
jnz ['short', 'loc_186E']
mov ['al,', '1']
jmp ['short', 'loc_1896']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__FindCloseChangeNotification@4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
test ['eax,', 'eax']
jnz ['short', 'loc_188B']
xor ['al,', 'al']
jmp ['short', 'loc_1896']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0FFFFFFFFh']
mov ['al,', '1']
pop ['esi']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?FindFirst@CFindChangeNotification@NFind@NFile@NWindows@@QAEPAXPB_W_NK@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?FindFirst@CFindChangeNotification@NFind@NFile@NWindows@@QAEPAXPB_W_NK@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '18h']
push ['esi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_24],', 'eax']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+bWatchSubtree],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_10],', 'ecx']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['short', 'loc_1951']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+dwNotifyFilter]']
push ['ecx']
movzx ['edx,', '[ebp+arg_4]']
push ['edx']
call ['?BoolToBOOL@@YGH_N@Z']
push ['eax']
mov ['eax,', '[ebp+lpPathName]']
push ['eax']
lea ['ecx,', '[ebp+bWatchSubtree]']
push ['ecx']
call ['?fs2fas@@YG?AVAString@@PB_W@Z']
mov ['[ebp+var_20],', 'eax']
mov ['edx,', '[ebp+var_20]']
mov ['[ebp+var_24],', 'edx']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_24]']
call ['??BAString@@QBEPBDXZ']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__FindFirstChangeNotificationA@12']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['ecx,', '[ebp+var_10]']
mov ['[ecx],', 'eax']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+bWatchSubtree]']
call ['??1AString@@QAE@XZ']
jmp ['short', 'loc_1978']
mov ['esi,', 'esp']
mov ['edx,', '[ebp+dwNotifyFilter]']
push ['edx']
movzx ['eax,', '[ebp+arg_4]']
push ['eax']
call ['?BoolToBOOL@@YGH_N@Z']
push ['eax']
mov ['ecx,', '[ebp+lpPathName]']
push ['ecx']
call ['dword', 'ptr', 'ds:__imp__FindFirstChangeNotificationW@12']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['edx,', '[ebp+var_10]']
mov ['[edx],', 'eax']
mov ['eax,', '[ebp+var_10]']
mov ['eax,', '[eax]']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['esi']
add ['esp,', '24h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['0Ch']
endp
?MyGetLogicalDriveStrings@NFind@NFile@NWindows@@YG_NAAV?$CObjectVector@VUString@@@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?MyGetLogicalDriveStrings@NFind@NFile@NWindows@@YG_NAAV?$CObjectVector@VUString@@@@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '7Ch']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_88]']
mov ['ecx,', '1Fh']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['ecx,', '[ebp+arg_0]']
call ['?Clear@?$CObjectVector@VUString@@@@QAEXXZ']
movzx ['eax,', 'byte', 'ptr', 'ds:?g_IsNT@@3_NA']
test ['eax,', 'eax']
jnz ['loc_1B48']
mov ['ecx,', '[ebp+arg_0]']
call ['?Clear@?$CObjectVector@VUString@@@@QAEXXZ']
mov ['esi,', 'esp']
push ['0']
push ['0']
call ['dword', 'ptr', 'ds:__imp__GetLogicalDriveStringsA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+nBufferLength],', 'eax']
cmp ['[ebp+nBufferLength],', '0']
jnz ['short', 'loc_1A17']
xor ['al,', 'al']
jmp ['loc_1C60']
mov ['ecx,', '[ebp+nBufferLength]']
push ['ecx']
lea ['ecx,', '[ebp+var_18]']
call ['??0?$CObjArray@D@@QAE@I@Z']
mov ['[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_18]']
call ['??B?$CObjArray@D@@QAEPADXZ']
mov ['esi,', 'esp']
push ['eax']
mov ['edx,', '[ebp+nBufferLength]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__GetLogicalDriveStringsA@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_20],', 'eax']
cmp ['[ebp+var_20],', '0']
jz ['short', 'loc_1A57']
mov ['eax,', '[ebp+var_20]']
cmp ['eax,', '[ebp+nBufferLength]']
jbe ['short', 'loc_1A72']
mov ['[ebp+var_6D],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_18]']
call ['??1?$CObjArray@D@@QAE@XZ']
mov ['al,', '[ebp+var_6D]']
jmp ['loc_1C60']
lea ['ecx,', '[ebp+var_30]']
call ['??0AString@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
mov ['[ebp+var_38],', '0']
mov ['[ebp+var_3C],', '0']
jmp ['short', 'loc_1A97']
mov ['ecx,', '[ebp+var_3C]']
add ['ecx,', '1']
mov ['[ebp+var_3C],', 'ecx']
mov ['edx,', '[ebp+var_3C]']
cmp ['edx,', '[ebp+var_20]']
jnb ['short', 'loc_1B12']
lea ['ecx,', '[ebp+var_18]']
call ['??B?$CObjArray@D@@QAEPADXZ']
mov ['ecx,', '[ebp+var_3C]']
movsx ['edx,', 'byte', 'ptr', '[eax+ecx]']
test ['edx,', 'edx']
jnz ['short', 'loc_1B0D']
lea ['ecx,', '[ebp+var_18]']
call ['??B?$CObjArray@D@@QAEPADXZ']
add ['eax,', '[ebp+var_38]']
push ['eax']
lea ['ecx,', '[ebp+var_30]']
call ['??4AString@@QAEAAV0@PBD@Z']
mov ['eax,', '[ebp+var_3C]']
add ['eax,', '1']
mov ['[ebp+var_38],', 'eax']
lea ['ecx,', '[ebp+var_30]']
push ['ecx']
lea ['edx,', '[ebp+var_7C]']
push ['edx']
call ['?fas2fs@@YG?AVUString@@ABVAString@@@Z']
mov ['[ebp+var_84],', 'eax']
mov ['eax,', '[ebp+var_84]']
mov ['[ebp+var_88],', 'eax']
mov ['byte', 'ptr', '[ebp+var_4],', '2']
mov ['ecx,', '[ebp+var_88]']
push ['ecx']
mov ['ecx,', '[ebp+arg_0]']
call ['?Add@?$CObjectVector@VUString@@@@QAEIABVUString@@@Z']
mov ['byte', 'ptr', '[ebp+var_4],', '1']
lea ['ecx,', '[ebp+var_7C]']
call ['??1UString@@QAE@XZ']
jmp ['loc_1A8E']
mov ['edx,', '[ebp+var_38]']
xor ['eax,', 'eax']
cmp ['edx,', '[ebp+var_20]']
setz ['al']
mov ['[ebp+var_7D],', 'al']
mov ['byte', 'ptr', '[ebp+var_4],', '0']
lea ['ecx,', '[ebp+var_30]']
call ['??1AString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_18]']
call ['??1?$CObjArray@D@@QAE@XZ']
mov ['al,', '[ebp+var_7D]']
jmp ['loc_1C60']
jmp ['loc_1C60']
mov ['esi,', 'esp']
push ['0']
push ['0']
call ['dword', 'ptr', 'ds:__imp__GetLogicalDriveStringsW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_40],', 'eax']
cmp ['[ebp+var_40],', '0']
jnz ['short', 'loc_1B6B']
xor ['al,', 'al']
jmp ['loc_1C60']
mov ['ecx,', '[ebp+var_40]']
push ['ecx']
lea ['ecx,', '[ebp+var_48]']
call ['??0?$CObjArray@_W@@QAE@I@Z']
mov ['[ebp+var_4],', '3']
lea ['ecx,', '[ebp+var_48]']
call ['??B?$CObjArray@_W@@QAEPA_WXZ']
mov ['esi,', 'esp']
push ['eax']
mov ['edx,', '[ebp+var_40]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__GetLogicalDriveStringsW@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_50],', 'eax']
cmp ['[ebp+var_50],', '0']
jz ['short', 'loc_1BAB']
mov ['eax,', '[ebp+var_50]']
cmp ['eax,', '[ebp+var_40]']
jbe ['short', 'loc_1BC6']
mov ['[ebp+var_7E],', '0']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_48]']
call ['??1?$CObjArray@_W@@QAE@XZ']
mov ['al,', '[ebp+var_7E]']
jmp ['loc_1C60']
lea ['ecx,', '[ebp+var_60]']
call ['??0UString@@QAE@XZ']
mov ['byte', 'ptr', '[ebp+var_4],', '4']
mov ['[ebp+var_68],', '0']
mov ['[ebp+var_6C],', '0']
jmp ['short', 'loc_1BEB']
mov ['ecx,', '[ebp+var_6C]']
add ['ecx,', '1']
mov ['[ebp+var_6C],', 'ecx']
mov ['edx,', '[ebp+var_6C]']
cmp ['edx,', '[ebp+var_50]']
jnb ['short', 'loc_1C34']
lea ['ecx,', '[ebp+var_48]']
call ['??B?$CObjArray@_W@@QAEPA_WXZ']
mov ['ecx,', '[ebp+var_6C]']
movzx ['edx,', 'word', 'ptr', '[eax+ecx*2]']
test ['edx,', 'edx']
jnz ['short', 'loc_1C32']
lea ['ecx,', '[ebp+var_48]']
call ['??B?$CObjArray@_W@@QAEPA_WXZ']
mov ['ecx,', '[ebp+var_68]']
lea ['edx,', '[eax+ecx*2]']
push ['edx']
lea ['ecx,', '[ebp+var_60]']
call ['??4UString@@QAEAAV0@PB_W@Z']
mov ['eax,', '[ebp+var_6C]']
add ['eax,', '1']
mov ['[ebp+var_68],', 'eax']
lea ['ecx,', '[ebp+var_60]']
push ['ecx']
mov ['ecx,', '[ebp+arg_0]']
call ['?Add@?$CObjectVector@VUString@@@@QAEIABVUString@@@Z']
jmp ['short', 'loc_1BE2']
mov ['edx,', '[ebp+var_68]']
xor ['eax,', 'eax']
cmp ['edx,', '[ebp+var_50]']
setz ['al']
mov ['[ebp+var_7F],', 'al']
mov ['byte', 'ptr', '[ebp+var_4],', '3']
lea ['ecx,', '[ebp+var_60]']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
lea ['ecx,', '[ebp+var_48]']
call ['??1?$CObjArray@_W@@QAE@XZ']
mov ['al,', '[ebp+var_7F]']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN30']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
pop ['edi']
pop ['esi']
add ['esp,', '88h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Len@UString@@QBEIXZ proc near          
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax+4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?IsEmpty@UString@@QBE_NXZ proc near     
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
xor ['ecx,', 'ecx']
cmp ['dword', 'ptr', '[eax+4],', '0']
setz ['cl']
mov ['al,', 'cl']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??BUString@@QBEPB_WXZ proc near         
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?IsDir@CFileInfoBase@NFind@NFile@NWindows@@QBE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
push ['10h']
mov ['ecx,', '[ebp+var_4]']
call ['?MatchesMask@CFileInfoBase@NFind@NFile@NWindows@@ABE_NI@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?MatchesMask@CFileInfoBase@NFind@NFile@NWindows@@ABE_NI@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax+20h]']
and ['eax,', '[ebp+arg_0]']
neg ['eax']
sbb ['eax,', 'eax']
neg ['eax']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
__unwindfunclet$?FindFirst@CFindFile@NFind@NFile@NWindows@@QAE_NPB_WAAUCFileInfo@234@@Z$0 proc near
lea ['ecx,', '[ebp-3C0h]']
jmp ['??1AString@@QAE@XZ']
endp
__ehhandler$?FindFirst@CFindFile@NFind@NFile@NWindows@@QAE_NPB_WAAUCFileInfo@234@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-3C8h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['ecx,', '[edx-4]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?FindFirst@CFindFile@NFind@NFile@NWindows@@QAE_NPB_WAAUCFileInfo@234@@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAA@@AAUCFileInfo@123@@Z$0 proc near
lea ['ecx,', '[ebp-18h]']
jmp ['??1AString@@QAE@XZ']
endp
__unwindfunclet$?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAA@@AAUCFileInfo@123@@Z$1 proc near
lea ['ecx,', '[ebp-24h]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAA@@AAUCFileInfo@123@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-28h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?Convert_WIN32_FIND_DATA_to_FileInfo@NFind@NFile@NWindows@@YGXABU_WIN32_FIND_DATAA@@AAUCFileInfo@123@@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?GetReducedName@CStreamInfo@NFind@NFile@NWindows@@QBE?AVUString@@XZ$0 proc near
lea ['ecx,', '[ebp-20h]']
jmp ['??1UString@@QAE@XZ']
endp
__unwindfunclet$?GetReducedName@CStreamInfo@NFind@NFile@NWindows@@QBE?AVUString@@XZ$1 proc near
mov ['eax,', '[ebp-28h]']
and ['eax,', '1']
jz ['locret_1DFA']
and ['dword', 'ptr', '[ebp-28h],', '0FFFFFFFEh']
mov ['ecx,', '[ebp+8]']
jmp ['??1UString@@QAE@XZ']
retn
endp
__ehhandler$?GetReducedName@CStreamInfo@NFind@NFile@NWindows@@QBE?AVUString@@XZ proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-20h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?GetReducedName@CStreamInfo@NFind@NFile@NWindows@@QBE?AVUString@@XZ']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?GetFileAttrib@NFind@NFile@NWindows@@YGKPB_W@Z$0 proc near
lea ['ecx,', '[ebp-20h]']
jmp ['??1AString@@QAE@XZ']
endp
__ehhandler$?GetFileAttrib@NFind@NFile@NWindows@@YGKPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-24h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?GetFileAttrib@NFind@NFile@NWindows@@YGKPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-68h]']
jmp ['??1CInFile@NIO@NFile@NWindows@@QAE@XZ']
endp
__unwindfunclet$?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z$1 proc near
lea ['ecx,', '[ebp-80h]']
jmp ['??1UString@@QAE@XZ']
endp
__unwindfunclet$?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z$2 proc near
lea ['ecx,', '[ebp-94h]']
jmp ['??1UString@@QAE@XZ']
endp
__unwindfunclet$?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z$3 proc near
lea ['ecx,', '[ebp-0B4h]']
jmp ['??1CStreamEnumerator@NFind@NFile@NWindows@@QAE@XZ']
endp
__unwindfunclet$?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z$4 proc near
lea ['ecx,', '[ebp-0D4h]']
jmp ['??1CStreamInfo@NFind@NFile@NWindows@@QAE@XZ']
endp
__unwindfunclet$?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z$5 proc near
lea ['ecx,', '[ebp-0ECh]']
jmp ['??1CFindFile@NFind@NFile@NWindows@@QAE@XZ']
endp
__unwindfunclet$?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z$6 proc near
lea ['ecx,', '[ebp-114h]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-12Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['ecx,', '[edx-4]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?Find@CFileInfo@NFind@NFile@NWindows@@QAE_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?DoesFileExist@NFind@NFile@NWindows@@YG_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-48h]']
jmp ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
endp
__ehhandler$?DoesFileExist@NFind@NFile@NWindows@@YG_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-50h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?DoesFileExist@NFind@NFile@NWindows@@YG_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?DoesDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-48h]']
jmp ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
endp
__ehhandler$?DoesDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-50h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?DoesDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?DoesFileOrDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z$0 proc near
lea ['ecx,', '[ebp-48h]']
jmp ['??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ']
endp
__ehhandler$?DoesFileOrDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-4Ch]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?DoesFileOrDirExist@NFind@NFile@NWindows@@YG_NPB_W@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?FindFirst@CFindChangeNotification@NFind@NFile@NWindows@@QAEPAXPB_W_NK@Z$0 proc near
lea ['ecx,', '[ebp-1Ch]']
jmp ['??1AString@@QAE@XZ']
endp
__ehhandler$?FindFirst@CFindChangeNotification@NFind@NFile@NWindows@@QAEPAXPB_W_NK@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-20h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?FindFirst@CFindChangeNotification@NFind@NFile@NWindows@@QAEPAXPB_W_NK@Z']
jmp ['___CxxFrameHandler3']
endp
__unwindfunclet$?MyGetLogicalDriveStrings@NFind@NFile@NWindows@@YG_NAAV?$CObjectVector@VUString@@@@@Z$0 proc near
lea ['ecx,', '[ebp-18h]']
jmp ['??1?$CObjArray@D@@QAE@XZ']
endp
__unwindfunclet$?MyGetLogicalDriveStrings@NFind@NFile@NWindows@@YG_NAAV?$CObjectVector@VUString@@@@@Z$1 proc near
lea ['ecx,', '[ebp-30h]']
jmp ['??1AString@@QAE@XZ']
endp
__unwindfunclet$?MyGetLogicalDriveStrings@NFind@NFile@NWindows@@YG_NAAV?$CObjectVector@VUString@@@@@Z$2 proc near
lea ['ecx,', '[ebp-7Ch]']
jmp ['??1UString@@QAE@XZ']
endp
__unwindfunclet$?MyGetLogicalDriveStrings@NFind@NFile@NWindows@@YG_NAAV?$CObjectVector@VUString@@@@@Z$3 proc near
lea ['ecx,', '[ebp-48h]']
jmp ['??1?$CObjArray@_W@@QAE@XZ']
endp
__unwindfunclet$?MyGetLogicalDriveStrings@NFind@NFile@NWindows@@YG_NAAV?$CObjectVector@VUString@@@@@Z$4 proc near
lea ['ecx,', '[ebp-60h]']
jmp ['??1UString@@QAE@XZ']
endp
__ehhandler$?MyGetLogicalDriveStrings@NFind@NFile@NWindows@@YG_NAAV?$CObjectVector@VUString@@@@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-88h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?MyGetLogicalDriveStrings@NFind@NFile@NWindows@@YG_NAAV?$CObjectVector@VUString@@@@@Z']
jmp ['___CxxFrameHandler3']
endp
??1AString@@QAE@XZ proc near            
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_8]']
push ['edx']
call ['??3@YAXPAX@Z']
add ['esp,', '4']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??BAString@@QBEPBDXZ proc near          
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1UString@@QAE@XZ proc near            
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_8]']
push ['edx']
call ['??3@YAXPAX@Z']
add ['esp,', '4']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?RightPtr@UString@@QBEPB_WI@Z proc near 
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
lea ['eax,', '[eax+ecx*2]']
mov ['ecx,', '[ebp+arg_0]']
shl ['ecx,', '1']
sub ['eax,', 'ecx']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?DeleteFrom@UString@@QAEXI@Z proc near  
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+arg_0]']
cmp ['ecx,', '[eax+4]']
jnb ['short', 'loc_2280']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+arg_0]']
mov ['[edx+4],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
xor ['eax,', 'eax']
mov ['ecx,', '[ebp+arg_0]']
mov ['[edx+ecx*2],', 'ax']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?IsHandleAllocated@CFindFileBase@NFind@NFile@NWindows@@QBE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
xor ['ecx,', 'ecx']
cmp ['dword', 'ptr', '[eax],', '0FFFFFFFFh']
setnz ['cl']
mov ['al,', 'cl']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?Empty@UString@@QAEXXZ proc near        
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+4],', '0']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
xor ['eax,', 'eax']
mov ['[edx],', 'ax']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??YUString@@QAEAAV0@_W@Z proc near      
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0Ch']
mov ['[ebp+var_C],', '0CCCCCCCCh']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[eax+8]']
cmp ['edx,', '[ecx+4]']
jnz ['short', 'loc_2310']
mov ['ecx,', '[ebp+var_4]']
call ['?Grow_1@UString@@AAEXXZ']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+4]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
mov ['[ebp+var_C],', 'eax']
mov ['ecx,', '[ebp+var_8]']
mov ['edx,', '[ebp+var_C]']
mov ['ax,', '[ebp+arg_0]']
mov ['[edx+ecx*2],', 'ax']
mov ['ecx,', '[ebp+var_8]']
add ['ecx,', '1']
mov ['[ebp+var_8],', 'ecx']
xor ['edx,', 'edx']
mov ['eax,', '[ebp+var_8]']
mov ['ecx,', '[ebp+var_C]']
mov ['[ecx+eax*2],', 'dx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_8]']
mov ['[edx+4],', 'eax']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '0Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Add_PathSepar@UString@@QAEXXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
push ['5Ch']
mov ['ecx,', '[ebp+var_4]']
call ['??YUString@@QAEAAV0@_W@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?IsEqualTo_NoCase@UString@@QBE_NPB_W@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
push ['edx']
call ['?StringsAreEqualNoCase@@YG_NPB_W0@Z']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
??8@YG_NABVUString@@PB_W@Z proc near    
push ['ebp']
mov ['ebp,', 'esp']
push ['esi']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Str2]']
push ['eax']
mov ['ecx,', '[ebp+arg_0]']
call ['??BUString@@QBEPB_WXZ']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__wcscmp']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
neg ['eax']
sbb ['eax,', 'eax']
add ['eax,', '1']
pop ['esi']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn ['8']
endp
?SetAsDir@CFileInfoBase@NFind@NFile@NWindows@@QAEXXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+20h],', '10h']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CStreamEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$??0CStreamEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
push ['ecx']
mov ['[ebp+var_10],', '0CCCCCCCCh']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_10],', 'ecx']
mov ['ecx,', '[ebp+var_10]']
call ['??0CFindStream@NFind@NFile@NWindows@@QAE@XZ']
mov ['[ebp+var_4],', '0']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
mov ['ecx,', '[ebp+var_10]']
add ['ecx,', '4']
call ['??0UString@@QAE@ABV0@@Z']
mov ['[ebp+var_4],', '0FFFFFFFFh']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
add ['esp,', '10h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
__unwindfunclet$??0CStreamEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z$0 proc near
mov ['ecx,', '[ebp-10h]']
jmp ['??1CFindStream@NFind@NFile@NWindows@@QAE@XZ']
endp
__ehhandler$??0CStreamEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-8]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$??0CStreamEnumerator@NFind@NFile@NWindows@@QAE@ABVUString@@@Z']
jmp ['___CxxFrameHandler3']
endp
??0CFindStream@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0CFindFileBase@NFind@NFile@NWindows@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CFindFileBase@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0FFFFFFFFh']
mov ['eax,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CFindStream@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??1CFindFileBase@NFind@NFile@NWindows@@QAE@XZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CFindFileBase@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?Close@CFindFileBase@NFind@NFile@NWindows@@QAE_NXZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CFindFile@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0CFindFileBase@NFind@NFile@NWindows@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CFindFile@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??1CFindFileBase@NFind@NFile@NWindows@@QAE@XZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CInFile@NIO@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0CFileBase@NIO@NFile@NWindows@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CFileBase@NIO@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0FFFFFFFFh']
mov ['eax,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CInFile@NIO@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??1CFileBase@NIO@NFile@NWindows@@QAE@XZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CFileBase@NIO@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?Close@CFileBase@NIO@NFile@NWindows@@QAE_NXZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CStreamEnumerator@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$??1CStreamEnumerator@NFind@NFile@NWindows@@QAE@XZ']
mov ['eax,', 'large', 'fs:0']
push ['eax']
push ['ecx']
mov ['[ebp+var_10],', '0CCCCCCCCh']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_10],', 'ecx']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+var_10]']
add ['ecx,', '4']
call ['??1UString@@QAE@XZ']
mov ['[ebp+var_4],', '0FFFFFFFFh']
mov ['ecx,', '[ebp+var_10]']
call ['??1CFindStream@NFind@NFile@NWindows@@QAE@XZ']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
add ['esp,', '10h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
__unwindfunclet$??1CStreamEnumerator@NFind@NFile@NWindows@@QAE@XZ$0 proc near
mov ['ecx,', '[ebp-10h]']
jmp ['??1CFindStream@NFind@NFile@NWindows@@QAE@XZ']
endp
__ehhandler$??1CStreamEnumerator@NFind@NFile@NWindows@@QAE@XZ proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-8]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$??1CStreamEnumerator@NFind@NFile@NWindows@@QAE@XZ']
jmp ['___CxxFrameHandler3']
endp
??0CStreamInfo@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0UString@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CStreamInfo@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??1UString@@QAE@XZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CFileInfo@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??0CFileInfoBase@NFind@NFile@NWindows@@QAE@XZ']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '28h']
call ['??0UString@@QAE@XZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0CFileInfoBase@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?ClearBase@CFileInfoBase@NFind@NFile@NWindows@@QAEXXZ']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??1CFileInfo@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '28h']
call ['??1UString@@QAE@XZ']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?IsHandleAllocated@CFindChangeNotification@NFind@NFile@NWindows@@QBE_NXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax],', '0FFFFFFFFh']
jz ['short', 'loc_27F0']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx],', '0']
jz ['short', 'loc_27F0']
mov ['[ebp+var_8],', '1']
jmp ['short', 'loc_27F7']
mov ['[ebp+var_8],', '0']
mov ['al,', 'byte', 'ptr', '[ebp+var_8]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?BoolToBOOL@@YGH_N@Z proc near          
push ['ebp']
mov ['ebp,', 'esp']
movzx ['eax,', '[ebp+arg_0]']
neg ['eax']
sbb ['eax,', 'eax']
neg ['eax']
pop ['ebp']
retn ['4']
endp
?Add@?$CObjectVector@VUString@@@@QAEIABVUString@@@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', '__ehhandler$?Add@?$CObjectVector@VUString@@@@QAEIABVUString@@@Z']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '10h']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_1C],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
mov ['[ebp+var_10],', 'ecx']
push ['0Ch']
call ['??2@YAPAXI@Z']
add ['esp,', '4']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_4],', '0']
cmp ['[ebp+var_18],', '0']
jz ['short', 'loc_2878']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
mov ['ecx,', '[ebp+var_18]']
call ['??0UString@@QAE@ABV0@@Z']
mov ['[ebp+var_1C],', 'eax']
jmp ['short', 'loc_287F']
mov ['[ebp+var_1C],', '0']
mov ['ecx,', '[ebp+var_1C]']
mov ['[ebp+var_14],', 'ecx']
mov ['[ebp+var_4],', '0FFFFFFFFh']
mov ['edx,', '[ebp+var_14]']
push ['edx']
mov ['ecx,', '[ebp+var_10]']
call ['?Add@?$CRecordVector@PAX@@QAEIQAX@Z']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
add ['esp,', '1Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
__unwindfunclet$?Add@?$CObjectVector@VUString@@@@QAEIABVUString@@@Z$0 proc near
mov ['eax,', '[ebp-18h]']
push ['eax']
call ['??3@YAXPAX@Z']
pop ['ecx']
retn
endp
__ehhandler$?Add@?$CObjectVector@VUString@@@@QAEIABVUString@@@Z proc near
mov ['edx,', '[esp+arg_4]']
lea ['eax,', '[edx+0Ch]']
mov ['ecx,', '[edx-14h]']
xor ['ecx,', 'eax']
call ['@__security_check_cookie@4']
mov ['eax,', 'offset', '__ehfuncinfo$?Add@?$CObjectVector@VUString@@@@QAEIABVUString@@@Z']
jmp ['___CxxFrameHandler3']
endp
?Clear@?$CObjectVector@VUString@@@@QAEXXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '14h']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_C],', 'eax']
mov ['[ebp+var_8],', 'eax']
mov ['[ebp+var_4],', 'eax']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?Size@?$CRecordVector@PAX@@QBEIXZ']
mov ['[ebp+var_8],', 'eax']
cmp ['[ebp+var_8],', '0']
jz ['short', 'loc_2974']
mov ['eax,', '[ebp+var_8]']
sub ['eax,', '1']
mov ['[ebp+var_8],', 'eax']
mov ['ecx,', '[ebp+var_8]']
push ['ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??A?$CRecordVector@PAX@@QAEAAPAXI@Z']
mov ['edx,', '[eax]']
mov ['[ebp+var_10],', 'edx']
mov ['eax,', '[ebp+var_10]']
mov ['[ebp+var_C],', 'eax']
cmp ['[ebp+var_C],', '0']
jz ['short', 'loc_296B']
push ['1']
mov ['ecx,', '[ebp+var_C]']
call ['??_GUString@@QAEPAXI@Z']
mov ['[ebp+var_14],', 'eax']
jmp ['short', 'loc_2972']
mov ['[ebp+var_14],', '0']
jmp ['short', 'loc_2930']
mov ['ecx,', '[ebp+var_4]']
call ['?Clear@?$CRecordVector@PAX@@QAEXXZ']
add ['esp,', '14h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0?$CObjArray@D@@QAE@I@Z proc near     
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0']
cmp ['[ebp+arg_0],', '0']
jz ['short', 'loc_29C9']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
call ['??2@YAPAXI@Z']
add ['esp,', '4']
mov ['[ebp+var_8],', 'eax']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_8]']
mov ['[edx],', 'eax']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
??1?$CObjArray@D@@QAE@XZ proc near      
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_8]']
push ['edx']
call ['??3@YAXPAX@Z']
add ['esp,', '4']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??B?$CObjArray@D@@QAEPADXZ proc near    
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??0?$CObjArray@_W@@QAE@I@Z proc near    
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0']
cmp ['[ebp+arg_0],', '0']
jz ['short', 'loc_2A7D']
xor ['ecx,', 'ecx']
mov ['eax,', '[ebp+arg_0]']
mov ['edx,', '2']
mul ['edx']
seto ['cl']
neg ['ecx']
or ['ecx,', 'eax']
push ['ecx']
call ['??2@YAPAXI@Z']
add ['esp,', '4']
mov ['[ebp+var_8],', 'eax']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_8]']
mov ['[eax],', 'ecx']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
??1?$CObjArray@_W@@QAE@XZ proc near     
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_8]']
push ['edx']
call ['??3@YAXPAX@Z']
add ['esp,', '4']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??B?$CObjArray@_W@@QAEPA_WXZ proc near  
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??_GUString@@QAEPAXI@Z proc near        
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['??1UString@@QAE@XZ']
mov ['eax,', '[ebp+arg_0]']
and ['eax,', '1']
jz ['short', 'loc_2B0E']
mov ['ecx,', '[ebp+var_4]']
push ['ecx']
call ['??3@YAXPAX@Z']
add ['esp,', '4']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?Size@?$CRecordVector@PAX@@QBEIXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax+4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?Clear@?$CRecordVector@PAX@@QAEXXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+4],', '0']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
?Add@?$CRecordVector@PAX@@QAEIQAX@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['ecx,', '[ebp+var_4]']
call ['?ReserveOnePosition@?$CRecordVector@PAX@@AAEXXZ']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
mov ['edx,', '[ebp+arg_0]']
mov ['[eax+ecx*4],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+4]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+4]']
add ['eax,', '1']
mov ['ecx,', '[ebp+var_4]']
mov ['[ecx+4],', 'eax']
mov ['eax,', '[ebp+var_8]']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
??A?$CRecordVector@PAX@@QAEAAPAXI@Z proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ebp+arg_0]']
lea ['eax,', '[ecx+edx*4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn ['4']
endp
?ReserveOnePosition@?$CRecordVector@PAX@@AAEXXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '14h']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+Dst],', 'eax']
mov ['[ebp+var_8],', 'eax']
mov ['[ebp+var_4],', 'eax']
mov ['[ebp+var_4],', 'ecx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[eax+4]']
cmp ['edx,', '[ecx+8]']
jnz ['loc_2C88']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+8]']
shr ['ecx,', '2']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+8]']
lea ['ecx,', '[eax+ecx+1]']
mov ['[ebp+var_8],', 'ecx']
xor ['ecx,', 'ecx']
mov ['eax,', '[ebp+var_8]']
mov ['edx,', '4']
mul ['edx']
seto ['cl']
neg ['ecx']
or ['ecx,', 'eax']
push ['ecx']
call ['??2@YAPAXI@Z']
add ['esp,', '4']
mov ['[ebp+var_10],', 'eax']
mov ['eax,', '[ebp+var_10]']
mov ['[ebp+Dst],', 'eax']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+4],', '0']
jz ['short', 'loc_2C63']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+4]']
shl ['eax,', '2']
push ['eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
push ['edx']
mov ['eax,', '[ebp+Dst]']
push ['eax']
call ['_memcpy']
add ['esp,', '0Ch']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
mov ['[ebp+var_14],', 'edx']
mov ['eax,', '[ebp+var_14]']
push ['eax']
call ['??3@YAXPAX@Z']
add ['esp,', '4']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+Dst]']
mov ['[ecx],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_8]']
mov ['[eax+8],', 'ecx']
add ['esp,', '14h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
??__Eg_FindStreamLoader@NFind@NFile@NWindows@@YAXXZ proc near
push ['ebp']
mov ['ebp,', 'esp']
mov ['ecx,', 'offset', '?g_FindStreamLoader@NFind@NFile@NWindows@@3UCFindStreamLoader@123@A']
call ['??0CFindStreamLoader@NFind@NFile@NWindows@@QAE@XZ']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
??0CFindStreamLoader@NFind@NFile@NWindows@@QAE@XZ proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
push ['esi']
push ['edi']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
mov ['esi,', 'esp']
push ['offset', '??_C@_0BB@EOFBAKLA@FindFirstStreamW?$AA@']
mov ['edi,', 'esp']
push ['offset', '??_C@_0N@MDJJJHMB@kernel32?4dll?$AA@']
call ['dword', 'ptr', 'ds:__imp__GetModuleHandleA@4']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__GetProcAddress@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['ds:_g_FindFirstStreamW,', 'eax']
mov ['esi,', 'esp']
push ['offset', '??_C@_0BA@IBDCENBE@FindNextStreamW?$AA@']
mov ['edi,', 'esp']
push ['offset', '??_C@_0N@MDJJJHMB@kernel32?4dll?$AA@']
call ['dword', 'ptr', 'ds:__imp__GetModuleHandleA@4']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__GetProcAddress@8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['ds:_g_FindNextStreamW,', 'eax']
mov ['eax,', '[ebp+var_4]']
pop ['edi']
pop ['esi']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
