sub_28          proc near               
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', 'loc_167']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '0Ch']
mov ['[ebp+var_18],', '0CCCCCCCCh']
mov ['[ebp+var_14],', '0CCCCCCCCh']
mov ['[ebp+var_10],', '0CCCCCCCCh']
mov ['eax,', 'ds:dword_26C']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
push ['0E8h']
call ['nullsub_2']
add ['esp,', '4']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_4],', '0']
cmp ['[ebp+var_14],', '0']
jz ['short', 'loc_8C']
mov ['ecx,', '[ebp+var_14]']
call ['nullsub_1']
mov ['[ebp+var_18],', 'eax']
jmp ['short', 'loc_93']
mov ['[ebp+var_18],', '0']
mov ['eax,', '[ebp+var_18]']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_4],', '0FFFFFFFFh']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
add ['esp,', '18h']
cmp ['ebp,', 'esp']
call ['nullsub_3']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
sub_C8          proc near               
push ['ebp']
mov ['ebp,', 'esp']
push ['0FFFFFFFFh']
push ['offset', 'loc_18D']
mov ['eax,', 'large', 'fs:0']
push ['eax']
sub ['esp,', '0Ch']
mov ['[ebp+var_18],', '0CCCCCCCCh']
mov ['[ebp+var_14],', '0CCCCCCCCh']
mov ['[ebp+var_10],', '0CCCCCCCCh']
mov ['eax,', 'ds:dword_26C']
xor ['eax,', 'ebp']
push ['eax']
lea ['eax,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'eax']
push ['14h']
call ['nullsub_2']
add ['esp,', '4']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_4],', '0']
cmp ['[ebp+var_14],', '0']
jz ['short', 'loc_129']
mov ['ecx,', '[ebp+var_14]']
call ['nullsub_4']
mov ['[ebp+var_18],', 'eax']
jmp ['short', 'loc_130']
mov ['[ebp+var_18],', '0']
mov ['eax,', '[ebp+var_18]']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_4],', '0FFFFFFFFh']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_C]']
mov ['large', 'fs:0,', 'ecx']
pop ['ecx']
add ['esp,', '18h']
cmp ['ebp,', 'esp']
call ['nullsub_3']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
sub_15C         proc near               
mov ['eax,', '[ebp-14h]']
push ['eax']
call ['nullsub_5']
pop ['ecx']
retn
endp
sub_182         proc near               
mov ['eax,', '[ebp-14h]']
push ['eax']
call ['nullsub_5']
pop ['ecx']
retn
endp
sub_208         proc near               
push ['ebp']
mov ['ebp,', 'esp']
mov ['ecx,', 'offset', 'unk_24C']
call ['sub_220']
cmp ['ebp,', 'esp']
call ['nullsub_3']
pop ['ebp']
retn
endp
sub_220         proc near               
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', 'ecx']
push ['offset', 'off_8']
call ['nullsub_7']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['nullsub_3']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
