; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23918.0 

	TITLE	C:\workpace\openssl\openssl-1.0.2h\crypto\evp\p5_crpt2.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_PKCS5_PBKDF2_HMAC_SHA1
PUBLIC	_PKCS5_PBKDF2_HMAC
PUBLIC	_PKCS5_v2_PBE_keyivgen
PUBLIC	_PKCS5_v2_PBKDF2_keyivgen
PUBLIC	??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@ ; `string'
PUBLIC	??_C@_0BF@JMOFLBJO@keylen?5?$DM?$DN?5sizeof?5key?$AA@ ; `string'
EXTRN	_OPENSSL_cleanse:PROC
EXTRN	_OpenSSLDie:PROC
EXTRN	_ERR_put_error:PROC
EXTRN	_ASN1_INTEGER_get:PROC
EXTRN	_OBJ_nid2sn:PROC
EXTRN	_OBJ_obj2nid:PROC
EXTRN	_EVP_MD_size:PROC
EXTRN	_EVP_CIPHER_CTX_cipher:PROC
EXTRN	_EVP_CIPHER_CTX_key_length:PROC
EXTRN	_EVP_CipherInit_ex:PROC
EXTRN	_EVP_sha1:PROC
EXTRN	_EVP_get_cipherbyname:PROC
EXTRN	_EVP_get_digestbyname:PROC
EXTRN	_EVP_CIPHER_asn1_to_param:PROC
EXTRN	_EVP_PBE_find:PROC
EXTRN	_PBE2PARAM_free:PROC
EXTRN	_d2i_PBE2PARAM:PROC
EXTRN	_PBKDF2PARAM_free:PROC
EXTRN	_d2i_PBKDF2PARAM:PROC
EXTRN	_HMAC_CTX_init:PROC
EXTRN	_HMAC_CTX_cleanup:PROC
EXTRN	_HMAC_Init_ex:PROC
EXTRN	_HMAC_Update:PROC
EXTRN	_HMAC_Final:PROC
EXTRN	_HMAC_CTX_copy:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__chkstk:PROC
EXTRN	_memcpy:PROC
EXTRN	___security_cookie:DWORD
;	COMDAT ??_C@_0BF@JMOFLBJO@keylen?5?$DM?$DN?5sizeof?5key?$AA@
CONST	SEGMENT
??_C@_0BF@JMOFLBJO@keylen?5?$DM?$DN?5sizeof?5key?$AA@ DB 'keylen <= sizeo'
	DB	'f key', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
CONST	SEGMENT
??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@ DB '.\crypto\evp\p5_'
	DB	'crpt2.c', 00H				; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _PKCS5_v2_PBKDF2_keyivgen
_TEXT	SEGMENT
_rv$1$ = -92						; size = 4
_pbuf$ = -88						; size = 4
_hmac_md_nid$ = -84					; size = 4
_prfmd$1$ = -80						; size = 4
_pass$GSCopy$1$ = -76					; size = 4
_ctx$GSCopy$1$ = -72					; size = 4
_key$ = -68						; size = 64
__$ArrayPad$ = -4					; size = 4
_ctx$ = 8						; size = 4
_pass$ = 12						; size = 4
_passlen$ = 16						; size = 4
_param$ = 20						; size = 4
_c$ = 24						; size = 4
_md$ = 28						; size = 4
_en_de$ = 32						; size = 4
_PKCS5_v2_PBKDF2_keyivgen PROC				; COMDAT
; File c:\workpace\openssl\openssl-1.0.2h\crypto\evp\p5_crpt2.c
; Line 250
	mov	eax, 92					; 0000005cH
	call	__chkstk
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+92], eax
	mov	eax, DWORD PTR _pass$[esp+88]
	push	ebx
	push	ebp
	push	esi
	mov	esi, DWORD PTR _ctx$[esp+100]
; Line 255
	xor	ebp, ebp
	push	edi
	mov	edi, DWORD PTR _param$[esp+104]
; Line 257
	xor	ebx, ebx
; Line 260
	push	esi
	mov	DWORD PTR _ctx$GSCopy$1$[esp+112], esi
	mov	DWORD PTR _pass$GSCopy$1$[esp+112], eax
	mov	DWORD PTR _rv$1$[esp+112], 0
	call	_EVP_CIPHER_CTX_cipher
	add	esp, 4
	test	eax, eax
	jne	SHORT $LN2@PKCS5_v2_P
; Line 261
	push	261					; 00000105H
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	push	131					; 00000083H
; Line 262
	jmp	$LN16@PKCS5_v2_P
$LN2@PKCS5_v2_P:
; Line 264
	push	esi
	call	_EVP_CIPHER_CTX_key_length
	mov	ebp, eax
	add	esp, 4
; Line 265
	cmp	ebp, 64					; 00000040H
	jbe	SHORT $LN15@PKCS5_v2_P
	push	OFFSET ??_C@_0BF@JMOFLBJO@keylen?5?$DM?$DN?5sizeof?5key?$AA@
	push	265					; 00000109H
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	call	_OpenSSLDie
	add	esp, 12					; 0000000cH
$LN15@PKCS5_v2_P:
; Line 269
	test	edi, edi
	je	$LN4@PKCS5_v2_P
	cmp	DWORD PTR [edi], 16			; 00000010H
	jne	$LN4@PKCS5_v2_P
; Line 274
	mov	ecx, DWORD PTR [edi+4]
	mov	eax, DWORD PTR [ecx+8]
	mov	DWORD PTR _pbuf$[esp+108], eax
; Line 277
	lea	eax, DWORD PTR _pbuf$[esp+108]
	push	DWORD PTR [ecx]
	push	eax
	push	0
	call	_d2i_PBKDF2PARAM
	mov	ebx, eax
	add	esp, 12					; 0000000cH
	test	ebx, ebx
	jne	SHORT $LN5@PKCS5_v2_P
; Line 278
	push	278					; 00000116H
; Line 279
	jmp	$LN17@PKCS5_v2_P
$LN5@PKCS5_v2_P:
; Line 282
	push	esi
	call	_EVP_CIPHER_CTX_key_length
	mov	ebp, eax
	add	esp, 4
; Line 286
	mov	eax, DWORD PTR [ebx+8]
	test	eax, eax
	je	SHORT $LN6@PKCS5_v2_P
	push	eax
	call	_ASN1_INTEGER_get
	add	esp, 4
	cmp	eax, ebp
	je	SHORT $LN6@PKCS5_v2_P
; Line 287
	push	287					; 0000011fH
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	push	123					; 0000007bH
; Line 288
	jmp	$LN16@PKCS5_v2_P
$LN6@PKCS5_v2_P:
; Line 291
	mov	eax, DWORD PTR [ebx+12]
	test	eax, eax
	je	SHORT $LN7@PKCS5_v2_P
; Line 292
	push	DWORD PTR [eax]
	call	_OBJ_obj2nid
	add	esp, 4
	jmp	SHORT $LN8@PKCS5_v2_P
$LN7@PKCS5_v2_P:
; Line 294
	mov	eax, 163				; 000000a3H
$LN8@PKCS5_v2_P:
; Line 296
	push	0
	lea	ecx, DWORD PTR _hmac_md_nid$[esp+112]
	push	ecx
	push	0
	push	eax
	push	1
	call	_EVP_PBE_find
	add	esp, 20					; 00000014H
	test	eax, eax
	jne	SHORT $LN9@PKCS5_v2_P
; Line 297
	push	297					; 00000129H
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	push	125					; 0000007dH
; Line 298
	jmp	$LN16@PKCS5_v2_P
$LN9@PKCS5_v2_P:
; Line 301
	push	DWORD PTR _hmac_md_nid$[esp+108]
	call	_OBJ_nid2sn
	push	eax
	call	_EVP_get_digestbyname
	add	esp, 8
	mov	DWORD PTR _prfmd$1$[esp+108], eax
; Line 302
	test	eax, eax
	jne	SHORT $LN10@PKCS5_v2_P
; Line 303
	push	303					; 0000012fH
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	push	125					; 0000007dH
; Line 304
	jmp	SHORT $LN16@PKCS5_v2_P
$LN10@PKCS5_v2_P:
; Line 307
	mov	eax, DWORD PTR [ebx]
	cmp	DWORD PTR [eax], 4
	je	SHORT $LN11@PKCS5_v2_P
; Line 308
	push	308					; 00000134H
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	push	126					; 0000007eH
; Line 309
	jmp	SHORT $LN16@PKCS5_v2_P
$LN11@PKCS5_v2_P:
; Line 313
	mov	eax, DWORD PTR [eax+4]
; Line 315
	push	DWORD PTR [ebx+4]
	mov	edi, DWORD PTR [eax+8]
	mov	esi, DWORD PTR [eax]
	call	_ASN1_INTEGER_get
; Line 316
	lea	ecx, DWORD PTR _key$[esp+112]
	push	ecx
	push	ebp
	push	DWORD PTR _prfmd$1$[esp+120]
	push	eax
	push	esi
	push	edi
	push	DWORD PTR _passlen$[esp+132]
	push	DWORD PTR _pass$GSCopy$1$[esp+140]
	call	_PKCS5_PBKDF2_HMAC
	add	esp, 36					; 00000024H
	test	eax, eax
	je	SHORT $err$19
; Line 319
	push	DWORD PTR _en_de$[esp+104]
	lea	eax, DWORD PTR _key$[esp+112]
	push	0
	push	eax
	push	0
	push	0
	push	DWORD PTR _ctx$GSCopy$1$[esp+128]
	call	_EVP_CipherInit_ex
	add	esp, 24					; 00000018H
	mov	DWORD PTR _rv$1$[esp+108], eax
	jmp	SHORT $err$19
$LN4@PKCS5_v2_P:
; Line 270
	push	270					; 0000010eH
$LN17@PKCS5_v2_P:
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	push	114					; 00000072H
$LN16@PKCS5_v2_P:
	push	164					; 000000a4H
	push	6
	call	_ERR_put_error
	add	esp, 20					; 00000014H
$err$19:
; Line 321
	lea	eax, DWORD PTR _key$[esp+108]
	push	ebp
	push	eax
	call	_OPENSSL_cleanse
; Line 322
	push	ebx
	call	_PBKDF2PARAM_free
; Line 324
	mov	ecx, DWORD PTR __$ArrayPad$[esp+120]
	add	esp, 12					; 0000000cH
	mov	eax, DWORD PTR _rv$1$[esp+108]
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 92					; 0000005cH
	ret	0
_PKCS5_v2_PBKDF2_keyivgen ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _PKCS5_v2_PBE_keyivgen
_TEXT	SEGMENT
_ctx$ = 8						; size = 4
_pass$ = 12						; size = 4
_passlen$ = 16						; size = 4
_pbuf$ = 20						; size = 4
_param$ = 20						; size = 4
_c$ = 24						; size = 4
_md$ = 28						; size = 4
_en_de$ = 32						; size = 4
_PKCS5_v2_PBE_keyivgen PROC				; COMDAT
; File c:\workpace\openssl\openssl-1.0.2h\crypto\evp\p5_crpt2.c
; Line 201
	mov	eax, DWORD PTR _param$[esp-4]
	push	ebx
	push	esi
	xor	esi, esi
	xor	ebx, ebx
	push	edi
	test	eax, eax
	je	$LN3@PKCS5_v2_P
	cmp	DWORD PTR [eax], 16			; 00000010H
	jne	$LN3@PKCS5_v2_P
	mov	ecx, DWORD PTR [eax+4]
	test	ecx, ecx
	je	$LN3@PKCS5_v2_P
; Line 207
	mov	eax, DWORD PTR [ecx+8]
	mov	DWORD PTR _pbuf$[esp+8], eax
; Line 209
	lea	eax, DWORD PTR _pbuf$[esp+8]
	push	DWORD PTR [ecx]
	push	eax
	push	ebx
	call	_d2i_PBE2PARAM
	mov	esi, eax
	add	esp, 12					; 0000000cH
	test	esi, esi
	jne	SHORT $LN4@PKCS5_v2_P
; Line 210
	push	210					; 000000d2H
; Line 211
	jmp	$LN10@PKCS5_v2_P
$LN4@PKCS5_v2_P:
; Line 216
	mov	eax, DWORD PTR [esi]
	push	DWORD PTR [eax]
	call	_OBJ_obj2nid
	add	esp, 4
	cmp	eax, 69					; 00000045H
	je	SHORT $LN5@PKCS5_v2_P
; Line 217
	push	218					; 000000daH
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	push	124					; 0000007cH
; Line 219
	jmp	$LN11@PKCS5_v2_P
$LN5@PKCS5_v2_P:
; Line 226
	mov	eax, DWORD PTR [esi+4]
	push	DWORD PTR [eax]
	call	_OBJ_obj2nid
	push	eax
	call	_OBJ_nid2sn
	push	eax
	call	_EVP_get_cipherbyname
	add	esp, 12					; 0000000cH
; Line 228
	test	eax, eax
	jne	SHORT $LN6@PKCS5_v2_P
; Line 229
	push	229					; 000000e5H
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	push	107					; 0000006bH
; Line 230
	jmp	SHORT $LN11@PKCS5_v2_P
$LN6@PKCS5_v2_P:
; Line 234
	push	DWORD PTR _en_de$[esp+8]
	mov	edi, DWORD PTR _ctx$[esp+12]
	push	0
	push	0
	push	0
	push	eax
	push	edi
	call	_EVP_CipherInit_ex
	add	esp, 24					; 00000018H
	test	eax, eax
	je	SHORT $err$13
; Line 236
	mov	eax, DWORD PTR [esi+4]
	push	DWORD PTR [eax+4]
	push	edi
	call	_EVP_CIPHER_asn1_to_param
	add	esp, 8
	test	eax, eax
	jns	SHORT $LN8@PKCS5_v2_P
; Line 237
	push	237					; 000000edH
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	push	122					; 0000007aH
; Line 238
	jmp	SHORT $LN11@PKCS5_v2_P
$LN8@PKCS5_v2_P:
; Line 240
	push	DWORD PTR _en_de$[esp+8]
	mov	eax, DWORD PTR [esi]
	push	DWORD PTR _md$[esp+12]
	push	DWORD PTR _c$[esp+16]
	push	DWORD PTR [eax+4]
	push	DWORD PTR _passlen$[esp+24]
	push	DWORD PTR _pass$[esp+28]
	push	edi
	call	_PKCS5_v2_PBKDF2_keyivgen
	add	esp, 28					; 0000001cH
	mov	ebx, eax
; Line 243
	push	esi
	call	_PBE2PARAM_free
	add	esp, 4
; Line 244
	mov	eax, ebx
	pop	edi
	pop	esi
	pop	ebx
; Line 245
	ret	0
$LN3@PKCS5_v2_P:
; Line 203
	push	203					; 000000cbH
$LN10@PKCS5_v2_P:
	push	OFFSET ??_C@_0BI@BNAJCHDH@?4?2crypto?2evp?2p5_crpt2?4c?$AA@
	push	114					; 00000072H
$LN11@PKCS5_v2_P:
	push	118					; 00000076H
	push	6
	call	_ERR_put_error
	add	esp, 20					; 00000014H
$err$13:
; Line 243
	push	esi
	call	_PBE2PARAM_free
	add	esp, 4
; Line 244
	mov	eax, ebx
	pop	edi
	pop	esi
	pop	ebx
; Line 245
	ret	0
_PKCS5_v2_PBE_keyivgen ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _PKCS5_PBKDF2_HMAC
_TEXT	SEGMENT
_itmp$ = -504						; size = 4
_j$1$ = -500						; size = 4
_mdlen$1$ = -496					; size = 4
_i$1$ = -492						; size = 4
_salt$GSCopy$1$ = -488					; size = 4
_hctx$ = -484						; size = 208
_hctx_tpl$ = -276					; size = 208
_digtmp$ = -68						; size = 64
__$ArrayPad$ = -4					; size = 4
_pass$ = 8						; size = 4
_passlen$ = 12						; size = 4
_salt$ = 16						; size = 4
_saltlen$ = 20						; size = 4
_iter$ = 24						; size = 4
_digest$ = 28						; size = 4
_keylen$ = 32						; size = 4
_out$ = 36						; size = 4
_PKCS5_PBKDF2_HMAC PROC					; COMDAT
; File c:\workpace\openssl\openssl-1.0.2h\crypto\evp\p5_crpt2.c
; Line 85
	mov	eax, 504				; 000001f8H
	call	__chkstk
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+504], eax
	mov	eax, DWORD PTR _salt$[esp+500]
	push	ebp
	mov	ebp, DWORD PTR _out$[esp+504]
	push	esi
	mov	esi, DWORD PTR _pass$[esp+508]
	push	edi
	mov	edi, DWORD PTR _digest$[esp+512]
; Line 91
	push	edi
	mov	DWORD PTR _salt$GSCopy$1$[esp+520], eax
	mov	DWORD PTR _i$1$[esp+520], 1
	call	_EVP_MD_size
	add	esp, 4
	mov	DWORD PTR _mdlen$1$[esp+516], eax
; Line 92
	test	eax, eax
	js	SHORT $LN50@PKCS5_PBKD
; Line 95
	lea	eax, DWORD PTR _hctx_tpl$[esp+516]
	push	eax
	call	_HMAC_CTX_init
	add	esp, 4
; Line 98
	test	esi, esi
	jne	SHORT $LN11@PKCS5_PBKD
; Line 99
	xor	ecx, ecx
	jmp	SHORT $LN13@PKCS5_PBKD
$LN11@PKCS5_PBKD:
; Line 100
	mov	ecx, DWORD PTR _passlen$[esp+512]
	cmp	ecx, -1
	jne	SHORT $LN13@PKCS5_PBKD
; Line 101
	mov	ecx, esi
	lea	edx, DWORD PTR [ecx+1]
	npad	3
$LL47@PKCS5_PBKD:
	mov	al, BYTE PTR [ecx]
	inc	ecx
	test	al, al
	jne	SHORT $LL47@PKCS5_PBKD
	sub	ecx, edx
$LN13@PKCS5_PBKD:
; Line 102
	push	0
	push	edi
	push	ecx
	lea	eax, DWORD PTR _hctx_tpl$[esp+528]
	push	esi
	push	eax
	call	_HMAC_Init_ex
	add	esp, 20					; 00000014H
	test	eax, eax
	jne	SHORT $LN24@PKCS5_PBKD
; Line 103
	lea	eax, DWORD PTR _hctx_tpl$[esp+516]
	push	eax
	call	_HMAC_CTX_cleanup
	add	esp, 4
$LN50@PKCS5_PBKD:
; Line 104
	pop	edi
	pop	esi
	xor	eax, eax
	pop	ebp
; Line 162
	mov	ecx, DWORD PTR __$ArrayPad$[esp+504]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 504				; 000001f8H
	ret	0
$LN24@PKCS5_PBKD:
; Line 106
	mov	eax, DWORD PTR _keylen$[esp+512]
	push	ebx
	test	eax, eax
	je	$LN3@PKCS5_PBKD
	mov	esi, DWORD PTR _mdlen$1$[esp+520]
	mov	ecx, 1
$LL2@PKCS5_PBKD:
; Line 107
	cmp	eax, esi
; Line 118
	mov	BYTE PTR _itmp$[esp+523], cl
	mov	ebx, eax
	mov	eax, ecx
	cmovg	ebx, esi
	shr	eax, 24					; 00000018H
	mov	BYTE PTR _itmp$[esp+520], al
	mov	eax, ecx
	shr	eax, 16					; 00000010H
	mov	BYTE PTR _itmp$[esp+521], al
	mov	eax, ecx
	shr	eax, 8
	mov	BYTE PTR _itmp$[esp+522], al
; Line 119
	lea	eax, DWORD PTR _hctx_tpl$[esp+520]
	push	eax
	lea	eax, DWORD PTR _hctx$[esp+524]
	push	eax
	call	_HMAC_CTX_copy
	add	esp, 8
	test	eax, eax
	je	$LN29@PKCS5_PBKD
; Line 125
	push	DWORD PTR _saltlen$[esp+516]
	lea	eax, DWORD PTR _hctx$[esp+524]
	push	DWORD PTR _salt$GSCopy$1$[esp+524]
	push	eax
	call	_HMAC_Update
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	$LN19@PKCS5_PBKD
	push	4
	lea	eax, DWORD PTR _itmp$[esp+524]
	push	eax
	lea	eax, DWORD PTR _hctx$[esp+528]
	push	eax
	call	_HMAC_Update
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	$LN19@PKCS5_PBKD
	push	0
	lea	eax, DWORD PTR _digtmp$[esp+524]
	push	eax
	lea	eax, DWORD PTR _hctx$[esp+528]
	push	eax
	call	_HMAC_Final
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	$LN19@PKCS5_PBKD
; Line 130
	lea	eax, DWORD PTR _hctx$[esp+520]
	push	eax
	call	_HMAC_CTX_cleanup
; Line 131
	push	ebx
	lea	eax, DWORD PTR _digtmp$[esp+528]
	push	eax
	push	ebp
	call	_memcpy
	add	esp, 16					; 00000010H
; Line 132
	mov	DWORD PTR _j$1$[esp+520], 1
	cmp	DWORD PTR _iter$[esp+516], 1
	jle	$LN5@PKCS5_PBKD
	npad	11
$LL6@PKCS5_PBKD:
; Line 133
	lea	eax, DWORD PTR _hctx_tpl$[esp+520]
	push	eax
	lea	eax, DWORD PTR _hctx$[esp+524]
	push	eax
	call	_HMAC_CTX_copy
	add	esp, 8
	test	eax, eax
	je	$LN29@PKCS5_PBKD
; Line 138
	push	esi
	lea	eax, DWORD PTR _digtmp$[esp+524]
	push	eax
	lea	eax, DWORD PTR _hctx$[esp+528]
	push	eax
	call	_HMAC_Update
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	$LN19@PKCS5_PBKD
	push	0
	lea	eax, DWORD PTR _digtmp$[esp+524]
	push	eax
	lea	eax, DWORD PTR _hctx$[esp+528]
	push	eax
	call	_HMAC_Final
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	$LN19@PKCS5_PBKD
; Line 143
	lea	eax, DWORD PTR _hctx$[esp+520]
	push	eax
	call	_HMAC_CTX_cleanup
	add	esp, 4
; Line 144
	xor	esi, esi
	test	ebx, ebx
	jle	$LN4@PKCS5_PBKD
	cmp	ebx, 32					; 00000020H
	jb	SHORT $LN35@PKCS5_PBKD
; Line 145
	lea	ecx, DWORD PTR [ebp-1]
	lea	eax, DWORD PTR _digtmp$[esp+ebx+519]
	add	ecx, ebx
	cmp	ebp, eax
	ja	SHORT $LN36@PKCS5_PBKD
	lea	eax, DWORD PTR _digtmp$[esp+520]
	cmp	ecx, eax
	jae	SHORT $LN35@PKCS5_PBKD
$LN36@PKCS5_PBKD:
	mov	eax, ebx
	and	eax, -2147483617			; 8000001fH
	jns	SHORT $LN49@PKCS5_PBKD
	dec	eax
	or	eax, -32				; ffffffe0H
	inc	eax
$LN49@PKCS5_PBKD:
	mov	edx, ebx
; Line 144
	lea	edi, DWORD PTR _digtmp$[esp+520]
	sub	edx, eax
	mov	ecx, ebp
	mov	eax, ebp
	neg	eax
	add	edi, eax
	lea	eax, DWORD PTR _digtmp$[esp+eax+536]
	npad	7
$LL9@PKCS5_PBKD:
; Line 145
	movups	xmm0, XMMWORD PTR [ecx]
	add	esi, 32					; 00000020H
	lea	ecx, DWORD PTR [ecx+32]
	movups	xmm1, XMMWORD PTR [edi+ecx-32]
	pxor	xmm1, xmm0
	movups	XMMWORD PTR [ecx-32], xmm1
	movups	xmm1, XMMWORD PTR [eax+ecx-32]
	movups	xmm0, XMMWORD PTR [ecx-16]
	pxor	xmm1, xmm0
	movups	XMMWORD PTR [ecx-16], xmm1
	cmp	esi, edx
	jl	SHORT $LL9@PKCS5_PBKD
$LN35@PKCS5_PBKD:
; Line 144
	cmp	esi, ebx
	jge	SHORT $LN4@PKCS5_PBKD
	lea	edi, DWORD PTR _digtmp$[esp+520]
	mov	edx, ebx
	sub	edi, ebp
	lea	eax, DWORD PTR [esi+ebp]
	sub	edx, esi
	npad	1
$LL34@PKCS5_PBKD:
; Line 145
	mov	cl, BYTE PTR [edi+eax]
	lea	eax, DWORD PTR [eax+1]
	xor	BYTE PTR [eax-1], cl
	sub	edx, 1
	jne	SHORT $LL34@PKCS5_PBKD
$LN4@PKCS5_PBKD:
; Line 132
	mov	esi, DWORD PTR _j$1$[esp+520]
	inc	esi
	cmp	esi, DWORD PTR _iter$[esp+516]
	mov	DWORD PTR _j$1$[esp+520], esi
	mov	esi, DWORD PTR _mdlen$1$[esp+520]
	jl	$LL6@PKCS5_PBKD
$LN5@PKCS5_PBKD:
; Line 147
	mov	eax, DWORD PTR _keylen$[esp+516]
; Line 149
	add	ebp, ebx
	mov	ecx, DWORD PTR _i$1$[esp+520]
	sub	eax, ebx
	inc	ecx
	mov	DWORD PTR _keylen$[esp+516], eax
	mov	DWORD PTR _i$1$[esp+520], ecx
	test	eax, eax
	jne	$LL2@PKCS5_PBKD
$LN3@PKCS5_PBKD:
; Line 151
	lea	eax, DWORD PTR _hctx_tpl$[esp+520]
	push	eax
	call	_HMAC_CTX_cleanup
	add	esp, 4
; Line 161
	mov	eax, 1
$LN48@PKCS5_PBKD:
; Line 162
	mov	ecx, DWORD PTR __$ArrayPad$[esp+520]
	pop	ebx
	pop	edi
	pop	esi
	pop	ebp
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 504				; 000001f8H
	ret	0
$LN19@PKCS5_PBKD:
; Line 126
	lea	eax, DWORD PTR _hctx_tpl$[esp+520]
	push	eax
	call	_HMAC_CTX_cleanup
; Line 127
	lea	eax, DWORD PTR _hctx$[esp+524]
	push	eax
	call	_HMAC_CTX_cleanup
	add	esp, 8
; Line 128
	xor	eax, eax
	jmp	SHORT $LN48@PKCS5_PBKD
$LN29@PKCS5_PBKD:
; Line 120
	lea	eax, DWORD PTR _hctx_tpl$[esp+520]
	push	eax
	call	_HMAC_CTX_cleanup
	add	esp, 4
; Line 121
	xor	eax, eax
	jmp	SHORT $LN48@PKCS5_PBKD
_PKCS5_PBKDF2_HMAC ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _PKCS5_PBKDF2_HMAC_SHA1
_TEXT	SEGMENT
_pass$ = 8						; size = 4
_passlen$ = 12						; size = 4
_salt$ = 16						; size = 4
_saltlen$ = 20						; size = 4
_iter$ = 24						; size = 4
_keylen$ = 28						; size = 4
_out$ = 32						; size = 4
_PKCS5_PBKDF2_HMAC_SHA1 PROC				; COMDAT
; File c:\workpace\openssl\openssl-1.0.2h\crypto\evp\p5_crpt2.c
; Line 168
	push	DWORD PTR _out$[esp-4]
	push	DWORD PTR _keylen$[esp]
	call	_EVP_sha1
	push	eax
	push	DWORD PTR _iter$[esp+8]
	push	DWORD PTR _saltlen$[esp+12]
	push	DWORD PTR _salt$[esp+16]
	push	DWORD PTR _passlen$[esp+20]
	push	DWORD PTR _pass$[esp+24]
	call	_PKCS5_PBKDF2_HMAC
	add	esp, 32					; 00000020H
; Line 170
	ret	0
_PKCS5_PBKDF2_HMAC_SHA1 ENDP
_TEXT	ENDS
END
