endp
?usageAndDie@@YAXH@Z proc near		
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0C0h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_C0]']
mov ['ecx,', '30h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['esi,', 'esp']
mov ['eax,', 'ds:_progName']
push ['eax']
push ['offset', '??_C@_0GA@JGCANGFP@Usage?3?5?$CFs?5?$FL?9v?$FN?5?$FL?9options?$FN?5?9r?5con@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
call ['_u_getDataDirectory_56']
mov ['esi,', 'esp']
push ['eax']
push ['offset', '??_C@_0CAI@BJCCOGDK@?7Read?5in?5Unicode?5confusable?5char@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '0C0h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CAI@BJCCOGDK@?7Read?5in?5Unicode?5confusable?5char@']
db ["'he", 'binary', "data',0Ah"]
db ["'options:',0Ah"]
db ["9,'-h", 'or', '-?', 'or', '--help', 'this', 'usage', "text',0Ah"]
db ["9,'-V", 'or', '--version', 'show', 'a', 'version', "message',0Ah"]
db ["9,'-c", 'or', '--copyright', 'include', 'a', 'copyright', "notice',0Ah"]
db ["9,'-v", 'or', '--verbose', 'turn', 'on', 'verbose', "output',0Ah"]
db ["9,'-q", 'or', '--quiet', 'do', 'not', 'display', 'warnings', 'and', "progress',0Ah"]
db ["9,'-i", 'or', '--icudatadir', 'directory', 'for', 'locating', 'any', 'needed', "intermedia'"]
db ["'te", 'data', "files,',0Ah"]
db ["9,'", 'followed', 'by', 'path,', 'defaults', 'to', "%s',0Ah"]
db ["9,'-d", 'or', '--destdir', 'destination', 'directory,', 'followed', 'by', 'the', "path',0Ah"]
db ['0']
assume ['cs:_rdata']
public ['??_C@_0GA@JGCANGFP@Usage?3?5?$CFs?5?$FL?9v?$FN?5?$FL?9options?$FN?5?9r?5con@']
db ["'onfusables.txt", '-o', "output-file',0Ah,0"]
assume ['cs:_bss']
assume ['es:nothing,', 'ss:nothing,', 'ds:_rdata,', 'fs:nothing,', 'gs:nothing']
assume ['cs:_rtc$TMZ']
assume ['cs:_rtc$IMZ']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_rdata,', 'fs:nothing,', 'gs:nothing']
endp
_main		proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '220h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_220]']
mov ['ecx,', '88h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', 'dword', 'ptr', 'ds:___security_cookie']
xor ['eax,', 'ebp']
mov ['[ebp+var_4],', 'eax']
mov ['[ebp+Code],', '0']
mov ['[ebp+var_3C],', '0']
mov ['[ebp+var_48],', '0']
mov ['eax,', '[ebp+argv]']
mov ['ecx,', '[eax]']
mov ['ds:_progName,', 'ecx']
push ['offset', '_options']
push ['0Ah']
mov ['eax,', '[ebp+argv]']
push ['eax']
mov ['ecx,', '[ebp+argc]']
push ['ecx']
call ['_u_parseArgs']
add ['esp,', '10h']
mov ['[ebp+argc],', 'eax']
cmp ['[ebp+argc],', '0']
jge ['short', 'loc_5C0']
mov ['eax,', '[ebp+argc]']
neg ['eax']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+argv]']
mov ['edx,', '[ecx+eax*4]']
push ['edx']
push ['offset', '??_C@_0CF@BGPNLJEE@error?5in?5command?5line?5argument?5?$CC@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
push ['1']
call ['?usageAndDie@@YAXH@Z']
db ['83h']
db ['0C4h']
db ['4']
movsx ['eax,', 'ds:byte_156']
test ['eax,', 'eax']
jnz ['short', 'loc_5D6']
movsx ['eax,', 'ds:byte_16A']
test ['eax,', 'eax']
jz ['short', 'loc_5E0']
push ['0']
call ['?usageAndDie@@YAXH@Z']
db ['83h']
db ['0C4h']
db ['4']
movsx ['eax,', 'ds:byte_192']
test ['eax,', 'eax']
jz ['short', 'loc_601']
movsx ['eax,', 'ds:byte_1A6']
test ['eax,', 'eax']
jz ['short', 'loc_601']
movsx ['eax,', 'ds:byte_1BA']
test ['eax,', 'eax']
jnz ['short', 'loc_635']
mov ['esi,', 'esp']
push ['offset', '??_C@_0FI@EJGIKDKB@confusables?5file?0?5whole?5script?5c@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
push ['1']
call ['?usageAndDie@@YAXH@Z']
db ['83h']
db ['0C4h']
db ['4']
mov ['eax,', 'ds:dword_184']
mov ['[ebp+Filename],', 'eax']
mov ['eax,', 'ds:dword_198']
mov ['[ebp+var_24],', 'eax']
mov ['eax,', 'ds:dword_1AC']
mov ['[ebp+Format],', 'eax']
movsx ['eax,', 'ds:byte_1CE']
test ['eax,', 'eax']
jz ['short', 'loc_666']
mov ['eax,', 'ds:dword_1C0']
push ['eax']
call ['_u_setDataDirectory_56']
add ['esp,', '4']
mov ['[ebp+Code],', '0']
movsx ['eax,', 'ds:byte_1E2']
test ['eax,', 'eax']
jz ['short', 'loc_680']
mov ['eax,', 'ds:dword_1D4']
mov ['[ebp+var_3C],', 'eax']
movsx ['eax,', 'ds:byte_1F6']
test ['eax,', 'eax']
jz ['short', 'loc_692']
mov ['[ebp+var_48],', 'offset', '??_C@_0GD@IBBFEJOD@?5Copyright?5?$CIC?$CJ?52015?0?5Internation@']
mov ['[ebp+var_51],', '0']
movsx ['eax,', 'ds:byte_20A']
test ['eax,', 'eax']
jz ['short', 'loc_6A5']
mov ['[ebp+var_51],', '1']
lea ['eax,', '[ebp+Code]']
push ['eax']
call ['_u_init_56']
add ['esp,', '4']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['?U_FAILURE@@YACW4UErrorCode@@@Z']
add ['esp,', '4']
movsx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_712']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['_u_errorName_56']
add ['esp,', '4']
mov ['esi,', 'esp']
push ['eax']
mov ['ecx,', '[ebp+argv]']
mov ['edx,', '[ecx]']
push ['edx']
push ['offset', '??_C@_0CK@CCPENKNA@?$CFs?3?5can?5not?5initialize?5ICU?4?5?5sta@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['1']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+Code],', '0']
mov ['[ebp+var_60],', '0']
lea ['eax,', '[ebp+var_60]']
push ['eax']
mov ['ecx,', '[ebp+Filename]']
push ['ecx']
call ['?readFile@@YAPBDPBDPAH@Z']
add ['esp,', '8']
mov ['[ebp+var_6C],', 'eax']
cmp ['[ebp+var_6C],', '0']
jnz ['short', 'loc_765']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Filename]']
push ['eax']
push ['offset', '??_C@_0CC@GGFBKNDA@gencfu?3?5error?5reading?5file?5?5?$CC?$CFs?$CC@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['0FFFFFFFFh']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_78],', '0']
lea ['eax,', '[ebp+var_78]']
push ['eax']
mov ['ecx,', '[ebp+var_24]']
push ['ecx']
call ['?readFile@@YAPBDPBDPAH@Z']
add ['esp,', '8']
mov ['[ebp+var_84],', 'eax']
cmp ['[ebp+var_84],', '0']
jnz ['short', 'loc_7B7']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Filename]']
push ['eax']
push ['offset', '??_C@_0CC@GGFBKNDA@gencfu?3?5error?5reading?5file?5?5?$CC?$CFs?$CC@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['0FFFFFFFFh']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_D4],', '0']
mov ['[ebp+var_D0],', '0']
lea ['eax,', '[ebp+Code]']
push ['eax']
lea ['ecx,', '[ebp+var_D4]']
push ['ecx']
lea ['edx,', '[ebp+var_E0]']
push ['edx']
mov ['eax,', '[ebp+var_78]']
push ['eax']
mov ['ecx,', '[ebp+var_84]']
push ['ecx']
mov ['edx,', '[ebp+var_60]']
push ['edx']
mov ['eax,', '[ebp+var_6C]']
push ['eax']
call ['_uspoof_openFromSource_56']
add ['esp,', '1Ch']
mov ['[ebp+var_EC],', 'eax']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['?U_FAILURE@@YACW4UErrorCode@@@Z']
add ['esp,', '4']
movsx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['loc_89D']
cmp ['[ebp+var_E0],', '4']
jnz ['short', 'loc_829']
mov ['eax,', '[ebp+var_24]']
mov ['[ebp+var_220],', 'eax']
jmp ['short', 'loc_832']
mov ['ecx,', '[ebp+Filename]']
mov ['[ebp+var_220],', 'ecx']
mov ['edx,', '[ebp+var_220]']
mov ['[ebp+var_F8],', 'edx']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_D0]']
push ['eax']
mov ['ecx,', '[ebp+var_D4]']
push ['ecx']
mov ['edx,', '[ebp+var_F8]']
push ['edx']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['_u_errorName_56']
add ['esp,', '4']
push ['eax']
push ['offset', '??_C@_0EK@PGOHHDOL@gencfu?3?5uspoof_openFromSource?5er@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '18h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
lea ['eax,', '[ebp+Code]']
push ['eax']
push ['0']
push ['0']
mov ['ecx,', '[ebp+var_EC]']
push ['ecx']
call ['_uspoof_serialize_56']
add ['esp,', '10h']
mov ['[ebp+var_104],', 'eax']
cmp ['[ebp+Code],', '0Fh']
jz ['short', 'loc_90A']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['_u_errorName_56']
add ['esp,', '4']
mov ['esi,', 'esp']
push ['eax']
push ['offset', '??_C@_0CI@EGHHOIMB@gencfu?3?5uspoof_serialize?$CI?$CJ?5retur@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+Code],', '0']
mov ['eax,', '[ebp+var_104]']
push ['eax']
call ['??_U@YAPAXI@Z']
add ['esp,', '4']
mov ['[ebp+var_218],', 'eax']
mov ['ecx,', '[ebp+var_218]']
mov ['[ebp+var_110],', 'ecx']
lea ['eax,', '[ebp+Code]']
push ['eax']
mov ['ecx,', '[ebp+var_104]']
push ['ecx']
mov ['edx,', '[ebp+var_110]']
push ['edx']
mov ['eax,', '[ebp+var_EC]']
push ['eax']
call ['_uspoof_serialize_56']
add ['esp,', '10h']
push ['1']
mov ['eax,', '[ebp+var_110]']
add ['eax,', '4']
push ['eax']
call ['_uprv_checkValidMemory']
add ['esp,', '8']
push ['4']
mov ['ecx,', '[ebp+var_110]']
add ['ecx,', '4']
push ['ecx']
push ['offset', 'off_21C']
call ['_memcpy']
add ['esp,', '0Ch']
lea ['eax,', '[ebp+Code]']
push ['eax']
mov ['ecx,', '[ebp+var_48]']
push ['ecx']
push ['offset', 'dword_210']
mov ['edx,', '[ebp+Format]']
push ['edx']
push ['0']
mov ['eax,', '[ebp+var_3C]']
push ['eax']
call ['_udata_create']
add ['esp,', '18h']
mov ['[ebp+var_128],', 'eax']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['?U_FAILURE@@YACW4UErrorCode@@@Z']
add ['esp,', '4']
movsx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_A06']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['_u_errorName_56']
add ['esp,', '4']
mov ['esi,', 'esp']
push ['eax']
mov ['ecx,', '[ebp+Format]']
push ['ecx']
push ['offset', '??_C@_0CP@KIGEKLKE@gencfu?3?5Could?5not?5open?5output?5fi@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+var_104]']
push ['eax']
mov ['ecx,', '[ebp+var_110]']
push ['ecx']
mov ['edx,', '[ebp+var_128]']
push ['edx']
call ['_udata_writeBlock']
add ['esp,', '0Ch']
lea ['eax,', '[ebp+Code]']
push ['eax']
mov ['ecx,', '[ebp+var_128]']
push ['ecx']
call ['_udata_finish']
add ['esp,', '8']
mov ['[ebp+var_11C],', 'eax']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['?U_FAILURE@@YACW4UErrorCode@@@Z']
add ['esp,', '4']
movsx ['ecx,', 'al']
test ['ecx,', 'ecx']
jz ['short', 'loc_A90']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
push ['offset', '??_C@_0CK@IHKICEBE@gencfu?3?5Error?5?$CFd?5writing?5the?5out@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Code]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+var_11C]']
cmp ['eax,', '[ebp+var_104]']
jz ['short', 'loc_ADD']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+Format]']
push ['eax']
push ['offset', '??_C@_0CL@FPJDDKML@gencfu?3?5Error?5writing?5to?5output?5@']
mov ['edi,', 'esp']
call ['dword', 'ptr', 'ds:__imp____iob_func']
cmp ['edi,', 'esp']
call ['__RTC_CheckEsp']
add ['eax,', '40h']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fprintf']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
push ['0FFFFFFFFh']
call ['dword', 'ptr', 'ds:__imp__exit']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+var_EC]']
push ['eax']
call ['_uspoof_close_56']
add ['esp,', '4']
mov ['eax,', '[ebp+var_110]']
mov ['[ebp+var_20C],', 'eax']
mov ['ecx,', '[ebp+var_20C]']
push ['ecx']
call ['??_V@YAXPAX@Z']
add ['esp,', '4']
mov ['eax,', '[ebp+var_6C]']
mov ['[ebp+var_200],', 'eax']
mov ['ecx,', '[ebp+var_200]']
push ['ecx']
call ['??_V@YAXPAX@Z']
add ['esp,', '4']
mov ['eax,', '[ebp+var_84]']
mov ['[ebp+var_1F4],', 'eax']
mov ['ecx,', '[ebp+var_1F4]']
push ['ecx']
call ['??_V@YAXPAX@Z']
add ['esp,', '4']
call ['_u_cleanup_56']
movsx ['eax,', '[ebp+var_51]']
test ['eax,', 'eax']
jnz ['short', 'loc_B5E']
mov ['esi,', 'esp']
push ['offset', '??_C@_0CG@GGJHILCD@gencfu?3?5tool?5completed?5successfu@']
call ['dword', 'ptr', 'ds:__imp__printf']
add ['esp,', '4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['eax,', 'eax']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN29']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
pop ['edi']
pop ['esi']
pop ['ebx']
mov ['ecx,', '[ebp+var_4]']
xor ['ecx,', 'ebp']
call ['@__security_check_cookie@4']
add ['esp,', '220h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['10h']
dd ['offset', '$LN28']
dd ['offset', '$LN23']
dd ['0FFFFFFA0h,', '4']
dd ['offset', '$LN24']
db ['88h,', '0FFh']
dw ['0FFFFh']
dd ['4']
dd ['offset', '$LN25']
dd ['0FFFFFF2Ch,', '48h']
dd ['offset', '$LN26']
dd ['0FFFFFF20h,', '4']
dd ['offset', '$LN27']
align ['10h']
assume ['cs:_rdata']
public ['??_C@_0CG@GGJHILCD@gencfu?3?5tool?5completed?5successfu@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CL@FPJDDKML@gencfu?3?5Error?5writing?5to?5output?5@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CK@IHKICEBE@gencfu?3?5Error?5?$CFd?5writing?5the?5out@']
align ['10h']
assume ['cs:_rdata']
public ['??_C@_0CP@KIGEKLKE@gencfu?3?5Could?5not?5open?5output?5fi@']
align ['10h']
assume ['cs:_rdata']
public ['??_C@_0CI@EGHHOIMB@gencfu?3?5uspoof_serialize?$CI?$CJ?5retur@']
assume ['cs:_rdata']
public ['??_C@_0EK@PGOHHDOL@gencfu?3?5uspoof_openFromSource?5er@']
db ["'lumn", "%d',0Ah,0"]
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CC@GGFBKNDA@gencfu?3?5error?5reading?5file?5?5?$CC?$CFs?$CC@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0CK@CCPENKNA@?$CFs?3?5can?5not?5initialize?5ICU?4?5?5sta@']
align ['4']
assume ['cs:_rdata']
public ['??_C@_0GD@IBBFEJOD@?5Copyright?5?$CIC?$CJ?52015?0?5Internation@']
db ["'and", 'others.', 'All', 'Rights', 'Reserved.', "',0"]
align ['4']
assume ['cs:_rdata']
public ['??_C@_0FI@EJGIKDKB@confusables?5file?0?5whole?5script?5c@']
db ["'ust", 'all', 'be', "specified.',0Ah,0"]
assume ['cs:_rdata']
public ['??_C@_0CF@BGPNLJEE@error?5in?5command?5line?5argument?5?$CC@']
align ['4']
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_rdata,', 'fs:nothing,', 'gs:nothing']
endp
?U_FAILURE@@YACW4UErrorCode@@@Z	proc near 
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0C0h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_C0]']
mov ['ecx,', '30h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
cmp ['[ebp+arg_0],', '0']
setnle ['al']
pop ['edi']
pop ['esi']
pop ['ebx']
mov ['esp,', 'ebp']
pop ['ebp']
retn
assume ['cs:_text']
assume ['es:nothing,', 'ss:nothing,', 'ds:_rdata,', 'fs:nothing,', 'gs:nothing']
endp
?readFile@@YAPBDPBDPAH@Z proc near	
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '108h']
push ['ebx']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_108]']
mov ['ecx,', '42h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['esi,', 'esp']
push ['offset', '??_C@_02JDPG@rb?$AA@']
mov ['eax,', '[ebp+Filename]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fopen']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+File],', 'eax']
cmp ['[ebp+File],', '0']
jnz ['short', 'loc_EDD']
xor ['eax,', 'eax']
jmp ['loc_FF2']
mov ['esi,', 'esp']
push ['2']
push ['0']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fseek']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__ftell']
add ['esp,', '4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+Count],', 'eax']
mov ['esi,', 'esp']
push ['0']
push ['0']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fseek']
add ['esp,', '0Ch']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+Count]']
add ['eax,', '0Ah']
push ['eax']
call ['??_U@YAPAXI@Z']
add ['esp,', '4']
mov ['[ebp+var_104],', 'eax']
mov ['ecx,', '[ebp+var_104]']
mov ['[ebp+DstBuf],', 'ecx']
cmp ['[ebp+DstBuf],', '0']
jnz ['short', 'loc_F6B']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fclose']
add ['esp,', '4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['eax,', 'eax']
jmp ['loc_FF2']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+File]']
push ['eax']
mov ['ecx,', '[ebp+Count]']
push ['ecx']
push ['1']
mov ['edx,', '[ebp+DstBuf]']
push ['edx']
call ['dword', 'ptr', 'ds:__imp__fread']
add ['esp,', '10h']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_2C],', 'eax']
mov ['eax,', '[ebp+var_2C]']
cmp ['eax,', '[ebp+Count]']
jz ['short', 'loc_FC8']
mov ['eax,', '[ebp+DstBuf]']
mov ['[ebp+var_F8],', 'eax']
mov ['ecx,', '[ebp+var_F8]']
push ['ecx']
call ['??_V@YAXPAX@Z']
add ['esp,', '4']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fclose']
add ['esp,', '4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
xor ['eax,', 'eax']
jmp ['short', 'loc_FF2']
mov ['eax,', '[ebp+DstBuf]']
add ['eax,', '[ebp+Count]']
mov ['byte', 'ptr', '[eax],', '0']
mov ['eax,', '[ebp+arg_4]']
mov ['ecx,', '[ebp+Count]']
mov ['[eax],', 'ecx']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+File]']
push ['eax']
call ['dword', 'ptr', 'ds:__imp__fclose']
add ['esp,', '4']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+DstBuf]']
pop ['edi']
pop ['esi']
pop ['ebx']
add ['esp,', '108h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
align ['4']
assume ['cs:_rdata']
public ['??_C@_02JDPG@rb?$AA@']
extrn ['__imp__exit:near']
extrn ['_u_getDataDirectory_56:near']
extrn ['__imp__printf:near']
extrn ['__RTC_CheckEsp:near']
extrn ['__RTC_Shutdown:near']
extrn ['__RTC_InitBase:near']
extrn ['_u_cleanup_56:near']
extrn ['??_V@YAXPAX@Z:near']
extrn ['_uspoof_close_56:near']
extrn ['_udata_finish:near']
extrn ['_udata_writeBlock:near']
extrn ['_udata_create:near']
extrn ['_memcpy:near']
extrn ['_uprv_checkValidMemory:near']
extrn ['??_U@YAPAXI@Z:near']
extrn ['_uspoof_serialize_56:near']
extrn ['_uspoof_openFromSource_56:near']
extrn ['_u_errorName_56:near']
extrn ['_u_init_56:near']
extrn ['_u_setDataDirectory_56:near']
extrn ['__imp__fprintf:near']
extrn ['__imp____iob_func:near']
extrn ['_u_parseArgs:near']
extrn ['___security_cookie:near']
extrn ['@__security_check_cookie@4:near']
extrn ['@_RTC_CheckStackVars@8:near']
extrn ['__imp__fread:near']
extrn ['__imp__fclose:near']
extrn ['__imp__ftell:near']
extrn ['__imp__fseek:near']
extrn ['__imp__fopen:near']
end
