_schedule_timer proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0Ch']
push ['esi']
mov ['[ebp+var_C],', '0CCCCCCCCh']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
call ['_init_timers']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetTickCount@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['ds:_now,', 'eax']
mov ['eax,', '[ebp+arg_0]']
add ['eax,', 'ds:_now']
mov ['[ebp+var_4],', 'eax']
mov ['ecx,', '[ebp+var_4]']
sub ['ecx,', 'ds:_now']
jnz ['short', 'loc_64']
mov ['edx,', 'ds:_now']
add ['edx,', '1']
mov ['[ebp+var_4],', 'edx']
push ['10h']
push ['1']
call ['_safemalloc']
add ['esp,', '8']
mov ['[ebp+var_8],', 'eax']
mov ['eax,', '[ebp+var_8]']
mov ['ecx,', '[ebp+arg_4]']
mov ['[eax],', 'ecx']
mov ['edx,', '[ebp+var_8]']
mov ['eax,', '[ebp+arg_8]']
mov ['[edx+4],', 'eax']
mov ['ecx,', '[ebp+var_8]']
mov ['edx,', '[ebp+var_4]']
mov ['[ecx+8],', 'edx']
mov ['eax,', '[ebp+var_8]']
mov ['ecx,', 'ds:_now']
mov ['[eax+0Ch],', 'ecx']
mov ['edx,', '[ebp+var_8]']
push ['edx']
mov ['eax,', 'ds:_timers']
push ['eax']
call ['_add234']
add ['esp,', '8']
cmp ['[ebp+var_8],', 'eax']
jz ['short', 'loc_BE']
mov ['ecx,', '[ebp+var_8]']
push ['ecx']
call ['_safefree']
add ['esp,', '4']
jmp ['short', 'loc_D4']
mov ['edx,', '[ebp+var_8]']
mov ['eax,', '[edx+4]']
push ['eax']
mov ['ecx,', 'ds:_timer_contexts']
push ['ecx']
call ['_add234']
add ['esp,', '8']
push ['0']
mov ['edx,', 'ds:_timers']
push ['edx']
call ['_index234']
add ['esp,', '8']
mov ['[ebp+var_C],', 'eax']
mov ['eax,', '[ebp+var_C]']
cmp ['eax,', '[ebp+var_8]']
jnz ['short', 'loc_FF']
mov ['ecx,', '[ebp+var_C]']
mov ['edx,', '[ecx+8]']
push ['edx']
call ['_timer_change_notify']
add ['esp,', '4']
mov ['eax,', '[ebp+var_4]']
pop ['esi']
add ['esp,', '0Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_init_timers    proc near               
push ['ebp']
mov ['ebp,', 'esp']
push ['esi']
cmp ['ds:_timers,', '0']
jnz ['short', 'loc_161']
push ['offset', '_compare_timers']
call ['_newtree234']
add ['esp,', '4']
mov ['ds:_timers,', 'eax']
push ['offset', '_compare_timer_contexts']
call ['_newtree234']
add ['esp,', '4']
mov ['ds:_timer_contexts,', 'eax']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetTickCount@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['ds:_now,', 'eax']
pop ['esi']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_compare_timers proc near               
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '10h']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_C],', 'eax']
mov ['[ebp+var_8],', 'eax']
mov ['[ebp+var_4],', 'eax']
mov ['eax,', '[ebp+arg_0]']
mov ['[ebp+var_4],', 'eax']
mov ['ecx,', '[ebp+arg_4]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+8]']
sub ['eax,', 'ds:_now']
mov ['[ebp+var_C],', 'eax']
mov ['ecx,', '[ebp+var_8]']
mov ['edx,', '[ecx+8]']
sub ['edx,', 'ds:_now']
mov ['[ebp+var_10],', 'edx']
mov ['eax,', '[ebp+var_C]']
cmp ['eax,', '[ebp+var_10]']
jge ['short', 'loc_1BC']
or ['eax,', '0FFFFFFFFh']
jmp ['short', 'loc_21D']
jmp ['short', 'loc_1CB']
mov ['ecx,', '[ebp+var_C]']
cmp ['ecx,', '[ebp+var_10]']
jle ['short', 'loc_1CB']
mov ['eax,', '1']
jmp ['short', 'loc_21D']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_8]']
mov ['ecx,', '[edx]']
cmp ['ecx,', '[eax]']
jnb ['short', 'loc_1DE']
or ['eax,', '0FFFFFFFFh']
jmp ['short', 'loc_21D']
jmp ['short', 'loc_1F1']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_8]']
mov ['ecx,', '[edx]']
cmp ['ecx,', '[eax]']
jbe ['short', 'loc_1F1']
mov ['eax,', '1']
jmp ['short', 'loc_21D']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_8]']
mov ['ecx,', '[edx+4]']
cmp ['ecx,', '[eax+4]']
jnb ['short', 'loc_206']
or ['eax,', '0FFFFFFFFh']
jmp ['short', 'loc_21D']
jmp ['short', 'loc_21B']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_8]']
mov ['ecx,', '[edx+4]']
cmp ['ecx,', '[eax+4]']
jbe ['short', 'loc_21B']
mov ['eax,', '1']
jmp ['short', 'loc_21D']
xor ['eax,', 'eax']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_compare_timer_contexts proc near       
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['eax,', '[ebp+arg_0]']
mov ['[ebp+var_4],', 'eax']
mov ['ecx,', '[ebp+arg_4]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_4]']
cmp ['edx,', '[ebp+var_8]']
jnb ['short', 'loc_25B']
or ['eax,', '0FFFFFFFFh']
jmp ['short', 'loc_26C']
jmp ['short', 'loc_26A']
mov ['eax,', '[ebp+var_4]']
cmp ['eax,', '[ebp+var_8]']
jbe ['short', 'loc_26A']
mov ['eax,', '1']
jmp ['short', 'loc_26C']
xor ['eax,', 'eax']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_run_timers     proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
push ['esi']
mov ['[ebp+var_4],', '0CCCCCCCCh']
call ['_init_timers']
mov ['esi,', 'esp']
call ['dword', 'ptr', 'ds:__imp__GetTickCount@0']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['ds:_now,', 'eax']
mov ['eax,', '1']
test ['eax,', 'eax']
jz ['loc_386']
push ['0']
mov ['ecx,', 'ds:_timers']
push ['ecx']
call ['_index234']
add ['esp,', '8']
mov ['[ebp+var_4],', 'eax']
cmp ['[ebp+var_4],', '0']
jnz ['short', 'loc_2CF']
xor ['eax,', 'eax']
jmp ['loc_386']
push ['0']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+4]']
push ['eax']
mov ['ecx,', 'ds:_timer_contexts']
push ['ecx']
call ['_find234']
add ['esp,', '0Ch']
test ['eax,', 'eax']
jnz ['short', 'loc_30A']
push ['0']
mov ['edx,', 'ds:_timers']
push ['edx']
call ['_delpos234']
add ['esp,', '8']
mov ['eax,', '[ebp+var_4]']
push ['eax']
call ['_safefree']
add ['esp,', '4']
jmp ['short', 'loc_381']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+0Ch]']
sub ['edx,', '0Ah']
mov ['eax,', 'ds:_now']
sub ['eax,', 'edx']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+0Ch]']
sub ['edx,', '0Ah']
mov ['ecx,', '[ebp+var_4]']
mov ['ecx,', '[ecx+8]']
sub ['ecx,', 'edx']
cmp ['eax,', 'ecx']
jbe ['short', 'loc_36F']
push ['0']
mov ['edx,', 'ds:_timers']
push ['edx']
call ['_delpos234']
add ['esp,', '8']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+8]']
push ['ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+4]']
push ['eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
call ['edx']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['eax,', '[ebp+var_4]']
push ['eax']
call ['_safefree']
add ['esp,', '4']
jmp ['short', 'loc_381']
mov ['ecx,', '[ebp+arg_4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+8]']
mov ['[ecx],', 'eax']
mov ['eax,', '1']
jmp ['short', 'loc_386']
jmp ['loc_2A1']
pop ['esi']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_expire_timer_context proc near
push ['ebp']
mov ['ebp,', 'esp']
call ['_init_timers']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
mov ['ecx,', 'ds:_timer_contexts']
push ['ecx']
call ['_del234']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
