_newtree234     proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
push ['8']
push ['1']
call ['_safemalloc']
add ['esp,', '8']
mov ['[ebp+var_4],', 'eax']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax],', '0']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+arg_0]']
mov ['[ecx+4],', 'edx']
mov ['eax,', '[ebp+var_4]']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_freetree234    proc near
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
push ['ecx']
call ['_freenode234']
add ['esp,', '4']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
call ['_safefree']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_freenode234    proc near               
push ['ebp']
mov ['ebp,', 'esp']
cmp ['[ebp+arg_0],', '0']
jnz ['short', 'loc_103']
jmp ['short', 'loc_14B']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax+4]']
push ['ecx']
call ['_freenode234']
add ['esp,', '4']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx+8]']
push ['eax']
call ['_freenode234']
add ['esp,', '4']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx+0Ch]']
push ['edx']
call ['_freenode234']
add ['esp,', '4']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax+10h]']
push ['ecx']
call ['_freenode234']
add ['esp,', '4']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
call ['_safefree']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_count234       proc near
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+arg_0]']
cmp ['dword', 'ptr', '[eax],', '0']
jz ['short', 'loc_175']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
push ['edx']
call ['_countnode234']
add ['esp,', '4']
jmp ['short', 'loc_177']
jmp ['short', 'loc_177']
xor ['eax,', 'eax']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_countnode234   proc near               
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '8']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0']
cmp ['[ebp+arg_0],', '0']
jnz ['short', 'loc_1AD']
xor ['eax,', 'eax']
jmp ['short', 'loc_20A']
mov ['[ebp+var_8],', '0']
jmp ['short', 'loc_1BF']
mov ['eax,', '[ebp+var_8]']
add ['eax,', '1']
mov ['[ebp+var_8],', 'eax']
cmp ['[ebp+var_8],', '4']
jge ['short', 'loc_1D7']
mov ['ecx,', '[ebp+var_8]']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[ebp+var_4]']
add ['eax,', '[edx+ecx*4+14h]']
mov ['[ebp+var_4],', 'eax']
jmp ['short', 'loc_1B6']
mov ['[ebp+var_8],', '0']
jmp ['short', 'loc_1E9']
mov ['ecx,', '[ebp+var_8]']
add ['ecx,', '1']
mov ['[ebp+var_8],', 'ecx']
cmp ['[ebp+var_8],', '3']
jge ['short', 'loc_207']
mov ['edx,', '[ebp+var_8]']
mov ['eax,', '[ebp+arg_0]']
cmp ['dword', 'ptr', '[eax+edx*4+24h],', '0']
jz ['short', 'loc_205']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '1']
mov ['[ebp+var_4],', 'ecx']
jmp ['short', 'loc_1E0']
mov ['eax,', '[ebp+var_4]']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_add234         proc near
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+arg_0]']
cmp ['dword', 'ptr', '[eax+4],', '0']
jnz ['short', 'loc_228']
xor ['eax,', 'eax']
jmp ['short', 'loc_23A']
push ['0FFFFFFFFh']
mov ['ecx,', '[ebp+arg_4]']
push ['ecx']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
call ['_add234_internal']
add ['esp,', '0Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_add234_internal proc near              
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '44h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_44]']
mov ['ecx,', '11h']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['eax,', '[ebp+arg_4]']
mov ['[ebp+var_14],', 'eax']
mov ['ecx,', '[ebp+arg_0]']
cmp ['dword', 'ptr', '[ecx],', '0']
jnz ['loc_318']
push ['30h']
push ['1']
call ['_safemalloc']
add ['esp,', '8']
mov ['edx,', '[ebp+arg_0]']
mov ['[edx],', 'eax']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['dword', 'ptr', '[ecx+2Ch],', '0']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx]']
mov ['dword', 'ptr', '[eax+28h],', '0']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['dword', 'ptr', '[edx+8],', '0']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['dword', 'ptr', '[ecx+4],', '0']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx]']
mov ['dword', 'ptr', '[eax+10h],', '0']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['dword', 'ptr', '[edx+0Ch],', '0']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['dword', 'ptr', '[ecx+18h],', '0']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx]']
mov ['dword', 'ptr', '[eax+14h],', '0']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['dword', 'ptr', '[edx+20h],', '0']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['dword', 'ptr', '[ecx+1Ch],', '0']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx]']
mov ['dword', 'ptr', '[eax],', '0']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['eax,', '[ebp+arg_4]']
mov ['[edx+24h],', 'eax']
mov ['eax,', '[ebp+var_14]']
jmp ['loc_CD4']
mov ['[ebp+var_4],', '0']
mov ['ecx,', '[ebp+arg_0]']
mov ['[ebp+var_8],', 'ecx']
mov ['edx,', '[ebp+var_8]']
cmp ['dword', 'ptr', '[edx],', '0']
jz ['loc_4EB']
mov ['eax,', '[ebp+var_8]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_4],', 'ecx']
cmp ['[ebp+arg_8],', '0']
jl ['loc_3EE']
mov ['edx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[edx+4],', '0']
jnz ['short', 'loc_357']
mov ['eax,', '[ebp+arg_8]']
mov ['[ebp+var_24],', 'eax']
jmp ['loc_3E9']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+arg_8]']
cmp ['edx,', '[ecx+14h]']
jg ['short', 'loc_36B']
mov ['[ebp+var_24],', '0']
jmp ['short', 'loc_3E9']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+14h]']
add ['ecx,', '1']
mov ['edx,', '[ebp+arg_8]']
sub ['edx,', 'ecx']
mov ['[ebp+arg_8],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+arg_8]']
cmp ['ecx,', '[eax+18h]']
jg ['short', 'loc_390']
mov ['[ebp+var_24],', '1']
jmp ['short', 'loc_3E9']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+18h]']
add ['eax,', '1']
mov ['ecx,', '[ebp+arg_8]']
sub ['ecx,', 'eax']
mov ['[ebp+arg_8],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+arg_8]']
cmp ['eax,', '[edx+1Ch]']
jg ['short', 'loc_3B5']
mov ['[ebp+var_24],', '2']
jmp ['short', 'loc_3E9']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+1Ch]']
add ['edx,', '1']
mov ['eax,', '[ebp+arg_8]']
sub ['eax,', 'edx']
mov ['[ebp+arg_8],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+arg_8]']
cmp ['edx,', '[ecx+20h]']
jg ['short', 'loc_3DA']
mov ['[ebp+var_24],', '3']
jmp ['short', 'loc_3E9']
xor ['eax,', 'eax']
jmp ['loc_CD4']
xor ['eax,', 'eax']
jnz ['loc_357']
jmp ['loc_4D9']
mov ['esi,', 'esp']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+24h]']
push ['edx']
mov ['eax,', '[ebp+arg_4]']
push ['eax']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx+4]']
call ['edx']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_18],', 'eax']
cmp ['[ebp+var_18],', '0']
jge ['short', 'loc_422']
mov ['[ebp+var_24],', '0']
jmp ['loc_4D9']
cmp ['[ebp+var_18],', '0']
jnz ['short', 'loc_438']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax+24h]']
jmp ['loc_CD4']
jmp ['loc_4D9']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+28h],', '0']
jz ['short', 'loc_469']
mov ['esi,', 'esp']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+28h]']
push ['eax']
mov ['ecx,', '[ebp+arg_4]']
push ['ecx']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx+4]']
call ['eax']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_18],', 'eax']
cmp ['[ebp+var_18],', '0']
jge ['short', 'loc_472']
mov ['[ebp+var_24],', '1']
jmp ['short', 'loc_4D9']
cmp ['[ebp+var_18],', '0']
jnz ['short', 'loc_485']
mov ['ecx,', '[ebp+var_4]']
mov ['eax,', '[ecx+28h]']
jmp ['loc_CD4']
jmp ['short', 'loc_4D9']
mov ['edx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[edx+2Ch],', '0']
jz ['short', 'loc_4B6']
mov ['esi,', 'esp']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+2Ch]']
push ['ecx']
mov ['edx,', '[ebp+arg_4]']
push ['edx']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax+4]']
call ['ecx']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_18],', 'eax']
cmp ['[ebp+var_18],', '0']
jge ['short', 'loc_4BF']
mov ['[ebp+var_24],', '2']
jmp ['short', 'loc_4D9']
cmp ['[ebp+var_18],', '0']
jnz ['short', 'loc_4D2']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+2Ch]']
jmp ['loc_CD4']
jmp ['short', 'loc_4D9']
mov ['[ebp+var_24],', '3']
mov ['eax,', '[ebp+var_24]']
mov ['ecx,', '[ebp+var_4]']
lea ['edx,', '[ecx+eax*4+4]']
mov ['[ebp+var_8],', 'edx']
jmp ['loc_325']
mov ['[ebp+var_C],', '0']
mov ['[ebp+var_1C],', '0']
mov ['[ebp+var_10],', '0']
mov ['[ebp+var_20],', '0']
cmp ['[ebp+var_4],', '0']
jz ['loc_B75']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax+28h],', '0']
jnz ['loc_5EF']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '4']
cmp ['[ebp+var_8],', 'ecx']
jnz ['short', 'loc_57C']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+8]']
mov ['[edx+0Ch],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+18h]']
mov ['[edx+1Ch],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+24h]']
mov ['[edx+28h],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_10]']
mov ['[edx+8],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_20]']
mov ['[ecx+18h],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+arg_4]']
mov ['[eax+24h],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_C]']
mov ['[edx+4],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_1C]']
mov ['[ecx+14h],', 'edx']
jmp ['short', 'loc_5A9']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_10]']
mov ['[eax+0Ch],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_20]']
mov ['[edx+1Ch],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+arg_4]']
mov ['[ecx+28h],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_C]']
mov ['[eax+8],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_1C]']
mov ['[edx+18h],', 'eax']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+4],', '0']
jz ['short', 'loc_5BD']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+4]']
mov ['ecx,', '[ebp+var_4]']
mov ['[eax],', 'ecx']
mov ['edx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[edx+8],', '0']
jz ['short', 'loc_5D1']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+8]']
mov ['edx,', '[ebp+var_4]']
mov ['[ecx],', 'edx']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax+0Ch],', '0']
jz ['short', 'loc_5E5']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+0Ch]']
mov ['eax,', '[ebp+var_4]']
mov ['[edx],', 'eax']
jmp ['loc_B75']
jmp ['loc_AF5']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+2Ch],', '0']
jnz ['loc_766']
mov ['edx,', '[ebp+var_4]']
add ['edx,', '4']
cmp ['[ebp+var_8],', 'edx']
jnz ['short', 'loc_681']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+0Ch]']
mov ['[eax+10h],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+1Ch]']
mov ['[eax+20h],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+28h]']
mov ['[eax+2Ch],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+8]']
mov ['[eax+0Ch],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+18h]']
mov ['[eax+1Ch],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+24h]']
mov ['[eax+28h],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_10]']
mov ['[eax+8],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_20]']
mov ['[edx+18h],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+arg_4]']
mov ['[ecx+24h],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_C]']
mov ['[eax+4],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_1C]']
mov ['[edx+14h],', 'eax']
jmp ['loc_70C']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '8']
cmp ['[ebp+var_8],', 'ecx']
jnz ['short', 'loc_6DF']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+0Ch]']
mov ['[edx+10h],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+1Ch]']
mov ['[edx+20h],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+28h]']
mov ['[edx+2Ch],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_10]']
mov ['[edx+0Ch],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_20]']
mov ['[ecx+1Ch],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+arg_4]']
mov ['[eax+28h],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_C]']
mov ['[edx+8],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_1C]']
mov ['[ecx+18h],', 'edx']
jmp ['short', 'loc_70C']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_10]']
mov ['[eax+10h],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_20]']
mov ['[edx+20h],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+arg_4]']
mov ['[ecx+2Ch],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_C]']
mov ['[eax+0Ch],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_1C]']
mov ['[edx+1Ch],', 'eax']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+4],', '0']
jz ['short', 'loc_720']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+4]']
mov ['ecx,', '[ebp+var_4]']
mov ['[eax],', 'ecx']
mov ['edx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[edx+8],', '0']
jz ['short', 'loc_734']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+8]']
mov ['edx,', '[ebp+var_4]']
mov ['[ecx],', 'edx']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax+0Ch],', '0']
jz ['short', 'loc_748']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+0Ch]']
mov ['eax,', '[ebp+var_4]']
mov ['[edx],', 'eax']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+10h],', '0']
jz ['short', 'loc_75C']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+10h]']
mov ['ecx,', '[ebp+var_4]']
mov ['[eax],', 'ecx']
jmp ['loc_B75']
jmp ['loc_AF5']
push ['30h']
push ['1']
call ['_safemalloc']
add ['esp,', '8']
mov ['[ebp+var_28],', 'eax']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['[edx],', 'ecx']
mov ['edx,', '[ebp+var_4]']
add ['edx,', '4']
cmp ['[ebp+var_8],', 'edx']
jnz ['loc_829']
mov ['eax,', '[ebp+var_28]']
mov ['ecx,', '[ebp+var_C]']
mov ['[eax+4],', 'ecx']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+var_1C]']
mov ['[edx+14h],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+arg_4]']
mov ['[ecx+24h],', 'edx']
mov ['eax,', '[ebp+var_28]']
mov ['ecx,', '[ebp+var_10]']
mov ['[eax+8],', 'ecx']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+var_20]']
mov ['[edx+18h],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+24h]']
mov ['[ecx+28h],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+8]']
mov ['[ecx+0Ch],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+18h]']
mov ['[ecx+1Ch],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+28h]']
mov ['[ebp+arg_4],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+0Ch]']
mov ['[eax+4],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+1Ch]']
mov ['[eax+14h],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+2Ch]']
mov ['[eax+24h],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+10h]']
mov ['[eax+8],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+20h]']
mov ['[eax+18h],', 'edx']
jmp ['loc_A0D']
mov ['eax,', '[ebp+var_4]']
add ['eax,', '8']
cmp ['[ebp+var_8],', 'eax']
jnz ['loc_8D3']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+4]']
mov ['[ecx+4],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+14h]']
mov ['[ecx+14h],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+24h]']
mov ['[ecx+24h],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_C]']
mov ['[ecx+8],', 'edx']
mov ['eax,', '[ebp+var_28]']
mov ['ecx,', '[ebp+var_1C]']
mov ['[eax+18h],', 'ecx']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+arg_4]']
mov ['[edx+28h],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_10]']
mov ['[ecx+0Ch],', 'edx']
mov ['eax,', '[ebp+var_28]']
mov ['ecx,', '[ebp+var_20]']
mov ['[eax+1Ch],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+28h]']
mov ['[ebp+arg_4],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+0Ch]']
mov ['[ecx+4],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+1Ch]']
mov ['[ecx+14h],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+2Ch]']
mov ['[ecx+24h],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+10h]']
mov ['[ecx+8],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+20h]']
mov ['[ecx+18h],', 'eax']
jmp ['loc_A0D']
mov ['ecx,', '[ebp+var_4]']
add ['ecx,', '0Ch']
cmp ['[ebp+var_8],', 'ecx']
jnz ['loc_977']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+4]']
mov ['[edx+4],', 'ecx']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+14h]']
mov ['[edx+14h],', 'ecx']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+24h]']
mov ['[edx+24h],', 'ecx']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+8]']
mov ['[edx+8],', 'ecx']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+18h]']
mov ['[edx+18h],', 'ecx']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+28h]']
mov ['[edx+28h],', 'ecx']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[ebp+var_C]']
mov ['[edx+0Ch],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_1C]']
mov ['[ecx+1Ch],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_10]']
mov ['[eax+4],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_20]']
mov ['[edx+14h],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+2Ch]']
mov ['[ecx+24h],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+10h]']
mov ['[ecx+8],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+20h]']
mov ['[ecx+18h],', 'eax']
jmp ['loc_A0D']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+4]']
mov ['[ecx+4],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+14h]']
mov ['[ecx+14h],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+24h]']
mov ['[ecx+24h],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+8]']
mov ['[ecx+8],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+18h]']
mov ['[ecx+18h],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+28h]']
mov ['[ecx+28h],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+0Ch]']
mov ['[ecx+0Ch],', 'eax']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+1Ch]']
mov ['[ecx+1Ch],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_C]']
mov ['[ecx+4],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_1C]']
mov ['[eax+14h],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+arg_4]']
mov ['[edx+24h],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_10]']
mov ['[ecx+8],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_20]']
mov ['[eax+18h],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+2Ch]']
mov ['[ebp+arg_4],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+0Ch],', '0']
mov ['edx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[edx+10h],', '0']
mov ['eax,', '[ebp+var_28]']
mov ['dword', 'ptr', '[eax+10h],', '0']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+1Ch],', '0']
mov ['edx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[edx+20h],', '0']
mov ['eax,', '[ebp+var_28]']
mov ['dword', 'ptr', '[eax+20h],', '0']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+28h],', '0']
mov ['edx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[edx+2Ch],', '0']
mov ['eax,', '[ebp+var_28]']
mov ['dword', 'ptr', '[eax+2Ch],', '0']
mov ['ecx,', '[ebp+var_28]']
cmp ['dword', 'ptr', '[ecx+4],', '0']
jz ['short', 'loc_A7B']
mov ['edx,', '[ebp+var_28]']
mov ['eax,', '[edx+4]']
mov ['ecx,', '[ebp+var_28]']
mov ['[eax],', 'ecx']
mov ['edx,', '[ebp+var_28]']
cmp ['dword', 'ptr', '[edx+8],', '0']
jz ['short', 'loc_A8F']
mov ['eax,', '[ebp+var_28]']
mov ['ecx,', '[eax+8]']
mov ['edx,', '[ebp+var_28]']
mov ['[ecx],', 'edx']
mov ['eax,', '[ebp+var_28]']
cmp ['dword', 'ptr', '[eax+0Ch],', '0']
jz ['short', 'loc_AA3']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ecx+0Ch]']
mov ['eax,', '[ebp+var_28]']
mov ['[edx],', 'eax']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+4],', '0']
jz ['short', 'loc_AB7']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+4]']
mov ['ecx,', '[ebp+var_4]']
mov ['[eax],', 'ecx']
mov ['edx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[edx+8],', '0']
jz ['short', 'loc_ACB']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+8]']
mov ['edx,', '[ebp+var_4]']
mov ['[ecx],', 'edx']
mov ['eax,', '[ebp+var_28]']
mov ['[ebp+var_C],', 'eax']
mov ['ecx,', '[ebp+var_C]']
push ['ecx']
call ['_countnode234']
add ['esp,', '4']
mov ['[ebp+var_1C],', 'eax']
mov ['edx,', '[ebp+var_4]']
mov ['[ebp+var_10],', 'edx']
mov ['eax,', '[ebp+var_10]']
push ['eax']
call ['_countnode234']
add ['esp,', '4']
mov ['[ebp+var_20],', 'eax']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx],', '0']
jz ['short', 'loc_B68']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
mov ['ecx,', '[eax+4]']
cmp ['ecx,', '[ebp+var_4]']
jnz ['short', 'loc_B17']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
add ['eax,', '4']
mov ['[ebp+var_34],', 'eax']
jmp ['short', 'loc_B62']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
mov ['eax,', '[edx+8]']
cmp ['eax,', '[ebp+var_4]']
jnz ['short', 'loc_B31']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
add ['edx,', '8']
mov ['[ebp+var_38],', 'edx']
jmp ['short', 'loc_B5C']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ecx+0Ch]']
cmp ['edx,', '[ebp+var_4]']
jnz ['short', 'loc_B4B']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
add ['ecx,', '0Ch']
mov ['[ebp+var_3C],', 'ecx']
jmp ['short', 'loc_B56']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
add ['eax,', '10h']
mov ['[ebp+var_3C],', 'eax']
mov ['ecx,', '[ebp+var_3C]']
mov ['[ebp+var_38],', 'ecx']
mov ['edx,', '[ebp+var_38]']
mov ['[ebp+var_34],', 'edx']
mov ['eax,', '[ebp+var_34]']
mov ['[ebp+var_8],', 'eax']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
mov ['[ebp+var_4],', 'edx']
jmp ['loc_507']
cmp ['[ebp+var_4],', '0']
jz ['loc_C02']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax],', '0']
jz ['short', 'loc_BFD']
mov ['ecx,', '[ebp+var_4]']
push ['ecx']
call ['_countnode234']
add ['esp,', '4']
mov ['[ebp+var_2C],', 'eax']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
mov ['ecx,', '[eax+4]']
cmp ['ecx,', '[ebp+var_4]']
jnz ['short', 'loc_BAC']
mov ['[ebp+var_40],', '0']
jmp ['short', 'loc_BDE']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
mov ['ecx,', '[eax+8]']
cmp ['ecx,', '[ebp+var_4]']
jnz ['short', 'loc_BC2']
mov ['[ebp+var_44],', '1']
jmp ['short', 'loc_BD8']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
mov ['ecx,', '[eax+0Ch]']
xor ['edx,', 'edx']
cmp ['ecx,', '[ebp+var_4]']
setnz ['dl']
add ['edx,', '2']
mov ['[ebp+var_44],', 'edx']
mov ['eax,', '[ebp+var_44]']
mov ['[ebp+var_40],', 'eax']
mov ['ecx,', '[ebp+var_40]']
mov ['[ebp+var_30],', 'ecx']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
mov ['ecx,', '[ebp+var_30]']
mov ['edx,', '[ebp+var_2C]']
mov ['[eax+ecx*4+14h],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_4],', 'ecx']
jmp ['short', 'loc_B7F']
jmp ['loc_CD1']
push ['30h']
push ['1']
call ['_safemalloc']
add ['esp,', '8']
mov ['edx,', '[ebp+arg_0]']
mov ['[edx],', 'eax']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ebp+var_C]']
mov ['[ecx+4],', 'edx']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ebp+var_1C]']
mov ['[ecx+14h],', 'edx']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ebp+arg_4]']
mov ['[ecx+24h],', 'edx']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ebp+var_10]']
mov ['[ecx+8],', 'edx']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ebp+var_20]']
mov ['[ecx+18h],', 'edx']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['dword', 'ptr', '[ecx+28h],', '0']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx]']
mov ['dword', 'ptr', '[eax+0Ch],', '0']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['dword', 'ptr', '[edx+1Ch],', '0']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['dword', 'ptr', '[ecx+2Ch],', '0']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx]']
mov ['dword', 'ptr', '[eax+10h],', '0']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['dword', 'ptr', '[edx+20h],', '0']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['dword', 'ptr', '[ecx],', '0']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx]']
cmp ['dword', 'ptr', '[eax+4],', '0']
jz ['short', 'loc_CB7']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['eax,', '[edx+4]']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
mov ['[eax],', 'edx']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
cmp ['dword', 'ptr', '[ecx+8],', '0']
jz ['short', 'loc_CD1']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx]']
mov ['ecx,', '[eax+8]']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[edx]']
mov ['[ecx],', 'eax']
mov ['eax,', '[ebp+var_14]']
pop ['edi']
pop ['esi']
add ['esp,', '44h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_addpos234      proc near
push ['ebp']
mov ['ebp,', 'esp']
cmp ['[ebp+arg_8],', '0']
jl ['short', 'loc_CFA']
mov ['eax,', '[ebp+arg_0]']
cmp ['dword', 'ptr', '[eax+4],', '0']
jz ['short', 'loc_CFE']
xor ['eax,', 'eax']
jmp ['short', 'loc_D12']
mov ['ecx,', '[ebp+arg_8]']
push ['ecx']
mov ['edx,', '[ebp+arg_4]']
push ['edx']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['_add234_internal']
add ['esp,', '0Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_index234       proc near               
push ['ebp']
mov ['ebp,', 'esp']
push ['ecx']
mov ['[ebp+var_4],', '0CCCCCCCCh']
mov ['eax,', '[ebp+arg_0]']
cmp ['dword', 'ptr', '[eax],', '0']
jnz ['short', 'loc_D42']
xor ['eax,', 'eax']
jmp ['loc_E20']
cmp ['[ebp+arg_4],', '0']
jl ['short', 'loc_D5B']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx]']
push ['edx']
call ['_countnode234']
add ['esp,', '4']
cmp ['[ebp+arg_4],', 'eax']
jl ['short', 'loc_D62']
xor ['eax,', 'eax']
jmp ['loc_E20']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_4],', 'ecx']
cmp ['[ebp+var_4],', '0']
jz ['loc_E1E']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+arg_4]']
cmp ['eax,', '[edx+14h]']
jge ['short', 'loc_D8D']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+4]']
mov ['[ebp+var_4],', 'edx']
jmp ['loc_E19']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+14h]']
add ['ecx,', '1']
mov ['edx,', '[ebp+arg_4]']
sub ['edx,', 'ecx']
mov ['[ebp+arg_4],', 'edx']
jns ['short', 'loc_DAA']
mov ['eax,', '[ebp+var_4]']
mov ['eax,', '[eax+24h]']
jmp ['short', 'loc_E20']
jmp ['short', 'loc_E19']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+arg_4]']
cmp ['edx,', '[ecx+18h]']
jge ['short', 'loc_DC0']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+8]']
mov ['[ebp+var_4],', 'ecx']
jmp ['short', 'loc_E19']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+18h]']
add ['eax,', '1']
mov ['ecx,', '[ebp+arg_4]']
sub ['ecx,', 'eax']
mov ['[ebp+arg_4],', 'ecx']
jns ['short', 'loc_DDD']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+28h]']
jmp ['short', 'loc_E20']
jmp ['short', 'loc_E19']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+arg_4]']
cmp ['ecx,', '[eax+1Ch]']
jge ['short', 'loc_DF3']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+0Ch]']
mov ['[ebp+var_4],', 'eax']
jmp ['short', 'loc_E19']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+1Ch]']
add ['edx,', '1']
mov ['eax,', '[ebp+arg_4]']
sub ['eax,', 'edx']
mov ['[ebp+arg_4],', 'eax']
jns ['short', 'loc_E10']
mov ['ecx,', '[ebp+var_4]']
mov ['eax,', '[ecx+2Ch]']
jmp ['short', 'loc_E20']
jmp ['short', 'loc_E19']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+10h]']
mov ['[ebp+var_4],', 'eax']
jmp ['loc_D6A']
xor ['eax,', 'eax']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_findrelpos234  proc near               
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '20h']
push ['esi']
mov ['eax,', '0CCCCCCCCh']
mov ['[ebp+var_20],', 'eax']
mov ['[ebp+var_1C],', 'eax']
mov ['[ebp+var_18],', 'eax']
mov ['[ebp+var_14],', 'eax']
mov ['[ebp+var_10],', 'eax']
mov ['[ebp+var_C],', 'eax']
mov ['[ebp+var_8],', 'eax']
mov ['[ebp+var_4],', 'eax']
mov ['eax,', '[ebp+arg_0]']
cmp ['dword', 'ptr', '[eax],', '0']
jnz ['short', 'loc_E6B']
xor ['eax,', 'eax']
jmp ['loc_104A']
cmp ['[ebp+arg_8],', '0']
jnz ['short', 'loc_E7A']
mov ['ecx,', '[ebp+arg_0]']
mov ['edx,', '[ecx+4]']
mov ['[ebp+arg_8],', 'edx']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_4],', 'ecx']
mov ['[ebp+var_10],', '0']
mov ['[ebp+var_14],', '0FFFFFFFFh']
mov ['[ebp+var_1C],', '0']
cmp ['[ebp+arg_4],', '0']
jnz ['short', 'loc_EDC']
cmp ['[ebp+arg_C],', '1']
jz ['short', 'loc_EC0']
cmp ['[ebp+arg_C],', '3']
jz ['short', 'loc_EC0']
push ['21Bh']
push ['offset', '$SG5139']
push ['offset', '$SG5140']
call ['__wassert']
add ['esp,', '0Ch']
cmp ['[ebp+arg_C],', '1']
jnz ['short', 'loc_ECF']
mov ['[ebp+var_1C],', '1']
jmp ['short', 'loc_EDC']
cmp ['[ebp+arg_C],', '3']
jnz ['short', 'loc_EDC']
mov ['[ebp+var_1C],', '0FFFFFFFFh']
mov ['eax,', '1']
test ['eax,', 'eax']
jz ['loc_FB9']
mov ['[ebp+var_18],', '0']
jmp ['short', 'loc_EFB']
mov ['ecx,', '[ebp+var_18]']
add ['ecx,', '1']
mov ['[ebp+var_18],', 'ecx']
cmp ['[ebp+var_18],', '4']
jge ['loc_F8E']
cmp ['[ebp+var_18],', '3']
jge ['short', 'loc_F53']
mov ['edx,', '[ebp+var_18]']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax+edx*4+24h],', '0']
jz ['short', 'loc_F53']
cmp ['[ebp+var_1C],', '0']
jz ['short', 'loc_F26']
mov ['ecx,', '[ebp+var_1C]']
mov ['[ebp+var_20],', 'ecx']
jmp ['short', 'loc_F47']
mov ['esi,', 'esp']
mov ['edx,', '[ebp+var_18]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+edx*4+24h]']
push ['ecx']
mov ['edx,', '[ebp+arg_4]']
push ['edx']
call ['[ebp+arg_8]']
add ['esp,', '8']
cmp ['esi,', 'esp']
call ['__RTC_CheckEsp']
mov ['[ebp+var_20],', 'eax']
mov ['eax,', '[ebp+var_20]']
mov ['[ebp+var_C],', 'eax']
cmp ['[ebp+var_C],', '0']
jge ['short', 'loc_F55']
jmp ['short', 'loc_F8E']
mov ['ecx,', '[ebp+var_18]']
mov ['edx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[edx+ecx*4+4],', '0']
jz ['short', 'loc_F72']
mov ['eax,', '[ebp+var_18]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_10]']
add ['edx,', '[ecx+eax*4+14h]']
mov ['[ebp+var_10],', 'edx']
cmp ['[ebp+var_C],', '0']
jnz ['short', 'loc_F80']
mov ['eax,', '[ebp+var_18]']
mov ['[ebp+var_14],', 'eax']
jmp ['short', 'loc_F8E']
mov ['ecx,', '[ebp+var_10]']
add ['ecx,', '1']
mov ['[ebp+var_10],', 'ecx']
jmp ['loc_EF2']
cmp ['[ebp+var_14],', '0']
jl ['short', 'loc_F96']
jmp ['short', 'loc_FB9']
mov ['edx,', '[ebp+var_18]']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax+edx*4+4],', '0']
jz ['short', 'loc_FB2']
mov ['ecx,', '[ebp+var_18]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4+4]']
mov ['[ebp+var_4],', 'eax']
jmp ['short', 'loc_FB4']
jmp ['short', 'loc_FB9']
jmp ['loc_EDC']
cmp ['[ebp+var_14],', '0']
jl ['short', 'loc_1001']
cmp ['[ebp+arg_C],', '1']
jz ['short', 'loc_FE5']
cmp ['[ebp+arg_C],', '3']
jz ['short', 'loc_FE5']
cmp ['[ebp+arg_10],', '0']
jz ['short', 'loc_FD9']
mov ['ecx,', '[ebp+arg_10]']
mov ['edx,', '[ebp+var_10]']
mov ['[ecx],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_4]']
mov ['eax,', '[ecx+eax*4+24h]']
jmp ['short', 'loc_104A']
cmp ['[ebp+arg_C],', '1']
jnz ['short', 'loc_FF6']
mov ['edx,', '[ebp+var_10]']
sub ['edx,', '1']
mov ['[ebp+var_10],', 'edx']
jmp ['short', 'loc_FFF']
mov ['eax,', '[ebp+var_10]']
add ['eax,', '1']
mov ['[ebp+var_10],', 'eax']
jmp ['short', 'loc_1020']
cmp ['[ebp+arg_C],', '0']
jnz ['short', 'loc_100B']
xor ['eax,', 'eax']
jmp ['short', 'loc_104A']
cmp ['[ebp+arg_C],', '1']
jz ['short', 'loc_1017']
cmp ['[ebp+arg_C],', '2']
jnz ['short', 'loc_1020']
mov ['ecx,', '[ebp+var_10]']
sub ['ecx,', '1']
mov ['[ebp+var_10],', 'ecx']
mov ['edx,', '[ebp+var_10]']
push ['edx']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['_index234']
add ['esp,', '8']
mov ['[ebp+var_8],', 'eax']
cmp ['[ebp+var_8],', '0']
jz ['short', 'loc_1047']
cmp ['[ebp+arg_10],', '0']
jz ['short', 'loc_1047']
mov ['ecx,', '[ebp+arg_10]']
mov ['edx,', '[ebp+var_10]']
mov ['[ecx],', 'edx']
mov ['eax,', '[ebp+var_8]']
pop ['esi']
add ['esp,', '20h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_find234        proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0']
push ['0']
mov ['eax,', '[ebp+arg_8]']
push ['eax']
mov ['ecx,', '[ebp+arg_4]']
push ['ecx']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
call ['_findrelpos234']
add ['esp,', '14h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_findrel234     proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['0']
mov ['eax,', '[ebp+arg_C]']
push ['eax']
mov ['ecx,', '[ebp+arg_8]']
push ['ecx']
mov ['edx,', '[ebp+arg_4]']
push ['edx']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['_findrelpos234']
add ['esp,', '14h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_findpos234     proc near
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+arg_C]']
push ['eax']
push ['0']
mov ['ecx,', '[ebp+arg_8]']
push ['ecx']
mov ['edx,', '[ebp+arg_4]']
push ['edx']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['_findrelpos234']
add ['esp,', '14h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_delpos234      proc near
push ['ebp']
mov ['ebp,', 'esp']
cmp ['[ebp+arg_4],', '0']
jl ['short', 'loc_1114']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
push ['ecx']
call ['_countnode234']
add ['esp,', '4']
cmp ['[ebp+arg_4],', 'eax']
jl ['short', 'loc_1118']
xor ['eax,', 'eax']
jmp ['short', 'loc_1128']
mov ['edx,', '[ebp+arg_4]']
push ['edx']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['_delpos234_internal']
add ['esp,', '8']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_delpos234_internal proc near           
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '74h']
push ['esi']
push ['edi']
lea ['edi,', '[ebp+var_74]']
mov ['ecx,', '1Dh']
mov ['eax,', '0CCCCCCCCh']
rep ['stosd']
mov ['[ebp+var_C],', '0FFFFFFFFh']
mov ['[ebp+var_8],', '0']
mov ['eax,', '[ebp+arg_0]']
mov ['ecx,', '[eax]']
mov ['[ebp+var_4],', 'ecx']
mov ['edx,', '1']
test ['edx,', 'edx']
jz ['loc_1AF3']
cmp ['[ebp+var_4],', '0']
jz ['loc_16E3']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+arg_4]']
cmp ['ecx,', '[eax+14h]']
jge ['short', 'loc_1193']
mov ['[ebp+var_10],', '0']
jmp ['loc_1225']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+14h]']
add ['eax,', '1']
mov ['ecx,', '[ebp+arg_4]']
sub ['ecx,', 'eax']
mov ['[ebp+arg_4],', 'ecx']
jns ['short', 'loc_11B4']
mov ['[ebp+var_C],', '0']
jmp ['loc_16E3']
jmp ['short', 'loc_1225']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+arg_4]']
cmp ['eax,', '[edx+18h]']
jge ['short', 'loc_11C8']
mov ['[ebp+var_10],', '1']
jmp ['short', 'loc_1225']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+18h]']
add ['edx,', '1']
mov ['eax,', '[ebp+arg_4]']
sub ['eax,', 'edx']
mov ['[ebp+arg_4],', 'eax']
jns ['short', 'loc_11E9']
mov ['[ebp+var_C],', '1']
jmp ['loc_16E3']
jmp ['short', 'loc_1225']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+arg_4]']
cmp ['edx,', '[ecx+1Ch]']
jge ['short', 'loc_11FD']
mov ['[ebp+var_10],', '2']
jmp ['short', 'loc_1225']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+1Ch]']
add ['ecx,', '1']
mov ['edx,', '[ebp+arg_4]']
sub ['edx,', 'ecx']
mov ['[ebp+arg_4],', 'edx']
jns ['short', 'loc_121E']
mov ['[ebp+var_C],', '2']
jmp ['loc_16E3']
jmp ['short', 'loc_1225']
mov ['[ebp+var_10],', '3']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+eax*4+4]']
mov ['[ebp+var_14],', 'edx']
mov ['eax,', '[ebp+var_14]']
cmp ['dword', 'ptr', '[eax+28h],', '0']
jnz ['loc_16D8']
cmp ['[ebp+var_10],', '0']
jle ['loc_139E']
mov ['ecx,', '[ebp+var_10]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4]']
cmp ['dword', 'ptr', '[eax+28h],', '0']
jz ['loc_139E']
mov ['ecx,', '[ebp+var_10]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4]']
mov ['[ebp+var_18],', 'eax']
mov ['ecx,', '[ebp+var_18]']
cmp ['dword', 'ptr', '[ecx+2Ch],', '0']
jz ['short', 'loc_127A']
mov ['[ebp+var_54],', '2']
jmp ['short', 'loc_1289']
mov ['edx,', '[ebp+var_18]']
xor ['eax,', 'eax']
cmp ['dword', 'ptr', '[edx+28h],', '0']
setnz ['al']
mov ['[ebp+var_54],', 'eax']
mov ['ecx,', '[ebp+var_54]']
mov ['[ebp+var_1C],', 'ecx']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[eax+8]']
mov ['[edx+0Ch],', 'ecx']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[eax+18h]']
mov ['[edx+1Ch],', 'ecx']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[eax+24h]']
mov ['[edx+28h],', 'ecx']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[eax+4]']
mov ['[edx+8],', 'ecx']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[eax+14h]']
mov ['[edx+18h],', 'ecx']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_4]']
mov ['eax,', '[ecx+eax*4+20h]']
mov ['[edx+24h],', 'eax']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ebp+var_1C]']
mov ['eax,', '[ebp+var_18]']
mov ['edx,', '[eax+edx*4+8]']
mov ['[ecx+4],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_1C]']
mov ['edx,', '[ebp+var_18]']
mov ['ecx,', '[edx+ecx*4+18h]']
mov ['[eax+14h],', 'ecx']
mov ['edx,', '[ebp+var_14]']
cmp ['dword', 'ptr', '[edx+4],', '0']
jz ['short', 'loc_130F']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[eax+4]']
mov ['edx,', '[ebp+var_14]']
mov ['[ecx],', 'edx']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_1C]']
mov ['esi,', '[ebp+var_18]']
mov ['edx,', '[esi+edx*4+24h]']
mov ['[ecx+eax*4+20h],', 'edx']
mov ['eax,', '[ebp+var_1C]']
mov ['ecx,', '[ebp+var_18]']
mov ['dword', 'ptr', '[ecx+eax*4+8],', '0']
mov ['edx,', '[ebp+var_1C]']
mov ['eax,', '[ebp+var_18]']
mov ['dword', 'ptr', '[eax+edx*4+18h],', '0']
mov ['ecx,', '[ebp+var_1C]']
mov ['edx,', '[ebp+var_18]']
mov ['dword', 'ptr', '[edx+ecx*4+24h],', '0']
mov ['eax,', '[ebp+var_14]']
push ['eax']
call ['_countnode234']
add ['esp,', '4']
mov ['ecx,', '[ebp+var_10]']
mov ['edx,', '[ebp+var_4]']
mov ['[edx+ecx*4+14h],', 'eax']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+arg_4]']
add ['edx,', '[ecx+eax*4+10h]']
mov ['[ebp+arg_4],', 'edx']
mov ['eax,', '[ebp+var_18]']
push ['eax']
call ['_countnode234']
add ['esp,', '4']
mov ['ecx,', '[ebp+var_10]']
mov ['edx,', '[ebp+var_4]']
mov ['[edx+ecx*4+10h],', 'eax']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+arg_4]']
sub ['edx,', '[ecx+eax*4+10h]']
mov ['[ebp+arg_4],', 'edx']
jmp ['loc_16D8']
cmp ['[ebp+var_10],', '3']
jge ['loc_14FC']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+eax*4+8],', '0']
jz ['loc_14FC']
mov ['edx,', '[ebp+var_10]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+edx*4+8]']
cmp ['dword', 'ptr', '[ecx+28h],', '0']
jz ['loc_14FC']
mov ['edx,', '[ebp+var_10]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+edx*4+8]']
mov ['[ebp+var_20],', 'ecx']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_4]']
mov ['eax,', '[ecx+eax*4+24h]']
mov ['[edx+28h],', 'eax']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ebp+var_20]']
mov ['eax,', '[edx+4]']
mov ['[ecx+0Ch],', 'eax']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ebp+var_20]']
mov ['eax,', '[edx+14h]']
mov ['[ecx+1Ch],', 'eax']
mov ['ecx,', '[ebp+var_14]']
cmp ['dword', 'ptr', '[ecx+0Ch],', '0']
jz ['short', 'loc_1416']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[edx+0Ch]']
mov ['ecx,', '[ebp+var_14]']
mov ['[eax],', 'ecx']
mov ['edx,', '[ebp+var_10]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_20]']
mov ['ecx,', '[ecx+24h]']
mov ['[eax+edx*4+24h],', 'ecx']
mov ['edx,', '[ebp+var_20]']
mov ['eax,', '[ebp+var_20]']
mov ['ecx,', '[eax+8]']
mov ['[edx+4],', 'ecx']
mov ['edx,', '[ebp+var_20]']
mov ['eax,', '[ebp+var_20]']
mov ['ecx,', '[eax+18h]']
mov ['[edx+14h],', 'ecx']
mov ['[ebp+var_24],', '0']
jmp ['short', 'loc_1450']
mov ['edx,', '[ebp+var_24]']
add ['edx,', '1']
mov ['[ebp+var_24],', 'edx']
cmp ['[ebp+var_24],', '2']
jge ['short', 'loc_14A1']
mov ['eax,', '[ebp+var_24]']
mov ['ecx,', '[ebp+var_20]']
cmp ['dword', 'ptr', '[ecx+eax*4+28h],', '0']
jz ['short', 'loc_14A1']
mov ['edx,', '[ebp+var_24]']
mov ['eax,', '[ebp+var_20]']
mov ['ecx,', '[ebp+var_24]']
mov ['esi,', '[ebp+var_20]']
mov ['ecx,', '[esi+ecx*4+0Ch]']
mov ['[eax+edx*4+8],', 'ecx']
mov ['edx,', '[ebp+var_24]']
mov ['eax,', '[ebp+var_20]']
mov ['ecx,', '[ebp+var_24]']
mov ['esi,', '[ebp+var_20]']
mov ['ecx,', '[esi+ecx*4+1Ch]']
mov ['[eax+edx*4+18h],', 'ecx']
mov ['edx,', '[ebp+var_24]']
mov ['eax,', '[ebp+var_20]']
mov ['ecx,', '[ebp+var_24]']
mov ['esi,', '[ebp+var_20]']
mov ['ecx,', '[esi+ecx*4+28h]']
mov ['[eax+edx*4+24h],', 'ecx']
jmp ['short', 'loc_1447']
mov ['edx,', '[ebp+var_24]']
mov ['eax,', '[ebp+var_20]']
mov ['dword', 'ptr', '[eax+edx*4+8],', '0']
mov ['ecx,', '[ebp+var_24]']
mov ['edx,', '[ebp+var_20]']
mov ['dword', 'ptr', '[edx+ecx*4+18h],', '0']
mov ['eax,', '[ebp+var_24]']
mov ['ecx,', '[ebp+var_20]']
mov ['dword', 'ptr', '[ecx+eax*4+24h],', '0']
mov ['edx,', '[ebp+var_14]']
push ['edx']
call ['_countnode234']
add ['esp,', '4']
mov ['ecx,', '[ebp+var_10]']
mov ['edx,', '[ebp+var_4]']
mov ['[edx+ecx*4+14h],', 'eax']
mov ['eax,', '[ebp+var_20]']
push ['eax']
call ['_countnode234']
add ['esp,', '4']
mov ['ecx,', '[ebp+var_10]']
mov ['edx,', '[ebp+var_4]']
mov ['[edx+ecx*4+18h],', 'eax']
jmp ['loc_16D8']
cmp ['[ebp+var_10],', '0']
jle ['short', 'loc_151F']
mov ['eax,', '[ebp+var_10]']
sub ['eax,', '1']
mov ['[ebp+var_10],', 'eax']
mov ['ecx,', '[ebp+var_10]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4+14h]']
mov ['ecx,', '[ebp+arg_4]']
lea ['edx,', '[ecx+eax+1]']
mov ['[ebp+arg_4],', 'edx']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+eax*4+4]']
mov ['[ebp+var_28],', 'edx']
mov ['eax,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx+eax*4+8]']
mov ['[ebp+var_14],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ecx+8]']
mov ['[eax+10h],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ecx+18h]']
mov ['[eax+20h],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ecx+24h]']
mov ['[eax+2Ch],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ecx+4]']
mov ['[eax+0Ch],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ecx+14h]']
mov ['[eax+1Ch],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_10]']
mov ['edx,', '[ebp+var_4]']
mov ['ecx,', '[edx+ecx*4+24h]']
mov ['[eax+28h],', 'ecx']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[ebp+var_28]']
mov ['ecx,', '[eax+8]']
mov ['[edx+8],', 'ecx']
mov ['edx,', '[ebp+var_14]']
mov ['eax,', '[ebp+var_28]']
mov ['ecx,', '[eax+18h]']
mov ['[edx+18h],', 'ecx']
mov ['edx,', '[ebp+var_14]']
cmp ['dword', 'ptr', '[edx+8],', '0']
jz ['short', 'loc_15B1']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[eax+8]']
mov ['edx,', '[ebp+var_14]']
mov ['[ecx],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ecx+24h]']
mov ['[eax+24h],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ecx+4]']
mov ['[eax+4],', 'edx']
mov ['eax,', '[ebp+var_14]']
mov ['ecx,', '[ebp+var_28]']
mov ['edx,', '[ecx+14h]']
mov ['[eax+14h],', 'edx']
mov ['eax,', '[ebp+var_14]']
cmp ['dword', 'ptr', '[eax+4],', '0']
jz ['short', 'loc_15E9']
mov ['ecx,', '[ebp+var_14]']
mov ['edx,', '[ecx+4]']
mov ['eax,', '[ebp+var_14]']
mov ['[edx],', 'eax']
mov ['ecx,', '[ebp+var_14]']
push ['ecx']
call ['_countnode234']
add ['esp,', '4']
mov ['edx,', '[ebp+var_10]']
mov ['ecx,', '[ebp+var_4]']
mov ['[ecx+edx*4+18h],', 'eax']
mov ['edx,', '[ebp+var_28]']
push ['edx']
call ['_safefree']
add ['esp,', '4']
mov ['eax,', '[ebp+var_10]']
mov ['[ebp+var_2C],', 'eax']
jmp ['short', 'loc_161C']
mov ['ecx,', '[ebp+var_2C]']
add ['ecx,', '1']
mov ['[ebp+var_2C],', 'ecx']
cmp ['[ebp+var_2C],', '3']
jge ['short', 'loc_1682']
mov ['edx,', '[ebp+var_2C]']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax+edx*4+8],', '0']
jz ['short', 'loc_1682']
mov ['ecx,', '[ebp+var_2C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_2C]']
mov ['esi,', '[ebp+var_4]']
mov ['eax,', '[esi+eax*4+8]']
mov ['[edx+ecx*4+4],', 'eax']
mov ['ecx,', '[ebp+var_2C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_2C]']
mov ['esi,', '[ebp+var_4]']
mov ['eax,', '[esi+eax*4+18h]']
mov ['[edx+ecx*4+14h],', 'eax']
cmp ['[ebp+var_2C],', '2']
jge ['short', 'loc_166C']
mov ['ecx,', '[ebp+var_2C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4+28h]']
mov ['[ebp+var_58],', 'eax']
jmp ['short', 'loc_1673']
mov ['[ebp+var_58],', '0']
mov ['ecx,', '[ebp+var_2C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_58]']
mov ['[edx+ecx*4+24h],', 'eax']
jmp ['short', 'loc_1613']
mov ['ecx,', '[ebp+var_2C]']
mov ['edx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[edx+ecx*4+4],', '0']
mov ['eax,', '[ebp+var_2C]']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+eax*4+14h],', '0']
cmp ['[ebp+var_2C],', '3']
jge ['short', 'loc_16B2']
mov ['edx,', '[ebp+var_2C]']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+edx*4+24h],', '0']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+24h],', '0']
jnz ['short', 'loc_16D8']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[ebp+var_14]']
mov ['[edx],', 'eax']
mov ['ecx,', '[ebp+var_14]']
mov ['dword', 'ptr', '[ecx],', '0']
mov ['edx,', '[ebp+var_4]']
push ['edx']
call ['_safefree']
add ['esp,', '4']
mov ['eax,', '[ebp+var_14]']
mov ['[ebp+var_4],', 'eax']
jmp ['loc_1172']
cmp ['[ebp+var_8],', '0']
jnz ['short', 'loc_16F6']
mov ['ecx,', '[ebp+var_C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4+24h]']
mov ['[ebp+var_8],', 'eax']
cmp ['[ebp+var_C],', '0FFFFFFFFh']
jnz ['short', 'loc_1703']
xor ['eax,', 'eax']
jmp ['loc_1AF3']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx],', '0']
jnz ['short', 'loc_173A']
mov ['edx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[edx+28h],', '0']
jnz ['short', 'loc_173A']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax+4],', '0']
jnz ['short', 'loc_173A']
mov ['ecx,', '[ebp+var_4]']
push ['ecx']
call ['_safefree']
add ['esp,', '4']
mov ['edx,', '[ebp+arg_0]']
mov ['dword', 'ptr', '[edx],', '0']
mov ['eax,', '[ebp+var_8]']
jmp ['loc_1AF3']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax+4],', '0']
jnz ['loc_1824']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+28h],', '0']
jz ['loc_1824']
mov ['edx,', '[ebp+var_C]']
mov ['[ebp+var_30],', 'edx']
jmp ['short', 'loc_1765']
mov ['eax,', '[ebp+var_30]']
add ['eax,', '1']
mov ['[ebp+var_30],', 'eax']
cmp ['[ebp+var_30],', '2']
jge ['short', 'loc_178E']
mov ['ecx,', '[ebp+var_30]']
mov ['edx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[edx+ecx*4+28h],', '0']
jz ['short', 'loc_178E']
mov ['eax,', '[ebp+var_30]']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ebp+var_30]']
mov ['esi,', '[ebp+var_4]']
mov ['edx,', '[esi+edx*4+28h]']
mov ['[ecx+eax*4+24h],', 'edx']
jmp ['short', 'loc_175C']
mov ['eax,', '[ebp+var_30]']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+eax*4+24h],', '0']
mov ['edx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[edx],', '0']
jz ['short', 'loc_1817']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ecx+4]']
cmp ['edx,', '[ebp+var_4]']
jnz ['short', 'loc_17BA']
mov ['[ebp+var_5C],', '0']
jmp ['short', 'loc_17EC']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ecx+8]']
cmp ['edx,', '[ebp+var_4]']
jnz ['short', 'loc_17D0']
mov ['[ebp+var_60],', '1']
jmp ['short', 'loc_17E6']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ecx+0Ch]']
xor ['eax,', 'eax']
cmp ['edx,', '[ebp+var_4]']
setnz ['al']
add ['eax,', '2']
mov ['[ebp+var_60],', 'eax']
mov ['ecx,', '[ebp+var_60]']
mov ['[ebp+var_5C],', 'ecx']
mov ['edx,', '[ebp+var_5C]']
mov ['[ebp+var_34],', 'edx']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax]']
mov ['edx,', '[ebp+var_34]']
mov ['eax,', '[ecx+edx*4+14h]']
sub ['eax,', '1']
mov ['ecx,', '[ebp+var_4]']
mov ['edx,', '[ecx]']
mov ['ecx,', '[ebp+var_34]']
mov ['[edx+ecx*4+14h],', 'eax']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx]']
mov ['[ebp+var_4],', 'eax']
jmp ['short', 'loc_179C']
mov ['eax,', '[ebp+var_8]']
jmp ['loc_1AF3']
jmp ['loc_1AEE']
mov ['ecx,', '[ebp+var_C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4+4]']
cmp ['dword', 'ptr', '[eax+28h],', '0']
jz ['loc_1913']
mov ['ecx,', '[ebp+var_C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4+4]']
mov ['[ebp+var_38],', 'eax']
mov ['ecx,', '[ebp+var_38]']
cmp ['dword', 'ptr', '[ecx+4],', '0']
jz ['short', 'loc_18A7']
mov ['edx,', '[ebp+var_38]']
cmp ['dword', 'ptr', '[edx+10h],', '0']
jz ['short', 'loc_1862']
mov ['eax,', '[ebp+var_38]']
mov ['ecx,', '[eax+10h]']
mov ['[ebp+var_64],', 'ecx']
jmp ['short', 'loc_189F']
mov ['edx,', '[ebp+var_38]']
cmp ['dword', 'ptr', '[edx+0Ch],', '0']
jz ['short', 'loc_1876']
mov ['eax,', '[ebp+var_38]']
mov ['ecx,', '[eax+0Ch]']
mov ['[ebp+var_68],', 'ecx']
jmp ['short', 'loc_1899']
mov ['edx,', '[ebp+var_38]']
cmp ['dword', 'ptr', '[edx+8],', '0']
jz ['short', 'loc_188A']
mov ['eax,', '[ebp+var_38]']
mov ['ecx,', '[eax+8]']
mov ['[ebp+var_6C],', 'ecx']
jmp ['short', 'loc_1893']
mov ['edx,', '[ebp+var_38]']
mov ['eax,', '[edx+4]']
mov ['[ebp+var_6C],', 'eax']
mov ['ecx,', '[ebp+var_6C]']
mov ['[ebp+var_68],', 'ecx']
mov ['edx,', '[ebp+var_68]']
mov ['[ebp+var_64],', 'edx']
mov ['eax,', '[ebp+var_64]']
mov ['[ebp+var_38],', 'eax']
jmp ['short', 'loc_1845']
mov ['ecx,', '[ebp+var_38]']
cmp ['dword', 'ptr', '[ecx+2Ch],', '0']
jz ['short', 'loc_18BB']
mov ['edx,', '[ebp+var_38]']
mov ['eax,', '[edx+2Ch]']
mov ['[ebp+var_70],', 'eax']
jmp ['short', 'loc_18DE']
mov ['ecx,', '[ebp+var_38]']
cmp ['dword', 'ptr', '[ecx+28h],', '0']
jz ['short', 'loc_18CF']
mov ['edx,', '[ebp+var_38]']
mov ['eax,', '[edx+28h]']
mov ['[ebp+var_74],', 'eax']
jmp ['short', 'loc_18D8']
mov ['ecx,', '[ebp+var_38]']
mov ['edx,', '[ecx+24h]']
mov ['[ebp+var_74],', 'edx']
mov ['eax,', '[ebp+var_74]']
mov ['[ebp+var_70],', 'eax']
mov ['ecx,', '[ebp+var_70]']
mov ['[ebp+var_3C],', 'ecx']
mov ['edx,', '[ebp+var_C]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[ebp+var_3C]']
mov ['[eax+edx*4+24h],', 'ecx']
mov ['edx,', '[ebp+var_C]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+edx*4+14h]']
sub ['ecx,', '1']
mov ['[ebp+arg_4],', 'ecx']
mov ['edx,', '[ebp+var_C]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+edx*4+4]']
mov ['[ebp+var_4],', 'ecx']
jmp ['loc_1AEE']
mov ['edx,', '[ebp+var_C]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+edx*4+8]']
cmp ['dword', 'ptr', '[ecx+28h],', '0']
jz ['short', 'loc_1973']
mov ['edx,', '[ebp+var_C]']
mov ['eax,', '[ebp+var_4]']
mov ['ecx,', '[eax+edx*4+8]']
mov ['[ebp+var_40],', 'ecx']
mov ['edx,', '[ebp+var_40]']
cmp ['dword', 'ptr', '[edx+4],', '0']
jz ['short', 'loc_1944']
mov ['eax,', '[ebp+var_40]']
mov ['ecx,', '[eax+4]']
mov ['[ebp+var_40],', 'ecx']
jmp ['short', 'loc_1930']
mov ['edx,', '[ebp+var_40]']
mov ['eax,', '[edx+24h]']
mov ['[ebp+var_44],', 'eax']
mov ['ecx,', '[ebp+var_C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_44]']
mov ['[edx+ecx*4+24h],', 'eax']
mov ['ecx,', '[ebp+var_C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4+8]']
mov ['[ebp+var_4],', 'eax']
mov ['[ebp+arg_4],', '0']
jmp ['loc_1AEE']
mov ['ecx,', '[ebp+var_C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4+4]']
mov ['[ebp+var_48],', 'eax']
mov ['ecx,', '[ebp+var_C]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[edx+ecx*4+8]']
mov ['[ebp+var_4C],', 'eax']
mov ['ecx,', '[ebp+var_48]']
mov ['edx,', '[ebp+var_C]']
mov ['eax,', '[ebp+var_4]']
mov ['edx,', '[eax+edx*4+24h]']
mov ['[ecx+28h],', 'edx']
mov ['eax,', '[ebp+var_48]']
mov ['ecx,', '[ebp+var_4C]']
mov ['edx,', '[ecx+4]']
mov ['[eax+0Ch],', 'edx']
mov ['eax,', '[ebp+var_48]']
mov ['ecx,', '[ebp+var_4C]']
mov ['edx,', '[ecx+14h]']
mov ['[eax+1Ch],', 'edx']
mov ['eax,', '[ebp+var_48]']
cmp ['dword', 'ptr', '[eax+0Ch],', '0']
jz ['short', 'loc_19C9']
mov ['ecx,', '[ebp+var_48]']
mov ['edx,', '[ecx+0Ch]']
mov ['eax,', '[ebp+var_48]']
mov ['[edx],', 'eax']
mov ['ecx,', '[ebp+var_48]']
mov ['edx,', '[ebp+var_4C]']
mov ['eax,', '[edx+24h]']
mov ['[ecx+2Ch],', 'eax']
mov ['ecx,', '[ebp+var_48]']
mov ['edx,', '[ebp+var_4C]']
mov ['eax,', '[edx+8]']
mov ['[ecx+10h],', 'eax']
mov ['ecx,', '[ebp+var_48]']
mov ['edx,', '[ebp+var_4C]']
mov ['eax,', '[edx+18h]']
mov ['[ecx+20h],', 'eax']
mov ['ecx,', '[ebp+var_48]']
cmp ['dword', 'ptr', '[ecx+10h],', '0']
jz ['short', 'loc_1A01']
mov ['edx,', '[ebp+var_48]']
mov ['eax,', '[edx+10h]']
mov ['ecx,', '[ebp+var_48]']
mov ['[eax],', 'ecx']
mov ['edx,', '[ebp+var_4C]']
push ['edx']
call ['_safefree']
add ['esp,', '4']
mov ['eax,', '[ebp+var_48]']
push ['eax']
call ['_countnode234']
add ['esp,', '4']
mov ['ecx,', '[ebp+var_C]']
mov ['edx,', '[ebp+var_4]']
mov ['[edx+ecx*4+14h],', 'eax']
mov ['eax,', '[ebp+var_C]']
mov ['[ebp+var_50],', 'eax']
jmp ['short', 'loc_1A34']
mov ['ecx,', '[ebp+var_50]']
add ['ecx,', '1']
mov ['[ebp+var_50],', 'ecx']
cmp ['[ebp+var_50],', '2']
jge ['short', 'loc_1A85']
mov ['edx,', '[ebp+var_50]']
mov ['eax,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[eax+edx*4+28h],', '0']
jz ['short', 'loc_1A85']
mov ['ecx,', '[ebp+var_50]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_50]']
mov ['esi,', '[ebp+var_4]']
mov ['eax,', '[esi+eax*4+28h]']
mov ['[edx+ecx*4+24h],', 'eax']
mov ['ecx,', '[ebp+var_50]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_50]']
mov ['esi,', '[ebp+var_4]']
mov ['eax,', '[esi+eax*4+0Ch]']
mov ['[edx+ecx*4+8],', 'eax']
mov ['ecx,', '[ebp+var_50]']
mov ['edx,', '[ebp+var_4]']
mov ['eax,', '[ebp+var_50]']
mov ['esi,', '[ebp+var_4]']
mov ['eax,', '[esi+eax*4+1Ch]']
mov ['[edx+ecx*4+18h],', 'eax']
jmp ['short', 'loc_1A2B']
mov ['ecx,', '[ebp+var_50]']
mov ['edx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[edx+ecx*4+24h],', '0']
mov ['eax,', '[ebp+var_50]']
mov ['ecx,', '[ebp+var_4]']
mov ['dword', 'ptr', '[ecx+eax*4+8],', '0']
mov ['edx,', '[ebp+var_50]']
mov ['eax,', '[ebp+var_4]']
mov ['dword', 'ptr', '[eax+edx*4+18h],', '0']
mov ['ecx,', '[ebp+var_4]']
cmp ['dword', 'ptr', '[ecx+24h],', '0']
jnz ['short', 'loc_1AD5']
mov ['edx,', '[ebp+arg_0]']
mov ['eax,', '[ebp+var_48]']
mov ['[edx],', 'eax']
mov ['ecx,', '[ebp+var_48]']
mov ['dword', 'ptr', '[ecx],', '0']
mov ['edx,', '[ebp+var_4]']
push ['edx']
call ['_safefree']
add ['esp,', '4']
mov ['eax,', '[ebp+var_48]']
mov ['[ebp+var_4],', 'eax']
mov ['ecx,', '[ebp+var_48]']
mov ['edx,', '[ecx+14h]']
mov ['eax,', '[ebp+var_48]']
mov ['ecx,', '[eax+18h]']
lea ['edx,', '[edx+ecx+1]']
mov ['[ebp+arg_4],', 'edx']
jmp ['loc_1165']
pop ['edi']
pop ['esi']
add ['esp,', '74h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
_del234         proc near
push ['ebp']
mov ['ebp,', 'esp']
sub ['esp,', '0Ch']
mov ['[ebp+var_C],', '0CCCCCCCCh']
mov ['[ebp+var_8],', '0CCCCCCCCh']
mov ['[ebp+var_4],', '0CCCCCCCCh']
lea ['eax,', '[ebp+var_8]']
push ['eax']
push ['0']
push ['0']
mov ['ecx,', '[ebp+arg_4]']
push ['ecx']
mov ['edx,', '[ebp+arg_0]']
push ['edx']
call ['_findrelpos234']
add ['esp,', '14h']
test ['eax,', 'eax']
jnz ['short', 'loc_1B43']
xor ['eax,', 'eax']
jmp ['short', 'loc_1B53']
mov ['eax,', '[ebp+var_8]']
push ['eax']
mov ['ecx,', '[ebp+arg_0]']
push ['ecx']
call ['_delpos234_internal']
add ['esp,', '8']
push ['edx']
mov ['ecx,', 'ebp']
push ['eax']
lea ['edx,', '$LN6']
call ['@_RTC_CheckStackVars@8']
pop ['eax']
pop ['edx']
add ['esp,', '0Ch']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
mov ['esp,', 'ebp']
pop ['ebp']
retn
endp
