_platform_default_fontspec proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['offset', '$SG87946']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['_strcmp']
add ['esp,', '8']
test ['eax,', 'eax']
jnz ['short', 'loc_73']
push ['0']
push ['0Ah']
push ['0']
push ['offset', '$SG87947']
call ['_fontspec_new']
add ['esp,', '10h']
jmp ['short', 'loc_86']
jmp ['short', 'loc_86']
push ['0']
push ['0']
push ['0']
push ['offset', '$SG87949']
call ['_fontspec_new']
add ['esp,', '10h']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_platform_default_filename proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['offset', '$SG87954']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['_strcmp']
add ['esp,', '8']
test ['eax,', 'eax']
jnz ['short', 'loc_BD']
push ['offset', '$SG87955']
call ['_filename_from_str']
add ['esp,', '4']
jmp ['short', 'loc_CA']
jmp ['short', 'loc_CA']
push ['offset', '$SG87957']
call ['_filename_from_str']
add ['esp,', '4']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_platform_default_s proc near
push ['ebp']
mov ['ebp,', 'esp']
push ['offset', '$SG87962']
mov ['eax,', '[ebp+arg_0]']
push ['eax']
call ['_strcmp']
add ['esp,', '8']
test ['eax,', 'eax']
jnz ['short', 'loc_FB']
push ['offset', '$SG87963']
call ['_dupstr']
add ['esp,', '4']
jmp ['short', 'loc_FD']
xor ['eax,', 'eax']
cmp ['ebp,', 'esp']
call ['__RTC_CheckEsp']
pop ['ebp']
retn
endp
_platform_default_i proc near
push ['ebp']
mov ['ebp,', 'esp']
mov ['eax,', '[ebp+arg_4]']
pop ['ebp']
retn
endp
