_gg_encoding_convert
original code :
push|push|push|push|sub|mov|mov|mov|mov|mov|mov|mov|mov|xor|test|je|cmp|je|cmp|je|cmp|je|test|je|dec|jne|test|jne|mov|movsx|test|je|test|jle|mov|add|movzx|test|js|inc|movzx|test|je|inc|cmp|jne|cmp|je|cmp|jg|lea|mov|call|mov|test|je|test|je|test|jle|test|jle|mov|inc|add|mov|xor|mov|jmp|mov|mov|inc|movsx|test|je|cmp|je|inc|cmp|jle|test|jns|movzx|mov|cmp|cmp|ja|lea|cmp|jl|mov|shr|mov|or|mov|mov|and|or|mov|add|movsx|test|jne|mov|mov|jmp|mov|cmp|cmp|ja|add|jmp|dec|je|call|mov|xor|mov|mov|xor|jne|add|pop|pop|pop|pop|ret|lea|cmp|jl|mov|shr|mov|or|mov|mov|mov|shr|and|mov|or|mov|mov|and|or|mov|add|jmp|add|jmp|cmp|jne|cmp|je|lea|mov|call|mov|test|je|mov|mov|mov|mov|mov|call|mov|mov|jmp|cmp|je|cmp|jle|mov|jmp|xor|mov|mov|repne|not|lea|jmp|mov|jmp|mov|xor|jne|mov|mov|add|pop|pop|pop|pop|jmp|xor|jmp|mov|mov|test|je|test|jle|mov|mov|add|mov|mov|xor|jmp|inc|cmp|je|and|add|je|inc|mov|test|jne|mov|cmp|je|cmp|jle|mov|mov|inc|mov|call|mov|test|je|test|je|test|jle|mov|test|jle|mov|inc|add|mov|mov|mov|xor|xor|mov|mov|jmp|test|je|mov|inc|mov|inc|xor|mov|mov|test|je|cmp|je|inc|cmp|jle|cmp|ja|movsx|mov|and|cmp|je|mov|and|cmp|je|mov|and|cmp|je|mov|and|add|je|test|je|mov|inc|mov|mov|inc|xor|jmp|test|je|mov|inc|mov|mov|and|mov|mov|mov|jmp|test|je|mov|inc|mov|mov|and|mov|mov|mov|jmp|xor|jmp|test|je|mov|inc|mov|mov|and|mov|mov|mov|jmp|mov|mov|jmp|test|je|mov|sal|mov|and|or|mov|dec|jne|mov|cmp|jb|xor|jmp|inc|cmp|je|movzx|cmp|jne|add|mov|inc|jmp|cmp|je|mov|inc|jmp|mov|jmp|xor|jmp|call|mov|test|je|mov|inc|jmp|endproc|_table_cp1250|
disassembled code :
push|push|push|push|sub|mov|mov|mov|mov|mov|mov|mov|mov|xor|test|je|cmp|je|cmp|je|cmp|je|test|je|dec|jne|test|jne|mov|movsx|test|je|test|jle|mov|add|movzx|lea|test|js|inc|movzx|test|je|inc|cmp|jne|cmp|je|cmp|jg|lea|mov|call|mov|test|je|test|je|test|jle|test|jle|mov|inc|add|mov|xor|mov|jmp|mov|mov|inc|movsx|test|je|cmp|je|inc|cmp|jle|test|jns|movzx|mov|cmp|cmp|ja|lea|cmp|jl|mov|shr|mov|or|mov|mov|and|or|mov|add|movsx|test|jne|mov|mov|jmp|mov|cmp|cmp|ja|add|jmp|dec|je|call|mov|xor|mov|mov|xor|jne|add|pop|pop|pop|pop|ret|lea|cmp|jl|mov|shr|mov|or|mov|mov|mov|shr|and|mov|or|mov|mov|and|or|mov|add|jmp|add|jmp|cmp|jne|cmp|je|lea|mov|call|mov|test|je|mov|mov|mov|mov|mov|call|mov|mov|jmp|cmp|je|cmp|jle|mov|jmp|xor|mov|mov|repne|not|lea|jmp|mov|jmp|mov|xor|jne|mov|mov|add|pop|pop|pop|pop|jmp|xor|jmp|mov|mov|test|je|test|jle|mov|mov|add|mov|mov|xor|jmp|inc|cmp|je|and|add|je|inc|mov|test|jne|mov|cmp|je|cmp|jle|mov|mov|inc|mov|call|mov|test|je|test|je|test|jle|mov|test|jle|mov|inc|add|mov|mov|mov|xor|xor|mov|mov|jmp|test|je|mov|inc|mov|inc|xor|mov|mov|test|je|cmp|je|inc|cmp|jle|cmp|ja|movsx|mov|and|cmp|je|mov|and|cmp|je|mov|and|cmp|je|mov|and|add|je|test|je|mov|inc|mov|mov|inc|xor|jmp|test|je|mov|inc|mov|mov|and|mov|mov|mov|jmp|test|je|mov|inc|mov|mov|and|mov|mov|mov|jmp|xor|jmp|test|je|mov|inc|mov|mov|and|mov|mov|mov|jmp|mov|mov|jmp|test|je|mov|shl|mov|and|or|mov|dec|jne|mov|cmp|jb|xor|jmp|inc|cmp|je|movzx|cmp|jne|add|mov|inc|jmp|cmp|je|mov|inc|jmp|mov|jmp|xor|jmp|call|mov|test|je|mov|inc|jmp|

end _gg_encoding_convert
_table_cp1250
original code :

disassembled code :
push|push|push|push|sub|mov|mov|mov|mov|mov|mov|mov|mov|xor|test|je|cmp|je|cmp|je|cmp|je|test|je|dec|jne|test|jne|mov|movsx|test|je|test|jle|mov|add|movzx|lea|test|js|inc|movzx|test|je|inc|cmp|jne|cmp|je|cmp|jg|lea|mov|call|mov|test|je|test|je|test|jle|test|jle|mov|inc|add|mov|xor|mov|jmp|mov|mov|inc|movsx|test|je|cmp|je|inc|cmp|jle|test|jns|movzx|mov|cmp|cmp|ja|lea|cmp|jl|mov|shr|mov|or|mov|mov|and|or|mov|add|movsx|test|jne|mov|mov|jmp|mov|cmp|cmp|ja|add|jmp|dec|je|call|mov|xor|mov|mov|xor|jne|add|pop|pop|pop|pop|ret|lea|cmp|jl|mov|shr|mov|or|mov|mov|mov|shr|and|mov|or|mov|mov|and|or|mov|add|jmp|add|jmp|cmp|jne|cmp|je|lea|mov|call|mov|test|je|mov|mov|mov|mov|mov|call|mov|mov|jmp|cmp|je|cmp|jle|mov|jmp|xor|mov|mov|repne|not|lea|jmp|mov|jmp|mov|xor|jne|mov|mov|add|pop|pop|pop|pop|jmp|xor|jmp|mov|mov|test|je|test|jle|mov|mov|add|mov|mov|xor|jmp|inc|cmp|je|and|add|je|inc|mov|test|jne|mov|cmp|je|cmp|jle|mov|mov|inc|mov|call|mov|test|je|test|je|test|jle|mov|test|jle|mov|inc|add|mov|mov|mov|xor|xor|mov|mov|jmp|test|je|mov|inc|mov|inc|xor|mov|mov|test|je|cmp|je|inc|cmp|jle|cmp|ja|movsx|mov|and|cmp|je|mov|and|cmp|je|mov|and|cmp|je|mov|and|add|je|test|je|mov|inc|mov|mov|inc|xor|jmp|test|je|mov|inc|mov|mov|and|mov|mov|mov|jmp|test|je|mov|inc|mov|mov|and|mov|mov|mov|jmp|xor|jmp|test|je|mov|inc|mov|mov|and|mov|mov|mov|jmp|mov|mov|jmp|test|je|mov|shl|mov|and|or|mov|dec|jne|mov|cmp|jb|xor|jmp|inc|cmp|je|movzx|cmp|jne|add|mov|inc|jmp|cmp|je|mov|inc|jmp|mov|jmp|xor|jmp|call|mov|test|je|mov|inc|jmp|

end _table_cp1250
